// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, TrainerType } from '../../game/store/card/card-types';
import { TrainerCard } from '../../game/store/card/trainer-card';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, SEARCH_DECK_FOR_CARDS_TO_HAND } from '../../game/store/prefabs/prefabs';

export class Honedge extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = P;
  public hp: number = 50;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Lucky Find',
      cost: [C],
      damage: 0,
      text: 'Search your deck for an Item card, reveal it, and put it into your hand. Then, shuffle your deck.'
    },
    {
      name: 'Pierce',
      cost: [P],
      damage: 20,
      text: ''
    }
  ];

  public set: string = 'UNM';
  public setNumber: string = '92';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Honedge';
  public fullName: string = 'Honedge UNM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Lucky Find
    // Ref: set-unbroken-bonds/darmanitan.ts (search deck for cards)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      SEARCH_DECK_FOR_CARDS_TO_HAND(store, state, player, this,
        { superType: SuperType.TRAINER, trainerType: TrainerType.ITEM } as Partial<TrainerCard>,
        { min: 0, max: 1, allowCancel: true }
      );
    }

    return state;
  }
}
