// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, PokemonCardList } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { PUT_X_DAMAGE_COUNTERS_IN_ANY_WAY_YOU_LIKE } from '../../game/store/prefabs/attack-effects';

export class Medicham extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Meditite';
  public cardType: CardType = F;
  public hp: number = 110;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Pure Power',
      cost: [F],
      damage: 0,
      text: 'Put 4 damage counters on your opponent\'s Pokémon in any way you like.'
    },
    {
      name: 'Master Strike',
      cost: [F, F],
      damage: 60,
      damageCalculation: '+' as '+',
      text: 'If this Pokémon has a Karate Belt card attached to it, this attack does 60 more damage.'
    }
  ];

  public set: string = 'UNM';
  public setNumber: string = '110';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Medicham';
  public fullName: string = 'Medicham UNM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Pure Power
    // Ref: set-team-up/jynx.ts (PUT_X_DAMAGE_COUNTERS_IN_ANY_WAY_YOU_LIKE)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      PUT_X_DAMAGE_COUNTERS_IN_ANY_WAY_YOU_LIKE(4, store, state, effect);
    }

    // Attack 2: Master Strike
    // Ref: set-unbroken-bonds/sharpedo.ts (check attached card name)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const hasKarateBelt = (effect.player.active as PokemonCardList).tools.some(
        t => t.name === 'Karate Belt'
      );

      if (hasKarateBelt) {
        effect.damage += 60;
      }
    }

    return state;
  }
}
