import { Card } from '../../game/store/card/card';
import { AlolanExeggutorexArt, ArchaludonexArt, AzelfArt, AzumarillArt, CapsakidArt, CelebrationFanfareArt, CeruledgeArt, CeruledgeexArt, CharcadetArt, CherishCarrierArt, CounterGainArt, CrocalorArt, CyranoArt, DeinoArt, DragonsElixirArt, DraytonArt, DuraludonArt, EeveeArt, EternatusArt, ExcitingStadiumArt, ExeggcuteArt, FlygonexArt, FuecocoArt, GravityMountainArt, HelperBellArt, HoOhArt, HydreigonexArt, KlefkiArt, LatiasexArt, LisiasAppealArt, MagnemiteArt, MagnetonArt, MarillArt, MegatonBlowerArt, MespritArt, MiloticexArt, MiraculousIntercomArt, NinetalesArt, PalkiaArt, PalossandexArt, PerfectMixerArt, PikachuexArt, QuaxwellArt, RichEnergyArt, ScrambleSwitchArt, ShroodleArt, SkeledirgeArt, SmoochumArt, SylveonexArt, TatsugiriexArt, TeraOrbArt, TerapagosArt, TogekissArt, TogepiArt, TogeticArt, TrapinchArt, UxieArt, VibravaArt, VivillionArt, VulpixArt, ZweilousArt } from './card-images';
import { Sandygast } from './sandygast';

export const setSurgingSparks: Card[] = [
  new PikachuexArt(),
  new TerapagosArt(),
  new MagnemiteArt(),
  new MagnetonArt(),
  new ExcitingStadiumArt(),
  new GravityMountainArt(),
  new CyranoArt(),
  new MiraculousIntercomArt(),
  new FuecocoArt(),
  new CrocalorArt(),
  new SkeledirgeArt(),
  new MiloticexArt(),
  new TogepiArt(),
  new TogeticArt(),
  new TogekissArt(),
  new DeinoArt(),
  new ZweilousArt(),
  new HydreigonexArt(),
  new EternatusArt(),
  new VivillionArt(),
  new AzelfArt(),
  new UxieArt(),
  new MespritArt(),
  new ScrambleSwitchArt(),
  new NinetalesArt(),
  new CeruledgeArt(),
  new TatsugiriexArt(),
  new PalkiaArt(),
  new HoOhArt(),
  new AzumarillArt(),
  new PerfectMixerArt(),
  new CherishCarrierArt(),
  new MarillArt(),
  new TeraOrbArt(),
  new TrapinchArt(),
  new VibravaArt(),
  new FlygonexArt(),
  new CounterGainArt(),
  new HelperBellArt(),
  new DuraludonArt(),
  new ArchaludonexArt(),
  new MegatonBlowerArt(),
  new SmoochumArt(),
  new CelebrationFanfareArt(),
  new DragonsElixirArt(),
  new DraytonArt(),
  new RichEnergyArt(),
  new KlefkiArt(),
  new ExeggcuteArt(),
  new AlolanExeggutorexArt(),
  new VulpixArt(),
  new LatiasexArt(),
  new CeruledgeexArt(),
  new CharcadetArt(),
  new EeveeArt(),
  new SylveonexArt(),
  new LisiasAppealArt(),
  new Sandygast(),
  new PalossandexArt(),
  new CapsakidArt(),
  new ShroodleArt(),
  new QuaxwellArt(),
];
