// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE } from '../../game/store/prefabs/attack-effects';

export class Loudred extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Whismur';
  public cardType: CardType = C;
  public hp: number = 90;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Smash Kick',
      cost: [C],
      damage: 10,
      text: ''
    },
    {
      name: 'Stomp',
      cost: [C, C, C],
      damage: 40,
      damageCalculation: '+' as '+',
      text: 'Flip a coin. If heads, this attack does 40 more damage.'
    }
  ];

  public set: string = 'FCO';
  public setNumber: string = '81';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Loudred';
  public fullName: string = 'Loudred FCO';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Stomp
    // Ref: AGENTS-patterns.md (Flip coin if heads more damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE(store, state, effect, 40);
    }

    return state;
  }
}
