// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType, SuperType } from '../../game/store/card/card-types';
import { PlayerType, SlotType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { PutCountersEffect } from '../../game/store/effects/attack-effects';
import { WAS_ATTACK_USED, ATTACH_ENERGY_PROMPT } from '../../game/store/prefabs/prefabs';

export class Rotom extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = L;
  public hp: number = 70;
  public weakness = [{ type: F }];
  public resistance = [{ type: M, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Energy Extract',
      cost: [L],
      damage: 0,
      text: 'Search your deck for a basic Energy card and attach it to this Pokémon. Shuffle your deck afterward.'
    },
    {
      name: 'Plasmagic',
      cost: [C, C],
      damage: 0,
      text: 'Move 2 damage counters from each of your Pokémon to your opponent\'s Active Pokémon.'
    }
  ];

  public set: string = 'FCO';
  public setNumber: string = '24';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Rotom';
  public fullName: string = 'Rotom FCO';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Energy Extract
    // Ref: set-furious-fists/magmortar.ts (Flame Charge)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      state = ATTACH_ENERGY_PROMPT(
        store, state, player,
        PlayerType.BOTTOM_PLAYER,
        SlotType.DECK,
        [SlotType.ACTIVE],
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC },
        { min: 1, max: 1, allowCancel: true }
      );
    }

    // Attack 2: Plasmagic
    // Ref: set-boundaries-crossed/musharna.ts (damage counter movement concept)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      let totalCountersMoved = 0;

      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        const countersToMove = Math.min(20, cardList.damage);
        if (countersToMove > 0) {
          cardList.damage -= countersToMove;
          totalCountersMoved += countersToMove;
        }
      });

      if (totalCountersMoved > 0) {
        const putCounters = new PutCountersEffect(effect, totalCountersMoved);
        putCounters.target = opponent.active;
        store.reduceEffect(state, putCounters);
      }
    }

    return state;
  }
}
