// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StateUtils, StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { AfterAttackEffect, EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { SWITCH_ACTIVE_WITH_BENCHED, WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Timburr extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 70;
  public weakness = [{ type: P }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Knock Back',
      cost: [F, C],
      damage: 20,
      text: 'Your opponent switches the Defending Pokémon with 1 of his or her Benched Pokémon.'
    },
    {
      name: 'Low Kick',
      cost: [F, C, C],
      damage: 40,
      text: ''
    }
  ];

  public set: string = 'PLS';
  public setNumber: string = '79';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Timburr';
  public fullName: string = 'Timburr PLS';

  public usedKnockBack = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Knock Back
    // Ref: set-boundaries-crossed/lopunny.ts (Kick Away - opponent switches after damage)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      this.usedKnockBack = true;
    }

    if (effect instanceof AfterAttackEffect && this.usedKnockBack) {
      this.usedKnockBack = false;
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      if (opponent.bench.some(b => b.cards.length > 0)) {
        SWITCH_ACTIVE_WITH_BENCHED(store, state, opponent);
      }
    }

    if (effect instanceof EndTurnEffect) {
      this.usedKnockBack = false;
    }

    return state;
  }
}
