// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { HEAL_X_DAMAGE_FROM_THIS_POKEMON } from '../../game/store/prefabs/attack-effects';

export class Turtwig extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 70;
  public weakness = [{ type: R }];
  public resistance = [{ type: W, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Nap',
      cost: [C],
      damage: 0,
      text: 'Heal 20 damage from this Pokémon.'
    },
    {
      name: 'Razor Leaf',
      cost: [G, C, C],
      damage: 30,
      text: ''
    }
  ];

  public set: string = 'PLS';
  public setNumber: string = '1';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Turtwig';
  public fullName: string = 'Turtwig PLS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Nap
    // Ref: set-boundaries-crossed/azumarill.ts (HEAL_X_DAMAGE_FROM_THIS_POKEMON)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      HEAL_X_DAMAGE_FROM_THIS_POKEMON(20, effect, store, state);
    }

    return state;
  }
}
