services:
  ptcg-server:
    build:
      context: ./ptcg-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./ptcg-server:/usr/src/app
    environment:
      NODE_ENV: development
