// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, MULTIPLE_COIN_FLIPS_PROMPT } from '../../game/store/prefabs/prefabs';

export class Cinccino extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Minccino';
  public cardType: CardType = C;
  public hp: number = 90;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Slap',
      cost: [C],
      damage: 40,
      text: ''
    },
    {
      name: 'Triple Axel',
      cost: [C, C],
      damage: 50,
      damageCalculation: 'x' as 'x',
      text: 'Flip 3 coins. This attack does 50 damage for each heads.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'BRS';
  public setNumber: string = '125';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Cinccino';
  public fullName: string = 'Cinccino BRS 125';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Triple Axel
    // Ref: AGENTS-patterns.md (Multiple Coin Flips - flip 3 coins, X damage for each heads)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      MULTIPLE_COIN_FLIPS_PROMPT(store, state, effect.player, 3, results => {
        const heads = results.filter(r => r).length;
        effect.damage = 50 * heads;
      });
    }

    return state;
  }
}
