// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Claydol extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Baltoy';
  public cardType: CardType = P;
  public hp: number = 110;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Spinning Attack',
      cost: [C, C],
      damage: 40,
      text: ''
    },
    {
      name: 'Coinciding Figures',
      cost: [P, C, C],
      damage: 90,
      damageCalculation: '+' as '+',
      text: 'If you and your opponent have the same number of Benched Pokémon, this attack does 90 more damage.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'BRS';
  public setNumber: string = '59';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Claydol';
  public fullName: string = 'Claydol BRS 59';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Coinciding Figures
    // Ref: set-breakthrough/starmie.ts (Balance Bind - same bench count conditional)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const playerBenchCount = player.bench.filter(b => b.cards.length > 0).length;
      const opponentBenchCount = opponent.bench.filter(b => b.cards.length > 0).length;

      if (playerBenchCount === opponentBenchCount) {
        effect.damage += 90;
      }
    }

    return state;
  }
}
