import { Card } from '../../game/store/card/card';
import { AcerolasPremonitionArt, AggronVArt, AggronVMAXArt, ArceusVArt, ArceusVSTARArt, AxewArt, BibarelArt, BidoofArt, CherensCareArt, CleansingGlovesArt, CollapsedStadiumArt, CynthiasAmbitionArt, DoubleTurboEnergyArt, DruddigonArt, ElectabuzzArt, ElectivireArt, EmpoleonArt, EnteiVArt, FloatzelArt, GarchompArt, GloriaArt, GrotleArt, HaxorusArt, HeatranArt, KindlerArt, LaprasArt, LiepardArt, LumineonVArt, MagmaBasinArt, MagmortarArt, ManaphyArt, MarniesPrideArt, MinccinoArt, MoltresArt, PotHelmetArt, PurrloinArt, RaichuVArt, RaikouVArt, RoseannesBackupArt, ShayminVArt, ShayminVSTARArt, TeamYellsCheerArt, TorterraArt } from './card-images';


export const setBrilliantStars: Card[] = [

  new AcerolasPremonitionArt(),
  new AggronVArt(),
  new AggronVMAXArt(),
  new ArceusVArt(),
  new ArceusVSTARArt(),
  new AxewArt(),
  new BibarelArt(),
  new BidoofArt(),
  new CherensCareArt(),
  new CleansingGlovesArt(),
  new CollapsedStadiumArt(),
  new CynthiasAmbitionArt(),
  new DruddigonArt(),
  new DoubleTurboEnergyArt(),
  new ElectabuzzArt(),
  new ElectivireArt(),
  new EmpoleonArt(),
  new EnteiVArt(),
  new FloatzelArt(),
  new GarchompArt(),
  new GloriaArt(),
  new GrotleArt(),
  new HaxorusArt(),
  new HeatranArt(),
  new KindlerArt(),
  new LaprasArt(),
  new LumineonVArt(),
  new MagmaBasinArt(),
  new MagmortarArt(),
  new ManaphyArt(),
  new MarniesPrideArt(),
  new MinccinoArt(),
  new MoltresArt(),
  new RaichuVArt(),
  new RaikouVArt(),
  new RoseannesBackupArt(),
  new PurrloinArt(),
  new LiepardArt(),
  new ShayminVArt(),
  new ShayminVSTARArt(),
  new PotHelmetArt(),
  new TeamYellsCheerArt(),
  new TorterraArt()

];
