// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, WAS_POWER_USED } from '../../game/store/prefabs/prefabs';

export class Klinklang extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Klang';
  public cardType: CardType = M;
  public hp: number = 150;
  public weakness = [{ type: R }];
  public resistance = [{ type: G, value: -30 }];
  public retreat = [C, C, C];

  public powers = [  {
    name: 'Gear Wall',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Your Basic Pokémon take 20 less damage from attacks from your opponent\'s Pokémon (after applying Weakness and Resistance).'
  }];

  public attacks = [
    {
      name: 'Tumbling Attack',
      cost: [M, C, C],
      damage: 90,
      damageCalculation: '+' as '+',
      text: 'Flip a coin. If heads, this attack does 90 more damage.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'BRS';
  public setNumber: string = '104';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Klinklang';
  public fullName: string = 'Klinklang (BRS 104)';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Gear Wall
    // TODO: Your Basic Pokémon take 20 less damage from attacks from your opponent's Pokémon (after applying Weakness and Resistance).
    if (WAS_POWER_USED(effect, 0, this)) {
      // Implement ability here
    }

    // Attack 1: Tumbling Attack
    // TODO: Flip a coin. If heads, this attack does 90 more damage.
    if (WAS_ATTACK_USED(effect, 0, this)) {
      // Implement effect here
    }

    return state;
  }
}
