import { Card } from '../../game/store/card/card';
import { ArctibaxArt, ArtazonArt, BaxcaliburArt, BossOrdersArt, BramblinArt, BraveyCharmArt, CetitanArt, CetoddleArt, ChienPaoexArt, ChiYuexArt, ChoiceBeltArt, ClavellArt, CufantArt, DeinoArt, DeliveryDroneArt, DudunsparceArt, FightingAuLaitArt, FlamigoArt, FloragatoArt, ForretressexArt, Frigibax2Art, FrigibaxArt, GiacomoArt, GreatBallArt, GrushaArt, HoppipArt, HydreigonArt, IonoArt, JetEnergyArt, LokixArt, LuminousEnergyArt, LuxrayArt, MagnemiteArt, MeowscaradaexArt, MimikyuArt, MisdreavusArt, MurkrowArt, NoibatArt, NoivernexArt, OrthwormArt, PelipperArt, PinecoArt, ReversalEnergyArt, ShinxArt, SpiritombArt, SprigatitoArt, SquawkabillyexArt, SuperiorEnergyRetrievalArt, SuperRodArt, TadbulbArt, TherapeuticEnergyArt, TingLuexArt, TinkatinkArt, TinkatonArt, TinkatuffArt, WattrelArt, WingullArt, WoChienexArt, ZweilousArt } from './card-images';
import { ArctibaxIR, BaxcaliburIR, BossOrdersFA, BossOrdersSIR, ChiYuexFA, ChiYuexSIR, ChienPaoexFA, ChienPaoexHR, ChienPaoexSIR, ClavellFA, FlamigoIR, FrigibaxIR, GiacomoFA, GiacomoSIR, GrushaFA, GrushaSIR, IonoFA, IonoSIR, MeowscaradaexFA, MeowscaradaexHR, MeowscaradaexSIR, NoivernexFA, SquawkabillyexFA, SquawkabillyexSIR, SuperRodHR, SuperiorEnergyRetrievalHR, TingLuexFA, TingLuexHR, TingLuexSIR, WoChienexFA, WoChienexSIR } from './full-art';

//import { CalamitousSnowyMountain } from './new calamitous-snowy-mountain';

export const setPaldeaEvolved: Card[] = [

  new ArctibaxArt(),
  new ArtazonArt(),
  new BaxcaliburArt(),
  new BossOrdersArt(),
  new BramblinArt(),
  new BraveyCharmArt(),
  new CetitanArt(),
  new CetoddleArt(),
  new ChiYuexArt(),
  new ChienPaoexArt(),
  new ChoiceBeltArt(),
  new ClavellArt(),
  new CufantArt(),
  new DeinoArt(),
  new DeliveryDroneArt(),
  new DudunsparceArt(),
  new FightingAuLaitArt(),
  new FlamigoArt(),
  new FloragatoArt(),
  new ForretressexArt(),
  new FrigibaxArt(),
  new Frigibax2Art(),
  new GiacomoArt(),
  new GreatBallArt(),
  new GrushaArt(),
  new HoppipArt(),
  new HydreigonArt(),
  new IonoArt(),
  new JetEnergyArt(),
  new LokixArt(),
  new LuminousEnergyArt(),
  new LuxrayArt(),
  new MagnemiteArt(),
  new MeowscaradaexArt(),
  new MimikyuArt(),
  new MisdreavusArt(),
  new MurkrowArt(),
  new NoibatArt(),
  new NoivernexArt(),
  new OrthwormArt(),
  new PelipperArt(),
  new PinecoArt(),
  new ReversalEnergyArt(),
  new ShinxArt(),
  new SpiritombArt(),
  new SprigatitoArt(),
  new SquawkabillyexArt(),
  new SuperRodArt(),
  new SuperiorEnergyRetrievalArt(),
  new TadbulbArt(),
  new TherapeuticEnergyArt(),
  new TingLuexArt(),
  new TinkatinkArt(),
  new TinkatuffArt(),
  new TinkatonArt(),
  new WattrelArt(),
  new WingullArt(),
  new WoChienexArt(),
  new ZweilousArt(),

  // Full Art
  new ArctibaxIR(),
  new BaxcaliburIR(),
  new BossOrdersFA(),
  new ChiYuexFA(),
  new ChienPaoexFA(),
  new ClavellFA(),
  new FlamigoIR(),
  new FrigibaxIR(),
  new GiacomoFA(),
  new GrushaFA(),
  new IonoFA(),
  new MeowscaradaexFA(),
  new NoivernexFA(),
  new SquawkabillyexFA(),
  new SuperRodHR(),
  new SuperiorEnergyRetrievalHR(),
  new TingLuexFA(),
  new WoChienexFA(),
  new MeowscaradaexSIR(),
  new WoChienexSIR(),
  new ChiYuexSIR(),
  new ChienPaoexSIR(),
  new TingLuexSIR(),
  new SquawkabillyexSIR(),
  new BossOrdersSIR(),
  new GiacomoSIR(),
  new GrushaSIR(),
  new IonoSIR(),
  new MeowscaradaexHR(),
  new ChienPaoexHR(),
  new TingLuexHR(),


];
