import { Card } from '../../game/store/card/card';
import { ArctibaxArt, ArtazonArt, BaxcaliburArt, BossOrdersArt, BramblinArt, BraveyCharmArt, CetitanArt, CetoddleArt, ChienPaoexArt, ChiYuexArt, ChoiceBeltArt, CufantArt, DeinoArt, DeliveryDroneArt, DudunsparceArt, FightingAuLaitArt, FlamigoArt, Frigibax2Art, FrigibaxArt, GiacomoArt, GreatBallArt, GrushaArt, HydreigonArt, IonoArt, JetEnergyArt, LokixArt, LuminousEnergyArt, LuxrayArt, MagnemiteArt, MimikyuArt, MurkrowArt, NoibatArt, NoivernexArt, OrthwormArt, PelipperArt, ReversalEnergyArt, ShinxArt, SpiritombArt, SquawkabillyexArt, SuperiorEnergyRetrievalArt, SuperRodArt, TadbulbArt, TherapeuticEnergyArt, TingLuexArt, TinkatinkArt, TinkatonArt, TinkatuffArt, WattrelArt, WingullArt, WoChienexArt, ZweilousArt } from './card-images';

//import { CalamitousSnowyMountain } from './new calamitous-snowy-mountain';

export const setPaldeaEvolved: Card[] = [

  new ArctibaxArt(),
  new ArtazonArt(),
  new BaxcaliburArt(),
  new BossOrdersArt(),
  new BramblinArt(),
  new BraveyCharmArt(),
  new CetitanArt(),
  new CetoddleArt(),
  new ChiYuexArt(),
  new ChienPaoexArt(),
  new ChoiceBeltArt(),
  new CufantArt(),
  new DeinoArt(),
  new DeliveryDroneArt(),
  new DudunsparceArt(),
  new FightingAuLaitArt(),
  new FlamigoArt(),
  new FrigibaxArt(),
  new Frigibax2Art(),
  new GiacomoArt(),
  new GreatBallArt(),
  new GrushaArt(),
  new HydreigonArt(),
  new IonoArt(),
  new JetEnergyArt(),
  new LokixArt(),
  new LuminousEnergyArt(),
  new LuxrayArt(),
  new MagnemiteArt(),
  new MimikyuArt(),
  new MurkrowArt(),
  new NoibatArt(),
  new NoivernexArt(),
  new OrthwormArt(),
  new PelipperArt(),
  new ReversalEnergyArt(),
  new ShinxArt(),
  new SpiritombArt(),
  new SquawkabillyexArt(),
  new SuperRodArt(),
  new SuperiorEnergyRetrievalArt(),
  new TadbulbArt(),
  new TherapeuticEnergyArt(),
  new TingLuexArt(),
  new TinkatinkArt(),
  new TinkatuffArt(),
  new TinkatonArt(),
  new WattrelArt(),
  new WingullArt(),
  new WoChienexArt(),
  new ZweilousArt()

];
