// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { FLIP_A_COIN_UNTIL_YOU_GET_TAILS_DO_X_DAMAGE_PER_HEADS } from '../../game/store/prefabs/attack-effects';

export class Audino extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = C;
  public hp: number = 80;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Relaxed Roll',
      cost: [C, C, C],
      damage: 30,
      damageCalculation: 'x' as 'x',
      text: 'Flip a coin until you get tails. This attack does 30 damage times the number heads.'
    }
  ];

  public set: string = 'LTR';
  public setNumber: string = 'RC17';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Audino';
  public fullName: string = 'Audino LTR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Relaxed Roll
    // Ref: set-plasma-blast/lairon.ts (Iron Head)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      return FLIP_A_COIN_UNTIL_YOU_GET_TAILS_DO_X_DAMAGE_PER_HEADS(store, state, effect, 30);
    }

    return state;
  }
}
