// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { HealEffect } from '../../game/store/effects/game-effects';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { FLIP_A_COIN_UNTIL_YOU_GET_TAILS_DO_X_MORE_DAMAGE_PER_HEADS } from '../../game/store/prefabs/attack-effects';

export class Meloetta2 extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 90;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Magical Dance',
      cost: [C],
      damage: 0,
      text: 'Heal 30 damage from each of your Benched Pokémon.'
    },
    {
      name: 'Shooting Star Pirouette',
      cost: [F, C, C],
      damage: 40,
      damageCalculation: '+' as const,
      text: 'Flip a coin until you get tails. This attack does 30 more damage for each heads.'
    }
  ];

  public set: string = 'LTR';
  public setNumber: string = '86';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Meloetta';
  public fullName: string = 'Meloetta LTR 86';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Magical Dance
    // Ref: set-plasma-blast/lapras.ts (Cleanse Away)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      player.bench.forEach(benched => {
        if (benched.cards.length > 0) {
          const healEffect = new HealEffect(player, benched, 30);
          store.reduceEffect(state, healEffect);
        }
      });
    }

    // Attack 2: Shooting Star Pirouette
    // Ref: set-plasma-storm/torterra.ts (Rumble Stomp)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      return FLIP_A_COIN_UNTIL_YOU_GET_TAILS_DO_X_MORE_DAMAGE_PER_HEADS(store, state, effect, 30);
    }

    return state;
  }
}
