// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType } from '../../game/store/card/card-types';
import { StateUtils, StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Ninetales extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Vulpix';
  public cardType: CardType = R;
  public hp: number = 90;
  public weakness = [{ type: W }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Color Coordination',
      cost: [C, C, C],
      damage: 50,
      damageCalculation: '+' as const,
      text: 'If this Pokémon has any basic Energy attached to it that is the same type as the Defending Pokémon, this attack does 40 more damage.'
    }
  ];

  public set: string = 'LTR';
  public setNumber: string = '21';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Ninetales';
  public fullName: string = 'Ninetales LTR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Color Coordination
    // Refs: set-plasma-freeze/quagsire.ts (Mud Gun - energy type check), set-jungle/electrode.ts (defending type check)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      const defendingCard = opponent.active.getPokemonCard();

      if (defendingCard) {
        const defendingType = defendingCard.cardType;
        const checkEnergy = new CheckProvidedEnergyEffect(player);
        store.reduceEffect(state, checkEnergy);

        const hasMatchingEnergy = checkEnergy.energyMap.some(em =>
          em.card.energyType === EnergyType.BASIC
          && em.provides.includes(defendingType)
        );

        if (hasMatchingEnergy) {
          effect.damage += 40;
        }
      }
    }

    return state;
  }
}
