// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, PlayerType, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';
import { CheckRetreatCostEffect, CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';

export class Serperior extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Servine';
  public cardType: CardType = G;
  public hp: number = 140;
  public weakness = [{ type: R }];
  public retreat = [C, C];

  public powers = [  {
    name: 'Royal Garden',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'If this Pokémon has any [G] Energy attached to it, this Pokémon has no Retreat Cost.'
  }];

  public attacks = [
    {
      name: 'Solar Beam',
      cost: [G, C, C],
      damage: 80,
      text: ''
    }
  ];

  public set: string = 'LTR';
  public setNumber: string = 'RC3';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Serperior';
  public fullName: string = 'Serperior LTR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Royal Garden
    // Ref: set-dark-explorers/darkrai-ex.ts (Dark Cloak)
    if (effect instanceof CheckRetreatCostEffect) {
      const player = effect.player;

      // Only applies to this Serperior itself
      if (effect.player.active.getPokemonCard() !== this) {
        return state;
      }

      // Check if this Serperior is in play
      let isInPlay = false;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card) => {
        if (card === this) {
          isInPlay = true;
        }
      });

      if (!isInPlay) {
        return state;
      }

      // Check if ability is blocked
      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Check if this Pokemon has Grass energy attached
      const checkProvidedEnergyEffect = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkProvidedEnergyEffect);

      const energyMap = checkProvidedEnergyEffect.energyMap;
      const hasGrassEnergy = StateUtils.checkEnoughEnergy(energyMap, [CardType.GRASS]);

      if (hasGrassEnergy) {
        effect.cost = [];
      }
    }

    return state;
  }
}
