// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { CheckRetreatCostEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED } from '../../game/store/prefabs/attack-effects';

export class Ariados extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Spinarak';
  public cardType: CardType = D;
  public hp: number = 90;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'String Bind',
      cost: [D],
      damage: 10,
      damageCalculation: '+' as '+',
      text: 'This attack does 30 more damage for each Colorless in your opponent\'s Active Pokémon\'s Retreat Cost.'
    },
    {
      name: 'Venomous Fang',
      cost: [D, C, C],
      damage: 80,
      text: 'Your opponent\'s Active Pokémon is now Poisoned.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'LOR';
  public setNumber: string = '113';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Ariados';
  public fullName: string = 'Ariados (LOR 113)';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: String Bind
    // Ref: set-unbroken-bonds/krookodile.ts (Chomp Chomp Panic - CheckRetreatCostEffect Colorless counting)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const checkRetreat = new CheckRetreatCostEffect(opponent);
      store.reduceEffect(state, checkRetreat);
      const colorlessCount = checkRetreat.cost.filter(c => c === CardType.COLORLESS).length;

      effect.damage += 30 * colorlessCount;
    }

    // Attack 2: Venomous Fang
    // Ref: AGENTS-patterns.md (YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED(store, state, effect);
    }

    return state;
  }
}
