import { Card } from '../../game/store/card/card';
import { ArezuArt, BouffalantArt, BoxOfDisasterArt, ColresssExperimentArt, ComfeyArt, CramorantArt, CresseliaArt, DamagePumpArt, DelphoxVArt, DrapionVArt, EnergyLottoArt, GengarArt, GiftEnergyArt, GiratinaVArt, GiratinaVSTARArt, HisuianGoodraVArt, HisuianGoodraVSTARArt, HisuianZoroarkVArt, HisuianZoroarkVSTARArt, JynxArt, KyuremVArt, KyuremVMAXArt, LadyArt, LostCityArt, LostVacuumArt, MagnezoneVArt, MagnezoneVSTARArt, MawileArt, MirageGateArt, PanicMaskArt, PidgeotVArt, RadiantGardevoirArt, RadiantHisuianSneaslerArt, RotomVArt, SableyeArt, SnorlaxArt, VoloArt } from './card-images';


export const setLostOrigin: Card[] = [
  
  new BouffalantArt(),
  new ColresssExperimentArt(),
  new ComfeyArt(),
  new CramorantArt(),
  new CresseliaArt(),
  new DelphoxVArt(),
  new DrapionVArt(),
  new GengarArt(),
  new GiftEnergyArt(),
  new GiratinaVArt(),
  new GiratinaVSTARArt(),
  new HisuianGoodraVArt(),
  new HisuianGoodraVSTARArt(),
  new HisuianZoroarkVArt(),
  new HisuianZoroarkVSTARArt(),
  new JynxArt(),
  new KyuremVArt(),
  new KyuremVMAXArt(),
  new LadyArt(),
  new LostCityArt(),
  new LostVacuumArt(),
  new MawileArt(),
  new MirageGateArt(),
  new PidgeotVArt(),
  new RadiantHisuianSneaslerArt(),
  new RadiantGardevoirArt(),
  new RotomVArt(),
  new SableyeArt(),  
  new SnorlaxArt(),
  new VoloArt(),
  new MagnezoneVArt(),
  new MagnezoneVSTARArt(),
  new DamagePumpArt(),
  new BoxOfDisasterArt(),
  new EnergyLottoArt(),
  new PanicMaskArt(),
  new ArezuArt(),
];
