import { Card } from '../../game/store/card/card';
import { ArezuArt, BanetteArt, BouffalantArt, BoxOfDisasterArt, ColresssExperimentArt, ComfeyArt, CramorantArt, CresseliaArt, DamagePumpArt, DelphoxVArt, DrapionVArt, DrapionVSTARArt, GengarArt, GiftEnergyArt, GiratinaVArt, GiratinaVSTARArt, HisuianBasculegionArt, HisuianGoodraVArt, HisuianGoodraVSTARArt, HisuianZoroarkArt, HisuianZoroarkVArt, HisuianZoroarkVSTARArt, HisuianZoruaArt, JynxArt, KingdraArt, KyuremVArt, KyuremVMAXArt, LadyArt, LostCityArt, LostVacuumArt, MachampArt, MachopArt, MagnezoneVArt, MagnezoneVSTARArt, MawileArt, MirageGateArt, MissFortuneSistersArt, PanicMaskArt, PidgeotVArt, RadiantGardevoirArt, RadiantHisuianSneaslerArt, RotomVArt, SableyeArt, SilcoonArt, SnorlaxArt, ThortonArt, VoloArt } from './card-images';


export const setLostOrigin: Card[] = [

  new BanetteArt(),
  new BouffalantArt(),
  new ColresssExperimentArt(),
  new ComfeyArt(),
  new CramorantArt(),
  new CresseliaArt(),
  new DelphoxVArt(),
  new DrapionVArt(),
  new GengarArt(),
  new GiftEnergyArt(),
  new GiratinaVArt(),
  new GiratinaVSTARArt(),
  new HisuianBasculegionArt(),
  new HisuianGoodraVArt(),
  new HisuianGoodraVSTARArt(),
  new HisuianZoroarkVArt(),
  new HisuianZoroarkVSTARArt(),
  new HisuianZoruaArt(),
  new HisuianZoroarkArt(),
  new JynxArt(),
  new KingdraArt(),
  new KyuremVArt(),
  new KyuremVMAXArt(),
  new LadyArt(),
  new LostCityArt(),
  new LostVacuumArt(),
  new MachopArt(),
  new MachampArt(),
  new MawileArt(),
  new MirageGateArt(),
  new PidgeotVArt(),
  new RadiantHisuianSneaslerArt(),
  new RadiantGardevoirArt(),
  new RotomVArt(),
  new SableyeArt(),
  new SilcoonArt(),
  new SnorlaxArt(),
  new VoloArt(),
  new MissFortuneSistersArt(),
  new MagnezoneVArt(),
  new MagnezoneVSTARArt(),
  new DamagePumpArt(),
  new BoxOfDisasterArt(),
  new PanicMaskArt(),
  new ArezuArt(),
  new DrapionVSTARArt(),
  new ThortonArt(),
];
