// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { ADD_POISON_TO_PLAYER_ACTIVE, AFTER_ATTACK, WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { CardType, Stage } from '../../game/store/card/card-types';
import { StateUtils } from '../../game/store/state-utils';
import { ChoosePokemonPrompt } from '../../game/store/prompts/choose-pokemon-prompt';
import { GameMessage } from '../../game/game-message';
import { PutDamageEffect } from '../../game/store/effects/attack-effects';
import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Effect } from '../../game/store/effects/effect';
import { PlayerType, SlotType, State, StoreLike } from '../../game';
export class Roserade extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Roselia';
  public cardType: CardType = G;
  public hp: number = 120;
  public weakness = [{ type: R }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Poisonous Whip',
      cost: [G],
      damage: 30,
      text: 'Your opponent\'s Active Pokémon is now Poisoned.'
    },
    {
      name: 'Assassin\'s Rose',
      cost: [G, C],
      damage: 60,
      text: 'If your opponent\'s Active Pokémon is affected by a Special Condition, this attack also does 60 damage to 1 of your opponent\'s Benched Pokémon. (Don\'t apply Weakness and Resistance for Benched Pokémon.)'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'LOR';
  public setNumber: string = '15';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Roserade';
  public fullName: string = 'Roserade LOR 15';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Poisonous Whip
    // Ref: AGENTS-patterns.md (Poisoned)
    if (AFTER_ATTACK(effect, 0, this)) {
      ADD_POISON_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    // Attack 2: Assassin's Rose
    // Ref: set-astral-radiance/mamoswine.ts (bench damage pattern)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Check if opponent's Active Pokemon is affected by a Special Condition
      if (opponent.active.specialConditions.length > 0) {
        const hasBenched = opponent.bench.some(b => b.cards.length > 0);
        if (hasBenched) {
          store.prompt(state, new ChoosePokemonPrompt(
            player.id,
            GameMessage.CHOOSE_POKEMON_TO_DAMAGE,
            PlayerType.TOP_PLAYER,
            [SlotType.BENCH],
            { min: 1, max: 1, allowCancel: false }
          ), selected => {
            if (selected && selected.length > 0) {
              const damageEffect = new PutDamageEffect(effect, 60);
              damageEffect.target = selected[0];
              store.reduceEffect(state, damageEffect);
            }
          });
        }
      }
    }

    return state;
  }
}
