// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, DRAW_CARDS, MULTIPLE_COIN_FLIPS_PROMPT } from '../../game/store/prefabs/prefabs';

export class MrMime extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = Y;
  public hp: number = 90;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Happy Mime',
      cost: [Y],
      damage: 0,
      text: 'Each player draws a card.'
    },
    {
      name: 'Double Slap',
      cost: [Y, Y],
      damage: 40,
      damageCalculation: 'x' as 'x',
      text: 'Flip 2 coins. This attack does 40 damage for each heads.'
    }
  ];

  public set: string = 'HIF';
  public setNumber: string = '43';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mr. Mime';
  public fullName: string = 'Mr. Mime HIF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Happy Mime
    // Ref: set-stellar-crown/comfey.ts (Flower Shower)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      DRAW_CARDS(player, 1);
      DRAW_CARDS(opponent, 1);
    }

    // Attack 2: Double Slap
    // Ref: set-unified-minds/meloetta.ts (Double Slap pattern)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      MULTIPLE_COIN_FLIPS_PROMPT(store, state, player, 2, results => {
        const heads = results.filter(r => r).length;
        effect.damage = 40 * heads;
      });
    }

    return state;
  }
}
