/**
 * Exhaustive list of marker names known to be attack effects.
 * Used by `Marker.removeAttackEffects()` as a migration bridge:
 * markers matching EITHER `sourceType === 'attack'` OR name in this set
 * are removed. As individual cards get migrated to include `sourceType: 'attack'`,
 * they can eventually be removed from this whitelist.
 */
export const KNOWN_ATTACK_EFFECT_MARKERS = new Set([
  // PokemonCardList-level attack effects
  'ATTACK_USED_MARKER',
  'ATTACK_USED_2_MARKER',
  'DEFENDING_POKEMON_CANNOT_RETREAT_MARKER',
  'DEFENDING_POKEMON_CANNOT_ATTACK_MARKER',
  'PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER',
  'CLEAR_PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER',
  'DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER',
  'CLEAR_DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER',
  'DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER',
  'CLEAR_DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER',
  'PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER',
  'CLEAR_PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER',
  'PREVENT_ALL_DAMAGE_BY_POKEMON_WITH_ABILITIES_MARKER',
  'PREVENT_ALL_DAMAGE_BY_POKEMON_WITH_ABILITIES',
  'OPPONENTS_POKEMON_CANNOT_USE_THAT_ATTACK_MARKER',
  'OPPONENT_CANNOT_PLAY_ITEM_CARDS_MARKER',
  'PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER',
  'CLEAR_PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER',
  'PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN',
  'CLEAR_PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN',
  'PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN',
  'CLEAR_PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN',
  'NEXT_TURN_MORE_DAMAGE_MARKER',
  'NEXT_TURN_MORE_DAMAGE_MARKER_2',
  'DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_DEALS_LESS_DAMAGE_MARKER',
  'CLEAR_DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_DEALS_LESS_DAMAGE_MARKER',
  // Player-level attack effect locks
  'ATTACK_EFFECT_ITEM_LOCK',
  'ATTACK_EFFECT_SUPPORTER_LOCK',
  'ATTACK_EFFECT_TOOL_LOCK',
  'ATTACK_EFFECT_STADIUM_LOCK',
  'ATTACK_EFFECT_SPECIAL_ENERGY_LOCK',
]);

/**
 * Player-level markers that are scoped to the active Pokemon — they should be
 * removed when a Pokemon leaves active (switching). These are distinct from
 * player-scoped locks (item lock, tool lock, etc.) which persist across switches.
 *
 * Used by `Marker.removePokemonScopedMarkers()` as a migration bridge alongside
 * the `targetScope === 'pokemon'` metadata check.
 */
export const KNOWN_POKEMON_SCOPED_PLAYER_MARKERS = new Set([
  'ATTACK_USED_MARKER',
  'ATTACK_USED_2_MARKER',
  'KNOCKOUT_MARKER',
  'CLEAR_KNOCKOUT_MARKER',
  'OPPONENTS_POKEMON_CANNOT_USE_THAT_ATTACK_MARKER',
  'DEFENDING_POKEMON_CANNOT_RETREAT_MARKER',
  'PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER',
  'DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_DEALS_LESS_DAMAGE_MARKER',
  'CLEAR_DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_DEALS_LESS_DAMAGE_MARKER',
  'DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER',
  'CLEAR_DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER',
  'DEFENDING_POKEMON_CANNOT_ATTACK_MARKER',
  'DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER',
  'CLEAR_DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER',
  'PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER',
  'CLEAR_PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER',
  'PREVENT_ALL_DAMAGE_BY_POKEMON_WITH_ABILITIES',
  'PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER',
  'CLEAR_PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER',
]);

export const POKEMON_MARKERS = {
  ATTACK_USED_MARKER: 'ATTACK_USED_MARKER',
  ATTACK_USED_2_MARKER: 'ATTACK_USED_2_MARKER',
  CLEAR_KNOCKOUT_MARKER: 'CLEAR_KNOCKOUT_MARKER',
  CLEAR_KNOCKOUT_MARKER_2: 'CLEAR_KNOCKOUT_MARKER_2',
  KNOCKOUT_MARKER: 'KNOCKOUT_MARKER',
  PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN: 'PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN',
  CLEAR_PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN: 'CLEAR_PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN',
  PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN: 'PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN',
  CLEAR_PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN: 'CLEAR_PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN',
  OPPONENTS_POKEMON_CANNOT_USE_THAT_ATTACK_MARKER: 'OPPONENTS_POKEMON_CANNOT_USE_THAT_ATTACK_MARKER',
  DEFENDING_POKEMON_CANNOT_RETREAT_MARKER: 'DEFENDING_POKEMON_CANNOT_RETREAT_MARKER',
  PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER: 'PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER',
  CLEAR_PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER: 'CLEAR_PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER',
  DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER: 'DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER',
  CLEAR_DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER: 'CLEAR_DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER',
  DEFENDING_POKEMON_CANNOT_ATTACK_MARKER: 'DEFENDING_POKEMON_CANNOT_ATTACK_MARKER',
  DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER: 'DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER',
  CLEAR_DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER: 'CLEAR_DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER',
  PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER: 'PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER',
  CLEAR_PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER: 'CLEAR_PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER',
  PREVENT_ALL_DAMAGE_BY_POKEMON_WITH_ABILITIES_MARKER: 'PREVENT_ALL_DAMAGE_BY_POKEMON_WITH_ABILITIES_MARKER',
  OPPONENT_CANNOT_PLAY_ITEM_CARDS_MARKER: 'OPPONENT_CANNOT_PLAY_ITEM_CARDS_MARKER',
  PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER: 'PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER',
  CLEAR_PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER: 'CLEAR_PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER',
  UNRELENTING_ONSLAUGHT_MARKER: 'UNRELENTING_ONSLAUGHT_MARKER',
  UNRELENTING_ONSLAUGHT_2_MARKER: 'UNRELENTING_ONSLAUGHT_2_MARKER'
};