import { Format, Archetype } from '../card/card-types';

export const THEME_DECKS = [
  {
    id: -1,
    name: 'Soaring Skies',
    cards: ['Alolan Grimer (UNM 127)', 'Alolan Grimer (UNM 127)', 'Chinchou (CES 49)', 'Chinchou (CES 49)', 'Lanturn (CES 50)', 'Lanturn (CES 50)', 'Dratini (UNM 148)', 'Dratini (UNM 148)', 'Dratini (UNM 148)', 'Dragonair (UNM 150)', 'Dragonair (UNM 150)', 'Dragonair (UNM 150)', 'Dragonite (UNM 151)', 'Dragonite (UNM 151)', 'Pidgey (TEU 121)', 'Pidgey (TEU 121)', 'Pidgey (TEU 121)', 'Pidgeotto (TEU 123)', 'Pidgeotto (TEU 123)', 'Pidgeot (TEU 124)', 'Thundurus (UNM 68)', 'Thundurus (UNM 68)', 'Tornadus (UNM 178)', 'Tornadus (UNM 178)', 'Bug Catcher (UNM 189)', 'Bug Catcher (UNM 189)', 'Cynthia (UPR 119)', 'Cynthia (UPR 119)', 'Fisherman (CES 130)', 'Hau (CES 132)', 'Hau (CES 132)', 'Lillie (UPR 125)', 'Lillie (UPR 125)', 'Pokémon Fan Club (UPR 133)', 'Pokémon Fan Club (UPR 133)', 'Tate & Liza (CES 148)', 'Energy Recycle System (CES 128)', 'Pokémon Communication (TEU 152)', 'Pokémon Communication (TEU 152)', 'Super Scoop Up (CES 146)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)'],
    format: [Format.THEME],
    isValid: true,
    cardTypes: '[]',
    manualArchetype1: Archetype.DRAGONITE,
    manualArchetype2: Archetype.PIDGEOTTO,
  },
  {
    id: -2,
    name: 'Relentless Flame',
    cards: ['Charmander (TEU 12)', 'Charmander (TEU 12)', 'Charmander (TEU 12)', 'Charmeleon (TEU 13)', 'Charmeleon (TEU 13)', 'Farfetch\'d (TEU 127)', 'Farfetch\'d (TEU 127)', 'Farfetch\'d (TEU 127)', 'Charizard (TEU 14)', 'Charizard (TEU 14)', 'Nidoran F (TEU 54)', 'Nidoran F (TEU 54)', 'Nidoran F (TEU 54)', 'Nidorina (TEU 55)', 'Nidorina (TEU 55)', 'Ponyta (TEU 17)', 'Ponyta (TEU 17)', 'Ponyta (TEU 17)', 'Nidoqueen (TEU 56)', 'Nidoqueen (TEU 56)', 'Rapidash (TEU 18)', 'Rapidash (TEU 18)', 'Brock\'s Grit (TEU 135)', 'Brock\'s Grit (TEU 135)', 'Copycat (CES 127)', 'Copycat (CES 127)', 'Cynthia (UPR 119)', 'Cynthia (UPR 119)', 'Hau (CES 132)', 'Hau (CES 132)', 'Pokémon Fan Club (UPR 133)', 'Pokémon Fan Club (UPR 133)', 'Professor Kukui (SUM 128)', 'Professor Kukui (SUM 128)', 'Nest Ball (SUM 123)', 'Nest Ball (SUM 123)', 'Super Scoop Up (CES 146)', 'Super Scoop Up (CES 146)', 'Timer Ball (SUM 134)', 'Timer Ball (SUM 134)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)', 'Fire Energy (SUM R)'],
    format: [Format.THEME],
    isValid: true,
    cardTypes: '[]',
    manualArchetype1: Archetype.CHARIZARD,
    manualArchetype2: Archetype.NIDOQUEEN,
  },
  {
    id: -3,
    name: 'Charizard',
    cards: ['Charmander (VIV 23)', 'Charmander (VIV 23)', 'Charmander (VIV 23)', 'Charmeleon (VIV 24)', 'Charmeleon (VIV 24)', 'Charmeleon (VIV 24)', 'Lugia (DAA 140)', 'Charizard (SWSH 66)', 'Charizard (VIV 25)', 'Slugma (VIV 27)', 'Slugma (VIV 27)', 'Slugma (VIV 27)', 'Sudowoodo (SSH 100)', 'Sudowoodo (SSH 100)', 'Magcargo (VIV 28)', 'Magcargo (VIV 28)', 'Yanma (VIV 6)', 'Yanma (VIV 6)', 'Yanma (VIV 6)', 'Yanmega (VIV 7)', 'Yanmega (VIV 7)', 'Bede (SSH 157)', 'Bede (SSH 157)', 'Dan (RCL 158)', 'Dan (RCL 158)', 'Hop (SSH 165)', 'Hop (SSH 165)', 'Hop (SSH 165)', 'Hop (SSH 165)', 'Leon (VIV 154)', 'Leon (VIV 154)', 'Marnie (SSH 208)', 'Marnie (SSH 208)', 'Sonia (CPA 65)', 'Sonia (CPA 65)', 'Evolution Incense (SSH 163)', 'Great Ball (SSH 164)', 'Great Ball (SSH 164)', 'Ordinary Rod (SSH 171)', 'Ordinary Rod (SSH 171)', 'Switch (SSH 183)', 'Switch (SSH 183)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)', 'Fire Energy (SSH R)'],
    format: [Format.THEME],
    isValid: true,
    cardTypes: '[]',
    manualArchetype1: Archetype.CHARIZARD,
  },
  {
    id: -4,
    name: 'Twilight Rogue',
    cards: ['Dusknoir (BUS 53)', 'Dusknoir (BUS 53)', 'Duskull (BUS 51)', 'Duskull (BUS 51)', 'Duskull (BUS 51)', 'Furfrou (FLI 99)', 'Dusclops (BUS 52)', 'Dusclops (BUS 52)', 'Inkay (FLI 50)', 'Inkay (FLI 50)', 'Malamar (FLI 51)', 'Lycanroc (SMP 118)', 'Rockruff (FLI 75)', 'Rockruff (FLI 75)', 'Rockruff (FLI 75)', 'Salandit (CIN 46)', 'Salandit (CIN 46)', 'Lycanroc (FLI 76)', 'Salazzle (CIN 47)', 'Salazzle (CIN 47)', 'Solrock (BUS 69)', 'Cynthia (UPR 119)', 'Hau (SUM 120)', 'Hau (SUM 120)', 'Lady (FLI 109)', 'Lillie (UPR 125)', 'Pokémon Fan Club (UPR 133)', 'Professor Kukui (SUM 128)', 'Professor Kukui (SUM 128)', 'Escape Rope (BUS 114)', 'Field Blower (GRI 125)', 'Nest Ball (SUM 123)', 'Nest Ball (SUM 123)', 'Rescue Stretcher (GRI 130)', 'Super Scoop Up (CES 146)', 'Timer Ball (SUM 134)', 'Timer Ball (SUM 134)', 'Escape Board (UPR 122)', 'Weakness Policy (BUS 126)', 'Brooklet Hill (GRI 120)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)'],
    format: [Format.THEME],
    isValid: true,
    cardTypes: '[]',
    manualArchetype1: Archetype.LYCANROC,
    manualArchetype2: Archetype.DUSKNOIR,
  },
  {
    id: -5,
    name: 'Towering Heights',
    cards: ['Gible (UNM 112)', 'Gible (UNM 112)', 'Gible (UNM 112)', 'Gabite (UNM 113)', 'Gabite (UNM 113)', 'Gabite (UNM 113)', 'Garchomp (UNM 114)', 'Garchomp (UNM 114)', 'Groudon (CEC 113)', 'Groudon (CEC 113)', 'Mew (UNB 76)', 'Passimian (CEC 125)', 'Passimian (CEC 125)', 'Throh (CEC 118)', 'Throh (CEC 118)', 'Tympole (CEC 58)', 'Tympole (CEC 58)', 'Tympole (CEC 58)', 'Palpitoad (CEC 116)', 'Palpitoad (CEC 116)', 'Palpitoad (CEC 116)', 'Seismitoad (CEC 117)', 'Seismitoad (CEC 117)', 'Bug Catcher (UNM 189)', 'Bug Catcher (UNM 189)', 'Cynthia (UPR 119)', 'Cynthia (UPR 119)', 'Hau (CES 132)', 'Hau (CES 132)', 'Lady (FLI 109)', 'Lillie (UPR 125)', 'Lillie (UPR 125)', 'Pokémon Fan Club (UPR 133)', 'Pokémon Fan Club (UPR 133)', 'Tate & Liza (CES 148)', 'Tate & Liza (CES 148)', 'Pokémon Communication (TEU 152)', 'Pokémon Communication (TEU 152)', 'Super Scoop Up (CES 146)', 'Super Scoop Up (CES 146)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Fighting Energy (SUM F)', 'Draw Energy (CEC 209)', 'Draw Energy (CEC 209)'],
    format: [Format.THEME],
    isValid: true,
    cardTypes: '[]',
    manualArchetype1: Archetype.GROUDON,
    manualArchetype2: Archetype.GARCHOMP,
  },
  {
    id: -6,
    name: 'Unseen Depths',
    cards: ['Aipom (CEC 169)', 'Aipom (CEC 169)', 'Aipom (CEC 169)', 'Ambipom (CEC 170)', 'Ambipom (CEC 170)', 'Kyogre (CEC 53)', 'Kyogre (CEC 53)', 'Phione (CEC 57)', 'Piplup (CEC 54)', 'Piplup (CEC 54)', 'Piplup (CEC 54)', 'Prinplup (CEC 55)', 'Prinplup (CEC 55)', 'Prinplup (CEC 55)', 'Empoleon (CEC 56)', 'Empoleon (CEC 56)', 'Psyduck (CEC 40)', 'Psyduck (CEC 40)', 'Psyduck (CEC 40)', 'Golduck (CEC 41)', 'Golduck (CEC 41)', 'Pyukumuku (UNB 53)', 'Pyukumuku (UNB 53)', 'Cynthia (UPR 119)', 'Cynthia (UPR 119)', 'Hau (CES 132)', 'Hau (CES 132)', 'Lillie (UPR 125)', 'Lillie (UPR 125)', 'Pokémon Fan Club (UPR 133)', 'Pokémon Fan Club (UPR 133)', 'Roller Skater (CEC 203)', 'Roller Skater (CEC 203)', 'Tate & Liza (CES 148)', 'Tate & Liza (CES 148)', 'Pokémon Communication (TEU 152)', 'Pokémon Communication (TEU 152)', 'Super Scoop Up (CES 146)', 'Super Scoop Up (CES 146)', 'Viridian Forest (TEU 156)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Water Energy (SUM W)', 'Draw Energy (CEC 209)', 'Draw Energy (CEC 209)'],
    format: [Format.THEME],
    isValid: true,
    cardTypes: '[]',
    manualArchetype1: Archetype.KYOGRE,
    manualArchetype2: Archetype.EMPOLEON,
  },
  {
    id: -7,
    name: 'Laser Focus',
    cards: ['Audino (UNM 177)', 'Audino (UNM 177)', 'Dedenne (UNM 145)', 'Dedenne (UNM 145)', 'Inkay (FLI 50)', 'Inkay (FLI 50)', 'Malamar (FLI 51)', 'Malamar (FLI 51)', 'Mesprit (UNM 84)', 'Mesprit (UNM 84)', 'Necrozma (UNM 101)', 'Necrozma (UNM 101)', 'Tauros (UNM 164)', 'Tauros (UNM 164)', 'Type: Null (UNM 183)', 'Type: Null (UNM 183)', 'Type: Null (UNM 183)', 'Silvally (UNM 184)', 'Silvally (UNM 184)', 'Yungoos (UNM 180)', 'Yungoos (UNM 180)', 'Yungoos (UNM 180)', 'Gumshoos (UNM 181)', 'Gumshoos (UNM 181)', 'Bug Catcher (UNM 189)', 'Bug Catcher (UNM 189)', 'Cynthia (UPR 119)', 'Cynthia (UPR 119)', 'Hau (CES 132)', 'Hau (CES 132)', 'Lillie (UPR 125)', 'Lillie (UPR 125)', 'Pokémon Fan Club (UPR 133)', 'Pokémon Fan Club (UPR 133)', 'Tate & Liza (CES 148)', 'Mysterious Treasure (FLI 113)', 'Mysterious Treasure (FLI 113)', 'Super Scoop Up (CES 146)', 'U-Turn Board (UNM 211)', 'U-Turn Board (UNM 211)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Psychic Energy (SUM P)', 'Weakness Guard Energy (UNM 213)', 'Weakness Guard Energy (UNM 213)'],
    format: [Format.THEME],
    isValid: true,
    cardTypes: '[]',
    manualArchetype1: Archetype.NECROZMA,
    manualArchetype2: Archetype.MALAMAR,
  },
  {
    id: -8,
    name: 'Storm Caller',
    cards: ['Blitzle (LOT 81)', 'Blitzle (LOT 81)', 'Blitzle (LOT 81)', 'Zebstrika (LOT 82)', 'Furfrou (FLI 99)', 'Mareep (LOT 76)', 'Mareep (LOT 76)', 'Mareep (LOT 76)', 'Flaaffy (LOT 77)', 'Flaaffy (LOT 77)', 'Ampharos (LOT 78)', 'Ampharos (LOT 78)', 'Poipole (LOT 107)', 'Poipole (LOT 107)', 'Poipole (LOT 107)', 'Naganadel (LOT 108)', 'Naganadel (LOT 108)', 'Raikou (LOT 79)', 'Raikou (LOT 79)', 'Smeargle (LOT 157)', 'Copycat (CES 127)', 'Hau (CES 132)', 'Hau (CES 132)', 'Kahili (LOT 179)', 'Lady (FLI 109)', 'Lillie (UPR 125)', 'Pokémon Fan Club (UPR 133)', 'Professor Kukui (SUM 128)', 'Professor Kukui (SUM 128)', 'Tate & Liza (CES 148)', 'Energy Switch (CES 129)', 'Escape Rope (BUS 114)', 'Nest Ball (SUM 123)', 'Nest Ball (SUM 123)', 'Rescue Stretcher (GRI 130)', 'Rescue Stretcher (GRI 130)', 'Super Scoop Up (CES 146)', 'Timer Ball (SUM 134)', 'Timer Ball (SUM 134)', 'Ultra Ball (SUM 135)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)', 'Lightning Energy (SUM L)'],
    format: [Format.THEME],
    isValid: true,
    cardTypes: '[]',
    manualArchetype1: Archetype.RAIKOU,
    manualArchetype2: Archetype.AMPHAROS,
  }
]; 