// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Breloom extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Shroomish';
  public cardType: CardType = G;
  public hp: number = 120;
  public weakness = [{ type: R }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Headbutt',
      cost: [G],
      damage: 30,
      text: ''
    },
    {
      name: 'Impact Blow',
      cost: [G, G, C],
      damage: 150,
      text: 'During your next turn, this Pokémon can\'t use Impact Blow.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'FST';
  public setNumber: string = '5';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Breloom';
  public fullName: string = 'Breloom (FST 5)';
  public legacyFullName = 'Breloom FST';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Impact Blow
    // Ref: set-plasma-blast/escavalier.ts (cannotUseAttacksNextTurnPending pattern)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      player.active.cannotUseAttacksNextTurnPending.push('Impact Blow');
    }

    return state;
  }
}
