// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class BreloomV extends PokemonCard {
  public tags = [CardTag.POKEMON_V, CardTag.SINGLE_STRIKE];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 210;
  public weakness = [{ type: R }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Counter',
      cost: [G, C],
      damage: 20,
      damageCalculation: '+' as '+',
      text: 'If this Pokémon was damaged by an attack during your opponent\'s last turn, this attack does that much more damage.'
    },
    {
      name: 'Mach Cross',
      cost: [G, G, C],
      damage: 140,
      text: ''
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'FST';
  public setNumber: string = '6';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Breloom V';
  public fullName: string = 'Breloom V FST 6';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Counter
    // Ref: set-pokemon-go/conkeldurr-v.ts (Counter - damageTakenLastTurn)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const activeCard = effect.player.active.getPokemonCard();
      if (activeCard !== undefined && activeCard.damageTakenLastTurn !== undefined) {
        effect.damage += activeCard.damageTakenLastTurn;
      }
    }

    return state;
  }
}
