// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, JUST_EVOLVED, IS_ABILITY_BLOCKED, COIN_FLIP_PROMPT, DISCARD_TOP_X_CARDS_FROM_YOUR_DECK } from '../../game/store/prefabs/prefabs';
import { DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON } from '../../game/store/prefabs/attack-effects';

export class Feraligatr extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Croconaw';
  public cardType: CardType = W;
  public hp: number = 170;
  public weakness = [{ type: L }];
  public retreat = [C, C, C];

  public powers = [{
    name: 'Rowdy',
    powerType: PowerType.ABILITY,
    text: 'When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you must flip a coin. If heads, discard the top 5 cards of your opponent\'s deck. If tails, discard the top 5 cards of your deck.'
  }];

  public attacks = [
    {
      name: 'Crunch',
      cost: [W, W, C],
      damage: 140,
      text: 'Discard an Energy from your opponent\'s Active Pokémon.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'FST';
  public setNumber: string = '57';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Feraligatr';
  public fullName: string = 'Feraligatr FST 57';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Rowdy (on-evolve - coin flip, discard 5 from opponent's or own deck)
    // Ref: set-lost-thunder/ninjask.ts (JUST_EVOLVED + IS_ABILITY_BLOCKED), set-unbroken-bonds/malamar.ts (DISCARD_TOP_X_CARDS_FROM_YOUR_DECK on opponent)
    if (JUST_EVOLVED(effect, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      COIN_FLIP_PROMPT(store, state, player, result => {
        if (result) {
          // Heads: discard top 5 of opponent's deck
          DISCARD_TOP_X_CARDS_FROM_YOUR_DECK(store, state, opponent, 5, this, effect);
        } else {
          // Tails: discard top 5 of your own deck
          DISCARD_TOP_X_CARDS_FROM_YOUR_DECK(store, state, player, 5, this, effect);
        }
      });
    }

    // Attack 1: Crunch
    // Ref: set-unbroken-bonds/krookodile.ts (Crunch - DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON(store, state, effect);
    }

    return state;
  }
}
