// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { CheckAttackCostEffect } from '../../game/store/effects/check-effects';
import { IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class Huntail extends PokemonCard {
  public tags = [CardTag.FUSION_STRIKE];
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Clamperl';
  public cardType: CardType = W;
  public hp: number = 110;
  public weakness = [{ type: L }];
  public retreat = [C];

  public powers = [  {
    name: 'Single Strike Jammer',
    powerType: PowerType.ABILITY,
    text: 'Your opponent\'s Single Strike Pokémon\'s attacks cost Colorless more.'
  }];

  public attacks = [
    {
      name: 'Cavernous Chomp',
      cost: [W, C, C],
      damage: 80,
      text: ''
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'FST';
  public setNumber: string = '66';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Huntail';
  public fullName: string = 'Huntail (FST 66)';
  public legacyFullName = 'Huntail FST';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Single Strike Jammer
    // Ref: set-unbroken-bonds/persian.ts (CheckAttackCostEffect + IS_ABILITY_BLOCKED + forEachPokemon)
    if (effect instanceof CheckAttackCostEffect) {
      const player = effect.player;

      // Check if this Huntail is in play on the opponent's side
      // effect.player is the one attacking (whose cost we're checking)
      // This ability affects the opponent's Pokemon, so we check on the opposite player's side
      const attackingPokemon = player.active.getPokemonCard();
      if (!attackingPokemon || !attackingPokemon.tags.includes(CardTag.SINGLE_STRIKE)) {
        return state;
      }

      // Check if Huntail is in play on the other side
      let huntailInPlay = false;
      // We need to find if this huntail is in play for the opponent of the attacker
      // The attacker is effect.player, so we iterate over state.players to find the opponent
      state.players.forEach(p => {
        if (p !== player) {
          p.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card) => {
            if (card === this) {
              huntailInPlay = true;
            }
          });
        }
      });

      if (!huntailInPlay) {
        return state;
      }

      // Find the owner of this Huntail (opponent of the attacking player)
      let huntailOwner = state.players.find(p => p !== player);
      if (!huntailOwner) {
        return state;
      }

      if (IS_ABILITY_BLOCKED(store, state, huntailOwner, this)) {
        return state;
      }

      effect.cost.push(CardType.COLORLESS);
    }

    return state;
  }
}
