import { Card } from '../../game/store/card/card';
import { AccelgorArt, AdventurersDiscoveryArt, AzumarillArt, BasculinArt, BattleVIPPassArt, CookArt, CreamomaticArt, CroagunkArt, CrossSwitcherArt, DeoxysArt, DreepyArt, DunsparceArt, ElesasSparkleArt, FusionStrikeEnergyArt, GalarianLinooneArt, GenesectVArt, GengarVArt, GengarVMAXArt, HeatmorArt, InteleonVArt, InteleonVMAXArt, JudgeArt, MeloettaArt, MewVArt, MewVMAXArt, OricorioArt, PowerTabletArt, SchoolboyArt, SchoolgirlArt, ShaunaArt, ShellderArt, ShelmetArt, StarmieArt, StaryuArt, SwampertArt, TotodileArt, YveltalArt } from './card-images';


export const setFusionStrike: Card[] = [

  new AzumarillArt(),
  new BasculinArt(),
  new BattleVIPPassArt(),
  new CreamomaticArt(),
  new CroagunkArt(),
  new CrossSwitcherArt(),
  new CookArt(),
  new DeoxysArt(),
  new DreepyArt(),
  new DunsparceArt(),
  new ElesasSparkleArt(),
  new FusionStrikeEnergyArt(),
  new GalarianLinooneArt(),
  new GenesectVArt(),
  new GengarVArt(),
  new GengarVMAXArt(),
  new HeatmorArt(),
  new InteleonVArt(),
  new InteleonVMAXArt(),
  new JudgeArt(),
  new MeloettaArt(),
  new MewVArt(),
  new MewVMAXArt(),
  new OricorioArt(),
  new PowerTabletArt(),
  // new PyukumukuArt(),
  new YveltalArt(),
  new ShaunaArt(),
  new AdventurersDiscoveryArt(),
  new SchoolboyArt(),
  new SchoolgirlArt(),
  new AccelgorArt(),
  new ShellderArt(),
  new ShelmetArt(),
  new StarmieArt(),
  new StaryuArt(),
  new SwampertArt(),
  new TotodileArt(),
];