// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { AFTER_ATTACK, SWITCH_ACTIVE_WITH_BENCHED } from '../../game/store/prefabs/prefabs';
import { ConfirmPrompt, GameMessage } from '../../game';

export class Mantine extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 110;
  public weakness = [{ type: L }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Bounce',
      cost: [W],
      damage: 20,
      text: 'You may switch this Pokémon with 1 of your Benched Pokémon.'
    },
    {
      name: 'Wave Splash',
      cost: [C, C, C],
      damage: 80,
      text: ''
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'FST';
  public setNumber: string = '61';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mantine';
  public fullName: string = 'Mantine (FST 61)';
  public legacyFullName = 'Mantine FST';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Bounce
    // Ref: set-team-up/hitmonchan.ts (Hit and Run)
    if (AFTER_ATTACK(effect, 0, this)) {
      const player = effect.player;
      if (player.bench.some(b => b.cards.length > 0)) {
        state = store.prompt(state, new ConfirmPrompt(
          effect.player.id,
          GameMessage.WANT_TO_SWITCH_POKEMON,
        ), wantToUse => {
          if (wantToUse) {
            SWITCH_ACTIVE_WITH_BENCHED(store, state, player);
          }
        });
      }
    }

    return state;
  }
}
