// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';

export class PikachuV extends PokemonCard {
  public tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = L;
  public hp: number = 200;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Tail Whap',
      cost: [C],
      damage: 20,
      text: ''
    },
    {
      name: 'Thunderbolt',
      cost: [L, C, C],
      damage: 100,
      text: ''
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'FST';
  public setNumber: string = '86';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Pikachu V';
  public fullName: string = 'Pikachu V FST 86';
}
