// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';

export class Stantler extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = C;
  public hp: number = 110;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Rear Kick',
      cost: [C],
      damage: 20,
      text: ''
    },
    {
      name: 'Wild Dive',
      cost: [C, C],
      damage: 30,
      damageCalculation: 'x' as 'x',
      text: 'This attack does 30 damage for each Energy attached to your opponent\'s Active Pokémon.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'FST';
  public setNumber: string = '208';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Stantler';
  public fullName: string = 'Stantler (FST 208)';
  public legacyFullName = 'Stantler FST';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Wild Dive
    // Ref: set-lost-thunder/espeon.ts (Energy Crush - counting opponent energy)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      const checkEnergy = new CheckProvidedEnergyEffect(opponent, opponent.active);
      store.reduceEffect(state, checkEnergy);
      const totalEnergy = checkEnergy.energyMap.reduce((sum, e) => sum + e.provides.length, 0);
      effect.damage = 30 * totalEnergy;
    }

    return state;
  }
}
