export type EffectlessCardEntry = {
  set: string;
  setNumber: string;
  name: string;
  fullName: string;
};

/** Cards from commit 16cd523d (Effectless Card Format Restructured). */
export const EFFECTLESS_CARDS: EffectlessCardEntry[] = [
  { set: 'AOR', setNumber: '2', name: 'Gloom', fullName: 'Gloom AOR' },
  { set: 'AOR', setNumber: '9', name: 'Combee', fullName: 'Combee AOR' },
  { set: 'AOR', setNumber: '16', name: 'Larvesta', fullName: 'Larvesta AOR' },
  { set: 'AOR', setNumber: '47', name: 'Beldum', fullName: 'Beldum AOR' },
  { set: 'AOR', setNumber: '52', name: 'Ralts', fullName: 'Ralts AOR' },
  { set: 'ASC', setNumber: '4', name: 'Erika\'s Bellsprout', fullName: 'Erika\'s Bellsprout MC' },
  { set: 'ASC', setNumber: '9', name: 'Bayleef', fullName: 'Bayleef MC' },
  { set: 'ASC', setNumber: '11', name: 'Wurmple', fullName: 'Wurmple M2a' },
  { set: 'ASC', setNumber: '20', name: 'Charmander', fullName: 'Charmander MC' },
  { set: 'ASC', setNumber: '21', name: 'Charmeleon', fullName: 'Charmeleon MC' },
  { set: 'ASC', setNumber: '29', name: 'Tepig', fullName: 'Tepig MC' },
  { set: 'ASC', setNumber: '46', name: 'Snorunt', fullName: 'Snorunt M2a' },
  { set: 'ASC', setNumber: '52', name: 'Snom', fullName: 'Snom M2a' },
  { set: 'ASC', setNumber: '150', name: 'Dratini', fullName: 'Dratini M2a' },
  { set: 'ASC', setNumber: '165', name: 'Skitty', fullName: 'Skitty ASC' },
  { set: 'ASC', setNumber: '169', name: 'Larry\'s Staravia', fullName: 'Larry\'s Staravia MC' },
  { set: 'ASR', setNumber: '4', name: 'Scyther', fullName: 'Scyther ASR 4' },
  { set: 'ASR', setNumber: '6', name: 'Yanma', fullName: 'Yanma ASR' },
  { set: 'ASR', setNumber: '20', name: 'Dartrix', fullName: 'Dartrix ASR 20' },
  { set: 'ASR', setNumber: '21', name: 'Ponyta', fullName: 'Ponyta ASR 21' },
  { set: 'ASR', setNumber: '24', name: 'Quilava', fullName: 'Quilava ASR 24' },
  { set: 'ASR', setNumber: '41', name: 'Oshawott', fullName: 'Oshawott ASR 41' },
  { set: 'ASR', setNumber: '47', name: 'Bergmite', fullName: 'Bergmite ASR 47' },
  { set: 'ASR', setNumber: '58', name: 'Misdreavus', fullName: 'Misdreavus ASR 58' },
  { set: 'ASR', setNumber: '79', name: 'Hippopotas', fullName: 'Hippopotas ASR 79' },
  { set: 'ASR', setNumber: '88', name: 'Hisuian Qwilfish', fullName: 'Hisuian Qwilfish ASR' },
  { set: 'ASR', setNumber: '92', name: 'Hisuian Sneasel', fullName: 'Hisuian Sneasel ASR 92' },
  { set: 'ASR', setNumber: '103', name: 'Nickit', fullName: 'Nickit ASR 103' },
  { set: 'BCR', setNumber: '7', name: 'Scyther', fullName: 'Scyther BCR' },
  { set: 'BCR', setNumber: '11', name: 'Snivy', fullName: 'Snivy BCR' },
  { set: 'BCR', setNumber: '14', name: 'Cottonee', fullName: 'Cottonee BCR' },
  { set: 'BCR', setNumber: '24', name: 'Tepig', fullName: 'Tepig BCR' },
  { set: 'BCR', setNumber: '36', name: 'Marill', fullName: 'Marill BCR' },
  { set: 'BCR', setNumber: '39', name: 'Oshawott', fullName: 'Oshawott BCR' },
  { set: 'BCR', setNumber: '40', name: 'Dewott', fullName: 'Dewott BCR' },
  { set: 'BCR', setNumber: '42', name: 'Ducklett', fullName: 'Ducklett BCR' },
  { set: 'BCR', setNumber: '44', name: 'Frillish', fullName: 'Frillish BCR' },
  { set: 'BCR', setNumber: '51', name: 'Voltorb', fullName: 'Voltorb BCR' },
  { set: 'BCR', setNumber: '52', name: 'Electrode', fullName: 'Electrode BCR' },
  { set: 'BCR', setNumber: '53', name: 'Electabuzz', fullName: 'Electabuzz BCR' },
  { set: 'BCR', setNumber: '56', name: 'Blitzle', fullName: 'Blitzle BCR' },
  { set: 'BCR', setNumber: '58', name: 'Wobbuffet', fullName: 'Wobbuffet BCR' },
  { set: 'BCR', setNumber: '75', name: 'Gothita', fullName: 'Gothita BCR' },
  { set: 'BCR', setNumber: '78', name: 'Sandshrew', fullName: 'Sandshrew BCR' },
  { set: 'BCR', setNumber: '82', name: 'Makuhita', fullName: 'Makuhita BCR' },
  { set: 'BCR', setNumber: '87', name: 'Mienfoo', fullName: 'Mienfoo BCR 87' },
  { set: 'BCR', setNumber: '92', name: 'Vullaby', fullName: 'Vullaby BCR' },
  { set: 'BCR', setNumber: '112', name: 'Taillow', fullName: 'Taillow BCR' },
  { set: 'BCR', setNumber: '116', name: 'Buneary', fullName: 'Buneary BCR' },
  { set: 'BKP', setNumber: '4', name: 'Seedot', fullName: 'Seedot BKP' },
  { set: 'BKP', setNumber: '10', name: 'Growlithe', fullName: 'Growlithe BKP' },
  { set: 'BKP', setNumber: '12', name: 'Numel', fullName: 'Numel BKP' },
  { set: 'BKP', setNumber: '16', name: 'Psyduck', fullName: 'Psyduck BKP' },
  { set: 'BKP', setNumber: '25', name: 'Staryu', fullName: 'Staryu BKP' },
  { set: 'BKP', setNumber: '42', name: 'Electabuzz', fullName: 'Electabuzz BKP' },
  { set: 'BKP', setNumber: '43', name: 'Electivire', fullName: 'Electivire BKP' },
  { set: 'BKP', setNumber: '58', name: 'Espurr', fullName: 'Espurr BKP' },
  { set: 'BKP', setNumber: '71', name: 'Pancham', fullName: 'Pancham BKP' },
  { set: 'BKP', setNumber: '84', name: 'Spritzee', fullName: 'Spritzee BKP' },
  { set: 'BKT', setNumber: '8', name: 'Chespin', fullName: 'Chespin BKT 8' },
  { set: 'BKT', setNumber: '36', name: 'Piplup', fullName: 'Piplup BKT' },
  { set: 'BKT', setNumber: '46', name: 'Froakie', fullName: 'Froakie BKT' },
  { set: 'BKT', setNumber: '47', name: 'Frogadier', fullName: 'Frogadier BKT' },
  { set: 'BKT', setNumber: '100', name: 'Ralts', fullName: 'Ralts BKT 100' },
  { set: 'BKT', setNumber: '108', name: 'Axew', fullName: 'Axew BKT' },
  { set: 'BKT', setNumber: '121', name: 'Teddiursa', fullName: 'Teddiursa BKT' },
  { set: 'BKT', setNumber: '129', name: 'Rufflet', fullName: 'Rufflet BKT' },
  { set: 'BLK', setNumber: '1', name: 'Snivy', fullName: 'Snivy SV11B' },
  { set: 'BLK', setNumber: '37', name: 'Solosis', fullName: 'Solosis SV11B' },
  { set: 'BLK', setNumber: '45', name: 'Drilbur', fullName: 'Drillbur SV11B' },
  { set: 'BLW', setNumber: '1', name: 'Snivy', fullName: 'Snivy BLW 1' },
  { set: 'BLW', setNumber: '7', name: 'Pansage', fullName: 'Pansage BLW' },
  { set: 'BLW', setNumber: '15', name: 'Tepig', fullName: 'Tepig BLW' },
  { set: 'BLW', setNumber: '21', name: 'Pansear', fullName: 'Pansear BLW' },
  { set: 'BLW', setNumber: '27', name: 'Oshawott', fullName: 'Oshawott BLW' },
  { set: 'BLW', setNumber: '33', name: 'Panpour', fullName: 'Panpour BLW' },
  { set: 'BLW', setNumber: '36', name: 'Ducklett', fullName: 'Ducklett BLW' },
  { set: 'BLW', setNumber: '38', name: 'Alomomola', fullName: 'Alomomola BLW' },
  { set: 'BLW', setNumber: '40', name: 'Blitzle', fullName: 'Blitzle BLW' },
  { set: 'BLW', setNumber: '50', name: 'Woobat', fullName: 'Woobat BLW' },
  { set: 'BLW', setNumber: '58', name: 'Timburr', fullName: 'Timburr BLW' },
  { set: 'BLW', setNumber: '66', name: 'Purrloin', fullName: 'Purrloin BLW' },
  { set: 'BLW', setNumber: '68', name: 'Scraggy', fullName: 'Scraggy BLW' },
  { set: 'BLW', setNumber: '77', name: 'Patrat', fullName: 'Patrat BLW' },
  { set: 'BRS', setNumber: '1', name: 'Exeggcute', fullName: 'Exeggcute BRS 1' },
  { set: 'BRS', setNumber: '3', name: 'Shroomish', fullName: 'Shroomish BRS' },
  { set: 'BRS', setNumber: '6', name: 'Turtwig', fullName: 'Turtwig BRS 6' },
  { set: 'BRS', setNumber: '12', name: 'Cherubi', fullName: 'Cherubi BRS' },
  { set: 'BRS', setNumber: '19', name: 'Magmar', fullName: 'Magmar BRS 19' },
  { set: 'BRS', setNumber: '32', name: 'Corphish', fullName: 'Corphish BRS 32' },
  { set: 'BRS', setNumber: '36', name: 'Prinplup', fullName: 'Prinplup BRS 36' },
  { set: 'BRS', setNumber: '42', name: 'Cubchoo', fullName: 'Cubchoo BRS 42' },
  { set: 'BRS', setNumber: '49', name: 'Shinx', fullName: 'Shinx BRS 49' },
  { set: 'BRS', setNumber: '53', name: 'Clefairy', fullName: 'Clefairy BRS 53' },
  { set: 'BRS', setNumber: '73', name: 'Nosepass', fullName: 'Nosepass BRS 73' },
  { set: 'BRS', setNumber: '75', name: 'Vibrava', fullName: 'Vibrava BRS 75' },
  { set: 'BRS', setNumber: '78', name: 'Riolu', fullName: 'Riolu BRS' },
  { set: 'BRS', setNumber: '80', name: 'Throh', fullName: 'Throh BRS 80' },
  { set: 'BRS', setNumber: '82', name: 'Golett', fullName: 'Golett BRS 82' },
  { set: 'BRS', setNumber: '86', name: 'Sneasel', fullName: 'Sneasel BRS 86' },
  { set: 'BRS', setNumber: '93', name: 'Morgrem', fullName: 'Morgrem BRS 93' },
  { set: 'BRS', setNumber: '102', name: 'Klink', fullName: 'Klink BRS 102' },
  { set: 'BRS', setNumber: '107', name: 'Gible', fullName: 'Gible BRS' },
  { set: 'BRS', setNumber: '108', name: 'Gabite', fullName: 'Gabite BRS 108' },
  { set: 'BRS', setNumber: '111', name: 'Fraxure', fullName: 'Fraxure BRS 111' },
  { set: 'BRS', setNumber: '118', name: 'Staravia', fullName: 'Staravia BRS 118' },
  { set: 'BRS', setNumber: '120', name: 'Bidoof', fullName: 'Bidoof BRS' },
  { set: 'BS', setNumber: '7', name: 'Hitmonchan', fullName: 'Hitmonchan BS' },
  { set: 'BS', setNumber: '26', name: 'Dratini', fullName: 'Dratini BS' },
  { set: 'BS', setNumber: '28', name: 'Growlithe', fullName: 'Growlithe BS' },
  { set: 'BS', setNumber: '41', name: 'Seel', fullName: 'Seel BS' },
  { set: 'BS', setNumber: '47', name: 'Diglett', fullName: 'Diglett BS' },
  { set: 'BS', setNumber: '52', name: 'Machop', fullName: 'Machop BS' },
  { set: 'BS', setNumber: '60', name: 'Ponyta', fullName: 'Ponyta BS' },
  { set: 'BS', setNumber: '61', name: 'Rattata', fullName: 'Rattata BS' },
  { set: 'BS', setNumber: '65', name: 'Staryu', fullName: 'Staryu BS' },
  { set: 'BS', setNumber: '67', name: 'Voltorb', fullName: 'Voltorb BS' },
  { set: 'BST', setNumber: '4', name: 'Cacnea', fullName: 'Cacnea BST' },
  { set: 'BST', setNumber: '7', name: 'Cherubi', fullName: 'Cherubi BST' },
  { set: 'BST', setNumber: '17', name: 'Blipbug', fullName: 'Blipbug BST' },
  { set: 'BST', setNumber: '24', name: 'Pignite', fullName: 'Pignite BST' },
  { set: 'BST', setNumber: '32', name: 'Seadra', fullName: 'Seadra BST' },
  { set: 'BST', setNumber: '36', name: 'Remoraid', fullName: 'Remoraid BST' },
  { set: 'BST', setNumber: '43', name: 'Bruxish', fullName: 'Bruxish BST' },
  { set: 'BST', setNumber: '46', name: 'Shinx', fullName: 'Shinx BST' },
  { set: 'BST', setNumber: '55', name: 'Spoink', fullName: 'Spoink BST' },
  { set: 'BST', setNumber: '69', name: 'Cubone', fullName: 'Cubone BST' },
  { set: 'BST', setNumber: '71', name: 'Gligar', fullName: 'Gligar BST' },
  { set: 'BST', setNumber: '74', name: 'Gurdurr', fullName: 'Gurdurr BST' },
  { set: 'BST', setNumber: '81', name: 'Silicobra', fullName: 'Silicobra BST' },
  { set: 'BST', setNumber: '95', name: 'Houndour', fullName: 'Houndour BST' },
  { set: 'BST', setNumber: '101', name: 'Bronzor', fullName: 'Bronzor BST' },
  { set: 'BST', setNumber: '112', name: 'Fearow', fullName: 'Fearow BST' },
  { set: 'BST', setNumber: '113', name: 'Lickitung', fullName: 'Lickitung BST' },
  { set: 'BST', setNumber: '115', name: 'Glameow', fullName: 'Glameow BST' },
  { set: 'BUS', setNumber: '12', name: 'Pansage', fullName: 'Pansage BUS' },
  { set: 'BUS', setNumber: '18', name: 'Charmander', fullName: 'Charmander BUS' },
  { set: 'BUS', setNumber: '19', name: 'Charmeleon', fullName: 'Charmeleon BUS' },
  { set: 'BUS', setNumber: '22', name: 'Pansear', fullName: 'Pansear BUS' },
  { set: 'BUS', setNumber: '36', name: 'Panpour', fullName: 'Panpour BUS' },
  { set: 'BUS', setNumber: '65', name: 'Rhyhorn', fullName: 'Rhyhorn BUS' },
  { set: 'BUS', setNumber: '70', name: 'Riolu', fullName: 'Riolu BUS' },
  { set: 'BUS', setNumber: '73', name: 'Crabrawler', fullName: 'Crabrawler BUS' },
  { set: 'BUS', setNumber: '76', name: 'Lycanroc', fullName: 'Lycanroc BUS 76' },
  { set: 'BUS', setNumber: '92', name: 'Kirlia', fullName: 'Kirlia BUS' },
  { set: 'BUS', setNumber: '95', name: 'Cutiefly', fullName: 'Cutiefly BUS' },
  { set: 'BUS', setNumber: '97', name: 'Morelull', fullName: 'Morelull BUS' },
  { set: 'BWP', setNumber: '13', name: 'Minccino', fullName: 'Minccino BWP' },
  { set: 'CEC', setNumber: '15', name: 'Deerling', fullName: 'Deerling CEC' },
  { set: 'CEC', setNumber: '31', name: 'Tepig', fullName: 'Tepig CEC' },
  { set: 'CEC', setNumber: '32', name: 'Pignite', fullName: 'Pignite CEC' },
  { set: 'CEC', setNumber: '34', name: 'Larvesta', fullName: 'Larvesta CEC' },
  { set: 'CEC', setNumber: '36', name: 'Litleo', fullName: 'Litleo CEC' },
  { set: 'CEC', setNumber: '45', name: 'Wailmer', fullName: 'Wailmer CEC' },
  { set: 'CEC', setNumber: '46', name: 'Wailord', fullName: 'Wailord CEC' },
  { set: 'CEC', setNumber: '49', name: 'Spheal', fullName: 'Spheal CEC' },
  { set: 'CEC', setNumber: '51', name: 'Sealeo', fullName: 'Sealeo CEC' },
  { set: 'CEC', setNumber: '64', name: 'Dewpider', fullName: 'Dewpider CEC' },
  { set: 'CEC', setNumber: '93', name: 'Phantump', fullName: 'Phantump CEC' },
  { set: 'CEC', setNumber: '111', name: 'Anorith', fullName: 'Anorith CEC' },
  { set: 'CEC', setNumber: '119', name: 'Pancham', fullName: 'Pancham CEC' },
  { set: 'CEC', setNumber: '120', name: 'Pangoro', fullName: 'Pangoro CEC' },
  { set: 'CEC', setNumber: '121', name: 'Crabrawler', fullName: 'Crabrawler CEC' },
  { set: 'CEC', setNumber: '161', name: 'Jangmo-o', fullName: 'Jangmo-o CEC 161' },
  { set: 'CEC', setNumber: '171', name: 'Teddiursa', fullName: 'Teddiursa CEC' },
  { set: 'CEL', setNumber: '15A1', name: 'Venusaur', fullName: 'Venusaur CEL 15A1' },
  { set: 'CEL', setNumber: '8', name: 'Surfing Pikachu V', fullName: 'Surfing Pikachu V CEL' },
  { set: 'CES', setNumber: '8', name: 'Treecko', fullName: 'Treecko CES 8' },
  { set: 'CES', setNumber: '12', name: 'Seedot', fullName: 'Seedot CES 12' },
  { set: 'CES', setNumber: '26', name: 'Torchic', fullName: 'Torchic CES 26' },
  { set: 'CES', setNumber: '33', name: 'Mudkip', fullName: 'Mudkip CES 33' },
  { set: 'CES', setNumber: '51', name: 'Electrike', fullName: 'Electrike CES' },
  { set: 'CES', setNumber: '63', name: 'Shuppet', fullName: 'Shuppet CES' },
  { set: 'CES', setNumber: '111', name: 'Wingull', fullName: 'Wingull CES' },
  { set: 'CG', setNumber: '49', name: 'Charmander', fullName: 'Charmander CG' },
  { set: 'CIN', setNumber: '10', name: 'Skiddo', fullName: 'Skiddo CIN' },
  { set: 'CIN', setNumber: '15', name: 'Staryu', fullName: 'Staryu CIN' },
  { set: 'CIN', setNumber: '19', name: 'Swinub', fullName: 'Swinub CIN' },
  { set: 'CIN', setNumber: '22', name: 'Remoraid', fullName: 'Remoraid CIN' },
  { set: 'CIN', setNumber: '24', name: 'Corphish', fullName: 'Corphish CIN' },
  { set: 'CIN', setNumber: '41', name: 'Spoink', fullName: 'Spoink CIN' },
  { set: 'CIN', setNumber: '55', name: 'Stufful', fullName: 'Stufful CIN' },
  { set: 'CIN', setNumber: '58', name: 'Houndour', fullName: 'Houndour CIN' },
  { set: 'CIN', setNumber: '65', name: 'Aron', fullName: 'Aron CIN' },
  { set: 'CIN', setNumber: '66', name: 'Lairon', fullName: 'Lairon CIN' },
  { set: 'CIN', setNumber: '75', name: 'Jangmo-o', fullName: 'Jangmo-o CIN' },
  { set: 'CIN', setNumber: '79', name: 'Swablu', fullName: 'Swablu CIN' },
  { set: 'CIN', setNumber: '82', name: 'Staravia', fullName: 'Staravia CIN' },
  { set: 'CIN', setNumber: '87', name: 'Bunnelby', fullName: 'Bunnelby CIN' },
  { set: 'CPA', setNumber: '3', name: 'Kakuna', fullName: 'Kakuna CPA' },
  { set: 'CPA', setNumber: '11', name: 'Carvanha', fullName: 'Carvanha CPA' },
  { set: 'CPA', setNumber: '18', name: 'Hatenna', fullName: 'Hatenna CPA' },
  { set: 'CPA', setNumber: '19', name: 'Hattrem', fullName: 'Hattrem CPA' },
  { set: 'CPA', setNumber: '31', name: 'Rolycoly', fullName: 'Rolycoly CPA' },
  { set: 'CPA', setNumber: '33', name: 'Ekans', fullName: 'Ekans CPA' },
  { set: 'CPA', setNumber: '34', name: 'Arbok', fullName: 'Arbok CPA' },
  { set: 'CPA', setNumber: '38', name: 'Absol', fullName: 'Absol CPA' },
  { set: 'CPA', setNumber: '41', name: 'Scraggy', fullName: 'Scraggy CPA' },
  { set: 'CPA', setNumber: '48', name: 'Swablu', fullName: 'Swablu CPA' },
  { set: 'CRE', setNumber: '1', name: 'Weedle', fullName: 'Weedle CRE' },
  { set: 'CRE', setNumber: '9', name: 'Snover', fullName: 'Snover CRE' },
  { set: 'CRE', setNumber: '13', name: 'Bounsweet', fullName: 'Bounsweet CRE' },
  { set: 'CRE', setNumber: '26', name: 'Scorbunny', fullName: 'Scorbunny CRE' },
  { set: 'CRE', setNumber: '35', name: 'Snorunt', fullName: 'Snorunt CRE' },
  { set: 'CRE', setNumber: '37', name: 'Spheal', fullName: 'Spheal CRE' },
  { set: 'CRE', setNumber: '38', name: 'Sealeo', fullName: 'Sealeo CRE' },
  { set: 'CRE', setNumber: '48', name: 'Flaaffy', fullName: 'Flaaffy CRE' },
  { set: 'CRE', setNumber: '54', name: 'Galarian Slowpoke', fullName: 'Galarian Slowpoke CRE' },
  { set: 'CRE', setNumber: '56', name: 'Haunter', fullName: 'Haunter CRE' },
  { set: 'CRE', setNumber: '62', name: 'Shuppet', fullName: 'Shuppet CRE' },
  { set: 'CRE', setNumber: '65', name: 'Golett', fullName: 'Golett CRE' },
  { set: 'CRE', setNumber: '69', name: 'Inkay', fullName: 'Inkay CRE' },
  { set: 'CRE', setNumber: '71', name: 'Hatenna', fullName: 'Hatenna CRE' },
  { set: 'CRE', setNumber: '91', name: 'Clobbopus', fullName: 'Clobbopus CRE' },
  { set: 'CRE', setNumber: '109', name: 'Aron', fullName: 'Aron CRE' },
  { set: 'CRE', setNumber: '110', name: 'Lairon', fullName: 'Lairon CRE' },
  { set: 'CRE', setNumber: '116', name: 'Porygon', fullName: 'Porygon CRE' },
  { set: 'CRI', setNumber: '5', name: 'Chespin', fullName: 'Chespin M4' },
  { set: 'CRI', setNumber: '14', name: 'Litleo', fullName: 'Litleo M4' },
  { set: 'CRI', setNumber: '16', name: 'Remoraid', fullName: 'Remoraid M4' },
  { set: 'CRI', setNumber: '23', name: 'Bergmite', fullName: 'Bergmite M4' },
  { set: 'CRI', setNumber: '40', name: 'Pumpkaboo', fullName: 'Pumpkaboo M4' },
  { set: 'CRI', setNumber: '44', name: 'Phanpy', fullName: 'Phanpy M4' },
  { set: 'CRI', setNumber: '53', name: 'Stunky', fullName: 'Stunky M4' },
  { set: 'CRI', setNumber: '58', name: 'Skrelp', fullName: 'Skrelp M4' },
  { set: 'CRI', setNumber: '59', name: 'Beldum', fullName: 'Beldum M4' },
  { set: 'CRI', setNumber: '62', name: 'Ferroseed', fullName: 'Ferroseed M4' },
  { set: 'CRI', setNumber: '67', name: 'Sliggoo', fullName: 'Sliggoo M4' },
  { set: 'CRZ', setNumber: '4', name: 'Tangela', fullName: 'Tangela CRZ 4' },
  { set: 'CRZ', setNumber: '24', name: 'Larvesta', fullName: 'Larvesta CRZ 24' },
  { set: 'CRZ', setNumber: '49', name: 'Helioptile', fullName: 'Helioptile CRZ 49' },
  { set: 'CRZ', setNumber: '72', name: 'Pancham', fullName: 'Pancham CRZ 72' },
  { set: 'CRZ', setNumber: '81', name: 'Skrelp', fullName: 'Skrelp CRZ 81' },
  { set: 'CRZ', setNumber: '92', name: 'Pawniard', fullName: 'Pawniard CRZ 92' },
  { set: 'CRZ', setNumber: '117', name: 'Yungoos', fullName: 'Yungoos CRZ 117' },
  { set: 'DAA', setNumber: '3', name: 'Paras', fullName: 'Paras DAA' },
  { set: 'DAA', setNumber: '6', name: 'Pansage', fullName: 'Pansage DAA' },
  { set: 'DAA', setNumber: '9', name: 'Shelmet', fullName: 'Shelmet DAA' },
  { set: 'DAA', setNumber: '10', name: 'Accelgor', fullName: 'Accelgor DAA' },
  { set: 'DAA', setNumber: '26', name: 'Pansear', fullName: 'Pansear DAA' },
  { set: 'DAA', setNumber: '41', name: 'Panpour', fullName: 'Panpour DAA' },
  { set: 'DAA', setNumber: '43', name: 'Galarian Darumaka', fullName: 'Galarian Darumaka DAA' },
  { set: 'DAA', setNumber: '48', name: 'Cubchoo', fullName: 'Cubchoo DAA' },
  { set: 'DAA', setNumber: '55', name: 'Mareep', fullName: 'Mareep DAA' },
  { set: 'DAA', setNumber: '56', name: 'Flaaffy', fullName: 'Flaaffy DAA' },
  { set: 'DAA', setNumber: '62', name: 'Toxel', fullName: 'Toxel DAA' },
  { set: 'DAA', setNumber: '67', name: 'Jigglypuff', fullName: 'Jigglypuff DAA' },
  { set: 'DAA', setNumber: '70', name: 'Snubbull', fullName: 'Snubbull DAA' },
  { set: 'DAA', setNumber: '76', name: 'Golett', fullName: 'Golett DAA' },
  { set: 'DAA', setNumber: '77', name: 'Golurk', fullName: 'Golurk DAA' },
  { set: 'DAA', setNumber: '84', name: 'Diglett', fullName: 'Diglett DAA' },
  { set: 'DAA', setNumber: '86', name: 'Larvitar', fullName: 'Larvitar DAA' },
  { set: 'DAA', setNumber: '96', name: 'Diggersby', fullName: 'Diggersby DAA' },
  { set: 'DAA', setNumber: '102', name: 'Spinarak', fullName: 'Spinarak DAA' },
  { set: 'DAA', setNumber: '108', name: 'Deino', fullName: 'Deino DAA' },
  { set: 'DAA', setNumber: '109', name: 'Zweilous', fullName: 'Zweilous DAA' },
  { set: 'DAA', setNumber: '121', name: 'Aron', fullName: 'Aron DAA' },
  { set: 'DAA', setNumber: '129', name: 'Meltan', fullName: 'Meltan DAA' },
  { set: 'DAA', setNumber: '131', name: 'Cufant', fullName: 'Cufant DAA' },
  { set: 'DAA', setNumber: '134', name: 'Tauros', fullName: 'Tauros DAA' },
  { set: 'DAA', setNumber: '148', name: 'Ducklett', fullName: 'Ducklett DAA' },
  { set: 'DAA', setNumber: '151', name: 'Fletchling', fullName: 'Fletchling DAA' },
  { set: 'DEX', setNumber: '1', name: 'Bulbasaur', fullName: 'Bulbasaur DEX' },
  { set: 'DEX', setNumber: '7', name: 'Dwebble', fullName: 'Dwebble DEX' },
  { set: 'DEX', setNumber: '15', name: 'Torchic', fullName: 'Torchic DEX 15' },
  { set: 'DEX', setNumber: '41', name: 'Joltik', fullName: 'Joltik DEX' },
  { set: 'DEX', setNumber: '42', name: 'Joltik', fullName: 'Joltik DEX 42' },
  { set: 'DEX', setNumber: '58', name: 'Timburr', fullName: 'Timburr DEX' },
  { set: 'DEX', setNumber: '78', name: 'Pawniard', fullName: 'Pawniard DEX' },
  { set: 'DEX', setNumber: '84', name: 'Eevee', fullName: 'Eevee DEX 84' },
  { set: 'DF', setNumber: '68', name: 'Trapinch', fullName: 'Trapinch DF 68' },
  { set: 'DRI', setNumber: '7', name: 'Cynthia\'s Roselia', fullName: 'Cynthia\'s Roselia DRI' },
  { set: 'DRI', setNumber: '35', name: 'Ethan\'s Slugma', fullName: 'Ethan\'s Slugma DRI' },
  { set: 'DRI', setNumber: '64', name: 'Cetoddle', fullName: 'Cetoddle DRI' },
  { set: 'DRI', setNumber: '68', name: 'Electabuzz', fullName: 'Electabuzz DRI' },
  { set: 'DRI', setNumber: '117', name: 'Team Rocket\'s Nidoran ♂', fullName: 'Team Rocket\'s Nidoran M DRI' },
  { set: 'DRI', setNumber: '135', name: 'Marnie\'s Morgrem', fullName: 'Marnie\'s Morgrem DRI' },
  { set: 'DRI', setNumber: '138', name: 'Arven\'s Maschiff', fullName: 'Arven\'s Maschiff DRI' },
  { set: 'DRI', setNumber: '143', name: 'Steven\'s Beldum', fullName: 'Steven\'s Beldum DRI' },
  { set: 'DRI', setNumber: '156', name: 'Taillow', fullName: 'Taillow DRI' },
  { set: 'DRM', setNumber: '25', name: 'Wooper', fullName: 'Wooper DRM' },
  { set: 'DRM', setNumber: '35', name: 'Dratini', fullName: 'Dratini DRM 35' },
  { set: 'DRV', setNumber: '6', name: 'Bagon', fullName: 'Bagon DRV' },
  { set: 'DRV', setNumber: '15', name: 'Fraxure', fullName: 'Fraxure DRV 15' },
  { set: 'DRX', setNumber: '20', name: 'Magmar', fullName: 'Magmar DRX' },
  { set: 'DRX', setNumber: '30', name: 'Sealeo', fullName: 'Sealeo DRX' },
  { set: 'DRX', setNumber: '32', name: 'Buizel', fullName: 'Buizel DRX' },
  { set: 'DRX', setNumber: '33', name: 'Floatzel', fullName: 'Floatzel DRX' },
  { set: 'DRX', setNumber: '50', name: 'Drifloon', fullName: 'Drifloon DRX' },
  { set: 'DRX', setNumber: '60', name: 'Cubone', fullName: 'Cubone DRX' },
  { set: 'DRX', setNumber: '62', name: 'Nosepass', fullName: 'Nosepass DRX' },
  { set: 'DRX', setNumber: '72', name: 'Murkrow', fullName: 'Murkrow DRX' },
  { set: 'DRX', setNumber: '74', name: 'Houndour', fullName: 'Houndour DRX' },
  { set: 'DRX', setNumber: '86', name: 'Gible', fullName: 'Gible DRX' },
  { set: 'DRX', setNumber: '105', name: 'Swablu', fullName: 'Swablu DRX 105' },
  { set: 'DS', setNumber: '57', name: 'Bagon', fullName: 'Bagon DS 57' },
  { set: 'DS', setNumber: '80', name: 'Porygon', fullName: 'Porygon DS' },
  { set: 'EM', setNumber: '71', name: 'Voltorb', fullName: 'Voltorb EM' },
  { set: 'EPO', setNumber: '4', name: 'Sewaddle', fullName: 'Sewaddle EPO 4' },
  { set: 'EPO', setNumber: '20', name: 'Darumaka', fullName: 'Darumaka EPO' },
  { set: 'EPO', setNumber: '29', name: 'Cubchoo', fullName: 'Cubchoo EPO 29' },
  { set: 'EPO', setNumber: '33', name: 'Joltik', fullName: 'Joltik EPO' },
  { set: 'EPO', setNumber: '44', name: 'Gothita', fullName: 'Gothita EPO 44' },
  { set: 'EPO', setNumber: '55', name: 'Drilbur', fullName: 'Drilbur EPO 55' },
  { set: 'EPO', setNumber: '60', name: 'Sandile', fullName: 'Sandile EPO' },
  { set: 'EPO', setNumber: '71', name: 'Ferroseed', fullName: 'Ferroseed EPO 71' },
  { set: 'EPO', setNumber: '80', name: 'Pidove', fullName: 'Pidove EPO' },
  { set: 'EPO', setNumber: '86', name: 'Rufflet', fullName: 'Rufflet EPO' },
  { set: 'EVO', setNumber: '19', name: 'Ponyta', fullName: 'Ponyta EVO' },
  { set: 'EVO', setNumber: '23', name: 'Poliwag', fullName: 'Poliwag EVO' },
  { set: 'EVO', setNumber: '62', name: 'Hitmonchan', fullName: 'Hitmonchan EVO' },
  { set: 'EVO', setNumber: '111', name: 'Surfing Pikachu', fullName: 'Surfing Pikachu EVO' },
  { set: 'EVS', setNumber: '9', name: 'Petilil', fullName: 'Petilil EVS' },
  { set: 'EVS', setNumber: '17', name: 'Applin', fullName: 'Applin EVS' },
  { set: 'EVS', setNumber: '22', name: 'Litleo', fullName: 'Litleo EVS' },
  { set: 'EVS', setNumber: '24', name: 'Psyduck', fullName: 'Psyduck EVS' },
  { set: 'EVS', setNumber: '26', name: 'Tentacool', fullName: 'Tentacool EVS' },
  { set: 'EVS', setNumber: '33', name: 'Lombre', fullName: 'Lombre EVS' },
  { set: 'EVS', setNumber: '35', name: 'Carvanha', fullName: 'Carvanha EVS' },
  { set: 'EVS', setNumber: '42', name: 'Tympole', fullName: 'Tympole EVS' },
  { set: 'EVS', setNumber: '44', name: 'Bergmite', fullName: 'Bergmite EVS' },
  { set: 'EVS', setNumber: '52', name: 'Chinchou', fullName: 'Chinchou EVS' },
  { set: 'EVS', setNumber: '54', name: 'Mareep', fullName: 'Mareep EVS' },
  { set: 'EVS', setNumber: '61', name: 'Drowzee', fullName: 'Drowzee EVS' },
  { set: 'EVS', setNumber: '78', name: 'Cutiefly', fullName: 'Cutiefly EVS' },
  { set: 'EVS', setNumber: '84', name: 'Hippopotas', fullName: 'Hippopotas EVS' },
  { set: 'EVS', setNumber: '86', name: 'Roggenrola', fullName: 'Roggenrola EVS' },
  { set: 'EVS', setNumber: '89', name: 'Palpitoad', fullName: 'Palpitoad EVS' },
  { set: 'EVS', setNumber: '102', name: 'Zorua', fullName: 'Zorua EVS' },
  { set: 'EVS', setNumber: '104', name: 'Nickit', fullName: 'Nickit EVS' },
  { set: 'EVS', setNumber: '107', name: 'Bagon', fullName: 'Bagon EVS' },
  { set: 'EVS', setNumber: '114', name: 'Zweilous', fullName: 'Zweilous EVS' },
  { set: 'EVS', setNumber: '126', name: 'Teddiursa', fullName: 'Teddiursa EVS' },
  { set: 'EVS', setNumber: '127', name: 'Ursaring', fullName: 'Ursaring EVS' },
  { set: 'FCO', setNumber: '2', name: 'Burmy', fullName: 'Burmy FCO' },
  { set: 'FCO', setNumber: '15', name: 'Seel', fullName: 'Seel FCO' },
  { set: 'FCO', setNumber: '17', name: 'Omanyte', fullName: 'Omanyte FCO' },
  { set: 'FCO', setNumber: '36', name: 'Diglett', fullName: 'Diglett FCO' },
  { set: 'FCO', setNumber: '38', name: 'Kabuto', fullName: 'Kabuto FCO' },
  { set: 'FCO', setNumber: '65', name: 'Jigglypuff', fullName: 'Jigglypuff FCO' },
  { set: 'FCO', setNumber: '70', name: 'Cottonee', fullName: 'Cottonee FCO' },
  { set: 'FCO', setNumber: '75', name: 'Kangaskhan', fullName: 'Kangaskhan FCO' },
  { set: 'FCO', setNumber: '87', name: 'Minccino', fullName: 'Minccino FCO 87' },
  { set: 'FFI', setNumber: '6', name: 'Shroomish', fullName: 'Shroomish FFI' },
  { set: 'FFI', setNumber: '25', name: 'Amaura', fullName: 'Amaura FFI' },
  { set: 'FFI', setNumber: '44', name: 'Machop', fullName: 'Machop FFI' },
  { set: 'FFI', setNumber: '45', name: 'Machoke', fullName: 'Machoke FFI' },
  { set: 'FFI', setNumber: '51', name: 'Makuhita', fullName: 'Makuhita FFI' },
  { set: 'FFI', setNumber: '66', name: 'Scraggy', fullName: 'Scraggy FFI' },
  { set: 'FFI', setNumber: '87', name: 'Noibat', fullName: 'Noibat FFI' },
  { set: 'FLF', setNumber: '4', name: 'Pineco', fullName: 'Pineco FLF' },
  { set: 'FLF', setNumber: '6', name: 'Nuzleaf', fullName: 'Nuzleaf FLF' },
  { set: 'FLF', setNumber: '18', name: 'Litleo', fullName: 'Litleo FLF' },
  { set: 'FLF', setNumber: '19', name: 'Litleo', fullName: 'Litleo FLF 19' },
  { set: 'FLF', setNumber: '24', name: 'Spheal', fullName: 'Spheal FLF' },
  { set: 'FLF', setNumber: '63', name: 'Flabébé', fullName: 'Flabébé FLF 63' },
  { set: 'FLF', setNumber: '81', name: 'Sentret', fullName: 'Sentret FLF' },
  { set: 'FLI', setNumber: '15', name: 'Fennekin', fullName: 'Fennekin FLI 15' },
  { set: 'FLI', setNumber: '18', name: 'Litleo', fullName: 'Litleo FLI' },
  { set: 'FLI', setNumber: '22', name: 'Froakie', fullName: 'Froakie FLI' },
  { set: 'FLI', setNumber: '25', name: 'Clauncher', fullName: 'Clauncher FLI' },
  { set: 'FLI', setNumber: '37', name: 'Helioptile', fullName: 'Helioptile FLI' },
  { set: 'FLI', setNumber: '52', name: 'Skrelp', fullName: 'Skrelp FLI' },
  { set: 'FST', setNumber: '4', name: 'Shroomish', fullName: 'Shroomish FST 4' },
  { set: 'FST', setNumber: '7', name: 'Pansage', fullName: 'Pansage FST 7' },
  { set: 'FST', setNumber: '13', name: 'Shelmet', fullName: 'Shelmet FST' },
  { set: 'FST', setNumber: '16', name: 'Phantump', fullName: 'Phantump FST 16' },
  { set: 'FST', setNumber: '17', name: 'Trevenant', fullName: 'Trevenant FST 17' },
  { set: 'FST', setNumber: '19', name: 'Dewpider', fullName: 'Dewpider FST 19' },
  { set: 'FST', setNumber: '28', name: 'Vulpix', fullName: 'Vulpix FST 28' },
  { set: 'FST', setNumber: '29', name: 'Vulpix', fullName: 'Vulpix FST 29' },
  { set: 'FST', setNumber: '30', name: 'Ninetales', fullName: 'Ninetales FST 30' },
  { set: 'FST', setNumber: '34', name: 'Slugma', fullName: 'Slugma FST 34' },
  { set: 'FST', setNumber: '46', name: 'Sizzlipede', fullName: 'Sizzlipede FST 46' },
  { set: 'FST', setNumber: '49', name: 'Centiskorch', fullName: 'Centiskorch FST 49' },
  { set: 'FST', setNumber: '50', name: 'Shellder', fullName: 'Shellder FST' },
  { set: 'FST', setNumber: '55', name: 'Totodile', fullName: 'Totodile FST' },
  { set: 'FST', setNumber: '56', name: 'Croconaw', fullName: 'Croconaw FST 56' },
  { set: 'FST', setNumber: '62', name: 'Mudkip', fullName: 'Mudkip FST' },
  { set: 'FST', setNumber: '65', name: 'Clamperl', fullName: 'Clamperl FST 65' },
  { set: 'FST', setNumber: '74', name: 'Clauncher', fullName: 'Clauncher FST 74' },
  { set: 'FST', setNumber: '80', name: 'Chewtle', fullName: 'Chewtle FST 80' },
  { set: 'FST', setNumber: '82', name: 'Arrokuda', fullName: 'Arrokuda FST 82' },
  { set: 'FST', setNumber: '83', name: 'Barraskewda', fullName: 'Barraskewda FST 83' },
  { set: 'FST', setNumber: '86', name: 'Pikachu V', fullName: 'Pikachu V FST 86' },
  { set: 'FST', setNumber: '91', name: 'Shinx', fullName: 'Shinx FST 91' },
  { set: 'FST', setNumber: '92', name: 'Luxio', fullName: 'Luxio FST 92' },
  { set: 'FST', setNumber: '93', name: 'Luxray', fullName: 'Luxray FST 93' },
  { set: 'FST', setNumber: '98', name: 'Helioptile', fullName: 'Helioptile FST 98' },
  { set: 'FST', setNumber: '100', name: 'Charjabug', fullName: 'Charjabug FST 100' },
  { set: 'FST', setNumber: '105', name: 'Toxel', fullName: 'Toxel FST 105' },
  { set: 'FST', setNumber: '115', name: 'Snubbull', fullName: 'Snubbull FST 115' },
  { set: 'FST', setNumber: '117', name: 'Galarian Corsola', fullName: 'Galarian Corsola FST 117' },
  { set: 'FST', setNumber: '121', name: 'Munna', fullName: 'Munna FST 121' },
  { set: 'FST', setNumber: '125', name: 'Sandygast', fullName: 'Sandygast FST 125' },
  { set: 'FST', setNumber: '135', name: 'Geodude', fullName: 'Geodude FST 135' },
  { set: 'FST', setNumber: '136', name: 'Graveler', fullName: 'Graveler FST 136' },
  { set: 'FST', setNumber: '142', name: 'Makuhita', fullName: 'Makuhita FST 142' },
  { set: 'FST', setNumber: '144', name: 'Baltoy', fullName: 'Baltoy FST 144' },
  { set: 'FST', setNumber: '146', name: 'Lucario V', fullName: 'Lucario V FST 146' },
  { set: 'FST', setNumber: '147', name: 'Drilbur', fullName: 'Drilbur FST 147' },
  { set: 'FST', setNumber: '150', name: 'Stufful', fullName: 'Stufful FST 150' },
  { set: 'FST', setNumber: '152', name: 'Clobbopus', fullName: 'Clobbopus FST 152' },
  { set: 'FST', setNumber: '153', name: 'Grapploct', fullName: 'Grapploct FST 153' },
  { set: 'FST', setNumber: '155', name: 'Falinks', fullName: 'Falinks FST 155' },
  { set: 'FST', setNumber: '158', name: 'Tyranitar V', fullName: 'Tyranitar V FST 158' },
  { set: 'FST', setNumber: '160', name: 'Galarian Linoone', fullName: 'Galarian Linoone FST' },
  { set: 'FST', setNumber: '163', name: 'Sharpedo', fullName: 'Sharpedo FST 163' },
  { set: 'FST', setNumber: '165', name: 'Croagunk', fullName: 'Croagunk FST' },
  { set: 'FST', setNumber: '167', name: 'Darkrai', fullName: 'Darkrai FST 167' },
  { set: 'FST', setNumber: '170', name: 'Zorua', fullName: 'Zorua FST 170' },
  { set: 'FST', setNumber: '175', name: 'Yveltal', fullName: 'Yveltal FST' },
  { set: 'FST', setNumber: '195', name: 'Goomy', fullName: 'Goomy FST 195' },
  { set: 'FST', setNumber: '206', name: 'Snorlax', fullName: 'Snorlax FST 206' },
  { set: 'FST', setNumber: '213', name: 'Lopunny', fullName: 'Lopunny FST 213' },
  { set: 'GE', setNumber: '61', name: 'Buizel', fullName: 'Buizel GE' },
  { set: 'GRI', setNumber: '1', name: 'Bellsprout', fullName: 'Bellsprout GRI' },
  { set: 'GRI', setNumber: '12', name: 'Lampent', fullName: 'Lampent GRI' },
  { set: 'GRI', setNumber: '27', name: 'Carvanha', fullName: 'Carvanha GRI' },
  { set: 'GRI', setNumber: '28', name: 'Sharpedo', fullName: 'Sharpedo GRI' },
  { set: 'GRI', setNumber: '29', name: 'Wailmer', fullName: 'Wailmer GRI' },
  { set: 'GRI', setNumber: '31', name: 'Snorunt', fullName: 'Snorunt GRI' },
  { set: 'GRI', setNumber: '63', name: 'Machop', fullName: 'Machop GRI 63' },
  { set: 'GRI', setNumber: '70', name: 'Barboach', fullName: 'Barboach GRI' },
  { set: 'GRI', setNumber: '99', name: 'Hakamo-o', fullName: 'Hakamo-o GRI' },
  { set: 'GRI', setNumber: '112', name: 'Stufful', fullName: 'Stufful GRI' },
  { set: 'HIF', setNumber: '1', name: 'Caterpie', fullName: 'Caterpie HIF' },
  { set: 'HIF', setNumber: '2', name: 'Metapod', fullName: 'Metapod HIF' },
  { set: 'HIF', setNumber: '3', name: 'Butterfree', fullName: 'Butterfree HIF' },
  { set: 'HIF', setNumber: '4', name: 'Paras', fullName: 'Paras HIF' },
  { set: 'HIF', setNumber: '5', name: 'Scyther', fullName: 'Scyther HIF 5' },
  { set: 'HIF', setNumber: '7', name: 'Charmander', fullName: 'Charmander HIF 7' },
  { set: 'HIF', setNumber: '7', name: 'Charmander', fullName: 'Charmander HIF' },
  { set: 'HIF', setNumber: '10', name: 'Magmar', fullName: 'Magmar HIF' },
  { set: 'HIF', setNumber: '11', name: 'Psyduck', fullName: 'Psyduck HIF' },
  { set: 'HIF', setNumber: '15', name: 'Magikarp', fullName: 'Magikarp HIF' },
  { set: 'HIF', setNumber: '17', name: 'Lapras', fullName: 'Lapras HIF' },
  { set: 'HIF', setNumber: '21', name: 'Voltorb', fullName: 'Voltorb HIF 21' },
  { set: 'HIF', setNumber: '26', name: 'Ekans', fullName: 'Ekans HIF 26' },
  { set: 'HIF', setNumber: '28', name: 'Koffing', fullName: 'Koffing HIF' },
  { set: 'HIF', setNumber: '30', name: 'Jynx', fullName: 'Jynx HIF' },
  { set: 'HIF', setNumber: '32', name: 'Mew', fullName: 'Mew HIF' },
  { set: 'HIF', setNumber: '33', name: 'Geodude', fullName: 'Geodude HIF' },
  { set: 'HIF', setNumber: '39', name: 'Clefairy', fullName: 'Clefairy HIF 39' },
  { set: 'HIF', setNumber: '40', name: 'Clefable', fullName: 'Clefable HIF' },
  { set: 'HIF', setNumber: '41', name: 'Jigglypuff', fullName: 'Jigglypuff HIF' },
  { set: 'HIF', setNumber: '45', name: 'Farfetch\'d', fullName: 'Farfetch\'d HIF' },
  { set: 'HIF', setNumber: '49', name: 'Eevee', fullName: 'Eevee HIF 49' },
  { set: 'HIF', setNumber: '50', name: 'Snorlax', fullName: 'Snorlax HIF' },
  { set: 'HIF', setNumber: 'SV35', name: 'Kirlia', fullName: 'Kirlia HIF' },
  { set: 'HP', setNumber: '62', name: 'Corphish', fullName: 'Corphish HP' },
  { set: 'HP', setNumber: '66', name: 'Horsea', fullName: 'Horsea HP' },
  { set: 'HP', setNumber: '77', name: 'Pidgey', fullName: 'Pidgey HP' },
  { set: 'HS', setNumber: '35', name: 'Bayleef', fullName: 'Bayleef HS' },
  { set: 'HS', setNumber: '59', name: 'Chikorita', fullName: 'Chikorita HS' },
  { set: 'HS', setNumber: '61', name: 'Cyndaquil', fullName: 'Cyndaquil HS' },
  { set: 'HS', setNumber: '86', name: 'Totodile', fullName: 'Totodile HS' },
  { set: 'JTG', setNumber: '6', name: 'Petilil', fullName: 'Petilil JTG' },
  { set: 'JTG', setNumber: '22', name: 'Torchic', fullName: 'Torchic JTG' },
  { set: 'JTG', setNumber: '23', name: 'Combusken', fullName: 'Combusken JTG' },
  { set: 'JTG', setNumber: '26', name: 'N\'s Darumaka', fullName: 'N\'s Darumaka JTG' },
  { set: 'JTG', setNumber: '35', name: 'Lotad', fullName: 'Lotad JTG' },
  { set: 'JTG', setNumber: '40', name: 'Wailmer', fullName: 'Wailmer JTG' },
  { set: 'JTG', setNumber: '52', name: 'Iono\'s Tadbulb', fullName: 'Iono\'s Tadbulb JTG' },
  { set: 'JTG', setNumber: '59', name: 'Shuppet', fullName: 'Shuppet JTG' },
  { set: 'JTG', setNumber: '61', name: 'Beldum', fullName: 'Beldum JTG' },
  { set: 'JTG', setNumber: '62', name: 'Metang', fullName: 'Metang JTG' },
  { set: 'JTG', setNumber: '78', name: 'Piloswine', fullName: 'Piloswine JTG' },
  { set: 'JTG', setNumber: '88', name: 'Toedscool', fullName: 'Toedscool JTG' },
  { set: 'JTG', setNumber: '97', name: 'N\'s Zorua', fullName: 'N\'s Zorua JTG' },
  { set: 'JTG', setNumber: '134', name: 'Hop\'s Corvisquire', fullName: 'Hop\'s Corvisquire JTG' },
  { set: 'JTG', setNumber: '135', name: 'Hop\'s Wooloo', fullName: 'Hop\'s Wooloo JTG' },
  { set: 'JU', setNumber: '46', name: 'Seaking', fullName: 'Seaking JU' },
  { set: 'JU', setNumber: '53', name: 'Goldeen', fullName: 'Goldeen JU' },
  { set: 'LM', setNumber: '63', name: 'Shuppet', fullName: 'Shuppet LM' },
  { set: 'LOR', setNumber: '1', name: 'Oddish', fullName: 'Oddish LOR 1' },
  { set: 'LOR', setNumber: '16', name: 'Phantump', fullName: 'Phantump LOR 16' },
  { set: 'LOR', setNumber: '33', name: 'Seel', fullName: 'Seel LOR 33' },
  { set: 'LOR', setNumber: '39', name: 'Shellos', fullName: 'Shellos LOR 39' },
  { set: 'LOR', setNumber: '42', name: 'Snover', fullName: 'Snover LOR 42' },
  { set: 'LOR', setNumber: '72', name: 'Shuppet', fullName: 'Shuppet LOR 72' },
  { set: 'LOR', setNumber: '86', name: 'Machop', fullName: 'Machop LOR' },
  { set: 'LOR', setNumber: '87', name: 'Machoke', fullName: 'Machoke LOR 87' },
  { set: 'LOR', setNumber: '103', name: 'Mienfoo', fullName: 'Mienfoo LOR 103' },
  { set: 'LOR', setNumber: '106', name: 'Binacle', fullName: 'Binacle LOR' },
  { set: 'LOR', setNumber: '125', name: 'Bronzor', fullName: 'Bronzor LOR 125' },
  { set: 'LOR', setNumber: '138', name: 'Lickitung', fullName: 'Lickitung LOR 138' },
  { set: 'LOR', setNumber: '139', name: 'Lickilicky', fullName: 'Lickilicky LOR 139' },
  { set: 'LOR', setNumber: '150', name: 'Skwovet', fullName: 'Skwovet LOR 150' },
  { set: 'LOT', setNumber: '12', name: 'Hoppip', fullName: 'Hoppip LOT 12' },
  { set: 'LOT', setNumber: '12', name: 'Hoppip', fullName: 'Hoppip LOT' },
  { set: 'LOT', setNumber: '40', name: 'Cyndaquil', fullName: 'Cyndaquil LOT 40' },
  { set: 'LOT', setNumber: '81', name: 'Blitzle', fullName: 'Blitzle LOT' },
  { set: 'LOT', setNumber: '109', name: 'Onix', fullName: 'Onix LOT' },
  { set: 'LOT', setNumber: '135', name: 'Marill', fullName: 'Marill LOT' },
  { set: 'LOT', setNumber: '155', name: 'Eevee', fullName: 'Eevee LOT' },
  { set: 'LTR', setNumber: '10', name: 'Sewaddle', fullName: 'Sewaddle LTR 10' },
  { set: 'LTR', setNumber: '13', name: 'Dwebble', fullName: 'Dwebble LTR' },
  { set: 'LTR', setNumber: '55', name: 'Natu', fullName: 'Natu LTR' },
  { set: 'LTR', setNumber: '57', name: 'Misdreavus', fullName: 'Misdreavus LTR' },
  { set: 'LTR', setNumber: '94', name: 'Gible', fullName: 'Gible LTR' },
  { set: 'M6', setNumber: '19', name: 'Frillish', fullName: 'Frillish M6' },
  { set: 'M6', setNumber: '29', name: 'Drowzee', fullName: 'Drowzee M6' },
  { set: 'M6', setNumber: '32', name: 'Golett', fullName: 'Golett M6' },
  { set: 'M6', setNumber: '42', name: 'Nidorina', fullName: 'Nidorina M6' },
  { set: 'MEE', setNumber: '4', name: 'Pawmo', fullName: 'Pawmo MEE' },
  { set: 'MEG', setNumber: '2', name: 'Ivysaur', fullName: 'Ivysaur M1L' },
  { set: 'MEG', setNumber: '8', name: 'Chikorita', fullName: 'Chikorita M1S' },
  { set: 'MEG', setNumber: '16', name: 'Nincada', fullName: 'Nincada M1S' },
  { set: 'MEG', setNumber: '35', name: 'Snover', fullName: 'Snover M1S' },
  { set: 'MEG', setNumber: '37', name: 'Clauncher', fullName: 'Clauncher M1S' },
  { set: 'MEG', setNumber: '45', name: 'Magnemite', fullName: 'Magnemite M1S' },
  { set: 'MEG', setNumber: '67', name: 'Gimmighoul', fullName: 'Gimmighoul M1L' },
  { set: 'MEG', setNumber: '72', name: 'Makuhita', fullName: 'Makuhita M1L' },
  { set: 'MEG', setNumber: '82', name: 'Nacli', fullName: 'Nacli M1L' },
  { set: 'MEM', setNumber: '4', name: 'Floragato', fullName: 'Floragato MEM' },
  { set: 'MEM', setNumber: '6', name: 'Smoliv', fullName: 'Smoliv MEM' },
  { set: 'MEM', setNumber: '7', name: 'Dolliv', fullName: 'Dolliv MEM' },
  { set: 'MEP', setNumber: '20', name: 'Sneasel', fullName: 'Sneasel M2' },
  { set: 'MEW', setNumber: '13', name: 'Weedle', fullName: 'Weedle MEW' },
  { set: 'MEW', setNumber: '17', name: 'Pidgeotto', fullName: 'Pidgeotto MEW' },
  { set: 'MEW', setNumber: '32', name: 'Nidoran ♂', fullName: 'Nidoran M MEW' },
  { set: 'MEW', setNumber: '33', name: 'Nidorino', fullName: 'Nidorino MEW' },
  { set: 'MEW', setNumber: '43', name: 'Oddish', fullName: 'Oddish MEW' },
  { set: 'MEW', setNumber: '48', name: 'Venonat', fullName: 'Venonat MEW' },
  { set: 'MEW', setNumber: '63', name: 'Abra', fullName: 'Abra MEW' },
  { set: 'MEZ', setNumber: '4', name: 'Purrloin', fullName: 'Purrloin MEZ' },
  { set: 'MEZ', setNumber: '6', name: 'Zorua', fullName: 'Zorua MEZ' },
  { set: 'NVI', setNumber: '22', name: 'Tympole', fullName: 'Tympole NVI' },
  { set: 'NVI', setNumber: '39', name: 'Tynamo', fullName: 'Tynamo NVI 39' },
  { set: 'OBF', setNumber: '13', name: 'Rowlet', fullName: 'Rowlet OBF' },
  { set: 'OBF', setNumber: '51', name: 'Palpitoad', fullName: 'Palpitoad OBF' },
  { set: 'OBF', setNumber: '105', name: 'Larvitar', fullName: 'Larvitar OBF' },
  { set: 'OBF', setNumber: '157', name: 'Dratini', fullName: 'Dratini OBF' },
  { set: 'OBF', setNumber: '162', name: 'Pidgey', fullName: 'Pidgey OBF' },
  { set: 'OBF', setNumber: '163', name: 'Pidgeotto', fullName: 'Pidgeotto OBF' },
  { set: 'PAF', setNumber: '60', name: 'Scraggy', fullName: 'Scraggy PAF' },
  { set: 'PAL', setNumber: '4', name: 'Pineco', fullName: 'Pineco PAL' },
  { set: 'PAL', setNumber: '13', name: 'Sprigatito', fullName: 'Sprigatito PAL' },
  { set: 'PAL', setNumber: '17', name: 'Tarountula', fullName: 'Tarountula PAL' },
  { set: 'PAL', setNumber: '36', name: 'Crocalor', fullName: 'Crocalor PAL' },
  { set: 'PAL', setNumber: '57', name: 'Frigibax', fullName: 'Frigibax PAL1' },
  { set: 'PAL', setNumber: '58', name: 'Frigibax', fullName: 'Frigibax PAL2' },
  { set: 'PAL', setNumber: '59', name: 'Arctibax', fullName: 'Arctibax PAL' },
  { set: 'PAL', setNumber: '66', name: 'Voltorb', fullName: 'Voltorb PAL' },
  { set: 'PAL', setNumber: '111', name: 'Pupitar', fullName: 'Pupitar PAL' },
  { set: 'PAL', setNumber: '125', name: 'Glimmet', fullName: 'Glimmet PAL' },
  { set: 'PAL', setNumber: '149', name: 'Cufant', fullName: 'Cufant PAL' },
  { set: 'PAL', setNumber: '152', name: 'Noibat', fullName: 'Noibat PAL' },
  { set: 'PAL', setNumber: '158', name: 'Wingull', fullName: 'Wingull PAL' },
  { set: 'PAR', setNumber: '13', name: 'Nymble', fullName: 'Nymble PAR' },
  { set: 'PAR', setNumber: '33', name: 'Remoraid', fullName: 'Remoraid PAR' },
  { set: 'PAR', setNumber: '43', name: 'Vanillite', fullName: 'Vanillite PAR' },
  { set: 'PAR', setNumber: '44', name: 'Vanillish', fullName: 'Vanillish PAR' },
  { set: 'PAR', setNumber: '94', name: 'Gible', fullName: 'Gible PAR' },
  { set: 'PAR', setNumber: '130', name: 'Honedge', fullName: 'Honedge PAR' },
  { set: 'PBL', setNumber: '13', name: 'Goldeen', fullName: 'Goldeen M5' },
  { set: 'PBL', setNumber: '15', name: 'Wailmer', fullName: 'Wailmer M5' },
  { set: 'PBL', setNumber: '18', name: 'Popplio', fullName: 'Popplio M5' },
  { set: 'PBL', setNumber: '19', name: 'Brionne', fullName: 'Brionne M5' },
  { set: 'PBL', setNumber: '25', name: 'Charjabug', fullName: 'Charjabug M5' },
  { set: 'PBL', setNumber: '42', name: 'Mankey', fullName: 'Mankey M5' },
  { set: 'PBL', setNumber: '43', name: 'Primeape', fullName: 'Primeape M5' },
  { set: 'PBL', setNumber: '49', name: 'Vullaby', fullName: 'Vullaby M5' },
  { set: 'PBL', setNumber: '57', name: 'Maschiff', fullName: 'Maschiff M5' },
  { set: 'PBL', setNumber: '69', name: 'Type: Null', fullName: 'Type: Null M5' },
  { set: 'PFL', setNumber: '5', name: 'Lotad', fullName: 'Lotad M2' },
  { set: 'PFL', setNumber: '12', name: 'Charmeleon', fullName: 'Charmeleon M2' },
  { set: 'PFL', setNumber: '52', name: 'Vibrava', fullName: 'Vibrava PFL' },
  { set: 'PFL', setNumber: '54', name: 'Gastly', fullName: 'Gastly MBG' },
  { set: 'PFL', setNumber: '55', name: 'Haunter', fullName: 'Haunter MBG' },
  { set: 'PHF', setNumber: '8', name: 'Karrablast', fullName: 'Karrablast PHF' },
  { set: 'PHF', setNumber: '9', name: 'Fletchinder', fullName: 'Fletchinder PHF' },
  { set: 'PHF', setNumber: '13', name: 'Krabby', fullName: 'Krabby PHF' },
  { set: 'PHF', setNumber: '18', name: 'Finneon', fullName: 'Finneon PHF' },
  { set: 'PHF', setNumber: '48', name: 'Roggenrola', fullName: 'Roggenrola PHF' },
  { set: 'PHF', setNumber: '60', name: 'Bronzor', fullName: 'Bronzor PHF' },
  { set: 'PHF', setNumber: '87', name: 'Bunnelby', fullName: 'Bunnelby PHF' },
  { set: 'PLB', setNumber: '6', name: 'Karrablast', fullName: 'Karrablast PLB' },
  { set: 'PLB', setNumber: '25', name: 'Snover', fullName: 'Snover PLB' },
  { set: 'PLB', setNumber: '31', name: 'Tynamo', fullName: 'Tynamo PLB' },
  { set: 'PLB', setNumber: '45', name: 'Golett', fullName: 'Golett PLB' },
  { set: 'PLB', setNumber: '47', name: 'Machop', fullName: 'Machop PLB' },
  { set: 'PLB', setNumber: '62', name: 'Bagon', fullName: 'Bagon PLB' },
  { set: 'PLB', setNumber: '72', name: 'Porygon', fullName: 'Porygon PLB' },
  { set: 'PLF', setNumber: '7', name: 'Grovyle', fullName: 'Grovyle PLF' },
  { set: 'PLF', setNumber: '32', name: 'Voltorb', fullName: 'Voltorb PLF' },
  { set: 'PLF', setNumber: '35', name: 'Chinchou', fullName: 'Chinchou PLF' },
  { set: 'PLF', setNumber: '55', name: 'Yamask', fullName: 'Yamask PLF 55' },
  { set: 'PLF', setNumber: '59', name: 'Mankey', fullName: 'Mankey PLF' },
  { set: 'PLF', setNumber: '69', name: 'Krokorok', fullName: 'Krokorok PLF' },
  { set: 'PLF', setNumber: '71', name: 'Pawniard', fullName: 'Pawniard PLF' },
  { set: 'PLF', setNumber: '72', name: 'Pawniard', fullName: 'Pawniard PLF 72' },
  { set: 'PLF', setNumber: '95', name: 'Starly', fullName: 'Starly PLF' },
  { set: 'PLS', setNumber: '8', name: 'Sewaddle', fullName: 'Sewaddle PLS' },
  { set: 'PLS', setNumber: '15', name: 'Chimchar', fullName: 'Chimchar PLS' },
  { set: 'PLS', setNumber: '24', name: 'Squirtle', fullName: 'Squirtle PLS' },
  { set: 'PLS', setNumber: '32', name: 'Carvanha', fullName: 'Carvanha PLS' },
  { set: 'PLS', setNumber: '36', name: 'Vanillish', fullName: 'Vanillish PLS' },
  { set: 'PLS', setNumber: '43', name: 'Magnemite', fullName: 'Magnemite PLS 43' },
  { set: 'PLS', setNumber: '64', name: 'Trubbish', fullName: 'Trubbish PLS 64' },
  { set: 'PLS', setNumber: '68', name: 'Elgyem', fullName: 'Elgyem PLS' },
  { set: 'PLS', setNumber: '71', name: 'Phanpy', fullName: 'Phanpy PLS' },
  { set: 'PLS', setNumber: '75', name: 'Riolu', fullName: 'Riolu PLS' },
  { set: 'PLS', setNumber: '77', name: 'Lucario', fullName: 'Lucario PLS' },
  { set: 'PLS', setNumber: '85', name: 'Scraggy', fullName: 'Scraggy PLS' },
  { set: 'POR', setNumber: '5', name: 'Servine', fullName: 'Servine M3' },
  { set: 'POR', setNumber: '7', name: 'Scatterbug', fullName: 'Scatterbug M3' },
  { set: 'POR', setNumber: '13', name: 'Fletchinder', fullName: 'Fletchinder M3' },
  { set: 'POR', setNumber: '15', name: 'Salandit', fullName: 'Salandit M3' },
  { set: 'POR', setNumber: '18', name: 'Seel', fullName: 'Seel M3' },
  { set: 'POR', setNumber: '20', name: 'Staryu', fullName: 'Staryu M3' },
  { set: 'POR', setNumber: '37', name: 'Nosepass', fullName: 'Nosepass M3' },
  { set: 'POR', setNumber: '56', name: 'Honedge', fullName: 'Honedge M3' },
  { set: 'POR', setNumber: '64', name: 'Bunnelby', fullName: 'Bunnelby M3' },
  { set: 'PRC', setNumber: '2', name: 'Kakuna', fullName: 'Kakuna PRC' },
  { set: 'PRC', setNumber: '10', name: 'Lotad', fullName: 'Lotad PRC' },
  { set: 'PRC', setNumber: '11', name: 'Lombre', fullName: 'Lombre PRC' },
  { set: 'PRC', setNumber: '13', name: 'Surskit', fullName: 'Surskit PRC' },
  { set: 'PRC', setNumber: '33', name: 'Mudkip', fullName: 'Mudkip PRC' },
  { set: 'PRC', setNumber: '39', name: 'Barboach', fullName: 'Barboach PRC' },
  { set: 'PRC', setNumber: '46', name: 'Spheal', fullName: 'Spheal PRC 46' },
  { set: 'PRC', setNumber: '57', name: 'Chinchou', fullName: 'Chinchou PRC' },
  { set: 'PRC', setNumber: '66', name: 'Nidoran ♀', fullName: 'Nidoran ♀ PRC' },
  { set: 'PRC', setNumber: '67', name: 'Nidorina', fullName: 'Nidorina PRC' },
  { set: 'PRC', setNumber: '71', name: 'Tentacool', fullName: 'Tentacool PRC 71' },
  { set: 'PRC', setNumber: '79', name: 'Meditite', fullName: 'Meditite PRC' },
  { set: 'PRC', setNumber: '82', name: 'Trapinch', fullName: 'Trapinch PRC' },
  { set: 'PRC', setNumber: '87', name: 'Hippopotas', fullName: 'Hippopotas PRC' },
  { set: 'PRC', setNumber: '102', name: 'Marill', fullName: 'Marill PRC' },
  { set: 'PRE', setNumber: '47', name: 'Larvitar', fullName: 'Larvitar PRE' },
  { set: 'PRE', setNumber: '48', name: 'Pupitar', fullName: 'Pupitar PRE' },
  { set: 'PRE', setNumber: '61', name: 'Sneasel', fullName: 'Sneasel PRE' },
  { set: 'PRE', setNumber: '66', name: 'Bronzor', fullName: 'Bronzor PRE' },
  { set: 'RCL', setNumber: '12', name: 'Snover', fullName: 'Snover RCL' },
  { set: 'RCL', setNumber: '16', name: 'Grubbin', fullName: 'Grubbin RCL' },
  { set: 'RCL', setNumber: '52', name: 'Arrokuda', fullName: 'Arrokuda RCL' },
  { set: 'RCL', setNumber: '58', name: 'Electabuzz', fullName: 'Electabuzz RCL' },
  { set: 'RCL', setNumber: '96', name: 'Nosepass', fullName: 'Nosepass RCL' },
  { set: 'RCL', setNumber: '99', name: 'Barboach', fullName: 'Barboach RCL' },
  { set: 'RCL', setNumber: '105', name: 'Rolycoly', fullName: 'Rolycoly RCL' },
  { set: 'RCL', setNumber: '106', name: 'Carkol', fullName: 'Carkol RCL' },
  { set: 'RCL', setNumber: '112', name: 'Koffing', fullName: 'Koffing RCL' },
  { set: 'RCL', setNumber: '123', name: 'Impidimp', fullName: 'Impidimp RCL' },
  { set: 'RCL', setNumber: '129', name: 'Bronzor', fullName: 'Bronzor RCL' },
  { set: 'RCL', setNumber: '133', name: 'Honedge', fullName: 'Honedge RCL' },
  { set: 'RCL', setNumber: '144', name: 'Tranquill', fullName: 'Tranquill RCL' },
  { set: 'RCL', setNumber: '151', name: 'Skwovet', fullName: 'Skwovet RCL' },
  { set: 'ROS', setNumber: '18', name: 'Wingull', fullName: 'Wingull ROS' },
  { set: 'ROS', setNumber: '24', name: 'Electrike', fullName: 'Electrike ROS' },
  { set: 'ROS', setNumber: '65', name: 'Spearow', fullName: 'Spearow ROS' },
  { set: 'ROS', setNumber: '72', name: 'Swellow', fullName: 'Swellow ROS 72' },
  { set: 'SCR', setNumber: '12', name: 'Applin', fullName: 'Applin SCR' },
  { set: 'SCR', setNumber: '17', name: 'Toedscool', fullName: 'Toedscool SCR' },
  { set: 'SCR', setNumber: '19', name: 'Ponyta', fullName: 'Ponyta SCR' },
  { set: 'SCR', setNumber: '27', name: 'Raboot', fullName: 'Raboot SCR' },
  { set: 'SCR', setNumber: '33', name: 'Marill', fullName: 'Marill SCR' },
  { set: 'SCR', setNumber: '43', name: 'Chewtle', fullName: 'Chewtle SCR' },
  { set: 'SCR', setNumber: '64', name: 'Milcery', fullName: 'Milcery SCR' },
  { set: 'SCR', setNumber: '77', name: 'Meditite', fullName: 'Meditite SCR 77' },
  { set: 'SCR', setNumber: '87', name: 'Crabrawler', fullName: 'Crabrawler SCR' },
  { set: 'SFA', setNumber: '7', name: 'Houndour', fullName: 'Houndour SFA' },
  { set: 'SFA', setNumber: '41', name: 'Cufant', fullName: 'Cufant SFA' },
  { set: 'SFA', setNumber: '44', name: 'Axew', fullName: 'Axew SFA' },
  { set: 'SHF', setNumber: '1', name: 'Yanma', fullName: 'Yanma SHF' },
  { set: 'SHF', setNumber: '4', name: 'Cacnea', fullName: 'Cacnea SHF' },
  { set: 'SHF', setNumber: '7', name: 'Dartrix', fullName: 'Dartrix SHF' },
  { set: 'SHF', setNumber: '14', name: 'Gossifleur', fullName: 'Gossifleur SHF 14' },
  { set: 'SHF', setNumber: '20', name: 'Horsea', fullName: 'Horsea SHF' },
  { set: 'SHF', setNumber: '23', name: 'Floatzel', fullName: 'Floatzel SHF' },
  { set: 'SHF', setNumber: '26', name: 'Chewtle', fullName: 'Chewtle SHF 26' },
  { set: 'SHF', setNumber: '43', name: 'Spinarak', fullName: 'Spinarak SHF' },
  { set: 'SIT', setNumber: '1', name: 'Venonat', fullName: 'Venonat SIT 1' },
  { set: 'SIT', setNumber: '3', name: 'Spinarak', fullName: 'Spinarak SIT 3' },
  { set: 'SIT', setNumber: '5', name: 'Sunkern', fullName: 'Sunkern SIT 5' },
  { set: 'SIT', setNumber: '9', name: 'Petilil', fullName: 'Petilil SIT 9' },
  { set: 'SIT', setNumber: '11', name: 'Foongus', fullName: 'Foongus SIT 11' },
  { set: 'SIT', setNumber: '19', name: 'Growlithe', fullName: 'Growlithe SIT 19' },
  { set: 'SIT', setNumber: '28', name: 'Fletchinder', fullName: 'Fletchinder SIT 28' },
  { set: 'SIT', setNumber: '47', name: 'Dewpider', fullName: 'Dewpider SIT 47' },
  { set: 'SIT', setNumber: '51', name: 'Chinchou', fullName: 'Chinchou SIT 51' },
  { set: 'SIT', setNumber: '76', name: 'Solosis', fullName: 'Solosis SIT 76' },
  { set: 'SIT', setNumber: '79', name: 'Elgyem', fullName: 'Elgyem SIT' },
  { set: 'SIT', setNumber: '81', name: 'Espurr', fullName: 'Espurr SIT 81' },
  { set: 'SIT', setNumber: '83', name: 'Swirlix', fullName: 'Swirlix SIT 83' },
  { set: 'SIT', setNumber: '88', name: 'Drakloak', fullName: 'Drakloak SIT' },
  { set: 'SIT', setNumber: '103', name: 'Zubat', fullName: 'Zubat SIT' },
  { set: 'SIT', setNumber: '104', name: 'Golbat', fullName: 'Golbat SIT' },
  { set: 'SIT', setNumber: '109', name: 'Croagunk', fullName: 'Croagunk SIT 109' },
  { set: 'SIT', setNumber: '121', name: 'Ferroseed', fullName: 'Ferroseed SIT 121' },
  { set: 'SIT', setNumber: '122', name: 'Ferrothorn', fullName: 'Ferrothorn SIT 122' },
  { set: 'SIT', setNumber: '132', name: 'Noibat', fullName: 'Noibat SIT 132' },
  { set: 'SIT', setNumber: '146', name: 'Archen', fullName: 'Archen SIT' },
  { set: 'SLG', setNumber: '1', name: 'Bulbasaur', fullName: 'Bulbasaur SLG' },
  { set: 'SLG', setNumber: '12', name: 'Larvesta', fullName: 'Larvesta SLG' },
  { set: 'SLG', setNumber: '15', name: 'Litten', fullName: 'Litten SLG' },
  { set: 'SLG', setNumber: '18', name: 'Totodile', fullName: 'Totodile SLG' },
  { set: 'SLG', setNumber: '22', name: 'Buizel', fullName: 'Buizel SLG' },
  { set: 'SLG', setNumber: '30', name: 'Voltorb', fullName: 'Voltorb SLG' },
  { set: 'SLG', setNumber: '43', name: 'Golett', fullName: 'Golett SLG' },
  { set: 'SLG', setNumber: '52', name: 'Zorua', fullName: 'Zorua SLG' },
  { set: 'SSH', setNumber: '5', name: 'Cottonee', fullName: 'Cottonee SSH' },
  { set: 'SSH', setNumber: '11', name: 'Grookey', fullName: 'Grookey SSH 11' },
  { set: 'SSH', setNumber: '16', name: 'Blipbug', fullName: 'Blipbug SSH' },
  { set: 'SSH', setNumber: '22', name: 'Vulpix', fullName: 'Vulpix SSH' },
  { set: 'SSH', setNumber: '31', name: 'Scorbunny', fullName: 'Scorbunny SSH 31' },
  { set: 'SSH', setNumber: '33', name: 'Raboot', fullName: 'Raboot SSH 33' },
  { set: 'SSH', setNumber: '37', name: 'Sizzlipede', fullName: 'Sizzlipede SSH' },
  { set: 'SSH', setNumber: '45', name: 'Goldeen', fullName: 'Goldeen SSH' },
  { set: 'SSH', setNumber: '54', name: 'Sobble', fullName: 'Sobble SSH 54' },
  { set: 'SSH', setNumber: '57', name: 'Drizzile', fullName: 'Drizzile SSH 57' },
  { set: 'SSH', setNumber: '60', name: 'Chewtle', fullName: 'Chewtle SSH' },
  { set: 'SSH', setNumber: '63', name: 'Snom', fullName: 'Snom SSH' },
  { set: 'SSH', setNumber: '66', name: 'Raichu', fullName: 'Raichu SSH' },
  { set: 'SSH', setNumber: '67', name: 'Chinchou', fullName: 'Chinchou SSH' },
  { set: 'SSH', setNumber: '70', name: 'Joltik', fullName: 'Joltik SSH' },
  { set: 'SSH', setNumber: '74', name: 'Yamper', fullName: 'Yamper SSH 74' },
  { set: 'SSH', setNumber: '92', name: 'Diglett', fullName: 'Diglett SSH' },
  { set: 'SSH', setNumber: '93', name: 'Dugtrio', fullName: 'Dugtrio SSH' },
  { set: 'SSH', setNumber: '96', name: 'Rhyhorn', fullName: 'Rhyhorn SSH' },
  { set: 'SSH', setNumber: '101', name: 'Baltoy', fullName: 'Baltoy SSH' },
  { set: 'SSH', setNumber: '102', name: 'Baltoy', fullName: 'Baltoy SSH 102' },
  { set: 'SSH', setNumber: '105', name: 'Mudbray', fullName: 'Mudbray SSH' },
  { set: 'SSH', setNumber: '108', name: 'Silicobra', fullName: 'Silicobra SSH 108' },
  { set: 'SSH', setNumber: '112', name: 'Clobbopus', fullName: 'Clobbopus SSH 112' },
  { set: 'SSH', setNumber: '123', name: 'Croagunk', fullName: 'Croagunk SSH' },
  { set: 'SSH', setNumber: '130', name: 'Ferroseed', fullName: 'Ferroseed SSH' },
  { set: 'SSH', setNumber: '133', name: 'Pawniard', fullName: 'Pawniard SSH' },
  { set: 'SSH', setNumber: '140', name: 'Snorlax', fullName: 'Snorlax SSH' },
  { set: 'SSH', setNumber: '146', name: 'Minccino', fullName: 'Minccino SSH 146' },
  { set: 'SSH', setNumber: '150', name: 'Rookidee', fullName: 'Rookidee SSH' },
  { set: 'SSH', setNumber: '153', name: 'Wooloo', fullName: 'Wooloo SSH 153' },
  { set: 'SSP', setNumber: '12', name: 'Capsakid', fullName: 'Capsakid SSP' },
  { set: 'SSP', setNumber: '22', name: 'Pansear', fullName: 'Pansear SSP' },
  { set: 'SSP', setNumber: '24', name: 'Larvesta', fullName: 'Larvesta SSP' },
  { set: 'SSP', setNumber: '27', name: 'Sizzlipede', fullName: 'Sizzlipede SSP' },
  { set: 'SSP', setNumber: '32', name: 'Charcadet', fullName: 'Charcadet SSP' },
  { set: 'SSP', setNumber: '44', name: 'Sealeo', fullName: 'Sealeo SSP' },
  { set: 'SSP', setNumber: '46', name: 'Shellos', fullName: 'Shellos SSP' },
  { set: 'SSP', setNumber: '51', name: 'Quaxwell', fullName: 'Quaxwell SSP' },
  { set: 'SSP', setNumber: '58', name: 'Magnemite', fullName: 'Magnemite SSP' },
  { set: 'SSP', setNumber: '70', name: 'Togepi', fullName: 'Togepi SSP' },
  { set: 'SSP', setNumber: '73', name: 'Marill', fullName: 'Marill SSP' },
  { set: 'SSP', setNumber: '90', name: 'Sandygast', fullName: 'Sandygast SSP' },
  { set: 'SSP', setNumber: '120', name: 'Shroodle', fullName: 'Shroodle SSP' },
  { set: 'SSP', setNumber: '146', name: 'Vigoroth', fullName: 'Vigoroth SSP' },
  { set: 'SSP', setNumber: '205', name: 'Phanpy', fullName: 'Phanpy SSP' },
  { set: 'STS', setNumber: '3', name: 'Hoppip', fullName: 'Hoppip STS' },
  { set: 'STS', setNumber: '4', name: 'Skiploom', fullName: 'Skiploom STS' },
  { set: 'STS', setNumber: '14', name: 'Larvesta', fullName: 'Larvesta STS' },
  { set: 'STS', setNumber: '19', name: 'Monferno', fullName: 'Monferno STS' },
  { set: 'STS', setNumber: '28', name: 'Shellos', fullName: 'Shellos STS' },
  { set: 'STS', setNumber: '30', name: 'Oshawott', fullName: 'Oshawott STS' },
  { set: 'STS', setNumber: '41', name: 'Joltik', fullName: 'Joltik STS' },
  { set: 'STS', setNumber: '94', name: 'Fletchling', fullName: 'Fletchling STS' },
  { set: 'STS', setNumber: '95', name: 'Fletchinder', fullName: 'Fletchinder STS' },
  { set: 'SUM', setNumber: '4', name: 'Paras', fullName: 'Paras SUM' },
  { set: 'SUM', setNumber: '9', name: 'Rowlet', fullName: 'Rowlet SUM' },
  { set: 'SUM', setNumber: '13', name: 'Grubbin', fullName: 'Grubbin SUM' },
  { set: 'SUM', setNumber: '24', name: 'Litten', fullName: 'Litten SUM' },
  { set: 'SUM', setNumber: '33', name: 'Shellder', fullName: 'Shellder SUM' },
  { set: 'SUM', setNumber: '39', name: 'Popplio', fullName: 'Popplio SUM' },
  { set: 'SUM', setNumber: '72', name: 'Crabrawler', fullName: 'Crabrawler SUM' },
  { set: 'SUM', setNumber: '76', name: 'Alolan Rattata', fullName: 'Alolan Rattata SUM' },
  { set: 'SUM', setNumber: '109', name: 'Yungoos', fullName: 'Yungoos SUM' },
  { set: 'SUM', setNumber: '111', name: 'Stufful', fullName: 'Stufful SUM' },
  { set: 'SV', setNumber: '93', name: 'Bulbasaur', fullName: 'Bulbasaur SV' },
  { set: 'SVI', setNumber: '40', name: 'Charcadet', fullName: 'Charcadet SVI' },
  { set: 'SVI', setNumber: '52', name: 'Quaxly', fullName: 'Quaxly SVI' },
  { set: 'SVI', setNumber: '53', name: 'Quaxwell', fullName: 'Quaxwell SVI' },
  { set: 'SVI', setNumber: '66', name: 'Mareep', fullName: 'Mareep SVI' },
  { set: 'SVI', setNumber: '74', name: 'Pawmi', fullName: 'Pawmi SVI' },
  { set: 'SVI', setNumber: '84', name: 'Ralts', fullName: 'Ralts SVI' },
  { set: 'SVI', setNumber: '100', name: 'Flittle', fullName: 'Flittle SVI' },
  { set: 'SVI', setNumber: '112', name: 'Riolu', fullName: 'Riolu SVI' },
  { set: 'SVI', setNumber: '130', name: 'Croagunk', fullName: 'Croagunk SVI' },
  { set: 'SVI', setNumber: '132', name: 'Pawniard', fullName: 'Pawniard SVI' },
  { set: 'SWSH', setNumber: '172', name: 'Tepig', fullName: 'Tepig SWSH' },
  { set: 'TEF', setNumber: '20', name: 'Bramblin', fullName: 'Bramblin TEF' },
  { set: 'TEF', setNumber: '55', name: 'Charjabug', fullName: 'Charjabug TEF' },
  { set: 'TEU', setNumber: '6', name: 'Paras', fullName: 'Paras TEU' },
  { set: 'TEU', setNumber: '23', name: 'Squirtle', fullName: 'Squirtle TEU 23' },
  { set: 'TEU', setNumber: '24', name: 'Wartortle', fullName: 'Wartortle TEU' },
  { set: 'TEU', setNumber: '36', name: 'Alolan Graveler', fullName: 'Alolan Graveler TEU' },
  { set: 'TEU', setNumber: '38', name: 'Voltorb', fullName: 'Voltorb TEU' },
  { set: 'TEU', setNumber: '49', name: 'Helioptile', fullName: 'Helioptile TEU' },
  { set: 'TEU', setNumber: '57', name: 'Nidoran ♂', fullName: 'Nidoran ♂ TEU' },
  { set: 'TEU', setNumber: '58', name: 'Nidorino', fullName: 'Nidorino TEU' },
  { set: 'TEU', setNumber: '62', name: 'Grimer', fullName: 'Grimer TEU' },
  { set: 'TEU', setNumber: '125', name: 'Meowth', fullName: 'Meowth TEU' },
  { set: 'TR', setNumber: '59', name: 'Machop', fullName: 'Machop TR' },
  { set: 'TR', setNumber: '68', name: 'Squirtle', fullName: 'Squirtle TR' },
  { set: 'TR', setNumber: '69', name: 'Voltorb', fullName: 'Voltorb TR' },
  { set: 'TWM', setNumber: '14', name: 'Grookey', fullName: 'Grookey TWM' },
  { set: 'TWM', setNumber: '78', name: 'Clefairy', fullName: 'Clefairy TWM' },
  { set: 'TWM', setNumber: '128', name: 'Dreepy', fullName: 'Dreepy TWM' },
  { set: 'TWM', setNumber: '137', name: 'Aipom', fullName: 'Aipom TWM' },
  { set: 'UF', setNumber: '51', name: 'Chikorita', fullName: 'Chikorita UF' },
  { set: 'UF', setNumber: '66', name: 'Pineco', fullName: 'Pineco UF' },
  { set: 'UF', setNumber: '79', name: 'Wooper', fullName: 'Wooper UF' },
  { set: 'UL', setNumber: '48', name: 'Chinchou', fullName: 'Chinchou UL' },
  { set: 'UNB', setNumber: '6', name: 'Oddish', fullName: 'Oddish UNB 6' },
  { set: 'UNB', setNumber: '13', name: 'Bellsprout', fullName: 'Bellsprout UNB' },
  { set: 'UNB', setNumber: '21', name: 'Growlithe', fullName: 'Growlithe UNB' },
  { set: 'UNB', setNumber: '44', name: 'Seel', fullName: 'Seel UNB' },
  { set: 'UNB', setNumber: '46', name: 'Krabby', fullName: 'Krabby UNB' },
  { set: 'UNB', setNumber: '54', name: 'Pikachu', fullName: 'Pikachu UNB' },
  { set: 'UNB', setNumber: '93', name: 'Rhyhorn', fullName: 'Rhyhorn UNB 93' },
  { set: 'UNB', setNumber: '96', name: 'Wooper', fullName: 'Wooper UNB' },
  { set: 'UNB', setNumber: '97', name: 'Quagsire', fullName: 'Quagsire UNB' },
  { set: 'UNB', setNumber: '110', name: 'Carvanha', fullName: 'Carvanha UNB' },
  { set: 'UNB', setNumber: '121', name: 'Alolan Diglett', fullName: 'Alolan Diglett UNB' },
  { set: 'UNB', setNumber: '143', name: 'Rattata', fullName: 'Rattata UNB' },
  { set: 'UNB', setNumber: '145', name: 'Spearow', fullName: 'Spearow UNB' },
  { set: 'UNM', setNumber: '2', name: 'Yanma', fullName: 'Yanma UNM' },
  { set: 'UNM', setNumber: '10', name: 'Dwebble', fullName: 'Dwebble UNM' },
  { set: 'UNM', setNumber: '17', name: 'Bounsweet', fullName: 'Bounsweet UNM' },
  { set: 'UNM', setNumber: '33', name: 'Salandit', fullName: 'Salandit UNM' },
  { set: 'UNM', setNumber: '34', name: 'Salazzle', fullName: 'Salazzle UNM' },
  { set: 'UNM', setNumber: '37', name: 'Snorunt', fullName: 'Snorunt UNM' },
  { set: 'UNM', setNumber: '39', name: 'Finneon', fullName: 'Finneon UNM' },
  { set: 'UNM', setNumber: '44', name: 'Tirtouga', fullName: 'Tirtouga UNM' },
  { set: 'UNM', setNumber: '48', name: 'Dewpider', fullName: 'Dewpider UNM' },
  { set: 'UNM', setNumber: '56', name: 'Pikachu', fullName: 'Pikachu UNM 56' },
  { set: 'UNM', setNumber: '80', name: 'Drifloon', fullName: 'Drifloon UNM' },
  { set: 'UNM', setNumber: '96', name: 'Mareanie', fullName: 'Mareanie UNM' },
  { set: 'UNM', setNumber: '97', name: 'Toxapex', fullName: 'Toxapex UNM' },
  { set: 'UNM', setNumber: '98', name: 'Salandit', fullName: 'Salandit UNM 98' },
  { set: 'UNM', setNumber: '99', name: 'Salazzle', fullName: 'Salazzle UNM 99' },
  { set: 'UNM', setNumber: '100', name: 'Cosmog', fullName: 'Cosmog UNM' },
  { set: 'UNM', setNumber: '112', name: 'Gible', fullName: 'Gible UNM' },
  { set: 'UNM', setNumber: '113', name: 'Gabite', fullName: 'Gabite UNM' },
  { set: 'UNM', setNumber: '115', name: 'Riolu', fullName: 'Riolu UNM' },
  { set: 'UNM', setNumber: '118', name: 'Drilbur', fullName: 'Drilbur UNM' },
  { set: 'UNM', setNumber: '129', name: 'Murkrow', fullName: 'Murkrow UNM 129' },
  { set: 'UNM', setNumber: '131', name: 'Sneasel', fullName: 'Sneasel UNM' },
  { set: 'UNM', setNumber: '174', name: 'Pidove', fullName: 'Pidove UNM' },
  { set: 'UNM', setNumber: '179', name: 'Fletchling', fullName: 'Fletchling UNM' },
  { set: 'UNM', setNumber: '180', name: 'Yungoos', fullName: 'Yungoos UNM' },
  { set: 'UP', setNumber: 'Ancient Mew', name: 'Ancient Mew', fullName: 'Ancient Mew UP' },
  { set: 'UPR', setNumber: '7', name: 'Turtwig', fullName: 'Turtwig UPR 7' },
  { set: 'UPR', setNumber: '20', name: 'Chimchar', fullName: 'Chimchar UPR' },
  { set: 'UPR', setNumber: '25', name: 'Salandit', fullName: 'Salandit UPR' },
  { set: 'UPR', setNumber: '32', name: 'Piplup', fullName: 'Piplup UPR 32' },
  { set: 'UPR', setNumber: '35', name: 'Buizel', fullName: 'Buizel UPR' },
  { set: 'UPR', setNumber: '64', name: 'Cranidos', fullName: 'Cranidos UPR' },
  { set: 'UPR', setNumber: '104', name: 'Eevee', fullName: 'Eevee UPR' },
  { set: 'VIV', setNumber: '4', name: 'Exeggcute', fullName: 'Exeggcute VIV' },
  { set: 'VIV', setNumber: '10', name: 'Seedot', fullName: 'Seedot VIV' },
  { set: 'VIV', setNumber: '11', name: 'Nuzleaf', fullName: 'Nuzleaf VIV' },
  { set: 'VIV', setNumber: '33', name: 'Oshawott', fullName: 'Oshawott VIV' },
  { set: 'VIV', setNumber: '45', name: 'Voltorb', fullName: 'Voltorb VIV' },
  { set: 'VIV', setNumber: '53', name: 'Blitzle', fullName: 'Blitzle VIV' },
  { set: 'VIV', setNumber: '54', name: 'Zebstrika', fullName: 'Zebstrika VIV' },
  { set: 'VIV', setNumber: '55', name: 'Joltik', fullName: 'Joltik VIV' },
  { set: 'VIV', setNumber: '75', name: 'Cottonee', fullName: 'Cottonee VIV' },
  { set: 'VIV', setNumber: '83', name: 'Wooper', fullName: 'Wooper VIV' },
  { set: 'VIV', setNumber: '94', name: 'Rockruff', fullName: 'Rockruff VIV' },
  { set: 'VIV', setNumber: '95', name: 'Lycanroc', fullName: 'Lycanroc VIV' },
  { set: 'VIV', setNumber: '96', name: 'Mudbray', fullName: 'Mudbray VIV' },
  { set: 'VIV', setNumber: '100', name: 'Clobbopus', fullName: 'Clobbopus VIV' },
  { set: 'VIV', setNumber: '103', name: 'Poochyena', fullName: 'Poochyena VIV' },
  { set: 'VIV', setNumber: '117', name: 'Metang', fullName: 'Metang VIV' },
  { set: 'VIV', setNumber: '130', name: 'Eevee', fullName: 'Eevee VIV' },
  { set: 'VIV', setNumber: '143', name: 'Pikipek', fullName: 'Pikipek VIV' },
  { set: 'WHT', setNumber: '11', name: 'Tepig', fullName: 'Tepig SV11W' },
  { set: 'WHT', setNumber: '12', name: 'Pignite', fullName: 'Pignite SV11W' },
  { set: 'WHT', setNumber: '21', name: 'Oshawott', fullName: 'Oshawott SV11W' },
  { set: 'WHT', setNumber: '41', name: 'Gothita', fullName: 'Gothita WHT' },
  { set: 'XY', setNumber: '6', name: 'Ledyba', fullName: 'Ledyba XY' },
  { set: 'XY', setNumber: '15', name: 'Scatterbug', fullName: 'Scatterbug XY' },
  { set: 'XY', setNumber: '24', name: 'Fennekin', fullName: 'Fennekin XY' },
  { set: 'XY', setNumber: '31', name: 'Shellder', fullName: 'Shellder XY' },
  { set: 'XY', setNumber: '47', name: 'Ekans', fullName: 'Ekans XY' },
  { set: 'XY', setNumber: '49', name: 'Spoink', fullName: 'Spoink XY' },
  { set: 'XY', setNumber: '69', name: 'Sandile', fullName: 'Sandile XY' },
  { set: 'XY', setNumber: '83', name: 'Honedge', fullName: 'Honedge XY' },
  { set: 'XY', setNumber: '94', name: 'Swirlix', fullName: 'Swirlix XY' },
  { set: 'XY', setNumber: '108', name: 'Lillipup', fullName: 'Lillipup XY' },
];
