// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PlayerType, PowerType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { CheckPokemonStatsEffect } from '../../game/store/effects/check-effects';
import { IS_ABILITY_BLOCKED, WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Aegislash extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Doublade';
  public cardType: CardType = M;
  public hp: number = 140;
  public weakness = [{ type: R }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C, C];

  public readonly REDUCE_DAMAGE_MARKER = 'AEGISLASH_PRC_REDUCE_DAMAGE_MARKER';
  public readonly CLEAR_REDUCE_DAMAGE_MARKER = 'AEGISLASH_PRC_CLEAR_REDUCE_DAMAGE_MARKER';

  public powers = [{
    name: 'Miracle Guard',
    useWhenInPlay: false,
    powerType: PowerType.ABILITY,
    text: 'Each of your Pokémon has no Weakness.'
  }];

  public attacks = [
    {
      name: 'Protect Charge',
      cost: [M, C, C],
      damage: 80,
      text: 'During your opponent\'s next turn, any damage done to this Pokémon by attacks is reduced by 20 (after applying Weakness and Resistance).'
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '100';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Aegislash';
  public fullName: string = 'Aegislash PRC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Miracle Guard
    // Ref: set-plasma-blast/mesprit.ts (Mental Shroud)
    if (effect instanceof CheckPokemonStatsEffect) {
      let aegislashOwner: any = null;

      state.players.forEach(p => {
        p.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
          if (cardList.getPokemonCard() === this) {
            aegislashOwner = p;
          }
        });
      });

      if (!aegislashOwner) {
        return state;
      }

      if (IS_ABILITY_BLOCKED(store, state, aegislashOwner, this)) {
        return state;
      }

      // Check if the target Pokemon belongs to the same player
      let targetOwner: any = null;
      state.players.forEach(p => {
        if (p.active === effect.target || p.bench.includes(effect.target)) {
          targetOwner = p;
        }
      });

      if (targetOwner === aegislashOwner) {
        effect.weakness = [];
      }
    }

    // Attack 1: Protect Charge
    // Ref: set-primal-clash/nosepass.ts (Stiffen)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      player.active.marker.addMarker(this.REDUCE_DAMAGE_MARKER, this);
      opponent.marker.addMarker(this.CLEAR_REDUCE_DAMAGE_MARKER, this);
    }

    if (effect instanceof DealDamageEffect && effect.target.cards.includes(this)) {
      if (effect.target.marker.hasMarker(this.REDUCE_DAMAGE_MARKER, this)) {
        effect.damage = Math.max(0, effect.damage - 20);
      }
    }

    if (effect instanceof EndTurnEffect
      && effect.player.marker.hasMarker(this.CLEAR_REDUCE_DAMAGE_MARKER, this)) {
      effect.player.marker.removeMarker(this.CLEAR_REDUCE_DAMAGE_MARKER, this);
      const opponent = StateUtils.getOpponent(state, effect.player);
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        cardList.marker.removeMarker(this.REDUCE_DAMAGE_MARKER, this);
      });
    }

    return state;
  }
}
