// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE } from '../../game/store/prefabs/attack-effects';

export class AggronEx extends PokemonCard {
  public tags = [CardTag.POKEMON_EX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = M;
  public hp: number = 180;
  public weakness = [{ type: R }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Steel Headbutt',
      cost: [M, C, C],
      damage: 50,
      damageCalculation: '+' as '+',
      text: 'Flip a coin. If heads, this attack does 30 more damage.'
    },
    {
      name: 'Raging Hammer',
      cost: [M, M, C, C],
      damage: 60,
      damageCalculation: '+' as '+',
      text: 'This attack does 10 more damage for each damage counter on this Pokémon.'
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '93';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Aggron-EX';
  public fullName: string = 'Aggron-EX PRC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Steel Headbutt
    // Ref: set-phantom-forces/murkrow.ts (Ambush)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      FLIP_A_COIN_IF_HEADS_DEAL_MORE_DAMAGE(store, state, effect, 30);
    }

    // Attack 2: Raging Hammer
    // Ref: AGENTS-patterns.md (damage counter based damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      effect.damage += Math.floor(player.active.damage / 10) * 10;
    }

    return state;
  }
}
