// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../game/store/card/trainer-card';
import { TrainerType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';

export class AggronSpiritLink extends TrainerCard {
  public trainerType: TrainerType = TrainerType.TOOL;
  public set: string = 'PRC';
  public setNumber: string = '123';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Aggron Spirit Link';
  public fullName: string = 'Aggron Spirit Link PRC';
  public text: string = 'Your turn does not end if the Pokémon this card is attached to becomes M Aggron-EX.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-primal-clash/groudon-spirit-link.ts (Spirit Link - no-op, handled by engine)
    return state;
  }
}
