// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { AfterAttackEffect, EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, SWITCH_ACTIVE_WITH_BENCHED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED } from '../../game/store/prefabs/attack-effects';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../game/store/prefabs/costs';

export class Masquerain extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Surskit';
  public cardType: CardType = G;
  public hp: number = 80;
  public weakness = [{ type: R }];
  public retreat = [C];

  public usedSpiralGyration = false;

  public attacks = [
    {
      name: 'Spiral Gyration',
      cost: [G],
      damage: 0,
      text: 'Your opponent\'s Active Pokémon is now Confused. Switch this Pokémon with 1 of your Benched Pokémon.'
    },
    {
      name: 'Air Slash',
      cost: [C, C],
      damage: 50,
      text: 'Discard an Energy attached to this Pokémon.'
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '14';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Masquerain';
  public fullName: string = 'Masquerain PRC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Spiral Gyration
    // Refs: set-x-and-y/conkeldurr.ts (confusion), set-flashfire/buneary.ts (self-switch after attack)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED(store, state, effect);
      this.usedSpiralGyration = true;
    }

    if (effect instanceof AfterAttackEffect && this.usedSpiralGyration) {
      this.usedSpiralGyration = false;
      const player = effect.player;
      if (player.bench.some(b => b.cards.length > 0)) {
        SWITCH_ACTIVE_WITH_BENCHED(store, state, player);
      }
    }

    if (effect instanceof EndTurnEffect) {
      this.usedSpiralGyration = false;
    }

    // Attack 2: Air Slash
    // Ref: AGENTS-patterns.md (discard energy cost)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 1);
    }

    return state;
  }
}
