// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, THIS_POKEMON_DOES_DAMAGE_TO_ITSELF } from '../../game/store/prefabs/prefabs';

export class Rhydon extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Rhyhorn';
  public cardType: CardType = F;
  public hp: number = 100;
  public weakness = [{ type: G }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Take Down',
      cost: [F, C, C],
      damage: 50,
      text: 'This Pokémon does 10 damage to itself.'
    },
    {
      name: 'Horn Drill',
      cost: [F, F, C, C],
      damage: 70,
      text: ''
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '75';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Rhydon';
  public fullName: string = 'Rhydon PRC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Take Down
    // Ref: set-primal-clash/rhyhorn.ts (Take Down)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      THIS_POKEMON_DOES_DAMAGE_TO_ITSELF(store, state, effect, 10);
    }

    return state;
  }
}
