// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PlayerType, PowerType, StateUtils, StoreLike, State } from '../../game';
import { DealDamageEffect, PutDamageEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED, MOVE_CARDS } from '../../game/store/prefabs/prefabs';

export class Rhyperior2 extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Rhydon';
  public cardType: CardType = F;
  public hp: number = 160;
  public weakness = [{ type: G }];
  public retreat = [C, C, C, C];

  public powers = [{
    name: 'Rock Wall',
    powerType: PowerType.ABILITY,
    text: 'Any damage done to your Pokémon by an opponent\'s attack is reduced by 10 (after applying Weakness and Resistance).'
  }];

  public attacks = [
    {
      name: 'Hammer Arm',
      cost: [F, F, C, C],
      damage: 100,
      text: 'Discard the top card of your opponent\'s deck.'
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '77';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Rhyperior';
  public fullName: string = 'Rhyperior PRC 77';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Rock Wall
    // Ref: set-ex-dragon-frontiers/kingdra-ex.ts (Extra Smoke - reduce damage to your Pokemon)
    if (effect instanceof DealDamageEffect || effect instanceof PutDamageEffect) {
      const targetCard = effect.target.getPokemonCard();
      if (!targetCard) { return state; }

      // Find the owner of the target
      let targetOwner: any = null;
      state.players.forEach(p => {
        p.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
          if (cardList === effect.target) {
            targetOwner = p;
          }
        });
      });
      if (!targetOwner) { return state; }

      // Check if Rhyperior is in play for the target owner
      let isInPlay = false;
      targetOwner.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList: any, card: PokemonCard) => {
        if (card === this) {
          isInPlay = true;
        }
      });
      if (!isInPlay) { return state; }

      if (IS_ABILITY_BLOCKED(store, state, targetOwner, this)) {
        return state;
      }

      // Only reduce damage from opponent's attacks
      const sourceOwner = effect.player;
      if (sourceOwner === targetOwner) { return state; }

      effect.damage = Math.max(0, effect.damage - 10);
    }

    // Attack 1: Hammer Arm
    // Ref: set-dragons-exalted/giratina-ex.ts (Dragon Pulse - discard top cards)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      MOVE_CARDS(store, state, opponent.deck, opponent.discard, { count: 1, sourceCard: this, sourceEffect: effect });
    }

    return state;
  }
}
