// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { GameMessage, PlayerType, SlotType, StoreLike, State, StateUtils } from '../../game';
import { PutDamageEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON } from '../../game/store/prefabs/attack-effects';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../game/store/prefabs/costs';
import { ChoosePokemonPrompt } from '../../game/store/prompts/choose-pokemon-prompt';

export class SharpedoEx extends PokemonCard {
  public tags = [CardTag.POKEMON_EX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = D;
  public hp: number = 170;
  public weakness = [{ type: L }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Hunt',
      cost: [D, C],
      damage: 0,
      text: 'Switch 1 of your opponent\'s Benched Pokémon with his or her Active Pokémon. This attack does 30 damage to the new Active Pokémon.'
    },
    {
      name: 'Jagged Fang',
      cost: [D, D, C],
      damage: 100,
      text: 'Discard an Energy attached to this Pokémon. Then, discard an Energy attached to your opponent\'s Active Pokémon.'
    }
  ];

  public set: string = 'PRC';
  public setNumber: string = '91';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Sharpedo-EX';
  public fullName: string = 'Sharpedo-EX PRC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Hunt
    // Ref: set-lost-origin/magnezone-v.ts (Magnetic Tension)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      const hasBench = opponent.bench.some(b => b.cards.length > 0);

      if (hasBench) {
        return store.prompt(state, new ChoosePokemonPrompt(
          player.id,
          GameMessage.CHOOSE_POKEMON_TO_SWITCH,
          PlayerType.TOP_PLAYER,
          [SlotType.BENCH],
          { allowCancel: false }
        ), result => {
          const cardList = result[0];
          opponent.switchPokemon(cardList);
          const damageEffect = new PutDamageEffect(effect, 30);
          damageEffect.target = opponent.active;
          store.reduceEffect(state, damageEffect);
        });
      }
    }

    // Attack 2: Jagged Fang
    // Refs: AGENTS-patterns.md (discard energy from self + opponent)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 1);
      DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON(store, state, effect);
    }

    return state;
  }
}
