import { Card } from '../../game/store/card/card';
import { AncientBoosterEnergyCapsuleArt, BeldumArt, BiancasDevotionArt, BuddyBuddyPoffinArt, CharjabugArt, ChatotArt, CincinnoArt, CroconawArt, CryptomaniacsDecipheringArt, DeliveryBoxArt, DrilburArt, DrumsOfAwakeningArt, DudunsparceArt, DunsparceArt, DuosionArt, EmergencyBoardArt, EriArt, ExplorersGuidanceArt, FeraligatrArt, FlutterManeArt, FutureBoosterEnergyCapsuleArt, GastlyArt, GengarexArt, GougingFireexArt, GrotleArt, HandTrimmerArt, HaunterArt, HerosCapeArt, IronCrownexArt, IronHandsArt, IronLeavesexArt, IronThornsArt, KoraidonArt, KoraidonexArt, MasterBallArt, MaximumBeltArt, MetangArt, MiraidonArt, MiraidonexArt, MistEnergyArt, MortysConvictionArt, MrMimeArt, NeoUpperEnergyArt, PikachuArt, PrimeCatcherArt, RabscaArt, RagingBoltexArt, RaichuArt, RebootPodArt, RellorArt, ReuniclusArt, RoaringMoonArt, SableyeArt, SalvatoreArt, SandyShocksArt, SolosisArt, TorterraexArt, TotodileArt, TurtwigArt, VictiniArt, VikavoltArt, WalkingWakeexArt } from './card-images';

export const setTemporalForces: Card[] = [
  
  new AncientBoosterEnergyCapsuleArt(),
  new BeldumArt(),
  new BiancasDevotionArt(),
  new BuddyBuddyPoffinArt(),
  new CharjabugArt(),
  new ChatotArt(),
  new CincinnoArt(),
  new CroconawArt(),
  new CryptomaniacsDecipheringArt(),
  new DeliveryBoxArt(),
  new DrilburArt(),
  new DrumsOfAwakeningArt(),
  new DudunsparceArt(),
  new DunsparceArt(),
  new DuosionArt(),
  new EmergencyBoardArt(),
  new EriArt(),
  new ExplorersGuidanceArt(),
  new FeraligatrArt(),
  new FlutterManeArt(),
  new FutureBoosterEnergyCapsuleArt(),
  new GastlyArt(),
  new GengarexArt(),
  new GougingFireexArt(),
  new GrotleArt(),
  new HandTrimmerArt(),
  new HaunterArt(),
  new HerosCapeArt(),
  new IronCrownexArt(),
  new IronHandsArt(),
  new IronLeavesexArt(),
  new IronThornsArt(),
  new KoraidonexArt(),
  new KoraidonArt(),
  new MasterBallArt(),
  new MaximumBeltArt(),
  new MetangArt(),
  new MiraidonexArt(),
  new MiraidonArt(),
  new MistEnergyArt(),
  new MortysConvictionArt(),
  new MrMimeArt(),
  new NeoUpperEnergyArt(),
  new PikachuArt(),
  new PrimeCatcherArt(),
  new RabscaArt(),
  new RagingBoltexArt(),
  new RaichuArt(),
  new RebootPodArt(),
  new RellorArt(),
  new ReuniclusArt(),
  new RoaringMoonArt(),
  new SableyeArt(),
  new SalvatoreArt(),
  new SandyShocksArt(),
  new SolosisArt(),
  new TorterraexArt(),
  new TotodileArt(),
  new TurtwigArt(),
  new VictiniArt(),
  new VikavoltArt(),
  new WalkingWakeexArt(),

];