import { Card } from '../../game/store/card/card';
import { AbsolArt, AxewArt, BindingMochiArt, CassiopeiaArt, ColresssObsessionArt, CopperajahArt, CresseliaArt, CufantArt, DangerousLaserArt, DartrixArt, DecidueyeArt, DusclopsArt, DusknoirArt, DuskullArt, FezandipitiexArt, FraxureArt, GalvantulaArt, HaxorusArt, HorseaArt, HoundoomArt, HoundourArt, IronMothArt, JaninesSecretTechniqueArt, KingdraexArt, KyuremArt, MunkidoriexArt, NeutralCenterArt, NightTimeAcademyArt, NightlyStretcherArt, OkidogiexArt, PecharuntexArt, PokeVitalAArt, PowerHourglassArt, RevavroomexArt, RowletArt, SeadraArt, SlitherWingArt, SneaselArt, TapuBuluArt, WeavileArt, XerosicsSchemeArt, ZoroarkArt, ZoruaArt } from './card-images';

export const setShroudedFable: Card[] = [
  new AbsolArt(),
  new AxewArt(),
  new BindingMochiArt(),
  new CassiopeiaArt(),
  new ColresssObsessionArt(),
  new CopperajahArt(),
  new CresseliaArt(),
  new CufantArt(),
  new DangerousLaserArt(),
  new DartrixArt(),
  new DecidueyeArt(),
  new DusclopsArt(),
  new DusknoirArt(),
  new DuskullArt(),
  new FezandipitiexArt(),
  new FraxureArt,
  new GalvantulaArt(),
  new HaxorusArt(),
  new HorseaArt(),
  new HoundoomArt(),
  new HoundourArt(),
  new IronMothArt(),
  new JaninesSecretTechniqueArt(),
  new KingdraexArt(),
  new KyuremArt(),
  new MunkidoriexArt(),
  new NeutralCenterArt(),
  new NightTimeAcademyArt(),
  new NightlyStretcherArt(),
  new OkidogiexArt(),
  new PecharuntexArt(),
  new PokeVitalAArt(),
  new PowerHourglassArt(),
  new RevavroomexArt(),
  new RowletArt(),
  new SeadraArt(),
  new SlitherWingArt(),
  new SneaselArt(),
  new TapuBuluArt(),
  new WeavileArt(),
  new XerosicsSchemeArt(),
  new ZoroarkArt(),
  new ZoruaArt(),

];
