// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { HEAL_X_DAMAGE_FROM_THIS_POKEMON } from '../../game/store/prefabs/attack-effects';

export class Bergmite extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 70;
  public weakness = [{ type: M }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Ice Block',
      cost: [W],
      damage: 0,
      text: 'Heal 30 damage from this Pok\u00e9mon.'
    },
    {
      name: 'Icy Snow',
      cost: [C, C],
      damage: 20,
      text: ''
    }
  ];

  public set: string = 'STS';
  public setNumber: string = '36';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Bergmite';
  public fullName: string = 'Bergmite STS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Ice Block
    // Ref: set-fates-collide/snorlax.ts (Rest)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      HEAL_X_DAMAGE_FROM_THIS_POKEMON(30, effect, store, state);
    }

    return state;
  }
}
