// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { CardTarget, GameMessage, PlayerType, StoreLike, State } from '../../game';
import { ChoosePokemonPrompt } from '../../game/store/prompts/choose-pokemon-prompt';
import { SlotType } from '../../game/store/actions/play-card-action';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Drifloon extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = P;
  public hp: number = 60;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Transfer Pain',
      cost: [C],
      damage: 0,
      text: 'Move 1 damage counter from 1 of your Pokémon to 1 of your opponent\'s Pokémon.'
    }
  ];

  public set: string = 'STS';
  public setNumber: string = '46';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Drifloon';
  public fullName: string = 'Drifloon STS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Transfer Pain
    // Ref: set-celestial-storm/banette-gx.ts (Shady Move - move damage counter pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      // Check if any of your Pokemon has damage
      let hasDamage = false;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        if (cardList.damage > 0) {
          hasDamage = true;
        }
      });

      if (!hasDamage) {
        return state;
      }

      // Build blocked list for Pokemon with no damage
      const blocked: CardTarget[] = [];
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card, target) => {
        if (cardList.damage === 0) {
          blocked.push(target);
        }
      });

      // Choose your Pokemon to remove damage from
      return store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { min: 1, max: 1, allowCancel: false, blocked }
      ), sourceTargets => {
        if (!sourceTargets || sourceTargets.length === 0) { return; }
        const source = sourceTargets[0];

        // Choose opponent's Pokemon to put damage on
        store.prompt(state, new ChoosePokemonPrompt(
          player.id,
          GameMessage.CHOOSE_POKEMON,
          PlayerType.TOP_PLAYER,
          [SlotType.ACTIVE, SlotType.BENCH],
          { min: 1, max: 1, allowCancel: false }
        ), destTargets => {
          if (!destTargets || destTargets.length === 0) { return; }
          const dest = destTargets[0];
          source.damage -= 10;
          dest.damage += 10;
        });
      });
    }

    return state;
  }
}
