// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../game/store/prefabs/costs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED, PUT_X_DAMAGE_COUNTERS_IN_ANY_WAY_YOU_LIKE } from '../../game/store/prefabs/attack-effects';

export class Drifblim extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Drifloon';
  public cardType: CardType = P;
  public hp: number = 100;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Eerie Wave',
      cost: [C, C],
      damage: 30,
      text: 'Your opponent\'s Active Pok\u00e9mon is now Confused.'
    },
    {
      name: 'Burst Curse',
      cost: [P, P],
      damage: 0,
      text: 'Discard 2 Energy attached to this Pok\u00e9mon. Put 8 damage counters on your opponent\'s Pok\u00e9mon in any way you like.'
    }
  ];

  public set: string = 'STS';
  public setNumber: string = '47';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Drifblim';
  public fullName: string = 'Drifblim STS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Eerie Wave
    // Ref: AGENTS-patterns.md (Confused)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED(store, state, effect);
    }

    // Attack 2: Burst Curse
    // Refs: set-furious-fists/magmar.ts (energy discard), set-fates-collide/wigglytuff.ts (damage counters any way)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 2);
      PUT_X_DAMAGE_COUNTERS_IN_ANY_WAY_YOU_LIKE(8, store, state, effect);
    }

    return state;
  }
}
