// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { CheckRetreatCostEffect } from '../../game/store/effects/check-effects';
import { IS_ABILITY_BLOCKED, NEXT_TURN_ATTACK_BONUS } from '../../game/store/prefabs/prefabs';

export class Klinklang extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Klang';
  public cardType: CardType = M;
  public hp: number = 140;
  public weakness = [{ type: R }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C, C];

  public powers = [{
    name: 'Heavy Bumper',
    powerType: PowerType.ABILITY,
    text: 'Any damage done to this Pok\u00e9mon by an opponent\'s attack is reduced by 10 for each Colorless in your opponent\'s Active Pok\u00e9mon\'s Retreat Cost (after applying Weakness and Resistance).'
  }];

  public attacks = [
    {
      name: 'Gear Spinner',
      cost: [M, M, C],
      damage: 70,
      text: 'During your next turn, this Pok\u00e9mon\'s Gear Spinner attack does 70 more damage (before applying Weakness and Resistance).'
    }
  ];

  public set: string = 'STS';
  public setNumber: string = '73';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Klinklang';
  public fullName: string = 'Klinklang STS';

  public readonly GEAR_SPINNER_MARKER = 'KLINKLANG_STS_GEAR_SPINNER';
  public readonly GEAR_SPINNER_MARKER_2 = 'KLINKLANG_STS_GEAR_SPINNER_2';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Heavy Bumper (passive - reduce damage based on opponent's retreat cost)
    // Ref: set-roaring-skies/altaria-2.ts (Clear Humming - passive stat interception)
    if (effect instanceof DealDamageEffect && effect.target.cards.includes(this)) {
      const targetCard = effect.target.getPokemonCard();
      if (targetCard !== this) {
        return state;
      }

      // Find the owner of this Pokemon
      let owner: any = null;
      state.players.forEach(p => {
        p.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
          if (cardList.getPokemonCard() === this) {
            owner = p;
          }
        });
      });

      if (!owner) {
        return state;
      }

      if (IS_ABILITY_BLOCKED(store, state, owner, this)) {
        return state;
      }

      // Get opponent's active Pokemon retreat cost
      const opponent = StateUtils.getOpponent(state, owner);
      const checkRetreat = new CheckRetreatCostEffect(opponent);
      store.reduceEffect(state, checkRetreat);

      // Count Colorless in retreat cost
      const colorlessCount = checkRetreat.cost.filter(c => c === CardType.COLORLESS).length;
      if (colorlessCount > 0) {
        effect.damage = Math.max(0, effect.damage - (10 * colorlessCount));
      }
    }

    // Attack 1: Gear Spinner
    // Ref: set-breakthrough/swoobat.ts (Wave Amplification - NEXT_TURN_ATTACK_BONUS)
    NEXT_TURN_ATTACK_BONUS(effect, {
      attack: this.attacks[0],
      source: this,
      bonusDamage: 70,
      bonusMarker: this.GEAR_SPINNER_MARKER,
      clearMarker: this.GEAR_SPINNER_MARKER_2
    });

    return state;
  }
}
