// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, SuperType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameMessage, PlayerType, SlotType, DiscardEnergyPrompt } from '../../game';
import { EnergyCard } from '../../game/store/card/energy-card';
import { DiscardCardsEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../game/store/prefabs/costs';

export class BlazikenGx extends PokemonCard {
  public tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Combusken';
  public cardType: CardType = R;
  public hp: number = 240;
  public weakness = [{ type: W }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Slash',
      cost: [C, C],
      damage: 60,
      text: ''
    },
    {
      name: 'Explosive Kick',
      cost: [R, R, C],
      damage: 210,
      text: 'Discard 2 [R] Energy from this Pokémon.'
    },
    {
      name: 'Blaze Out-GX',
      cost: [R],
      damage: 0,
      gxAttack: true,
      text: 'Discard 2 Energy from your opponent\'s Pokémon. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'CES';
  public setNumber: string = '28';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Blaziken-GX';
  public fullName: string = 'Blaziken-GX CES';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Explosive Kick
    // Ref: set-ultra-prism/heatran.ts (Boiling Impact - discard energy cost)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 2, CardType.FIRE);
    }

    // Attack 3: Blaze Out-GX
    // Ref: set-sun-and-moon/umbreon-gx.ts (Dark Call-GX)
    if (WAS_ATTACK_USED(effect, 2, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      // Count total energy on opponent's Pokemon
      let totalEnergy = 0;
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        totalEnergy += cardList.cards.filter(c => c instanceof EnergyCard).length;
      });

      if (totalEnergy === 0) {
        return state;
      }

      const maxDiscard = Math.min(2, totalEnergy);

      return store.prompt(state, new DiscardEnergyPrompt(
        player.id,
        GameMessage.CHOOSE_ENERGIES_TO_DISCARD,
        PlayerType.TOP_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { superType: SuperType.ENERGY },
        { allowCancel: false, min: maxDiscard, max: maxDiscard }
      ), transfers => {
        if (transfers === null || transfers.length === 0) {
          return state;
        }

        for (const transfer of transfers) {
          const target = StateUtils.getTarget(state, opponent, transfer.from);
          const discardEffect = new DiscardCardsEffect(effect, [transfer.card]);
          discardEffect.target = target;
          store.reduceEffect(state, discardEffect);
        }
      });
    }

    return state;
  }
}
