// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { GameMessage, PlayerType, SlotType, StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { PutDamageEffect } from '../../game/store/effects/attack-effects';
import { AfterAttackEffect, EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { ChoosePokemonPrompt } from '../../game/store/prompts/choose-pokemon-prompt';
import { ConfirmPrompt } from '../../game/store/prompts/confirm-prompt';
import { WAS_ATTACK_USED, SWITCH_ACTIVE_WITH_BENCHED } from '../../game/store/prefabs/prefabs';

export class Deoxys3 extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = P;
  public hp: number = 100;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Teleportation Burst',
      cost: [P],
      damage: 20,
      text: 'You may switch this Pokémon with 1 of your Benched Pokémon.'
    },
    {
      name: 'Spear Dive',
      cost: [C, C, C],
      damage: 0,
      text: 'This attack does 50 damage to 1 of your opponent\'s Pokémon. This damage isn\'t affected by Weakness or Resistance.'
    }
  ];

  public set: string = 'CES';
  public setNumber: string = '69';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Deoxys';
  public fullName: string = 'Deoxys CES 69';

  public usedTeleportationBurst: boolean = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Teleportation Burst
    // Ref: AGENTS-patterns.md (post-damage switching with "you may")
    if (WAS_ATTACK_USED(effect, 0, this)) {
      this.usedTeleportationBurst = true;
    }

    if (effect instanceof AfterAttackEffect && this.usedTeleportationBurst) {
      this.usedTeleportationBurst = false;
      const player = effect.player;

      if (player.bench.some(b => b.cards.length > 0)) {
        store.prompt(state, new ConfirmPrompt(
          player.id,
          GameMessage.WANT_TO_SWITCH_POKEMON,
        ), wantToSwitch => {
          if (wantToSwitch) {
            SWITCH_ACTIVE_WITH_BENCHED(store, state, player);
          }
        });
      }
    }

    if (effect instanceof EndTurnEffect) {
      this.usedTeleportationBurst = false;
    }

    // Attack 2: Spear Dive
    // Ref: set-emerging-powers/sigilyph.ts (Telekinesis)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      return store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON_TO_DAMAGE,
        PlayerType.TOP_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { allowCancel: false }
      ), targets => {
        const target = targets[0];
        const putDamage = new PutDamageEffect(effect, 50);
        putDamage.target = target;
        store.reduceEffect(state, putDamage);
      });
    }

    return state;
  }
}
