// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PlayerType, StoreLike, State, StateUtils } from '../../game';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { CheckHpEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, COIN_FLIP_PROMPT } from '../../game/store/prefabs/prefabs';

export class Meditite extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 70;
  public weakness = [{ type: P }];
  public retreat = [C];

  public readonly BIDE_MARKER = 'MEDITITE_CES_BIDE_MARKER';
  public readonly CLEAR_BIDE_MARKER = 'MEDITITE_CES_CLEAR_BIDE_MARKER';

  public attacks = [
    {
      name: 'Bide',
      cost: [F],
      damage: 0,
      text: 'Flip a coin. If heads, if this Pokémon would be Knocked Out by damage from an attack during your opponent\'s next turn, it is not Knocked Out, and its remaining HP becomes 10.'
    },
    {
      name: 'Kick',
      cost: [F, F],
      damage: 30,
      text: ''
    }
  ];

  public set: string = 'CES';
  public setNumber: string = '76';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Meditite';
  public fullName: string = 'Meditite CES';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Bide
    // Ref: set-steam-siege/seedot.ts (Bide)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      COIN_FLIP_PROMPT(store, state, player, result => {
        if (result) {
          player.active.marker.addMarker(this.BIDE_MARKER, this);
          opponent.marker.addMarker(this.CLEAR_BIDE_MARKER, this);
        }
      });
    }

    // Intercept damage that would KO this Pokemon
    if (effect instanceof DealDamageEffect && effect.target.cards.includes(this)
      && effect.target.getPokemonCard() === this) {
      if (effect.target.marker.hasMarker(this.BIDE_MARKER, this)) {
        const pokemon = effect.target;
        const checkHp = new CheckHpEffect(effect.player, pokemon);
        store.reduceEffect(state, checkHp);
        const totalDamage = pokemon.damage + effect.damage;
        if (totalDamage >= checkHp.hp) {
          effect.damage = checkHp.hp - 10 - pokemon.damage;
          if (effect.damage < 0) {
            effect.damage = 0;
          }
        }
      }
    }

    // Cleanup markers at end of opponent's turn
    if (effect instanceof EndTurnEffect
      && effect.player.marker.hasMarker(this.CLEAR_BIDE_MARKER, this)) {
      effect.player.marker.removeMarker(this.CLEAR_BIDE_MARKER, this);
      const opponent = StateUtils.getOpponent(state, effect.player);
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        cardList.marker.removeMarker(this.BIDE_MARKER, this);
      });
    }

    return state;
  }
}
