// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GameError, GameMessage } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_POWER_USED, IS_ABILITY_BLOCKED, USE_ABILITY_ONCE_PER_TURN, ABILITY_USED, REMOVE_MARKER_AT_END_OF_TURN, GUST_OPPONENT_BENCHED_POKEMON } from '../../game/store/prefabs/prefabs';

export class Salamence extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Shelgon';
  public cardType: CardType = N;
  public hp: number = 150;
  public weakness = [{ type: Y }];
  public retreat = [C, C, C];

  public powers = [{
    name: 'Dragon Wind',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'If this Pokémon is your Active Pokémon, once during your turn (before your attack), you may switch 1 of your opponent\'s Benched Pokémon with their Active Pokémon.'
  }];

  public attacks = [
    {
      name: 'Dragon Claw',
      cost: [R, W, C, C],
      damage: 100,
      text: ''
    }
  ];

  public set: string = 'CES';
  public setNumber: string = '106';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Salamence';
  public fullName: string = 'Salamence CES';

  public readonly DRAGON_WIND_MARKER = 'SALAMENCE_CES_DRAGON_WIND_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Dragon Wind
    // Refs: set-breakpoint/slowking.ts (once per turn ability), AGENTS-patterns.md (gust)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Must be active
      if (player.active.getPokemonCard() !== this) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      // Opponent must have benched Pokemon
      if (!opponent.bench.some(b => b.cards.length > 0)) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.DRAGON_WIND_MARKER, this);
      ABILITY_USED(player, this);

      GUST_OPPONENT_BENCHED_POKEMON(store, state, player);
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.DRAGON_WIND_MARKER, this);

    return state;
  }
}
