// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../game';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { CheckHpEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class ScizorGx extends PokemonCard {
  public tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Scyther';
  public cardType: CardType = M;
  public hp: number = 210;
  public weakness = [{ type: R }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C];

  public powers = [  {
    name: 'Danger Perception',
    powerType: PowerType.ABILITY,
    text: 'If this Pokémon\'s remaining HP is 100 or less, its attacks do 80 more damage to your opponent\'s Active Pokémon (before applying Weakness and Resistance).'
  }];

  public attacks = [
    {
      name: 'Steel Wing',
      cost: [M, C],
      damage: 80,
      text: 'During your opponent\'s next turn, this Pokémon takes 30 less damage from attacks (after applying Weakness and Resistance).'
    },
    {
      name: 'Cross-Cut-GX',
      cost: [C, C, C],
      damage: 100,
      damageCalculation: '+',
      text: 'If your opponent\'s Active Pokémon is an Evolution Pokémon, this attack does 100 more damage. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'CES';
  public setNumber: string = '90';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Scizor-GX';
  public fullName: string = 'Scizor-GX CES';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Danger Perception (passive - boost damage when HP is low)
    // Ref: set-forbidden-light/diancie.ts (Princess's Cheers - passive DealDamageEffect damage boost)
    if (effect instanceof DealDamageEffect && effect.source.cards.includes(this)) {
      const pokemonCard = effect.source.getPokemonCard();
      if (pokemonCard !== this) {
        return state;
      }

      const player = StateUtils.findOwner(state, effect.source);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Check remaining HP
      const checkHp = new CheckHpEffect(player, effect.source);
      store.reduceEffect(state, checkHp);
      const remainingHp = checkHp.hp - effect.source.damage;

      if (remainingHp <= 100) {
        effect.damage += 80;
      }
    }

    // Attack 1: Steel Wing
    // Ref: set-crimson-invasion/type-null.ts (Armor Press - take 30 less damage next turn)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      effect.player.active.damageReductionNextTurn = 30;
    }

    // Attack 2: Cross-Cut-GX
    // Ref: set-burning-shadows/machamp-gx.ts (Cross-Cut - evolution check for bonus damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      const opponent = StateUtils.getOpponent(state, player);
      const opponentActive = opponent.active.getPokemonCard();

      if (opponentActive && opponentActive.stage !== Stage.BASIC) {
        effect.damage += 100;
      }
    }

    return state;
  }
}
