// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Volbeat extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 70;
  public weakness = [{ type: R }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Pheromone Catch',
      cost: [G],
      damage: 20,
      damageCalculation: '+' as '+',
      text: 'If your Illumise used Pheromone Signals during your last turn, this attack does 100 more damage.'
    }
  ];

  public set: string = 'CES';
  public setNumber: string = '17';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Volbeat';
  public fullName: string = 'Volbeat CES';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Pheromone Catch
    // Ref: set-surging-sparks/koraidon.ts (playerLastAttack check)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const playerLastAttackInfo = state.playerLastAttack?.[player.id];

      if (playerLastAttackInfo
        && playerLastAttackInfo.sourceCard.name === 'Illumise'
        && playerLastAttackInfo.attack.name === 'Pheromone Signals') {
        effect.damage += 100;
      }
    }

    return state;
  }
}
