// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Wailord extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Wailmer';
  public cardType: CardType = W;
  public hp: number = 220;
  public weakness = [{ type: G }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Dwindling Wave',
      cost: [W, W, W, W],
      damage: 200,
      damageCalculation: '-' as '-',
      text: 'This attack does 40 less damage for each damage counter on this Pokémon.'
    }
  ];

  public set: string = 'CES';
  public setNumber: string = '40';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Wailord';
  public fullName: string = 'Wailord CES';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Dwindling Wave
    // Ref: AGENTS-patterns.md (damage counter conditional damage reduction)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const damageCounters = effect.player.active.damage / 10;
      effect.damage = Math.max(0, effect.damage - 40 * damageCounters);
    }

    return state;
  }
}
