// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PokemonCardList, PowerType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { PlayPokemonEffect } from '../../game/store/effects/play-card-effects';
import { IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class Caterpie extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 40;
  public weakness = [{ type: R }];
  public retreat = [C];

  public powers = [{
    name: 'Adaptive Evolution',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'This Pokémon can evolve during your first turn or the turn you play it.'
  }];

  public attacks = [
    {
      name: 'Bug Bite',
      cost: [G],
      damage: 10,
      text: ''
    }
  ];

  public set: string = 'FLF';
  public setNumber: string = '1';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Caterpie';
  public fullName: string = 'Caterpie FLF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-cosmic-eclipse/clamperl.ts (Evolutionary Advantage)
    // Adaptive Evolution allows evolution during first turn or turn played
    if (effect instanceof PlayPokemonEffect && effect.pokemonCard === this) {
      const player = effect.player;
      const cardList = StateUtils.findCardList(state, this) as PokemonCardList;
      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }
      // Allow evolution on the turn this Pokemon is played and on the first turn
      player.canEvolve = true;
      cardList.pokemonPlayedTurn = state.turn - 1;
    }

    return state;
  }
}
