// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { SlotType } from '../../game/store/actions/play-card-action';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, THIS_ATTACK_DOES_X_DAMAGE_TO_X_OF_YOUR_OPPONENTS_POKEMON } from '../../game/store/prefabs/prefabs';

export class MagnezoneEx extends PokemonCard {
  public tags = [CardTag.POKEMON_EX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = L;
  public hp: number = 180;
  public weakness = [{ type: F }];
  public resistance = [{ type: M, value: -20 }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Electro Ball',
      cost: [C, C],
      damage: 40,
      text: ''
    },
    {
      name: 'Dual Bullet',
      cost: [L, L, L],
      damage: 0,
      text: 'This attack does 50 damage to 2 of your opponent\'s Pok\u00e9mon. (Don\'t apply Weakness or Resistance for Benched Pok\u00e9mon.)'
    }
  ];

  public set: string = 'FLF';
  public setNumber: string = '35';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Magnezone-EX';
  public fullName: string = 'Magnezone-EX FLF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-x-and-y/m-blastoise-ex.ts (Hydro Bombard)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      THIS_ATTACK_DOES_X_DAMAGE_TO_X_OF_YOUR_OPPONENTS_POKEMON(50, effect, store, state, 2, 2, false, [SlotType.ACTIVE, SlotType.BENCH]);
    }

    return state;
  }
}
