import { Card } from '../../game/store/card/card';
import { AlakazamArt, BeedrillArt, BillArt, BlastoiseArt, ChanseyArt, CharizardArt, CharmanderArt, CharmeleonArt, ClefairyArt, ComputerSearchArt, DoduoArt, DoubleColorlessEnergyArt, DragonairArt, DugtrioArt, ElectabuzzArt, EnergyRemovalArt, EnergyRetrievalArt, GustOfWindArt, GyaradosArt, HitmonchanArt, ItemFinderArt, LassArt, MachampArt, MagnetonArt, MaintenanceArt, MewtwoArt, NidokingArt, NinetalesArt, PlusPowerArt, PokemonBreederArt, PokemonCenterArt, PokemonTraderArt, PoliwrathArt, ProfessorOakArt, RaichuArt, RattataArt, ScoopUpArt, SquirtleArt, SuperEnergyRemovalArt, SuperPotionArt, SwitchArt, VenusaurArt, WartortleArt, ZapdosArt } from './card-images';

export const setBaseSet: Card[] = [
  new AlakazamArt(),
  new BeedrillArt(),
  new BillArt(),
  new BlastoiseArt(),
  new ChanseyArt(),
  new CharizardArt(),
  new CharmanderArt(),
  new CharmeleonArt(),
  new ClefairyArt(),
  new ComputerSearchArt(),
  new DoduoArt(),
  new DoubleColorlessEnergyArt(),
  new DragonairArt(),
  new DugtrioArt(),
  new ElectabuzzArt(),
  new EnergyRemovalArt(),
  new EnergyRetrievalArt(),
  new GyaradosArt(),
  new GustOfWindArt(),
  new HitmonchanArt(),
  new ItemFinderArt(),
  new LassArt(),
  new MachampArt(),
  new MagnetonArt(),
  new MaintenanceArt(),
  new MewtwoArt(),
  new NidokingArt(),
  new NinetalesArt(),
  new PoliwrathArt(),
  new PlusPowerArt(),
  new PokemonBreederArt(),
  new PokemonCenterArt(),
  new PokemonTraderArt(),
  new ProfessorOakArt(),
  new RaichuArt(),
  new RattataArt(),
  new ScoopUpArt(),
  new SquirtleArt(),
  new SuperEnergyRemovalArt(),
  new SuperPotionArt(),
  new SwitchArt(),
  new VenusaurArt(),
  new WartortleArt(),
  new ZapdosArt()
];