import { Card } from '../../game/store/card/card';
import { MagmarArt } from '../set-pokemon-151/card-images';
import { AlakazamArt, ArcanineArt, BeedrillArt, BillArt, BlastoiseArt, ChanseyArt, CharizardArt, CharmanderArt, CharmeleonArt, ClefairyArt, ComputerSearchArt, DewgongArt, DoduoArt, DoubleColorlessEnergyArt, DragonairArt, DratiniArt, DugtrioArt, ElectabuzzArt, ElectrodeArt, EnergyRemovalArt, EnergyRetrievalArt, FarfetchdArt, GrowlitheArt, GustOfWindArt, GyaradosArt, HaunterArt, HitmonchanArt, ItemFinderArt, IvysaurArt, JynxArt, KadabraArt, KakunaArt, LassArt, MachampArt, MachokeArt, MagikarpArt, MagnetonArt, MaintenanceArt, MewtwoArt, NidokingArt, NidorinoArt, NinetalesArt, PidgeottoArt, PlusPowerArt, PokemonBreederArt, PokemonCenterArt, PokemonTraderArt, PoliwagArt, PoliwhirlArt, PoliwrathArt, ProfessorOakArt, RaichuArt, RattataArt, ScoopUpArt, SquirtleArt, SuperEnergyRemovalArt, SuperPotionArt, SwitchArt, VenusaurArt, WartortleArt, ZapdosArt } from './card-images';

export const setBaseSet: Card[] = [
  new AlakazamArt(),
  new ArcanineArt(),
  new BeedrillArt(),
  new BillArt(),
  new BlastoiseArt(),
  new ChanseyArt(),
  new CharizardArt(),
  new CharmanderArt(),
  new CharmeleonArt(),
  new ClefairyArt(),
  new ComputerSearchArt(),
  new DewgongArt(),
  new DoduoArt(),
  new DoubleColorlessEnergyArt(),
  new DragonairArt(),
  new DratiniArt(),
  new DugtrioArt(),
  new ElectabuzzArt(),
  new ElectrodeArt(),
  new EnergyRemovalArt(),
  new EnergyRetrievalArt(),
  new FarfetchdArt(),
  new GrowlitheArt(),
  new GyaradosArt(),
  new GustOfWindArt(),
  new HaunterArt(),
  new HitmonchanArt(),
  new ItemFinderArt(),
  new IvysaurArt(),
  new JynxArt(),
  new KadabraArt(),
  new KakunaArt(),
  new LassArt(),
  new MachampArt(),
  new MachokeArt(),
  new MagikarpArt(),
  new MagmarArt(),
  new MagnetonArt(),
  new MaintenanceArt(),
  new MewtwoArt(),
  new NidokingArt(),
  new NidorinoArt(),
  new NinetalesArt(),
  new PidgeottoArt(),
  new PlusPowerArt(),
  new PokemonBreederArt(),
  new PokemonCenterArt(),
  new PokemonTraderArt(),
  new PoliwagArt(),
  new PoliwhirlArt(),
  new PoliwrathArt(),
  new ProfessorOakArt(),
  new RaichuArt(),
  new RattataArt(),
  new ScoopUpArt(),
  new SquirtleArt(),
  new SuperEnergyRemovalArt(),
  new SuperPotionArt(),
  new SwitchArt(),
  new VenusaurArt(),
  new WartortleArt(),
  new ZapdosArt()
];