// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { ConfirmPrompt, GameMessage, StoreLike, State, StateUtils, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Bouffalant extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = C;
  public hp: number = 120;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public readonly BOUFFANT_HEAD_MARKER = 'BOUFFALANT_BOUFFANT_HEAD_MARKER';
  public readonly CLEAR_BOUFFANT_HEAD_MARKER = 'BOUFFALANT_CLEAR_BOUFFANT_HEAD_MARKER';

  public attacks = [
    {
      name: 'Bouffant Head',
      cost: [C, C],
      damage: 30,
      text: 'During your opponent\'s next turn, this Pokémon takes 30 less damage from attacks (after applying Weakness and Resistance).'
    },
    {
      name: 'Knock Over',
      cost: [C, C, C],
      damage: 80,
      text: 'You may discard any Stadium card in play.'
    }
  ];

  public set: string = 'BUS';
  public setNumber: string = '108';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Bouffalant';
  public fullName: string = 'Bouffalant BUS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Bouffant Head
    // Ref: set-guardians-rising/kommo-o-gx.ts (Adamantine Press)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      player.active.marker.addMarker(this.BOUFFANT_HEAD_MARKER, this);
      opponent.marker.addMarker(this.CLEAR_BOUFFANT_HEAD_MARKER, this);
    }

    // Reduce damage by 30
    if (effect instanceof DealDamageEffect && effect.target.cards.includes(this)) {
      const pokemonCard = effect.target.getPokemonCard();
      if (pokemonCard !== this) {
        return state;
      }

      if (effect.target.marker.hasMarker(this.BOUFFANT_HEAD_MARKER, this)) {
        effect.damage = Math.max(0, effect.damage - 30);
      }
    }

    // Cleanup at end of opponent's turn
    if (effect instanceof EndTurnEffect
      && effect.player.marker.hasMarker(this.CLEAR_BOUFFANT_HEAD_MARKER, this)) {
      effect.player.marker.removeMarker(this.CLEAR_BOUFFANT_HEAD_MARKER, this);
      const opponent = StateUtils.getOpponent(state, effect.player);
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        cardList.marker.removeMarker(this.BOUFFANT_HEAD_MARKER, this);
      });
    }

    // Attack 2: Knock Over
    // Ref: set-surging-sparks/chien-pao.ts (Snow Sink - discard stadium)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const stadiumCard = StateUtils.getStadiumCard(state);

      if (stadiumCard !== undefined) {
        store.prompt(state, new ConfirmPrompt(
          effect.player.id,
          GameMessage.WANT_TO_USE_ABILITY,
        ), wantToDiscard => {
          if (wantToDiscard) {
            const cardList = StateUtils.findCardList(state, stadiumCard);
            const owner = StateUtils.findOwner(state, cardList);
            cardList.moveTo(owner.discard);
          }
        });
      }
    }

    return state;
  }
}
