// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP } from '../../game/store/prefabs/attack-effects';

export class Darkrai extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = D;
  public hp: number = 120;
  public weakness = [{ type: F }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Hypnoblast',
      cost: [D, C],
      damage: 30,
      text: 'Your opponent\'s Active Pokémon is now Asleep.'
    },
    {
      name: 'Dark Raid',
      cost: [D, C, C],
      damage: 80,
      damageCalculation: '+' as '+',
      text: 'If your opponent has already used their GX attack, this attack does 80 more damage.'
    }
  ];

  public set: string = 'BUS';
  public setNumber: string = '87';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Darkrai';
  public fullName: string = 'Darkrai BUS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Hypnoblast
    // Ref: set-guardians-rising/victreebel.ts (Pollen Hazard)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP(store, state, effect);
    }

    // Attack 2: Dark Raid
    // Ref: AGENTS-patterns.md (conditional damage bonus)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const opponent = StateUtils.getOpponent(state, effect.player);
      if (opponent.usedGX) {
        effect.damage += 80;
      }
    }

    return state;
  }
}
