// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PlayerType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { PutDamageEffect } from '../../game/store/effects/attack-effects';
import { AfterAttackEffect, EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { MOVED_TO_ACTIVE_THIS_TURN, WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED, SWITCH_ACTIVE_WITH_BENCHED } from '../../game/store/prefabs/prefabs';

export class GolisopodGx extends PokemonCard {
  public tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Wimpod';
  public cardType: CardType = G;
  public hp: number = 210;
  public weakness = [{ type: R }];
  public retreat = [C, C, C];

  public readonly ARMOR_PRESS_MARKER = 'GOLISOPOD_GX_BUS_ARMOR_PRESS_MARKER';
  public readonly CLEAR_ARMOR_PRESS_MARKER = 'GOLISOPOD_GX_BUS_CLEAR_ARMOR_PRESS_MARKER';

  public usedCrossingCutGx = false;

  public attacks = [
    {
      name: 'First Impression',
      cost: [G],
      damage: 30,
      damageCalculation: '+' as '+',
      text: 'If this Pokémon was on the Bench and became your Active Pokémon this turn, this attack does 90 more damage.'
    },
    {
      name: 'Armor Press',
      cost: [G, C, C],
      damage: 100,
      text: 'During your opponent\'s next turn, this Pokémon takes 20 less damage from attacks (after applying Weakness and Resistance).'
    },
    {
      name: 'Crossing Cut-GX',
      cost: [G, C, C],
      damage: 150,
      text: 'Switch this Pokémon with 1 of your Benched Pokémon. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'BUS';
  public setNumber: string = '17';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Golisopod-GX';
  public fullName: string = 'Golisopod-GX BUS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: First Impression
    if (WAS_ATTACK_USED(effect, 0, this)) {
      if (MOVED_TO_ACTIVE_THIS_TURN(effect.player, this)) {
        effect.damage += 90;
      }
    }

    // Attack 2: Armor Press
    // Ref: set-guardians-rising/kommo-o-gx.ts (Adamantine Press)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      player.active.marker.addMarker(this.ARMOR_PRESS_MARKER, this);
      opponent.marker.addMarker(this.CLEAR_ARMOR_PRESS_MARKER, this);
    }

    if (effect instanceof PutDamageEffect && effect.target.cards.includes(this)) {
      const pokemonCard = effect.target.getPokemonCard();
      if (pokemonCard !== this) {
        return state;
      }

      if (effect.target.marker.hasMarker(this.ARMOR_PRESS_MARKER, this)) {
        effect.damage = Math.max(0, effect.damage - 20);
        return state;
      }
    }

    if (effect instanceof EndTurnEffect
      && effect.player.marker.hasMarker(this.CLEAR_ARMOR_PRESS_MARKER, this)) {
      effect.player.marker.removeMarker(this.CLEAR_ARMOR_PRESS_MARKER, this);
      const opponent = StateUtils.getOpponent(state, effect.player);
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        cardList.marker.removeMarker(this.ARMOR_PRESS_MARKER, this);
      });
    }

    // Attack 3: Crossing Cut-GX
    // Refs: set-guardians-rising/kommo-o-gx.ts (Ultra Uppercut-GX), set-guardians-rising/goodra.ts (Beat Slider - AfterAttackEffect switch)
    if (WAS_ATTACK_USED(effect, 2, this)) {
      BLOCK_IF_GX_ATTACK_USED(effect.player);
      effect.player.usedGX = true;
      this.usedCrossingCutGx = true;
    }

    if (effect instanceof AfterAttackEffect && this.usedCrossingCutGx) {
      this.usedCrossingCutGx = false;
      const player = effect.player;

      if (player.bench.some(b => b.cards.length > 0)) {
        SWITCH_ACTIVE_WITH_BENCHED(store, state, player);
      }
    }

    if (effect instanceof EndTurnEffect) {
      this.usedCrossingCutGx = false;
    }

    return state;
  }
}
