// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED, DISCARD_A_STADIUM_CARD_IN_PLAY } from '../../game/store/prefabs/prefabs';

export class MachampGx extends PokemonCard {
  public tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Machoke';
  public cardType: CardType = F;
  public hp: number = 250;
  public weakness = [{ type: P }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Cross-Cut',
      cost: [F, F],
      damage: 60,
      damageCalculation: '+' as '+',
      text: 'If your opponent\'s Active Pokémon is an Evolution Pokémon, this attack does 60 more damage.'
    },
    {
      name: 'Bedrock Breaker',
      cost: [F, F, F],
      damage: 130,
      text: 'Discard any Stadium card in play.'
    },
    {
      name: 'Muscle Punch-GX',
      cost: [F, F, F],
      damage: 180,
      gxAttack: true,
      text: 'This attack\'s damage isn\'t affected by Resistance. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'BUS';
  public setNumber: string = '64';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Machamp-GX';
  public fullName: string = 'Machamp-GX BUS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Cross-Cut
    // Ref: set-burning-shadows/lycanroc.ts (Dangerous Claws - stage check)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      const opponentActive = opponent.active.getPokemonCard();

      if (opponentActive && opponentActive.stage !== Stage.BASIC) {
        effect.damage += 60;
      }
    }

    // Attack 2: Bedrock Breaker
    // Ref: set-guardians-rising/vikavolt-gx.ts (discard stadium)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_A_STADIUM_CARD_IN_PLAY(state);
    }

    // Attack 3: Muscle Punch-GX
    // Ref: set-guardians-rising/vikavolt-gx.ts (GX attack pattern)
    if (WAS_ATTACK_USED(effect, 2, this)) {
      const player = effect.player;
      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      effect.ignoreResistance = true;
    }

    return state;
  }
}
