// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../game/store/card/trainer-card';
import { CardType, Stage, TrainerType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameError, GameMessage } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { UseStadiumEffect } from '../../game/store/effects/game-effects';
import { CheckRetreatCostEffect } from '../../game/store/effects/check-effects';

export class MountLanakila extends TrainerCard {
  public trainerType: TrainerType = TrainerType.STADIUM;
  public set: string = 'BUS';
  public setNumber: string = '118';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mount Lanakila';
  public fullName: string = 'Mount Lanakila BUS';
  public text: string = 'The Retreat Cost of each Basic Pokémon in play (both yours and your opponent\'s) is Colorless more.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-guardians-rising/altar-of-the-moone.ts (retreat cost modification stadium)
    if (effect instanceof CheckRetreatCostEffect && StateUtils.getStadiumCard(state) === this) {
      const pokemonCard = effect.player.active.getPokemonCard();

      if (pokemonCard && pokemonCard.stage === Stage.BASIC) {
        effect.cost.push(CardType.COLORLESS);
      }

      return state;
    }

    // Ref: set-guardians-rising/altar-of-the-moone.ts (prevent using stadium with no active effect)
    if (effect instanceof UseStadiumEffect && StateUtils.getStadiumCard(state) === this) {
      throw new GameError(GameMessage.CANNOT_USE_STADIUM);
    }

    return state;
  }
}
