import { Card } from '../../game/store/card/card';
import { AncientBoosterEnergyCapsuleArt, BounsweetArt, BruteBonnetArt, CounterCatcherArt, DefianceVestArt, DeoxysArt, EarthenVesselArt, ElekidArt, FroslassexArt, FutureBoosterEnergyCapsuleArt, GabiteArt, GarchompexArt, GholdengoexArt, GibleArt, GimmighoulArt, GroudonArt, IronBundleArt, IronHandsexArt, IronJugulisArt, IronValiantexArt, JirachiArt, KlawfArt, LatiosArt, LuxuriousCapeArt, MewtwoexArt, MiniorArt, MorpekoArt, NatuArt, ProfessorSadasVitalityArt, ProfessorTurosScenarioArt, RoaringMoonexArt, SandyShocksexArt, ScreamTailArt, SlitherWingArt, SnoruntArt, SteeneeArt, TapuKokoexArt, TechnicalMachineBlindsideArt, TechnicalMachineDevolutionArt, TechnicalMachineEvolutionArt, TechnicalMachineTurboEnergizeArt, TechnoRadarArt, TsareenaexArt, TulipArt, XatuArt } from './card-images';

export const setParadoxRift: Card[] = [
  
  new AncientBoosterEnergyCapsuleArt(),
  new BruteBonnetArt(),
  new BounsweetArt(),
  new CounterCatcherArt(),
  new DefianceVestArt(),
  new DeoxysArt(),
  new EarthenVesselArt(),
  new ElekidArt(),
  new FroslassexArt(),
  new FutureBoosterEnergyCapsuleArt(),
  new GabiteArt(),
  new GarchompexArt(),
  new GholdengoexArt(),
  new GibleArt(),
  new GimmighoulArt(),
  new IronBundleArt(),
  new IronHandsexArt(),
  new IronValiantexArt(),
  new JirachiArt(),
  new KlawfArt(),
  new LatiosArt(),
  new LuxuriousCapeArt(),
  new MewtwoexArt(),
  new MiniorArt(),
  new MorpekoArt(),
  new NatuArt(),
  new ProfessorSadasVitalityArt(),
  new ProfessorTurosScenarioArt(),
  new RoaringMoonexArt(),
  new SandyShocksexArt(),
  new ScreamTailArt(),
  new SlitherWingArt(),
  new SnoruntArt(),
  new SteeneeArt(),
  new TechnicalMachineBlindsideArt(),
  new TechnicalMachineDevolutionArt(),
  new TechnicalMachineEvolutionArt(),
  new TechnicalMachineTurboEnergizeArt(),
  new TechnoRadarArt(),
  new TsareenaexArt(),
  new TulipArt(),
  new XatuArt(),
  new GroudonArt(),
  new IronJugulisArt(),
  new TapuKokoexArt(),
];
