// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { AbstractAttackEffect, ApplyWeaknessEffect } from '../../game/store/effects/attack-effects';
import { WAS_ATTACK_USED, COIN_FLIP_PROMPT, IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED } from '../../game/store/prefabs/attack-effects';

export class Mew extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = P;
  public hp: number = 40;
  public weakness = [{ type: P }];
  public retreat = [C];

  public powers = [{
    name: 'Neutral Shield',
    powerType: PowerType.ABILITY,
    text: 'Prevent all effects of attacks, including damage, done to this Pokémon by your opponent\'s Evolution Pokémon.'
  }];

  public attacks = [
    {
      name: 'Psy Bolt',
      cost: [P, C],
      damage: 30,
      text: 'Flip a coin. If heads, your opponent\'s Active Pokémon is now Paralyzed.'
    }
  ];

  public set: string = 'EVO';
  public setNumber: string = '53';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mew';
  public fullName: string = 'Mew EVO';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Neutral Shield (passive - prevent all effects from Evolution Pokemon)
    // Ref: set-ancient-origins/giratina-ex.ts (Renegade Pulse - prevent effects from Mega Evolution)
    if (effect instanceof AbstractAttackEffect && effect.target.cards.includes(this)) {
      const sourceCard = effect.source.getPokemonCard();

      // Check if the attacking Pokemon is an Evolution Pokemon (not Basic)
      if (sourceCard && sourceCard.stage !== Stage.BASIC) {
        // Find the owner of Mew
        const targetPlayer = StateUtils.findOwner(state, effect.target);

        // Check if ability is blocked
        if (IS_ABILITY_BLOCKED(store, state, targetPlayer, this)) {
          return state;
        }

        // Allow Weakness & Resistance calculations through
        if (effect instanceof ApplyWeaknessEffect) {
          return state;
        }

        effect.preventDefault = true;
      }
    }

    // Attack 1: Psy Bolt
    // Ref: set-steam-siege/volcarona.ts (Shimmering Scales - coin flip + condition)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      COIN_FLIP_PROMPT(store, state, effect.player, result => {
        if (result) {
          YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED(store, state, effect);
        }
      });
    }

    return state;
  }
}
