// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, THIS_POKEMON_DOES_DAMAGE_TO_ITSELF, DISCARD_ALL_ENERGY_FROM_POKEMON } from '../../game/store/prefabs/prefabs';

export class Zapdos extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = L;
  public hp: number = 110;
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Thunder',
      cost: [L, L, C, C],
      damage: 90,
      text: 'This Pokémon does 30 damage to itself.'
    },
    {
      name: 'Thunderbolt',
      cost: [L, L, L, L],
      damage: 170,
      text: 'Discard all Energy attached to this Pokémon.'
    }
  ];

  public set: string = 'EVO';
  public setNumber: string = '42';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Zapdos';
  public fullName: string = 'Zapdos EVO';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Thunder
    // Ref: AGENTS-patterns.md (self-damage)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      THIS_POKEMON_DOES_DAMAGE_TO_ITSELF(store, state, effect, 30);
    }

    // Attack 2: Thunderbolt
    // Ref: set-steam-siege/volcarona.ts (Power Hurricane)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_ALL_ENERGY_FROM_POKEMON(store, state, effect, effect.player.active.getPokemonCard()!);
    }

    return state;
  }
}
