// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { PutCountersEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, ADD_MARKER, ON_DAMAGED_BY_OPPONENT_ATTACK_EVEN_IF_KNOCKED_OUT, CLEAR_MARKER_AND_OPPONENTS_POKEMON_MARKER_AT_END_OF_TURN } from '../../game/store/prefabs/prefabs';

export class Aggron extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Lairon';
  public cardType: CardType = M;
  public hp: number = 170;
  public weakness = [{ type: R }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C, C, C];

  public readonly EXTRA_TIGHT_PRESS_MARKER = 'AGGRON_UNB_EXTRA_TIGHT_PRESS_MARKER';
  public readonly CLEAR_EXTRA_TIGHT_PRESS_MARKER = 'AGGRON_UNB_CLEAR_EXTRA_TIGHT_PRESS_MARKER';

  public attacks = [
    {
      name: 'Extra-Tight Press',
      cost: [M, C, C],
      damage: 80,
      text: 'During your opponent\'s next turn, if this Pokémon is damaged by an attack (even if this Pokémon is Knocked Out), put 8 damage counters on the Attacking Pokémon.'
    },
    {
      name: 'Giga Impact',
      cost: [M, C, C, C],
      damage: 160,
      text: 'This Pokémon can\'t attack during your next turn.'
    }
  ];

  public set: string = 'UNB';
  public setNumber: string = '125';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Aggron';
  public fullName: string = 'Aggron UNB';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Extra-Tight Press
    // Ref: set-dragons-majesty/druddigon.ts (Rough Skin - damaged retaliation)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      ADD_MARKER(this.EXTRA_TIGHT_PRESS_MARKER, player.active, this);
      ADD_MARKER(this.CLEAR_EXTRA_TIGHT_PRESS_MARKER, opponent, this);
    }

    // Retaliate when damaged
    if (ON_DAMAGED_BY_OPPONENT_ATTACK_EVEN_IF_KNOCKED_OUT(state, effect, { source: this })) {
      if (effect.target.marker.hasMarker(this.EXTRA_TIGHT_PRESS_MARKER, this)) {
        const damageEffect = new PutCountersEffect(effect, 80);
        damageEffect.target = effect.source;
        store.reduceEffect(state, damageEffect);
      }
    }

    CLEAR_MARKER_AND_OPPONENTS_POKEMON_MARKER_AT_END_OF_TURN(state, effect, this.CLEAR_EXTRA_TIGHT_PRESS_MARKER, this.EXTRA_TIGHT_PRESS_MARKER, this);

    // Attack 2: Giga Impact
    // Ref: AGENTS.md (can't attack next turn)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      effect.player.active.cannotAttackNextTurnPending = true;
    }

    return state;
  }
}
