// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, COIN_FLIP_PROMPT, ADD_MARKER, PREVENT_DAMAGE_IF_TARGET_HAS_MARKER, CLEAR_MARKER_AND_OPPONENTS_POKEMON_MARKER_AT_END_OF_TURN } from '../../game/store/prefabs/prefabs';

export class Geodude extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 70;
  public weakness = [{ type: G }];
  public retreat = [C, C];

  public readonly DEFENSE_CURL_MARKER = 'GEODUDE_UNB_DEFENSE_CURL_MARKER';
  public readonly CLEAR_DEFENSE_CURL_MARKER = 'GEODUDE_UNB_CLEAR_DEFENSE_CURL_MARKER';

  public attacks = [
    {
      name: 'Defense Curl',
      cost: [F],
      damage: 0,
      text: 'Flip a coin. If heads, prevent all damage done to this Pokémon by attacks during your opponent\'s next turn.'
    },
    {
      name: 'Rock Throw',
      cost: [C, C, C],
      damage: 40,
      text: ''
    }
  ];

  public set: string = 'UNB';
  public setNumber: string = '87';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Geodude';
  public fullName: string = 'Geodude UNB';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Defense Curl
    // Ref: set-guardians-rising/alolan-sandshrew.ts (Defense Curl)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      return COIN_FLIP_PROMPT(store, state, player, result => {
        if (!result) {
          return;
        }
        ADD_MARKER(this.DEFENSE_CURL_MARKER, player.active, this);
        ADD_MARKER(this.CLEAR_DEFENSE_CURL_MARKER, opponent, this);
      });
    }

    PREVENT_DAMAGE_IF_TARGET_HAS_MARKER(effect, this.DEFENSE_CURL_MARKER, this);
    CLEAR_MARKER_AND_OPPONENTS_POKEMON_MARKER_AT_END_OF_TURN(state, effect, this.CLEAR_DEFENSE_CURL_MARKER, this.DEFENSE_CURL_MARKER, this);

    return state;
  }
}
