// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { ChoosePokemonPrompt, GameMessage, PlayerType, SlotType, StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { DAMAGE_OPPONENT_POKEMON, WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../game/store/prefabs/costs';

export class Charizard extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Charmeleon';
  public cardType: CardType = R;
  public hp: number = 160;
  public weakness = [{ type: W }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Split Bomb',
      cost: [R, C, C],
      damage: 0,
      text: 'This attack does 40 damage to 2 of your opponent\'s Pokémon. (Don\'t apply Weakness and Resistance for Benched Pokémon.)'
    },
    {
      name: 'Scorching Fire',
      cost: [R, C, C, C, C],
      damage: 150,
      text: 'Discard a [R] Energy attached to this Pokémon.'
    }
  ];

  public set: string = 'BCR';
  public setNumber: string = '20';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Charizard';
  public fullName: string = 'Charizard BCR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Split Bomb
    // Ref: set-temporal-forces/pikachu.ts (Random Spark target selection + damage helper)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const targetCount = Math.min(2, effect.opponent.getPokemonInPlay().length);
      if (targetCount === 0) {
        return state;
      }

      return store.prompt(state, new ChoosePokemonPrompt(
        effect.player.id,
        GameMessage.CHOOSE_POKEMON_TO_DAMAGE,
        PlayerType.TOP_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { min: targetCount, max: targetCount, allowCancel: false }
      ), selected => {
        const targets = selected || [];
        DAMAGE_OPPONENT_POKEMON(store, state, effect, 40, targets);
      });
    }

    // Attack 2: Scorching Fire
    // Ref: set-emerging-powers/simisear.ts (Flamethrower)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 1, CardType.FIRE);
    }

    return state;
  }
}
