// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { ADD_CONFUSION_TO_PLAYER_ACTIVE, AFTER_ATTACK, WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { CardType, Stage } from '../../game/store/card/card-types';
import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Effect } from '../../game/store/effects/effect';
import { State, StoreLike } from '../../game';
export class Grumpig extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Spoink';
  public cardType: CardType = P;
  public hp: number = 110;
  public weakness = [{ type: P }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Psybeam',
      cost: [P, C],
      damage: 30,
      text: 'The Defending Pokémon is now Confused.'
    },
    {
      name: 'Extrasensory',
      cost: [P, C, C],
      damage: 60,
      damageCalculation: '+' as const,
      text: 'If you have the same number of cards in your hand as your opponent, this attack does 60 more damage.'
    }
  ];

  public set: string = 'BCR';
  public setNumber: string = '60';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Grumpig';
  public fullName: string = 'Grumpig BCR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Psybeam
    // Ref: set-noble-victories/reuniclus-2.ts (Netherworld Gate)
    if (AFTER_ATTACK(effect, 0, this)) {
      ADD_CONFUSION_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    // Attack 2: Extrasensory
    // Ref: set-emerging-powers/grumpig.ts (Extrasensory)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      if (effect.player.hand.cards.length === effect.opponent.hand.cards.length) {
        effect.damage += 60;
      }
    }

    return state;
  }
}
