// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { ConfirmPrompt, GameMessage, PlayerType, PowerType, SlotType, StoreLike, State, StateUtils } from '../../game';
import { DealDamageEffect, PutDamageEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { DamageMap } from '../../game/store/prompts/move-damage-prompt';
import { PutDamagePrompt } from '../../game/store/prompts/put-damage-prompt';
import { WAS_ATTACK_USED, JUST_EVOLVED, IS_ABILITY_BLOCKED, ADD_MARKER, REMOVE_MARKER, HAS_MARKER } from '../../game/store/prefabs/prefabs';

export class GalarianObstagoon extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Galarian Linoone';
  public cardType: CardType = D;
  public hp: number = 160;
  public weakness = [{ type: G }];
  public retreat = [C, C];

  public readonly OBSTRUCT_MARKER = 'GALARIAN_OBSTAGOON_SSH_OBSTRUCT_MARKER';
  public readonly CLEAR_OBSTRUCT_MARKER = 'GALARIAN_OBSTAGOON_SSH_CLEAR_OBSTRUCT_MARKER';

  public powers = [{
    name: 'Untamed Shout',
    powerType: PowerType.ABILITY,
    text: 'When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may put 3 damage counters on 1 of your opponent\'s Pokémon.'
  }];

  public attacks = [
    {
      name: 'Obstruct',
      cost: [D, C],
      damage: 90,
      text: 'During your opponent\'s next turn, prevent all damage done to this Pokémon by attacks from Basic Pokémon.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SSH';
  public setNumber: string = '119';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Galarian Obstagoon';
  public fullName: string = 'Galarian Obstagoon SSH';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Untamed Shout (on-evolve - put 3 damage counters on 1 opponent's Pokemon)
    // Ref: set-unbroken-bonds/gengar.ts (Shadow Pain - JUST_EVOLVED + ConfirmPrompt + PutDamagePrompt)
    if (JUST_EVOLVED(effect, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      const opponent = StateUtils.getOpponent(state, player);

      store.prompt(state, new ConfirmPrompt(
        player.id,
        GameMessage.WANT_TO_USE_ABILITY,
      ), wantToUse => {
        if (wantToUse) {
          const maxAllowedDamage: DamageMap[] = [];
          opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList, card, target) => {
            maxAllowedDamage.push({ target, damage: 9999 });
          });

          store.prompt(state, new PutDamagePrompt(
            player.id,
            GameMessage.CHOOSE_POKEMON_TO_DAMAGE,
            PlayerType.TOP_PLAYER,
            [SlotType.ACTIVE, SlotType.BENCH],
            30, // 3 damage counters = 30 damage
            maxAllowedDamage,
            { allowCancel: false }
          ), targets => {
            const results = targets || [];
            for (const result of results) {
              const target = StateUtils.getTarget(state, player, result.target);
              target.damage += result.damage;
            }
          });
        }
      });
    }

    // Attack 1: Obstruct
    // Ref: set-unbroken-bonds/venomoth-gx.ts (Shinobi Mastery - prevent damage from Basic Pokemon marker pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      ADD_MARKER(this.OBSTRUCT_MARKER, player.active, this);
      ADD_MARKER(this.CLEAR_OBSTRUCT_MARKER, opponent, this);
    }

    // Intercept damage from Basic Pokemon
    if (effect instanceof DealDamageEffect
      && effect.target.marker.hasMarker(this.OBSTRUCT_MARKER, this)) {
      const card = effect.source.getPokemonCard();
      if (card && card.stage === Stage.BASIC) {
        effect.damage = 0;
      }
    }

    if (effect instanceof PutDamageEffect
      && effect.target.marker.hasMarker(this.OBSTRUCT_MARKER, this)) {
      const card = effect.source.getPokemonCard();
      if (card && card.stage === Stage.BASIC) {
        effect.preventDefault = true;
      }
    }

    // Cleanup marker at end of opponent's turn
    if (effect instanceof EndTurnEffect
      && HAS_MARKER(this.CLEAR_OBSTRUCT_MARKER, effect.player, this)) {
      REMOVE_MARKER(this.CLEAR_OBSTRUCT_MARKER, effect.player, this);
      const opponent = StateUtils.getOpponent(state, effect.player);
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        cardList.marker.removeMarker(this.OBSTRUCT_MARKER, this);
      });
    }

    return state;
  }
}
