// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Hitmonchan extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 120;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Coordinated Beatdown',
      cost: [F],
      damage: 20,
      damageCalculation: '+' as '+',
      text: 'If Hitmonlee is on your Bench, this attack does 20 more damage.'
    },
    {
      name: 'Mach Cross',
      cost: [F, F],
      damage: 60,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SSH';
  public setNumber: string = '95';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Hitmonchan';
  public fullName: string = 'Hitmonchan SSH';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Coordinated Beatdown
    // Ref: set-sword-and-shield/bisharp.ts (bench ally check pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const hasHitmonleeOnBench = player.bench.some(b => {
        const card = b.getPokemonCard();
        return card && card.name === 'Hitmonlee';
      });

      if (hasHitmonleeOnBench) {
        effect.damage += 20;
      }
    }

    return state;
  }
}
