// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Hitmonlee extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 120;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Low Sweep',
      cost: [C, C],
      damage: 40,
      text: ''
    },
    {
      name: 'Coordinated Strike',
      cost: [F, F, C],
      damage: 80,
      damageCalculation: '+' as '+',
      text: 'If Hitmonchan is on your Bench, this attack does 80 more damage.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SSH';
  public setNumber: string = '94';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Hitmonlee';
  public fullName: string = 'Hitmonlee SSH';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Coordinated Strike
    // Ref: set-dark-explorers/plusle.ts (bench partner check pattern)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const hasHitmonchan = player.bench.some(b => b.getPokemonCard()?.name === 'Hitmonchan');
      if (hasHitmonchan) {
        effect.damage += 80;
      }
    }

    return state;
  }
}
