// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';

export class LaprasVmax extends PokemonCard {
  public tags = [CardTag.POKEMON_VMAX];
  public stage: Stage = Stage.VMAX;
  public evolvesFrom: string = 'Lapras V';
  public cardType: CardType = W;
  public hp: number = 320;
  public weakness = [{ type: L }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'G-Max Pump',
      cost: [C, C, C],
      damage: 90,
      damageCalculation: '+' as '+',
      text: 'This attack does 30 more damage for each [W] Energy attached to this Pokémon.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SSH';
  public setNumber: string = '50';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Lapras VMAX';
  public fullName: string = 'Lapras VMAX SSH';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: G-Max Pump
    // Ref: set-pokemon-go/blastoise.ts (Hydro Pump)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const checkEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkEnergy);
      const waterCount = checkEnergy.energyMap.reduce((sum, em) =>
        sum + em.provides.filter(t => t === CardType.WATER || t === CardType.ANY).length, 0);
      effect.damage += waterCount * 30;
    }

    return state;
  }
}
