// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, MULTIPLE_COIN_FLIPS_PROMPT } from '../../game/store/prefabs/prefabs';

export class Hitmonchan extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 90;
  public weakness = [{ type: P }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Bullet Punch',
      cost: [C, C],
      damage: 20,
      damageCalculation: '+' as '+',
      text: 'Flip 2 coins. This attack does 20 more damage for each heads.'
    },
    {
      name: 'Mach Cross',
      cost: [F, C, C],
      damage: 60,
      text: ''
    }
  ];

  public set: string = 'FFI';
  public setNumber: string = '48';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Hitmonchan';
  public fullName: string = 'Hitmonchan FFI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Bullet Punch
    // Ref: set-flashfire/krokorok.ts (Double Swing - multiple coin flip pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      MULTIPLE_COIN_FLIPS_PROMPT(store, state, effect.player, 2, results => {
        const heads = results.filter(r => r).length;
        effect.damage += 20 * heads;
      });
    }

    return state;
  }
}
