import { Card } from '../../game/store/card/card';
import { AveryArt, BanetteArt, BeedrillArt, BlazikenVArt, BlazikenVMAXArt, BlisseyVArt, DrizzileArt, EchoingHornArt, ExpeditionUniformArt, FogCrystalArt, FroslassArt, GalarianArticunoVArt, GalarianMoltresVArt, GalladeArt, GardevoirArt, IceRiderCalyrexVArt, IceRiderCalyrexVMAXArt, InteleonArt, JustifiedGlovesArt, KarensConvictionArt, KirliaArt, KlaraArt, LuckyEnergyArt, MelonyArt, PathToThePeakArt, PeonyArt, ShadowRiderCalyrexVArt, ShadowRiderCalyrexVMAXArt, SneaselArt, SnoruntArt, SobbleArt, SpiralEnergyArt } from './card-images';

export const setChillingReign: Card[] = [
  
  new AveryArt(),
  new BanetteArt(),
  new BeedrillArt(),
  new BlazikenVArt(),
  new BlazikenVMAXArt(),
  new BlisseyVArt(),
  new DrizzileArt(),
  new EchoingHornArt(),
  new FogCrystalArt(),
  new FroslassArt(),
  new GalarianArticunoVArt(),
  new GalarianMoltresVArt(),
  new GardevoirArt(),
  new GalladeArt(),
  new IceRiderCalyrexVArt(),
  new IceRiderCalyrexVMAXArt(),
  new InteleonArt(),
  new JustifiedGlovesArt(),
  new KarensConvictionArt(),
  new KirliaArt(),
  new KlaraArt(),
  new LuckyEnergyArt(),
  new MelonyArt(),
  //new OldCemetery(),
  new PathToThePeakArt(),
  new PeonyArt(),
  new ShadowRiderCalyrexVArt(),
  new ShadowRiderCalyrexVMAXArt(),
  new SnoruntArt(),
  new SobbleArt(),
  new SpiralEnergyArt(),
  new ExpeditionUniformArt(),
  new SneaselArt(),
];
