import { Card } from '../../game/store/card/card';
import { AgathaArt, AveryArt, BanetteArt, BeedrillArt, BlazikenVArt, BlazikenVMAXArt, BlisseyVArt, CaitlinArt, DrizzileArt, DynaTreeHillArt, EchoingHornArt, ExpeditionUniformArt, FlanneryArt, FogCrystalArt, FroslassArt, GalarianArticunoVArt, GalarianMoltresVArt, GalarianZapdosVArt, GalladeArt, GardevoirArt, IceRiderCalyrexVArt, IceRiderCalyrexVMAXArt, InteleonArt, JustifiedGlovesArt, KarensConvictionArt, KirliaArt, KlaraArt, LuckyEnergyArt, MelonyArt, PathToThePeakArt, PeonyArt, Porygon2Art, ShadowRiderCalyrexVArt, ShadowRiderCalyrexVMAXArt, SneaselArt, SnoruntArt, SobbleArt, SpiralEnergyArt, ZarudeArt } from './card-images';

export const setChillingReign: Card[] = [
  
  new AgathaArt(),
  new AveryArt(),
  new BanetteArt(),
  new BeedrillArt(),
  new BlazikenVArt(),
  new BlazikenVMAXArt(),
  new BlisseyVArt(),
  new CaitlinArt(),
  new DrizzileArt(),
  new DynaTreeHillArt(),
  new EchoingHornArt(),
  new FlanneryArt(),
  new FogCrystalArt(),
  new FroslassArt(),
  new GalarianArticunoVArt(),
  new GalarianMoltresVArt(),
  new GalarianZapdosVArt(),
  new GardevoirArt(),
  new GalladeArt(),
  new IceRiderCalyrexVArt(),
  new IceRiderCalyrexVMAXArt(),
  new InteleonArt(),
  new JustifiedGlovesArt(),
  new KarensConvictionArt(),
  new KirliaArt(),
  new KlaraArt(),
  new LuckyEnergyArt(),
  new MelonyArt(),
  //new OldCemetery(),
  new PathToThePeakArt(),
  new PeonyArt(),
  new ShadowRiderCalyrexVArt(),
  new ShadowRiderCalyrexVMAXArt(),
  new SnoruntArt(),
  new SobbleArt(),
  new SpiralEnergyArt(),
  new ExpeditionUniformArt(),
  new SneaselArt(),
  new Porygon2Art(),
  new ZarudeArt()
];
