// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, SuperType } from '../../game/store/card/card-types';
import { GameMessage, PlayerType, SlotType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { DiscardCardsEffect } from '../../game/store/effects/attack-effects';
import { DiscardEnergyPrompt } from '../../game/store/prompts/discard-energy-prompt';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { HEAL_X_DAMAGE_FROM_THIS_POKEMON } from '../../game/store/prefabs/attack-effects';

export class Rillaboom extends PokemonCard {
  public tags = [CardTag.RAPID_STRIKE];
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Thwackey';
  public cardType: CardType = G;
  public hp: number = 180;
  public weakness = [{ type: R }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Wood Drain',
      cost: [G, C],
      damage: 60,
      text: 'Heal 30 damage from this Pokémon.'
    },
    {
      name: 'Raging Repeated Strike',
      cost: [G, G, C],
      damage: 120,
      damageCalculation: '+' as '+',
      text: 'Discard any amount of Energy from your Pokémon. This attack does 30 more damage for each card you discarded in this way.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'CRE';
  public setNumber: string = '18';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Rillaboom';
  public fullName: string = 'Rillaboom CRE';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Wood Drain
    // Ref: set-chilling-reign/hattrem.ts (Spiral Drain - HEAL_X_DAMAGE_FROM_THIS_POKEMON)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      HEAL_X_DAMAGE_FROM_THIS_POKEMON(30, effect, store, state);
    }

    // Attack 2: Raging Repeated Strike
    // Ref: set-champions-path/alcremie-vmax.ts (G-Max Whisk - DiscardEnergyPrompt + damage per discarded)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      // Count all energy across all Pokemon
      let totalEnergy = 0;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        totalEnergy += cardList.cards.filter(c => c.superType === SuperType.ENERGY).length;
      });

      if (totalEnergy === 0) {
        return state;
      }

      return store.prompt(state, new DiscardEnergyPrompt(
        player.id,
        GameMessage.CHOOSE_ENERGIES_TO_DISCARD,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { superType: SuperType.ENERGY },
        { allowCancel: false, min: 0, max: totalEnergy }
      ), transfers => {
        if (transfers === null || transfers.length === 0) {
          return state;
        }

        transfers.forEach(transfer => {
          const source = StateUtils.getTarget(state, player, transfer.from);
          const discardEffect = new DiscardCardsEffect(effect, [transfer.card]);
          discardEffect.target = source;
          store.reduceEffect(state, discardEffect);
        });

        effect.damage += transfers.length * 30;
      });
    }

    return state;
  }
}
