// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { ADD_POISON_TO_PLAYER_ACTIVE, AFTER_ATTACK, WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { CardType, SpecialCondition, Stage } from '../../game/store/card/card-types';
import { StateUtils } from '../../game/store/state-utils';
import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Effect } from '../../game/store/effects/effect';
import { State, StoreLike } from '../../game';
export class Scolipede extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Whirlipede';
  public cardType: CardType = D;
  public hp: number = 160;
  public weakness = [{ type: F }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Poison Sting',
      cost: [D],
      damage: 50,
      text: 'Your opponent\'s Active Pokémon is now Poisoned.'
    },
    {
      name: 'Venoshock',
      cost: [D, C, C],
      damage: 100,
      damageCalculation: '+' as '+',
      text: 'If your opponent\'s Active Pokémon is Poisoned, this attack does 120 more damage.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'CRE';
  public setNumber: string = '107';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Scolipede';
  public fullName: string = 'Scolipede CRE';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Poison Sting
    // Ref: AGENTS-patterns.md (YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED)
    if (AFTER_ATTACK(effect, 0, this)) {
      ADD_POISON_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    // Attack 2: Venoshock
    // Ref: set-unbroken-bonds/zubat.ts (Venoshock - if opponent Poisoned, +damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (opponent.active.specialConditions.includes(SpecialCondition.POISONED)) {
        effect.damage += 120;
      }
    }

    return state;
  }
}
