import { Card } from '../../game/store/card/card';
import { AlakazamexArt, BlastoiseexArt, BulbasaurArt, CharizardexArt, CharmanderArt, CharmeleonArt, CyclingRoadArt, DittoArt, DodrioArt, DoduoArt, EeveeArt, ElectabuzzArt, EnergyStickerArt, EreikasInvitationArt, GiovannisCharismaArt, GloomArt, GrabberArt, IvysaurArt, JolteonArt, KangaskhanexArt, MagmarArt, MewexArt, MoltresArt, OddishArt, PidgeottoArt, PidgeyArt, ScytherArt, SquirtleArt, VenomothArt, VenonatArt, VenusaurexArt, VileplumeArt, WartortleArt, ZapdosexArt } from './card-images';

export const setPokemon151: Card[] = [

  // new AntiqueHelixFossilArt(),
  new AlakazamexArt(),
  new BlastoiseexArt(),
  new BulbasaurArt(),
  new CharizardexArt(),
  new CharmeleonArt(),
  new CharmanderArt(),
  new CyclingRoadArt(),
  new DittoArt(),
  new DodrioArt(),
  new DoduoArt(),
  new EeveeArt(),
  new ElectabuzzArt(),
  new EnergyStickerArt(),
  new EreikasInvitationArt(),
  new GiovannisCharismaArt(),
  new GloomArt(),
  new GrabberArt(),
  new IvysaurArt(),
  new JolteonArt(),
  new KangaskhanexArt(),
  new MagmarArt(),
  new MewexArt(),
  new MoltresArt(),
  new OddishArt(),
  new PidgeottoArt(),
  new PidgeyArt(),
  new ScytherArt(),
  new SquirtleArt(),
  new VenonatArt(),
  new VenomothArt(),
  new VenusaurexArt(),
  new VileplumeArt(),
  new WartortleArt(),
  new ZapdosexArt(),
];