import { Card } from '../../game/store/card/card';
import { BellsproutArt, ButterfreeArt, ClefableArt, CuboneArt, DodrioArt, EeveeArt, ElectrodeArt, ExeggcuteArt, ExeggutorArt, FearowArt, FlareonArt, GloomArt, GoldeenArt, JigglypuffArt, JolteonArt, KangaskhanArt, LickitungArt, MankeyArt, MarowakArt, MeowthArt, MrMimeArt, NidoqueenArt, NidoranFemaleArt, NidorinaArt, OddishArt, ParasArt, ParasectArt, PersianArt, PidgeotArt, PikachuArt, PinsirArt, PokeBallArt, PrimeapeArt, RapidashArt, RhydonArt, RhyhornArt, ScytherArt, SnorlaxArt, SpearowArt, VaporeonArt, VenomothArt, VenonatArt, VictreebelArt, VileplumeArt, WeepinbellArt, WigglytuffArt } from './card-images';


export const setJungle: Card[] = [

  new BellsproutArt(),
  new ButterfreeArt(),
  new ClefableArt(),
  new CuboneArt(),
  new DodrioArt(),
  new EeveeArt(),
  new ElectrodeArt(),
  new ExeggcuteArt(),
  new ExeggutorArt(),
  new FearowArt(),
  new FlareonArt(),
  new GloomArt(),
  new GoldeenArt(),
  new JigglypuffArt(),
  new JolteonArt(),
  new KangaskhanArt(),
  new LickitungArt(),
  new MankeyArt(),
  new MarowakArt(),
  new MeowthArt(),
  new MrMimeArt(),
  new NidoqueenArt(),
  new NidorinaArt(),
  new NidoranFemaleArt(),
  new OddishArt(),
  new ParasArt(),
  new ParasectArt(),
  new PersianArt(),
  new PidgeotArt(),
  new PikachuArt(),
  new PinsirArt(),
  new PokeBallArt(),
  new PrimeapeArt(),
  new RapidashArt(),
  new RhydonArt(),
  new RhyhornArt(),
  new ScytherArt(),
  new SnorlaxArt(),
  new SpearowArt(),
  new VaporeonArt(),
  new VenomothArt(),
  new VenonatArt(),
  new VictreebelArt(),
  new VileplumeArt(),
  new WeepinbellArt(),
  new WigglytuffArt()


];