// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { CheckPokemonTypeEffect } from '../../game/store/effects/check-effects';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Fraxure extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Axew';
  public cardType: CardType = N;
  public hp: number = 80;
  public weakness = [{ type: Y }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Sharp Fang',
      cost: [C],
      damage: 20,
      text: ''
    },
    {
      name: 'Dragon Slayer',
      cost: [F, M, C],
      damage: 60,
      damageCalculation: '+' as '+',
      text: 'If your opponent\'s Active Pokémon is a Dragon Pokémon, this attack does 40 more damage (before applying Weakness and Resistance).'
    }
  ];

  public set: string = 'BKT';
  public setNumber: string = '110';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Fraxure';
  public fullName: string = 'Fraxure BKT';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Dragon Slayer
    // Ref: set-breakthrough/abomasnow.ts (Ice Age - check opponent type)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const opponent = StateUtils.getOpponent(state, effect.player);
      const checkType = new CheckPokemonTypeEffect(opponent.active);
      store.reduceEffect(state, checkType);

      if (checkType.cardTypes.includes(CardType.DRAGON)) {
        effect.damage += 40;
      }
    }

    return state;
  }
}
