// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class MGlalieEx extends PokemonCard {
  public tags = [CardTag.MEGA, CardTag.POKEMON_EX];
  public stage: Stage = Stage.MEGA;
  public evolvesFrom: string = 'Glalie-EX';
  public cardType: CardType = W;
  public hp: number = 220;
  public weakness = [{ type: M }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Cryo Mouth',
      cost: [W, C, C],
      damage: 100,
      damageCalculation: '+' as '+',
      text: 'If this Pokémon has 10 or more damage counters on it, this attack does 150 more damage.'
    }
  ];

  public set: string = 'BKT';
  public setNumber: string = '35';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'M Glalie-EX';
  public fullName: string = 'M Glalie-EX BKT';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Cryo Mouth
    // Ref: set-phantom-forces/feraligatr.ts (Second Strike - damage counter check for bonus)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      // 10 damage counters = 100 damage
      if (player.active.damage >= 100) {
        effect.damage += 150;
      }
    }

    return state;
  }
}
