// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Cacnea extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 60;
  public weakness = [{ type: R }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Sucker Punch',
      cost: [G],
      damage: 10,
      damageCalculation: '+' as '+',
      text: 'If this Pokémon has any [D] Energy attached to it, this attack does 30 more damage.'
    }
  ];

  public set: string = 'CIN';
  public setNumber: string = '5';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Cacnea';
  public fullName: string = 'Cacnea CIN';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Sucker Punch
    // Ref: set-burning-shadows/tynamo.ts (Aqua Shock - check energy type for bonus damage)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const checkEnergy = new CheckProvidedEnergyEffect(player, player.active);
      store.reduceEffect(state, checkEnergy);

      const hasDarkEnergy = checkEnergy.energyMap.some(em =>
        em.provides.includes(CardType.DARK)
      );

      if (hasDarkEnergy) {
        effect.damage += 30;
      }
    }

    return state;
  }
}
