import { Card } from '../../game/store/card/card';
import { ArmarougeArt, ArtazonArt, AtticusArt, CharcadetArt, CharizardexArt, CharmanderArt, CharmeleonArt, CliveArt, ElectricGeneratorArt, EspathraexArt, FrigibaxArt, GardevoirexArt, GastlyArt, GengarArt, HaunterArt, IonoArt, KilowattrelArt, MimeJrArt, MimikyuArt, MoonlightHillArt, NatuArt, NemonaArt, NestBallArt, NoibatArt, NoivernexArt, ProfessorsResearch2Art, ProfessorsResearchArt, RaltsArt, RareCandyArt, ScovillainexArt, SquawkabillyexArt, StudentsInPaldeaArt, TechnicalMachineCrisisPunchArt, UltraBallArt, XatuArt } from './card-images';

export const setPaldeaFates: Card[] = [
  new CharmeleonArt(),
  new AtticusArt(),
  new CliveArt(),
  new CharmanderArt(),
  new MimikyuArt(),
  new EspathraexArt(),
  new MoonlightHillArt(),
  new NemonaArt(),
  new ScovillainexArt(),
  new StudentsInPaldeaArt(),
  new GengarArt(),
  new KilowattrelArt(),
  new MimeJrArt(),
  new FrigibaxArt(),
  new GastlyArt(),
  new HaunterArt(),
  new TechnicalMachineCrisisPunchArt(),
  new RareCandyArt(),
  new CharizardexArt(),
  new ElectricGeneratorArt(),
  new IonoArt(),
  new NestBallArt(),
  new ProfessorsResearchArt(),
  new ProfessorsResearch2Art(),
  new UltraBallArt(),
  new ArmarougeArt(),
  new NatuArt(),
  new XatuArt(),
  new CharcadetArt(),
  new RaltsArt(),
  new GardevoirexArt(),
  new NoibatArt(),
  new NoivernexArt(),
  new SquawkabillyexArt(),
  new ArtazonArt(),
  

];
