import { Card } from '../../game/store/card/card';
import { Atticus } from './atticus';
import { CharmanderPAF, MimikyuPAF, RareCandyPAF, CharizardexPAF, ElectricGeneratorPAF, IonoPAF, NestBallPAF, ProfessorsResearchPAF, ProfessorsResearch2PAF, UltraBallPAF, ArmarougePAF, NatuPAF, XatuPAF, CharcadetPAF, RaltsPAF, GardevoirexPAF, NoibatPAF, NoivernexPAF, SquawkabillyexPAF, ArtazonPAF } from './card-images';
import { Charmeleon } from './charmeleon';
import { Clive } from './clive';
import { Espathraex } from './espathra-ex';
import { Frigibax } from './frigibax';
import { Gastly } from './gastly';
import { Gengar } from './gengar';
import { GreatTuskex } from './great-tusk-ex';
import { Haunter } from './haunter';
import { Kilowattrel } from './kilowattrel';
import { MimeJr } from './mime-jr';
import { MoonlightHill } from './moonlight-hill';
import { Scovillainex } from './scovillain-ex';
import { ArbolivaSV, ArctibaxSV, ArmarougeSV, ArvenSV, BaxcaliburSV, CapsakidSV, CharcadetSV, CharizardexSVSIR, CharmanderSV, CharmeleonSV, ChienPaoexUR, ChiYuexUR, CleffaSV, CliveSV, CliveSV2, DittoSV, DodrioSV, DoduoSV, DollivSV, DrifloonSV, EnteiSV, EspathraexSV, FinizenSV, FlamigoSV, ForretressexSV, FrigibaxSV, GardevoirexSV, GardevoirexSVSIR, GloomSV, HawluchaSV, IonoSV, JudgeSV, KilowattrelSV, KirliaSV, KlefkiSV, KoraidonexUR, LucarioSV, LuxraySV, MewexSV, MewexSVSIR, MimeJrSV, MimikyuSV, MiraidonexUR, MurkrowSV, NatuSV, NemonaSV, NemonaSV2, NoibatSV, NoivernexSV, OddishSV, PalafinSV, PalafinSVFA, PaldeanStudentSV1, PaldeanStudentSV2, PawmiSV, PawmiSVFA, PelipperSV, PennySV, PidgeotexSV, PidgeottoSV, PidgeySV, PinecoSV, RaltsSV, RevavroomSV, RioluSV, ScizorSV, SkwovetSV, SmolivSV, SnorlaxSV, SpiritombSV, SquawkabillyexSV, StarmieSV, StaryuSV, ThundurusSV, TingLuexUR, TinkatinkSV, TinkatonSV, TinkatuffSV, ToedscruelexSV, VileplumeSV, WattrelSV, WingullSV, WoChienexUR, WugtrioSVFA, XatuSV } from './shiny-vault';
import { StudentsInPaldea } from './students-in-paldea';
import { TechnicalMachineCrisisPunch } from './technical-machine-crisis-punch';

export const setPaldeaFates: Card[] = [
  new Charmeleon(),
  new Atticus(),
  new Clive(),
  new Espathraex(),
  new MoonlightHill(),
  new Scovillainex(),
  new StudentsInPaldea(),
  new Gengar(),
  new Kilowattrel(),
  new MimeJr(),
  new Frigibax(),
  new Gastly(),
  new Haunter(),
  new TechnicalMachineCrisisPunch(),
  new GreatTuskex(),

  //Reprints
  new CharmanderPAF(),
  new MimikyuPAF(),
  new RareCandyPAF(),
  new CharizardexPAF(),
  new ElectricGeneratorPAF(),
  new IonoPAF(),
  new NestBallPAF(),
  new ProfessorsResearchPAF(),
  new ProfessorsResearch2PAF(),
  new UltraBallPAF(),
  new ArmarougePAF(),
  new NatuPAF(),
  new XatuPAF(),
  new CharcadetPAF(),
  new RaltsPAF(),
  new GardevoirexPAF(),
  new NoibatPAF(),
  new NoivernexPAF(),
  new SquawkabillyexPAF(),
  new ArtazonPAF(),

  //Shiny Vault
  new OddishSV(),
  new GloomSV(),
  new VileplumeSV(),
  new PinecoSV(),
  new SmolivSV(),
  new DollivSV(),
  new ArbolivaSV(),
  new CapsakidSV(),
  new CharmanderSV(),
  new CharmeleonSV(),
  new EnteiSV(),
  new CharcadetSV(),
  new ArmarougeSV(),
  new StaryuSV(),
  new StarmieSV(),
  new FinizenSV(),
  new PalafinSV(),
  new FrigibaxSV(),
  new ArctibaxSV(),
  new BaxcaliburSV(),
  new LuxraySV(),
  new ThundurusSV(),
  new PawmiSV(),
  new WattrelSV(),
  new KilowattrelSV(),
  new CleffaSV(),
  new NatuSV(),
  new XatuSV(),
  new RaltsSV(),
  new KirliaSV(),
  new DrifloonSV(),
  new MimeJrSV(),
  new SpiritombSV(),
  new KlefkiSV(),
  new MimikyuSV(),
  new TinkatinkSV(),
  new TinkatuffSV(),
  new TinkatonSV(),
  new RioluSV(),
  new LucarioSV(),
  new HawluchaSV(),
  new MurkrowSV(),
  new ScizorSV(),
  new RevavroomSV(),
  new NoibatSV(),
  new PidgeySV(),
  new PidgeottoSV(),
  new DoduoSV(),
  new DodrioSV(),
  new DittoSV(),
  new SnorlaxSV(),
  new WingullSV(),
  new PelipperSV(),
  new SkwovetSV(),
  new FlamigoSV(),
  new ForretressexSV(),
  new ToedscruelexSV(),
  new EspathraexSV(),
  new MewexSV(),
  new GardevoirexSV(),
  new NoivernexSV(),
  new PidgeotexSV(),
  new SquawkabillyexSV(),
  new WugtrioSVFA(),
  new PalafinSVFA(),
  new PawmiSVFA(),
  new CliveSV(),
  new JudgeSV(),
  new NemonaSV(),
  new PaldeanStudentSV1(),
  new PaldeanStudentSV2(),
  new MewexSVSIR(),
  new GardevoirexSVSIR(),
  new CharizardexSVSIR(),
  new ArvenSV(),
  new CliveSV2(),
  new IonoSV(),
  new NemonaSV2(),
  new PennySV(),
  new WoChienexUR(),
  new ChiYuexUR(),
  new ChienPaoexUR(),
  new MiraidonexUR(),
  new TingLuexUR(),
  new KoraidonexUR(),
];
