export const setCodeReplacements = [
  { from: 'PR-SH', to: 'SWSH' },
  { from: 'SP', to: 'SWSH' },
  { from: 'PR-SW', to: 'SWSH' }
];

export const cardReplacements = [

  //Energy
  { from: 'Grass Energy 1', to: 'Grass Energy SVE 1' },
  { from: 'Basic Grass Energy 1', to: 'Grass Energy SVE 1' },
  { from: 'Basic Grass Energy SVE 1', to: 'Grass Energy SVE 1' },
  { from: 'Basic {G} Energy SVE 1', to: 'Grass Energy SVE 1' },
  { from: 'Basic {G} Energy SVE 1 PH', to: 'Grass Energy SVE 1' },
  { from: 'Basic {G} Energy SVE 9', to: 'Grass Energy SVE 1' },
  { from: 'Basic {G} Energy SVE 9 PH', to: 'Grass Energy SVE 1' },
  { from: 'Basic {G} Energy SVALT 112', to: 'Grass Energy SVE 1' },
  { from: 'Basic {G} Energy SVALT 131', to: 'Grass Energy SVE 1' },
  { from: 'Basic {G} Energy EVO 91', to: 'Grass Energy BS 99' },
  { from: 'Basic {G} Energy HS 115', to: 'Grass Energy HS 115' },
  { from: 'Basic {G} Energy SVI 257', to: 'Grass Energy PAL 278' },
  { from: 'Grass Energy2 SVE 9', to: 'Grass Energy SVE 9' },

  { from: 'Fire Energy 2', to: 'Fire Energy SVE 2' },
  { from: 'Basic Fire Energy 2', to: 'Fire Energy SVE 2' },
  { from: 'Basic Fire Energy SVE 2', to: 'Fire Energy SVE 2' },
  { from: 'Basic {R} Energy SVE 2', to: 'Fire Energy SVE 2' },
  { from: 'Basic {R} Energy SVE 2 PH', to: 'Fire Energy SVE 2' },
  { from: 'Basic {R} Energy SVE 10', to: 'Fire Energy SVE 2' },
  { from: 'Basic {R} Energy SVE 10 PH', to: 'Fire Energy SVE 2' },
  { from: 'Basic {R} Energy SVALT 113', to: 'Fire Energy SVE 2' },
  { from: 'Basic {R} Energy SVALT 132', to: 'Fire Energy SVE 2' },
  { from: 'Basic {R} Energy EVO 92', to: 'Fire Energy BS 98' },
  { from: 'Basic {R} Energy HS 116', to: 'Fire Energy HS 116' },
  { from: 'Basic {R} Energy OBF 230', to: 'Fire Energy OBF 230' },
  { from: 'Fire Energy2 SVE 10', to: 'Fire Energy SVE 10' },

  { from: 'Water Energy 3', to: 'Water Energy SVE 3' },
  { from: 'Basic Water Energy 3', to: 'Water Energy SVE 3' },
  { from: 'Basic Water Energy SVE 3', to: 'Water Energy SVE 3' },
  { from: 'Basic {W} Energy SVE 3', to: 'Water Energy SVE 3' },
  { from: 'Basic {W} Energy SVE 3 PH', to: 'Water Energy SVE 3' },
  { from: 'Basic {W} Energy SVE 11', to: 'Water Energy SVE 3' },
  { from: 'Basic {W} Energy SVE 11 PH', to: 'Water Energy SVE 3' },
  { from: 'Basic {W} Energy SVALT 114', to: 'Water Energy SVE 3' },
  { from: 'Basic {W} Energy SVALT 133', to: 'Water Energy SVE 3' },
  { from: 'Basic {W} Energy EVO 93', to: 'Water Energy BS 102' },
  { from: 'Basic {W} Energy HS 117', to: 'Water Energy HS 117' },
  { from: 'Basic {W} Energy PAL 279', to: 'Water Energy PAL 279' },
  { from: 'Water Energy2 SVE 11', to: 'Water Energy SVE 11' },

  { from: 'Lightning Energy 4', to: 'Lightning Energy SVE 4' },
  { from: 'Basic Lightning Energy 4', to: 'Lightning Energy SVE 4' },
  { from: 'Basic Lightning Energy SVE 4', to: 'Lightning Energy SVE 4' },
  { from: 'Basic {L} Energy SVE 4', to: 'Lightning Energy SVE 4' },
  { from: 'Basic {L} Energy SVE 4 PH', to: 'Lightning Energy SVE 4' },
  { from: 'Basic {L} Energy SVE 12', to: 'Lightning Energy SVE 4' },
  { from: 'Basic {L} Energy SVE 12 PH', to: 'Lightning Energy SVE 4' },
  { from: 'Basic {L} Energy SVALT 115', to: 'Lightning Energy SVE 4' },
  { from: 'Basic {L} Energy SVALT 134', to: 'Lightning Energy SVE 4' },
  { from: 'Basic {L} Energy EVO 94', to: 'Lightning Energy BS 100' },
  { from: 'Basic {L} Energy HS 118', to: 'Lightning Energy HS 118' },
  { from: 'Basic {L} Energy SVI 257', to: 'Lightning Energy SVI 257' },
  { from: 'Lightning Energy2 SVE 12', to: 'Lightning Energy SVE 12' },

  { from: 'Psychic Energy 5', to: 'Psychic Energy SVE 5' },
  { from: 'Basic Psychic Energy 5', to: 'Psychic Energy SVE 5' },
  { from: 'Basic Psychic Energy SVE 5', to: 'Psychic Energy SVE 5' },
  { from: 'Basic {P} Energy SVE 5', to: 'Psychic Energy SVE 5' },
  { from: 'Basic {P} Energy SVE 5 PH', to: 'Psychic Energy SVE 5' },
  { from: 'Basic {P} Energy SVE 13', to: 'Psychic Energy SVE 5' },
  { from: 'Basic {P} Energy SVE 13 PH', to: 'Psychic Energy SVE 5' },
  { from: 'Basic {P} Energy SVALT 116', to: 'Psychic Energy SVE 5' },
  { from: 'Basic {P} Energy SVALT 135', to: 'Psychic Energy SVE 5' },
  { from: 'Basic {P} Energy EVO 95', to: 'Psychic Energy BS 101' },
  { from: 'Basic {P} Energy HS 119', to: 'Psychic Energy HS 119' },
  { from: 'Basic {P} Energy MEW 207', to: 'Psychic Energy MEW 207' },
  { from: 'Psychic Energy2 SVE 13', to: 'Psychic Energy SVE 13' },

  { from: 'Fighting Energy 6', to: 'Fighting Energy SVE 6' },
  { from: 'Basic Fighting Energy 6', to: 'Fighting Energy SVE 6' },
  { from: 'Basic Fighting Energy SVE 6', to: 'Fighting Energy SVE 6' },
  { from: 'Basic {F} Energy SVE 6', to: 'Fighting Energy SVE 6' },
  { from: 'Basic {F} Energy SVE 6 PH', to: 'Fighting Energy SVE 6' },
  { from: 'Basic {F} Energy SVE 14', to: 'Fighting Energy SVE 6' },
  { from: 'Basic {F} Energy SVE 14 PH', to: 'Fighting Energy SVE 6' },
  { from: 'Basic {F} Energy SVALT 115', to: 'Fighting Energy SVE 6' },
  { from: 'Basic {F} Energy SVALT 136', to: 'Fighting Energy SVE 6' },
  { from: 'Basic {F} Energy EVO 96', to: 'Fighting Energy BS 97' },
  { from: 'Basic {F} Energy HS 120', to: 'Fighting Energy HS 120' },
  { from: 'Basic {F} Energy SVI 258', to: 'Fighting Energy SVI 258' },
  { from: 'Fighting Energy2 SVE 14', to: 'Fighting Energy SVE 14' },

  { from: 'Darkness Energy 7', to: 'Darkness Energy SVE 7' },
  { from: 'Basic Darkness Energy 7', to: 'Darkness Energy SVE 7' },
  { from: 'Basic Darkness Energy SVE 7', to: 'Darkness Energy SVE 7' },
  { from: 'Basic {D} Energy SVE 7', to: 'Darkness Energy SVE 7' },
  { from: 'Basic {D} Energy SVE 7 PH', to: 'Darkness Energy SVE 7' },
  { from: 'Basic {D} Energy SVE 15', to: 'Darkness Energy SVE 7' },
  { from: 'Basic {D} Energy SVE 15 PH', to: 'Darkness Energy SVE 7' },
  { from: 'Basic {D} Energy SVALT 118', to: 'Darkness Energy SVE 7' },
  { from: 'Basic {D} Energy SVALT 137', to: 'Darkness Energy SVE 7' },
  { from: 'Basic {D} Energy EVO 97', to: 'Darkness Energy EVO 97' },
  { from: 'Basic {D} Energy HS 121', to: 'Darkness Energy HS 121' },
  { from: 'Basic {D} Energy SFA 98', to: 'Darkness Energy SFA 98' },
  { from: 'Darkness Energy2 SVE 15', to: 'Darkness Energy SVE 15' },

  { from: 'Metal Energy 8', to: 'Metal Energy SVE 8' },
  { from: 'Basic Metal Energy 8', to: 'Metal Energy SVE 8' },
  { from: 'Basic Metal Energy SVE 8', to: 'Metal Energy SVE 8' },
  { from: 'Basic {M} Energy SVE 8', to: 'Metal Energy SVE 8' },
  { from: 'Basic {M} Energy SVE 8 PH', to: 'Metal Energy SVE 8' },
  { from: 'Basic {M} Energy SVE 16', to: 'Metal Energy SVE 8' },
  { from: 'Basic {M} Energy SVE 16 PH', to: 'Metal Energy SVE 8' },
  { from: 'Basic {M} Energy SVALT 119', to: 'Metal Energy SVE 8' },
  { from: 'Basic {M} Energy SVALT 138', to: 'Metal Energy SVE 8' },
  { from: 'Basic {M} Energy EVO 98', to: 'Metal Energy EVO 98' },
  { from: 'Basic {M} Energy HS 122', to: 'Metal Energy HS 122' },
  { from: 'Basic {M} Energy SFA 99', to: 'Metal Energy SFA 99' },
  { from: 'Metal Energy2 SVE 16', to: 'Metal Energy SVE 16' },

  //BS
  { from: 'Pokemon Breeder BS 76', to: 'Pokémon Breeder BS 76' },
  { from: 'Pokemon Trader BS 77', to: 'Pokémon Trader BS 77' },

  //SUM
  { from: 'Rotom Dex SUM 159', to: 'Rotom DexSR SM 159' },

  //SHF
  { from: 'Snom SHF SV33', to: 'Snom SHFSV SV33' },

  //STS
  { from: 'Pokémon Ranger STS 104', to: 'Pokemon Ranger STS 104' },

  //VIV
  { from: 'Talonflame V VIV 168', to: 'Talonflame VFA VIV 168' },

  //PGO
  { from: 'PokéStop PGO 68', to: 'PokeStop PGO 68' },

  //BRS
  { from: 'Ultra Ball BRS 186', to: 'Ultra BallHR BRS 186' },

  //ASR
  { from: 'Hisuian Qwilfish ASR 89', to: 'Hisuian Qwilfish2 ASR 89' },

  //SVI
  { from: 'Pokégear 3.0 SVI 186', to: 'Pokegear SVI 186' },
  { from: 'Pokémon Catcher SVI 187', to: 'Pokemon Catcher SVI 187' },
  { from: 'Riolu SVI 113', to: 'Riolu2 SVI 113' },

  //SVI FA
  { from: 'Armarouge SVI 203', to: 'ArmarougeIR SVI 203' },
  { from: 'Slowpoke SVI 204', to: 'SlowpokeIR SVI 204' },
  { from: 'Pawmot SVI 209', to: 'PawmotIR SVI 209' },
  { from: 'Arven SVI 235', to: 'ArvenFA SVI 235' },
  { from: 'Arven SVI 249', to: 'ArvenSIR SVI 249' },
  { from: 'Fighting Energy SVI 258', to: 'Fighting EnergyHR SVI 258' },
  { from: 'Lightning Energy SVI 257', to: 'Lightning EnergyHR SVI 257' },
  { from: 'Gardevoir ex SVI 228', to: 'Gardevoir exFA SVI 228' },
  { from: 'Gardevoir ex SVI 245', to: 'Gardevoir exSIR SVI 245' },
  { from: 'Jacq SVI 236', to: 'JacqFA SVI 236' },
  { from: 'Jacq SVI 250', to: 'JacqSIR SVI 250' },
  { from: 'Katy SVI 237', to: 'KatyFA SVI 237' },
  { from: 'Koraidon ex SVI 231', to: 'Koraidon exFA SVI 231' },
  { from: 'Koraidon ex SVI 247', to: 'Koraidon exSIR SVI 247' },
  { from: 'Koraidon ex SVI 254', to: 'Koraidon exHR SVI 254' },
  { from: 'Magnezone ex SVI 226', to: 'Magnezone exFA SVI 226' },
  { from: 'Miraidon ex SVI 227', to: 'Miraidon exFA SVI 227' },
  { from: 'Miraidon ex SVI 244', to: 'Miraidon exSIR SVI 244' },
  { from: 'Miraidon ex SVI 253', to: 'Miraidon exHR SVI 253' },
  { from: 'Miriam SVI 238', to: 'MiriamFA SVI 238' },
  { from: 'Miriam SVI 251', to: 'MiriamSIR SVI 251' },
  { from: 'Nest Ball SVI 255', to: 'Nest BallHR SVI 255' },
  { from: 'Penny SVI 239', to: 'PennyFA SVI 239' },
  { from: 'Penny SVI 252', to: 'PennySIR SVI 252' },
  { from: "Professor's Research SVI 240", to: "Professor's ResearchFA1 SVI 242" },
  { from: "Professor's Research SVI 241", to: "Professor's ResearchFA2 SVI 241" },
  { from: 'Ralts SVI 211', to: 'RaltsIR SVI 211' },
  { from: 'Kirlia SVI 212', to: 'KirliaIR SVI 212' },
  { from: 'Rare Candy SVI 256', to: 'Rare CandyHR SVI 256' },
  { from: 'Skwovet SVI 222', to: 'SkwovetIR SVI 222' },
  { from: 'Team Star Grunt SVI 242', to: 'Team Star GruntFA SVI 242' },

  //SVP
  { from: 'Charmander SVP 44', to: 'CharmanderIR SVP 44' },
  { from: 'Iron Bundle SVP 66', to: 'Iron Bundle SVP 66' },
  { from: 'Charizard ex SVP 74', to: 'Charizard ex2 SVP 74' },
  { from: 'Meowscarada ex SVP 78', to: 'Meowscarada exFA SVP 78' },
  { from: 'Skeledirge ex SVP 81', to: 'Skeledirge exFA SVP 81' },
  { from: 'Quaquaval ex SVP 84', to: 'Quaquaval exFA SVP 84' },
  { from: 'Pecharunt SVP 129', to: 'PecharuntIR SVP 129' },
  { from: 'Miraidon ex SVP 142', to: 'Miraidon ex2 SVP 142' },
  { from: 'Charizard ex SVP 161', to: 'Charizard ex3 SVP 161' },

  //PAL
  { from: 'Frigibax PAL 57', to: 'Frigibax PAL1 57' },
  { from: 'Frigibax PAL 58', to: 'Frigibax PAL2 58' },
  //PAL FA
  { from: 'Frigibax PAL 208', to: 'FrigibaxIR PAL 208' },
  { from: 'Arctibax PAL 209', to: 'ArctibaxIR PAL 209' },
  { from: 'Baxcalibur PAL 210', to: 'BaxcaliburIR PAL 210' },
  { from: 'Tinkatink PAL 216', to: 'TinkatinkIR PAL 216' },
  { from: 'Tinkatuff PAL 217', to: 'TinkatuffIR PAL 217' },
  { from: 'Flamigo PAL 227', to: 'FlamigoIR PAL 227' },
  { from: 'Meowscarada ex PAL 231', to: 'Meowscarada exFA PAL 231' },
  { from: 'Wo-Chien ex PAL 232', to: 'Wo-Chien exFA PAL 232' },
  { from: 'Chi-Yu ex PAL 234', to: 'Chi-Yu exFA PAL 234' },
  { from: 'Chien-Pao ex PAL 236', to: 'Chien-Pao exFA PAL 236' },
  { from: 'Tinkaton ex PAL 240', to: 'Tinkaton exFA PAL 240' },
  { from: 'Ting-Lu ex PAL 243', to: 'Ting-Lu exFA PAL 243' },
  { from: 'Noivern ex PAL 246', to: 'Noivern exFA PAL 246' },
  { from: 'Squawkabilly ex PAL 247', to: 'Squawkabilly exFA PAL 247' },
  { from: 'Boss\'s Orders PAL 248', to: 'Boss\'s OrdersFA PAL 248' },
  { from: 'Clavell PAL 249', to: 'ClavellFA PAL 249' },
  { from: 'Giacomo PAL 252', to: 'GiacomoFA PAL 252' },
  { from: 'Grusha PAL 253', to: 'GrushaFA PAL 253' },
  { from: 'Iono PAL 254', to: 'IonoFA PAL 254' },
  { from: 'Meowscarada ex PAL 256', to: 'Meowscarada exSIR PAL 256' },
  { from: 'Wo-Chien ex PAL 257', to: 'Wo-Chien exSIR PAL 257' },
  { from: 'Chi-Yu ex PAL 259', to: 'Chi-Yu exSIR PAL 259' },
  { from: 'Chien-Pao ex PAL 261', to: 'Chien-Pao exSIR PAL 261' },
  { from: 'Tinkaton ex PAL 262', to: 'Tinkaton exSIR PAL 262' },
  { from: 'Ting-Lu ex PAL 263', to: 'Ting-Lu exSIR PAL 263' },
  { from: 'Squawkabilly ex PAL 264', to: 'Squawkabilly exSIR PAL 264' },
  { from: 'Boss\'s Orders PAL 265', to: 'Boss\'s OrdersSIR PAL 265' },
  { from: 'Giacomo PAL 267', to: 'GiacomoSIR PAL 267' },
  { from: 'Grusha PAL 268', to: 'GrushaSIR PAL 268' },
  { from: 'Iono PAL 269', to: 'IonoSIR PAL 269' },
  { from: 'Meowscarada ex PAL 271', to: 'Meowscarada exHR PAL 271' },
  { from: 'Chien-Pao ex PAL 274', to: 'Chien-Pao exHR PAL 274' },
  { from: 'Ting-Lu ex PAL 275', to: 'Ting-Lu exHR PAL 275' },
  { from: 'Super Rod PAL 276', to: 'Super RodHR PAL 276' },
  { from: 'Superior Energy Retrieval PAL 277', to: 'Superior Energy RetrievalHR PAL 277' },
  { from: 'Froslass ex PAR 217', to: 'FroslassexFA PAR 217' },
  { from: 'Garchomp ex PAR 219', to: 'GarchompexFA PAR 219' },
  { from: 'Tsareena ex PAR 220', to: 'TsareenaexFA PAR 220' },
  { from: 'Tapu Koko ex PAR 222', to: 'TapuKokoexFA PAR 222' },
  { from: 'Iron Hands ex PAR 223', to: 'IronHandsexFA PAR 223' },
  { from: 'Iron Valiant ex PAR 225', to: 'IronValiantexFA PAR 225' },
  { from: 'Hoopa ex PAR 226', to: 'HoopaexFA PAR 226' },
  { from: 'Sandy Shocks ex PAR 228', to: 'SandyShocksexFA PAR 228' },
  { from: 'Roaring Moon ex PAR 229', to: 'RoaringMoonexFA PAR 229' },
  { from: 'Gholdengo ex PAR 231', to: 'GholdengoexFA PAR 231' },
  { from: 'Bombirdier ex PAR 234', to: 'BombirdierexFA PAR 234' },
  { from: 'Mela PAR 236', to: 'MelaFA PAR 236' },
  { from: 'Professor Sada\'s Vitality PAR 239', to: 'ProfessorSadasVitalityFA PAR 239' },
  { from: 'Professor Turo\'s Scenario PAR 240', to: 'ProfessorTurosScenarioFA PAR 240' },
  { from: 'Tulip PAR 244', to: 'TulipFA PAR 244' },
  { from: 'Garchomp ex PAR 245', to: 'GarchompexSIR PAR 245' },
  { from: 'Tapu Koko ex PAR 247', to: 'TapuKokoexSIR PAR 247' },
  { from: 'Iron Hands ex PAR 248', to: 'IronHandsexSIR PAR 248' },
  { from: 'Iron Valiant ex PAR 249', to: 'IronValiantexSIR PAR 249' },
  { from: 'Sandy Shocks ex PAR 250', to: 'SandyShocksexSIR PAR 250' },
  { from: 'Roaring Moon ex PAR 251', to: 'RoaringMoonexSIR PAR 251' },
  { from: 'Gholdengo ex PAR 252', to: 'GholdengoexSIR PAR 252' },
  { from: 'Mela PAR 254', to: 'MelaSIR PAR 254' },
  { from: 'Professor Sada\'s Vitality PAR 256', to: 'ProfessorSadasVitalitySIR PAR 256' },
  { from: 'Professor Turo\'s Scenario PAR 257', to: 'ProfessorTurosScenarioSIR PAR 257' },
  { from: 'Tulip PAR 259', to: 'TulipSIR PAR 259' },
  { from: 'Garchomp ex PAR 260', to: 'GarchompexHR PAR 260' },
  { from: 'Iron Valiant ex PAR 261', to: 'IronValiantexHR PAR 261' },
  { from: 'Roaring Moon ex PAR 262', to: 'RoaringMoonexHR PAR 262' },
  { from: 'Beach Court PAR 263', to: 'BeachCourtHR PAR 263' },
  { from: 'Counter Catcher PAR 264', to: 'CounterCatcherHR PAR 264' },
  { from: 'Luxurious Cape PAR 265', to: 'LuxuriousCapeHR PAR 265' },
  { from: 'Reversal Energy PAR 266', to: 'ReversalEnergyHR PAR 266' },

  //151
  //151 FA
  { from: 'Bulbasaur MEW 166', to: 'BulbasaurIR MEW 166' },
  { from: 'Ivysaur MEW 167', to: 'IvysaurIR MEW 167' },
  { from: 'Charmander MEW 168', to: 'CharmanderIR MEW 168' },
  { from: 'Charmeleon MEW 169', to: 'CharmeleonIR MEW 169' },
  { from: 'Squirtle MEW 170', to: 'SquirtleIR MEW 170' },
  { from: 'Wartortle MEW 171', to: 'WartortleIR MEW 171' },
  { from: 'Nidoking MEW 174', to: 'NidokingIR MEW 174' },
  { from: 'Venusaur ex MEW 182', to: 'Venusaur exFA MEW 182' },
  { from: 'Charizard ex MEW 183', to: 'Charizard exFA MEW 183' },
  { from: 'Blastoise ex MEW 184', to: 'Blastoise exFA MEW 184' },
  { from: 'Arbok ex MEW 185', to: 'Arbok exFA MEW 185' },
  { from: 'Alakazam ex MEW 188', to: 'Alakazam exFA MEW 188' },
  { from: 'Kangaskhan ex MEW 190', to: 'Kangaskhan exFA MEW 190' },
  { from: 'Zapdos ex MEW 192', to: 'Zapdos exFA MEW 192' },
  { from: 'Mew ex MEW 193', to: 'Mew exFA MEW 193' },
  { from: 'Erika\'s Invitation MEW 196', to: 'Erika\'s InvitationFA MEW 196' },
  { from: 'Giovanni\'s Charisma MEW 197', to: 'Giovanni\'s CharismaFA MEW 197' },
  { from: 'Venusaur ex MEW 198', to: 'Venusaur exSIR MEW 198' },
  { from: 'Charizard ex MEW 199', to: 'Charizard exSIR MEW 199' },
  { from: 'Blastoise ex MEW 200', to: 'Blastoise exSIR MEW 200' },
  { from: 'Alakazam ex MEW 201', to: 'Alakazam exSIR MEW 201' },
  { from: 'Zapdos ex MEW 202', to: 'Zapdos exSIR MEW 202' },
  { from: 'Erika\'s Invitation MEW 203', to: 'Erika\'s InvitationSIR MEW 203' },
  { from: 'Giovanni\'s Charisma MEW 204', to: 'Giovanni\'s CharismaSIR MEW 204' },
  { from: 'Mew ex MEW 205', to: 'Mew exHR MEW 205' },
  { from: 'Switch MEW 206', to: 'SwitchHR MEW 206' },
  { from: 'Psychic Energy MEW 207', to: 'Psychic Energy MEW 207' },

  //PAR
  { from: 'Toedscool PAL 57 ', to: 'Toedscool PAL2 57' },
  { from: 'Gimmighoul PAR 88', to: 'Gimmighoul2 PAR 88' },
  //PAR FA
  { from: 'Toedscruel PAR 185', to: 'ToedscruelIR PAR 185' },
  { from: 'Magby PAR 186', to: 'MagbyIR PAR 186' },
  { from: 'Iron Moth PAR 187', to: 'IronMothIR PAR 187' },
  { from: 'Snorunt PAR 188', to: 'SnoruntIR PAR 188' },
  { from: 'Mantyke PAR 189', to: 'MantykeIR PAR 189' },
  { from: 'Vanillish PAR 190', to: 'VanillishIR PAR 190' },
  { from: 'Blitzle PAR 195', to: 'BlitzleIR PAR 195' },
  { from: 'Joltik PAR 196', to: 'JoltikIR PAR 196' },
  { from: 'Gimmighoul PAR 198', to: 'GimmighoulIR PAR 198' },
  { from: 'Groudon PAR 199', to: 'GroudonIR PAR 199' },
  { from: 'Minior PAR 201', to: 'MiniorIR PAR 201' },
  { from: 'Garganacl PAR 202', to: 'GarganacIR PAR 202' },
  { from: 'Slither Wing PAR 203', to: 'SlitherWingIR PAR 203' },
  { from: 'Garbodor PAR 204', to: 'GarbodorIR PAR 204' },
  { from: 'Yveltal PAR 205', to: 'YveltalIR PAR 205' },
  { from: 'Morpeko PAR 206', to: 'MorpekoIR PAR 206' },
  { from: 'Brute Bonnet PAR 207', to: 'BruteBonnetIR PAR 207' },
  { from: 'Ferrothorn PAR 209', to: 'FerrothorIR PAR 209' },
  { from: 'Aegislash PAR 210', to: 'AegislashIR PAR 210' },
  { from: 'Swablu PAR 213', to: 'SwabluIR PAR 213' },
  { from: 'Porygon-Z PAR 214', to: 'PorygonZIR PAR 214' },
  { from: 'Cyclizar PAR 215', to: 'CyclizarIR PAR 215' },
  { from: 'Iron Jugulis PAR 216', to: 'IronJugulisIR PAR 216' },

  //PAF Shiny Vault & Full arts
  { from: 'Charmander PAF 109', to: 'CharmanderSV PAF 109' },
  { from: 'Charmeleon PAF 110', to: 'CharmeleonSV PAF 110' },
  { from: 'Frigibax PAF 128', to: 'FrigibaxSV PAF 128' },
  { from: 'Mime Jr. PAF 157', to: 'MimeJrSV PAF 157' },
  { from: 'Espathra ex PAF 214', to: 'Espathra exSV PAF 214' },
  { from: 'Wugtrio PAF 224', to: 'WugtrioFA PAF 224' },
  { from: 'Palafin PAF 225', to: 'PalafinFA PAF 225' },
  { from: 'Pawmi PAF 226', to: 'PawmiFA PAF 226' },
  { from: 'Clive PAF 227', to: 'CliveFA PAF 227' },
  { from: 'Nemona PAF 229', to: 'NemonaFA PAF 229' },
  { from: 'Paldean Student PAF 230', to: 'Paldean StudentFA PAF 230' },
  { from: 'Paldean Student PAF 231', to: 'Paldean StudentFA2 PAF 231' },
  { from: 'Mew ex PAF 232', to: 'Mew exSIR PAF 232' },
  { from: 'Gardevoir ex PAF 233', to: 'Gardevoir exSIR PAF 233' },
  { from: 'Charizard ex PAF 234', to: 'Charizard exSIR PAF 234' },
  { from: 'Arven PAF 236', to: 'ArvenSIR PAF 235' },
  { from: 'Clive PAF 236', to: 'CliveSIR PAF 236' },
  { from: 'Iono PAF 237', to: 'IonoSIR PAF 237' },
  { from: 'Nemona PAF 238', to: 'NemonaSIR PAF 238' },
  { from: 'Penny PAF 236', to: 'PennySIR PAF 239' },

  //TEF
  //TEF FA
  { from: 'Grotle TEF 164', to: 'GrotleIR TEF 164' },
  { from: 'Charjabug TEF 169', to: 'CharjabugIR TEF 169' },
  { from: 'Reuniclus TEF 171', to: 'ReuniclusIR TEF 171' },
  { from: 'Relicanth TEF 173', to: 'RelicanthIR TEF 173' },
  { from: 'Gastly TEF 177', to: 'GastlyIR TEF 177' },
  { from: 'Metagross TEF 178', to: 'MetagrossIR TEF 178' },
  { from: 'Chatot TEF 181', to: 'ChatotIR TEF 181' },
  { from: 'Minccino TEF 182', to: 'MinccinoIR TEF 182' },
  { from: 'Cinccino TEF 183', to: 'CinccinoIR TEF 183' },
  { from: 'Torterra ex TEF 185', to: 'TorterraexFA TEF 185' },
  { from: 'Iron Leaves ex TEF 186', to: 'IronLeavesexFA TEF 186' },
  { from: 'Gouging Fire ex TEF 188', to: 'GougingFireexFA TEF 188' },
  { from: 'Walking Wake ex TEF 189', to: 'WalkingWakeexFA TEF 189' },
  { from: 'Iron Crown ex TEF 191', to: 'IronCrownexFA TEF 191' },
  { from: 'Gengar ex TEF 193', to: 'GengarexFA TEF 193' },
  { from: 'Raging Bolt ex TEF 196', to: 'RagingBoltexFA TEF 196' },
  { from: 'Bianca\'s Devotion TEF 197', to: 'BiancasDevotionFA TEF 197' },
  { from: 'Ciphermaniac\'s Codebreaking TEF 198', to: 'CiphermaniacsCodebreakingFA TEF 198' },
  { from: 'Eri TEF 199', to: 'EriFA TEF 199' },
  { from: 'Explorer\'s Guidance TEF 200', to: 'ExplorersGuidanceFA TEF 200' },
  { from: 'Morty\'s Conviction TEF 201', to: 'MortysConvictionFA TEF 201' },
  { from: 'Salvatore TEF 202', to: 'SalvatoreFA TEF 202' },
  { from: 'Iron Leaves ex TEF 203', to: 'IronLeavesexSIR TEF 203' },
  { from: 'Gouging Fire ex TEF 204', to: 'GougingFireexSIR TEF 204' },
  { from: 'Walking Wake ex TEF 205', to: 'WalkingWakeexSIR TEF 205' },
  { from: 'Iron Crown ex TEF 206', to: 'IronCrownexSIR TEF 206' },
  { from: 'Raging Bolt ex TEF 208', to: 'RagingBoltexSIR TEF 208' },
  { from: 'Bianca\'s Devotion TEF 209', to: 'BiancasDevotionSIR TEF 209' },
  { from: 'Eri TEF 210', to: 'EriSIR TEF 210' },
  { from: 'Morty\'s Conviction TEF 211', to: 'MortysConvictionSIR TEF 211' },
  { from: 'Salvatore TEF 212', to: 'SalvatoreSIR TEF 212' },
  { from: 'Iron Leaves ex TEF 213', to: 'IronLeavesexHR TEF 213' },
  { from: 'Gouging Fire ex TEF 214', to: 'GougingFireexHR TEF 214' },
  { from: 'Walking Wake ex TEF 215', to: 'WalkingWakeexHR TEF 215' },
  { from: 'Iron Crown ex TEF 216', to: 'IronCrownexHR TEF 216' },
  { from: 'Raging Bolt ex TEF 218', to: 'RagingBoltexHR TEF 218' },

  //TWM
  { from: 'Applin TWM 17', to: 'Applin TWM1 17' },
  { from: 'Applin TWM 126', to: 'Applin TWM2 126' },
  { from: 'Dipplin TWM 18', to: 'Dipplin TWM1 18' },
  { from: 'Dipplin TWM 127', to: 'Dipplin TWM2 127' },
  //TWM FA
  { from: 'Dipplin TWM 170', to: 'DipplinIR TWM 170' },
  { from: 'Poltchageist TWM 171', to: 'PoltchageistIR TWM 171' },
  { from: 'Infernape TWM 173', to: 'InfernapeIR TWM 173' },
  { from: 'Froslass TWM 174', to: 'FroslassIR TWM 174' },
  { from: 'Phione TWM 175', to: 'PhioneIR TWM 175' },
  { from: 'Hisuian Growlithe TWM 181', to: 'HisuianGrowlitheIR TWM 181' },
  { from: 'Timburr TWM 183', to: 'TimburrIR TWM 183' },
  { from: 'Lairon TWM 184', to: 'LaironIR TWM 184' },
  { from: 'Applin TWM 185', to: 'ApplinIR TWM 185' },
  { from: 'Tatsugiri TWM 186', to: 'TatsugiriIR TWM 186' },
  { from: 'Chansey TWM 187', to: 'ChanseyIR TWM 187' },
  { from: 'Eevee TWM 188', to: 'EeveeIR TWM 188' },
  { from: 'Sinistcha ex TWM 189', to: 'Sinistcha exFA TWM 189' },
  { from: 'Teal Mask Ogerpon ex TWM 190', to: 'Teal Mask Ogerpon exFA TWM 190' },
  { from: 'Magcargo ex TWM 191', to: 'Magcargo exFA TWM 191' },
  { from: 'Hearthflame Mask Ogerpon ex TWM 192', to: 'Hearthflame Mask Ogerpon exFA TWM 192' },
  { from: 'Palafin ex TWM 193', to: 'Palafin exFA TWM 193' },
  { from: 'Wellspring Mask Ogerpon ex TWM 194', to: 'Wellspring Mask Ogerpon exFA TWM 194' },
  { from: 'Luxray ex TWM 195', to: 'Luxray exFA TWM 195' },
  { from: 'Iron Thorns ex TWM 196', to: 'Iron Thorns exFA TWM 196' },
  { from: 'Scream Tail ex TWM 197', to: 'Scream Tail exFA TWM 197' },
  { from: 'Greninja ex TWM 198', to: 'Greninja exFA TWM 198' },
  { from: 'Cornerstone Mask Ogerpon ex TWM 199', to: 'Cornerstone Mask Ogerpon exFA TWM 199' },
  { from: 'Dragapult ex TWM 200', to: 'Dragapult exFA TWM 200' },
  { from: 'Blissey ex TWM 201', to: 'Blissey exFA TWM 201' },
  { from: 'Bloodmoon Ursaluna ex TWM 202', to: 'Bloodmoon Ursaluna exFA TWM 202' },
  { from: 'Caretaker TWM 203', to: 'CaretakerFA TWM 203' },
  { from: 'Carmine TWM 204', to: 'CarmineFA TWM 204' },
  { from: 'Hassel TWM 205', to: 'HasselFA TWM 205' },
  { from: 'Kieran TWM 206', to: 'KieranFA TWM 206' },
  { from: 'Lana\'s Aid TWM 207', to: 'Lana\'s AidFA TWM 207' },
  { from: 'Perrin TWM 209', to: 'PerrinFA TWM 209' },
  { from: 'Sinistcha ex TWM 210', to: 'Sinistcha exSIR TWM 210' },
  { from: 'Teal Mask Ogerpon ex TWM 211', to: 'Teal Mask Ogerpon exSIR TWM 211' },
  { from: 'Hearthflame Mask Ogerpon ex TWM 212', to: 'Hearthflame Mask Ogerpon exSIR TWM 212' },
  { from: 'Wellspring Mask Ogerpon ex TWM 213', to: 'Wellspring Mask Ogerpon exSIR TWM 213' },
  { from: 'Greninja ex TWM 214', to: 'Greninja exSIR TWM 214' },
  { from: 'Cornerstone Mask Ogerpon ex TWM 215', to: 'Cornerstone Mask Ogerpon exSIR TWM 215' },
  { from: 'Bloodmoon Ursaluna ex TWM 216', to: 'Bloodmoon Ursaluna exSIR TWM 216' },
  { from: 'Carmine TWM 217', to: 'CarmineSIR TWM 217' },
  { from: 'Kieran TWM 218', to: 'KieranSIR TWM 218' },
  { from: 'Lana\'s Aid TWM 219', to: 'Lana\'s AidSIR TWM 219' },
  { from: 'Perrin TWM 220', to: 'PerrinSIR TWM 220' },
  { from: 'Teal Mask Ogerpon ex TWM 221', to: 'Teal Mask Ogerpon exHR TWM 221' },
  { from: 'Bloodmoon Ursaluna ex TWM 222', to: 'Bloodmoon Ursaluna exHR TWM 222' },
  { from: 'Buddy-Buddy Poffin TWM 223', to: 'Buddy-Buddy PoffinHR TWM 223' },
  { from: 'Enhanced Hammer TWM 224', to: 'Enhanced HammerHR TWM 224' },
  { from: 'Rescue Board TWM 225', to: 'Rescue BoardHR TWM 225' },

  //SFA
  { from: 'Janine\'s Secret Art SFA 59', to: 'Janine\'s Secret Technique SFA 59' },
  { from: 'Poké Vital A SFA 62', to: 'PokéVital A SFA 62' },
  { from: 'Tapu Bulu SFA 65', to: 'Tapu BuluIR SFA 65' },
  { from: 'Houndoom SFA 66', to: 'HoundoomIR SFA 66' },
  { from: 'Horsea SFA 67', to: 'HorseaIR SFA 67' },
  { from: 'Duskull SFA 68', to: 'DuskullIR SFA 68' },
  { from: 'Dusclops SFA 69', to: 'DusclopsIR SFA 69' },
  { from: 'Dusknoir SFA 70', to: 'DusknoirIR SFA 70' },
  { from: 'Cresselia SFA 71', to: 'CresseliaIR SFA 71' },
  { from: 'Zorua SFA 75', to: 'ZoruaIR SFA 75' },
  { from: 'Cufant SFA 76', to: 'CufantIR SFA 76' },
  { from: 'Fraxure SFA 77', to: 'FraxureIR SFA 77' },
  { from: 'Kingdra ex SFA 80', to: 'Kingdra exFA SFA 80' },
  { from: 'Revavroom ex SFA 81', to: 'Revavroom exFA SFA 81' },
  { from: 'Okidogi ex SFA 82', to: 'Okidogi exFA SFA 82' },
  { from: 'Munkidori ex SFA 83', to: 'Munkidori exFA SFA 83' },
  { from: 'Fezandipiti ex SFA 84', to: 'Fezandipiti exFA SFA 84' },
  { from: 'Pecharunt ex SFA 85', to: 'Pecharunt exFA SFA 85' },
  { from: 'Cassiopeia SFA 86', to: 'CassiopeiaFA SFA 86' },
  { from: 'Colress\'s Tenacity SFA 87', to: 'Colress\'s TenacityFA SFA 87' },
  { from: 'Janine\'s Secret Art SFA 88', to: 'Janine\'s Secret ArtFA SFA 88' },
  { from: 'Xerosic\'s Machinations SFA 89', to: 'Xerosic\'s MachinationsFA SFA 89' },
  { from: 'Okidogi ex SFA 90', to: 'Okidogi exSIR SFA 90' },
  { from: 'Munkidori ex SFA 91', to: 'Munkidori exSIR SFA 91' },
  { from: 'Fezandipiti ex SFA 92', to: 'Fezandipiti exSIR SFA 92' },
  { from: 'Pecharunt ex SFA 93', to: 'Pecharunt exSIR SFA 93' },
  { from: 'Cassiopeia SFA 94', to: 'CassiopeiaSIR SFA 94' },
  { from: 'Pecharunt ex SFA 95', to: 'Pecharunt exUR SFA 95' },
  { from: 'Powerglass SFA 97', to: 'PowerglassUR SFA 97' },

  //SCR FA
  { from: 'Bulbasaur SCR 143', to: 'BulbasaurIR SCR 143' },
  { from: 'Raboot SCR 147', to: 'RabootIR SCR 147' },
  { from: 'Squirtle SCR 148', to: 'SquirtleIR SCR 148' },
  { from: 'Joltik SCR 150', to: 'JoltikIR SCR 150' },
  { from: 'Zeraora SCR 151', to: 'ZeraoraIR SCR 151' },
  { from: 'Milcery SCR 152', to: 'MilceryIR SCR 152' },
  { from: 'Meditite SCR 153', to: 'MedititeIR SCR 153' },
  { from: 'Archaludon SCR 155', to: 'ArchaludonIR SCR 155' },
  { from: 'Hydrapple ex SCR 156', to: 'Hydrapple exFA SCR 156' },
  { from: 'Cinderace ex SCR 157', to: 'Cinderace exFA SCR 157' },
  { from: 'Lapras ex SCR 158', to: 'Lapras exFA SCR 158' },
  { from: 'Galvantula ex SCR 159', to: 'Galvantula exFA SCR 159' },
  { from: 'Medicham ex SCR 161', to: 'Medicham exFA SCR 161' },
  { from: 'Orthworm ex SCR 162', to: 'Orthworm exFA SCR 162' },
  { from: 'Briar SCR 163', to: 'BriarFA SCR 163' },
  { from: 'Crispin SCR 164', to: 'CrispinFA SCR 164' },
  { from: 'Kofu SCR 165', to: 'KofuFA SCR 165' },
  { from: 'Lacey SCR 166', to: 'LaceyFA SCR 166' },
  { from: 'Hydrapple ex SCR 167', to: 'Hydrapple exSIR SCR 167' },
  { from: 'Galvantula ex SCR 168', to: 'Galvantula exSIR SCR 168' },
  { from: 'Terapagos ex SCR 170', to: 'Terapagos exSIR SCR 170' },
  { from: 'Briar SCR 171', to: 'BriarSIR SCR 171' },
  { from: 'Lacey SCR 172', to: 'LaceySIR SCR 172' },
  { from: 'Terapagos ex SCR 173', to: 'Terapagos exHR SCR 173' },
  { from: 'Area Zero Underdepths SCR 174', to: 'Area Zero UnderdepthsHR SCR 174' },

  //SSP
  { from: 'Charcadet SSP 33', to: 'Charcadet 2 SSP 33' },

  //SSP FA
  { from: 'Larvesta SSP 196', to: 'LarvestaIR SSP 196' },
  { from: 'Feebas SSP 198', to: 'FeebasIR SSP 198' },
  { from: 'Milotic ex SSP 218', to: 'Milotic exFA SSP 218' },
  { from: 'Pikachu ex SSP 219', to: 'Pikachu exFA SSP 219' },
  { from: 'Latias ex SSP 220', to: 'Latias exFA SSP 220' },
  { from: 'Hydreigon ex SSP 223', to: 'Hydreigon exFA SSP 223' },
  { from: 'Archaludon ex SSP 224', to: 'Archaludon exFA SSP 224' },
  { from: 'Cyrano SSP 230', to: 'CyranoFA SSP 230' },
  { from: 'Lisia\'s Appeal SSP 234', to: 'Lisia\'s AppealFA SSP 234' },
  { from: 'Surfer SSP 235', to: 'SurferFA SSP 235' },
  { from: 'Milotic ex SSP 237', to: 'Milotic exSIR SSP 237' },
  { from: 'Pikachu ex SSP 238', to: 'Pikachu exSIR SSP 238' },
  { from: 'Latias ex SSP 239', to: 'Latias exSIR SSP 239' },
  { from: 'Hydreigon ex SSP 240', to: 'Hydreigon exSIR SSP 240' },
  { from: 'Archaludon ex SSP 241', to: 'Archaludon exSIR SSP 241' },
  { from: 'Lisia\'s Appeal SSP 246', to: 'Lisia\'s AppealSIR SSP 246' },
  { from: 'Pikachu ex SSP 247', to: 'Pikachu exUR SSP 247' },
  { from: 'Counter Gain SSP 249', to: 'Counter GainUR SSP 249' },

  //PRE FA
  { from: 'Professor\'s Research PRE 122', to: 'Professor\'s ResearchO PRE 122' },
  { from: 'Professor\'s Research PRE 123', to: 'Professor\'s ResearchE PRE 123' },
  { from: 'Professor\'s Research PRE 124', to: 'Professor\'s ResearchR PRE 124' },
  { from: 'Professor\'s Research PRE 125', to: 'Professor\'s ResearchS PRE 125' },
  { from: 'Amarys PRE 132', to: 'AmarysFA PRE 132' },
  { from: 'Atticus PRE 133', to: 'AtticusFA PRE 133' },
  { from: 'Atticus PRE 134', to: 'AtticusFA2 PRE 134' },
  { from: 'Eri PRE 136', to: 'EriFA PRE 136' },
  { from: 'Giacomo PRE 138', to: 'GiacomoFA PRE 138' },
  { from: 'Mela PRE 140', to: 'MelaFA PRE 140' },
  { from: 'Leafeon ex PRE 144', to: 'Leafeon exSAR PRE 144' },
  { from: 'Teal Mask Ogerpon ex PRE 144', to: 'Teal Mask Ogerpon exSAR PRE 144' },
  { from: 'Flareon ex PRE 146', to: 'Flareon exSAR PRE 146' },
  { from: 'Ceruledge ex PRE 147', to: 'Ceruledge exSAR PRE 147' },
  { from: 'Hearthflame Mask Ogerpon ex PRE 148', to: 'Hearthflame Mask Ogerpon exSAR PRE 148' },
  { from: 'Vaporeon ex PRE 149', to: 'Vaporeon exSAR PRE 149' },
  { from: 'Glaceon ex PRE 150', to: 'Glaceon exSAR PRE 150' },
  { from: 'Palafin ex PRE 151', to: 'Palafin exSAR PRE 151' },
  { from: 'Wellspring Mask Ogerpon ex PRE 152', to: 'Wellspring Mask Ogerpon exSAR PRE 152' },
  { from: 'Jolteon ex PRE 153', to: 'Jolteon exSAR PRE 153' },
  { from: 'Iron Hands ex PRE 154', to: 'Iron Hands exSAR PRE 154' },
  { from: 'Espeon ex PRE 155', to: 'Espeon exSAR PRE 155' },
  { from: 'Sylveon ex PRE 156', to: 'Sylveon exSAR PRE 156' },
  { from: 'Iron Valiant ex PRE 157', to: 'Iron Valiant exSAR PRE 157' },
  { from: 'Iron Crown ex PRE 158', to: 'Iron Crown exSAR PRE 158' },
  { from: 'Sandy Shocks ex PRE 159', to: 'Sandy Shocks exSAR PRE 159' },
  { from: 'Cornerstone Mask Ogerpon ex PRE 160', to: 'Cornerstone Mask Ogerpon exSAR PRE 160' },
  { from: 'Umbreon ex PRE 161', to: 'Umbreon exSAR PRE 161' },
  { from: 'Roaring Moon ex PRE 162', to: 'Roaring Moon exSAR PRE 162' },
  { from: 'Pecharunt ex PRE 163', to: 'Pecharunt exSAR PRE 163' },
  { from: 'Gholdengo ex PRE 164', to: 'Gholdengo exSAR PRE 164' },
  { from: 'Dragapult ex PRE 165', to: 'Dragapult exSAR PRE 165' },
  { from: 'Raging Bolt ex PRE 166', to: 'Raging Bolt exSAR PRE 166' },
  { from: 'Eevee ex PRE 167', to: 'Eevee exSAR PRE 167' },
  { from: 'Bloodmoon Ursaluna ex PRE 168', to: 'Bloodmoon Ursaluna exSAR PRE 168' },
  { from: 'Terapagos ex PRE 169', to: 'Terapagos exSAR PRE 169' },
  { from: 'Amarys PRE 170', to: 'AmarysSAR PRE 170' },
  { from: 'Crispin PRE 171', to: 'CrispinSAR PRE 171' },
  { from: 'Drayton PRE 172', to: 'DraytonSAR PRE 172' },
  { from: 'Janine\'s Secret Art PRE 173', to: 'Janine\'s Secret ArtSAR PRE 173' },
  { from: 'Kieran PRE 174', to: 'KieranSAR PRE 174' },
  { from: 'Lacey PRE 175', to: 'LaceySAR PRE 175' },
  { from: 'Iron Leaves ex PRE 176', to: 'Iron Leaves exUR PRE 176' },
  { from: 'Teal Mask Ogerpon ex PRE 177', to: 'Teal Mask Ogerpon exUR PRE 177' },
  { from: 'Walking Wake ex PRE 178', to: 'Walking Wake exUR PRE 178' },
  { from: 'Pikachu ex PRE 179', to: 'Pikachu exUR PRE 179' },
  { from: 'Terapagos ex PRE 180', to: 'Terapagos exUR PRE 180' },

  //SV9
  { from: 'Maractus SV9 101', to: 'MaractusIR SV9 101' },
  { from: 'Wailord SV9 103', to: 'WailordIR SV9 103' },
  { from: 'Iono\'s Kilowattrel SV9 104', to: 'Iono\'s KilowattrelIR SV9 104' },
  { from: 'Lillie\'s Ribombee SV9 105', to: 'Lillie\'s RibombeeIR SV9 105' },
  { from: 'Swinub SV9 106', to: 'SwinubIR SV9 106' },
  { from: 'Lycanroc SV9 107', to: 'LycanrocIR SV9 107' },
  { from: 'N\'s Zorua SV9 108', to: 'N\'s ZoruaIR SV9 108' },
  { from: 'N\'s Reshiram SV9 109', to: 'N\'s ReshiramIR SV9 109' },
  { from: 'Hop\'s Wooloo SV9 112', to: 'Hop\'s WoolooIR SV9 112' },
  { from: 'Volcanion ex SV9 113', to: 'Volcanion exFA SV9 113' },
  { from: 'Iono\'s Bellibolt ex SV9 114', to: 'Iono\'s Bellibolt exFA SV9 114' },
  { from: 'Lillie\'s Clefairy ex SV9 115', to: 'Lillie\'s Clefairy exFA SV9 115' },
  { from: 'Mamoswine ex SV9 116', to: 'Mamoswine exFA SV9 116' },
  { from: 'N\'s Zoroark ex SV9 117', to: 'N\'s Zoroark exFA SV9 117' },
  { from: 'Hop\'s Zacian ex SV9 118', to: 'Hop\'s Zacian exFA SV9 118' },
  { from: 'Salamence ex SV9 119', to: 'Salamence exFA SV9 119' },
  { from: 'Dudunsparce ex SV9 120', to: 'Dudunsparce exFA SV9 120' },
  { from: 'Iris\'s Fighting Spirit SV9 121', to: 'Iris\'s Fighting SpiritFA SV9 121' },
  { from: 'Ruffian SV9 122', to: 'RuffianFA SV9 122' },
  { from: 'Brock\'s Recruitment SV9 123', to: 'Brock\'s RecruitmentFA SV9 123' },
  { from: 'Volcanion ex SV9 124', to: 'Volcanion exSIR SV9 124' },
  { from: 'Iono\'s Bellibolt ex SV9 125', to: 'Iono\'s Bellibolt exSIR SV9 125' },
  { from: 'Lillie\'s Clefairy ex SV9 126', to: 'Lillie\'s Clefairy exSIR SV9 126' },
  { from: 'N\'s Zoroark ex SV9 127', to: 'N\'s Zoroark exSIR SV9 127' },
  { from: 'Hop\'s Zacian ex SV9 128', to: 'Hop\'s Zacian exSIR SV9 128' },
  { from: 'Salamence ex SV9 129', to: 'Salamence exSIR SV9 129' },
  { from: 'Iono\'s Bellibolt ex SV9 130', to: 'Iono\'s Bellibolt exUR SV9 130' },
  { from: 'N\'s Zoroark ex SV9 131', to: 'N\'s Zoroark exUR SV9 131' },
  { from: 'Spike Energy SV9 132', to: 'Spike EnergyUR SV9 132' },

  //SVOM
  { from: 'Marnie\'s Morpeko SVOM 20', to: 'Marnie\'s MorpekoIR SVOM 20' },

  //SVOD
  { from: 'Steven\'s Beldum SVOD 19', to: 'Steven\'s BeldumIR SVOD 19' },

  //SV9a
  { from: 'Ethan\'s Ho-Oh ex SV9a 86', to: 'Ethan\'s Ho-Oh exSIR SV9a 86' },
  { from: 'Cynthia\'s Roserade SV9a 65', to: 'Cynthia\'s RoseradeIR SV9a 65' },
];

export const exportReplacements = [

  //Energy
  { from: 'Grass Energy2 SVE 9', to: 'Grass Energy SVE 9' },
  { from: 'Fire Energy2 SVE 10', to: 'Fire Energy SVE 10' },
  { from: 'Water Energy2 SVE 11', to: 'Water Energy SVE 11' },
  { from: 'Lightning Energy2 SVE 12', to: 'Lightning Energy SVE 12' },
  { from: 'Psychic Energy2 SVE 13', to: 'Psychic Energy SVE 13' },
  { from: 'Fighting Energy2 SVE 14', to: 'Fighting Energy SVE 14' },
  { from: 'Darkness Energy2 SVE 15', to: 'Darkness Energy SVE 15' },
  { from: 'Metal Energy2 SVE 16', to: 'Metal Energy SVE 16' },

  //BS
  { from: 'Pokémon Breeder BS 76', to: 'Pokemon Breeder BS 76' },
  { from: 'Pokémon Trader BS 77', to: 'Pokemon Trader BS 77' },

  //SUM
  { from: 'Rotom DexSR SM 159', to: 'Rotom Dex SUM 159' },

  //SHF
  { from: 'Snom SHFSV SV33', to: 'Snom SHF SV33' },

  //STS
  { from: 'Pokemon Ranger STS 104', to: 'Pokémon Ranger STS 104' },

  //VIV
  { from: 'Talonflame VFA VIV 168', to: 'Talonflame V VIV 168' },

  //PGO
  { from: 'PokeStop PGO 68', to: 'PokéStop PGO 68' },

  //BRS
  { from: 'Ultra BallHR BRS 186', to: 'Ultra Ball BRS 186' },

  //ASR
  { from: 'Hisuian Qwilfish2 ASR 89', to: 'Hisuian Qwilfish ASR 89' },

  //SVI
  { from: 'Pokegear SVI 186', to: 'Pokégear 3.0 SVI 186' },
  { from: 'Pokemon Catcher SVI 187', to: 'Pokémon Catcher SVI 187' },
  { from: 'Riolu2 SVI 113', to: 'Riolu SVI 113' },

  //SVI FA
  { from: 'ArmarougeIR SVI 203', to: 'Armarouge SVI 203' },
  { from: 'SlowpokeIR SVI 204', to: 'Slowpoke SVI 204' },
  { from: 'PawmotIR SVI 209', to: 'Pawmot SVI 209' },
  { from: 'ArvenFA SVI 235', to: 'Arven SVI 235' },
  { from: 'ArvenSIR SVI 249', to: 'Arven SVI 249' },
  { from: 'Fighting EnergyHR SVI 258', to: 'Fighting Energy SVI 258' },
  { from: 'Lightning EnergyHR SVI 257', to: 'Lightning Energy SVI 257' },
  { from: 'Gardevoir exFA SVI 228', to: 'Gardevoir ex SVI 228' },
  { from: 'Gardevoir exSIR SVI 245', to: 'Gardevoir ex SVI 245' },
  { from: 'JacqFA SVI 236', to: 'Jacq SVI 236' },
  { from: 'JacqSIR SVI 250', to: 'Jacq SVI 250' },
  { from: 'KatyFA SVI 237', to: 'Katy SVI 237' },
  { from: 'Koraidon exFA SVI 231', to: 'Koraidon ex SVI 231' },
  { from: 'Koraidon exSIR SVI 247', to: 'Koraidon ex SVI 247' },
  { from: 'Koraidon exHR SVI 254', to: 'Koraidon ex SVI 254' },
  { from: 'Magnezone exFA SVI 226', to: 'Magnezone ex SVI 226' },
  { from: 'Miraidon exFA SVI 227', to: 'Miraidon ex SVI 227' },
  { from: 'Miraidon exSIR SVI 244', to: 'Miraidon ex SVI 244' },
  { from: 'Miraidon exHR SVI 253', to: 'Miraidon ex SVI 253' },
  { from: 'MiriamFA SVI 238', to: 'Miriam SVI 238' },
  { from: 'MiriamSIR SVI 251', to: 'Miriam SVI 251' },
  { from: 'Nest BallHR SVI 255', to: 'Nest Ball SVI 255' },
  { from: 'PennyFA SVI 239', to: 'Penny SVI 239' },
  { from: 'PennySIR SVI 252', to: 'Penny SVI 252' },
  { from: "Professor's ResearchFA1 SVI 242", to: "Professor's Research SVI 240" },
  { from: "Professor's ResearchFA2 SVI 241", to: "Professor's Research SVI 241" },
  { from: 'RaltsIR SVI 211', to: 'Ralts SVI 211' },
  { from: 'KirliaIR SVI 212', to: 'Kirlia SVI 212' },
  { from: 'Rare CandyHR SVI 256', to: 'Rare Candy SVI 256' },
  { from: 'SkwovetIR SVI 222', to: 'Skwovet SVI 222' },
  { from: 'Team Star GruntFA SVI 242', to: 'Team Star Grunt SVI 242' },

  //SVP
  { from: 'CharmanderIR SVP 44', to: 'Charmander SVP 44' },
  { from: 'Iron BundleIR SVP 66', to: 'Iron Bundle SVP 66' },
  { from: 'Charizard ex2 SVP 74', to: 'Charizard ex SVP 74' },
  { from: 'Meowscarada exFA SVP 78', to: 'Meowscarada ex SVP 78' },
  { from: 'Skeledirge exFA SVP 81', to: 'Skeledirge ex SVP 81' },
  { from: 'PecharuntIR SVP 129', to: 'Pecharunt SVP 129' },
  { from: 'Miraidon ex2 SVP 142', to: 'Miraidon ex SVP 142' },
  { from: 'Charizard ex3 SVP 161', to: 'Charizard ex SVP 161' },

  //PAL
  { from: 'Frigibax PAL1 57 ', to: 'Frigibax PAL 57' },
  { from: 'Frigibax PAL2 58 ', to: 'Frigibax PAL 58' },
  //PAL FA
  { from: 'FrigibaxIR PAL 208', to: 'Frigibax PAL 208' },
  { from: 'ArctibaxIR PAL 209', to: 'Arctibax PAL 209' },
  { from: 'BaxcaliburIR PAL 210', to: 'Baxcalibur PAL 210' },
  { from: 'TinkatinkIR PAL 216', to: 'Tinkatink PAL 216' },
  { from: 'TinkatuffIR PAL 217', to: 'Tinkatuff PAL 217' },
  { from: 'FlamigoIR PAL 227', to: 'Flamigo PAL 227' },
  { from: 'Meowscarada exFA PAL 231', to: 'Meowscarada ex PAL 231' },
  { from: 'Wo-Chien exFA PAL 232', to: 'Wo-Chien ex PAL 232' },
  { from: 'Chi-Yu exFA PAL 234', to: 'Chi-Yu ex PAL 234' },
  { from: 'Chien-Pao exFA PAL 236', to: 'Chien-Pao ex PAL 236' },
  { from: 'Tinkaton exFA PAL 240', to: 'Tinkaton ex PAL 240' },
  { from: 'Ting-Lu exFA PAL 243', to: 'Ting-Lu ex PAL 243' },
  { from: 'Noivern exFA PAL 246', to: 'Noivern ex PAL 246' },
  { from: 'Squawkabilly exFA PAL 247', to: 'Squawkabilly ex PAL 247' },
  { from: 'Boss\'s OrdersFA PAL 248', to: 'Boss\'s Orders PAL 248' },
  { from: 'ClavellFA PAL 249', to: 'Clavell PAL 249' },
  { from: 'GiacomoFA PAL 252', to: 'Giacomo PAL 252' },
  { from: 'GrushaFA PAL 253', to: 'Grusha PAL 253' },
  { from: 'IonoFA PAL 254', to: 'Iono PAL 254' },
  { from: 'Meowscarada exSIR PAL 256', to: 'Meowscarada ex PAL 256' },
  { from: 'Wo-Chien exSIR PAL 257', to: 'Wo-Chien ex PAL 257' },
  { from: 'Chi-Yu exSIR PAL 259', to: 'Chi-Yu ex PAL 259' },
  { from: 'Chien-Pao exSIR PAL 261', to: 'Chien-Pao ex PAL 261' },
  { from: 'Tinkaton exSIR PAL 262', to: 'Tinkaton ex PAL 262' },
  { from: 'Ting-Lu exSIR PAL 263', to: 'Ting-Lu ex PAL 263' },
  { from: 'Squawkabilly exSIR PAL 264', to: 'Squawkabilly ex PAL 264' },
  { from: 'Boss\'s OrdersSIR PAL 265', to: 'Boss\'s Orders PAL 265' },
  { from: 'GiacomoSIR PAL 267', to: 'Giacomo PAL 267' },
  { from: 'GrushaSIR PAL 268', to: 'Grusha PAL 268' },
  { from: 'IonoSIR PAL 269', to: 'Iono PAL 269' },
  { from: 'Meowscarada exHR PAL 271', to: 'Meowscarada ex PAL 271' },
  { from: 'Chien-Pao exHR PAL 274', to: 'Chien-Pao ex PAL 274' },
  { from: 'Ting-Lu exHR PAL 275', to: 'Ting-Lu ex PAL 275' },
  { from: 'Super RodHR PAL 276', to: 'Super Rod PAL 276' },
  { from: 'Superior Energy RetrievalHR PAL 277', to: 'Superior Energy Retrieval PAL 277' },

  //151 FA
  { from: 'BulbasaurIR MEW 166', to: 'Bulbasaur MEW 166' },
  { from: 'IvysaurIR MEW 167', to: 'Ivysaur MEW 167' },
  { from: 'CharmanderIR MEW 168', to: 'Charmander MEW 168' },
  { from: 'CharmeleonIR MEW 169', to: 'Charmeleon MEW 169' },
  { from: 'SquirtleIR MEW 170', to: 'Squirtle MEW 170' },
  { from: 'WartortleIR MEW 171', to: 'Wartortle MEW 171' },
  { from: 'NidokingIR MEW 174', to: 'Nidoking MEW 174' },
  { from: 'Venusaur exFA MEW 182', to: 'Venusaur ex MEW 182' },
  { from: 'Charizard exFA MEW 183', to: 'Charizard ex MEW 183' },
  { from: 'Blastoise exFA MEW 184', to: 'Blastoise ex MEW 184' },
  { from: 'Arbok exFA MEW 185', to: 'Arbok ex MEW 185' },
  { from: 'Alakazam exFA MEW 188', to: 'Alakazam ex MEW 188' },
  { from: 'Kangaskhan exFA MEW 190', to: 'Kangaskhan ex MEW 190' },
  { from: 'Zapdos exFA MEW 192', to: 'Zapdos ex MEW 192' },
  { from: 'Mew exFA MEW 193', to: 'Mew ex MEW 193' },
  { from: 'Erika\'s InvitationFA MEW 196', to: 'Erika\'s Invitation MEW 196' },
  { from: 'Giovanni\'s CharismaFA MEW 197', to: 'Giovanni\'s Charisma MEW 197' },
  { from: 'Venusaur exSIR MEW 198', to: 'Venusaur ex MEW 198' },
  { from: 'Charizard exSIR MEW 199', to: 'Charizard ex MEW 199' },
  { from: 'Blastoise exSIR MEW 200', to: 'Blastoise ex MEW 200' },
  { from: 'Alakazam exSIR MEW 201', to: 'Alakazam ex MEW 201' },
  { from: 'Zapdos exSIR MEW 202', to: 'Zapdos ex MEW 202' },
  { from: 'Erika\'s InvitationSIR MEW 203', to: 'Erika\'s Invitation MEW 203' },
  { from: 'Giovanni\'s CharismaSIR MEW 204', to: 'Giovanni\'s Charisma MEW 204' },
  { from: 'Mew exHR MEW 205', to: 'Mew ex MEW 205' },
  { from: 'SwitchHR MEW 206', to: 'Switch MEW 206' },
  { from: 'Psychic Energy MEW 207', to: 'Psychic Energy MEW 207' },

  //PAR
  { from: 'Toedscool PAL2 57 ', to: 'Toedscool PAL 57' },
  { from: 'Gimmighoul2 PAR 88', to: 'Gimmighoul PAR 88' },
  //PAR FA
  { from: 'ToedscruelIR PAR 185', to: 'Toedscruel PAR 185' },
  { from: 'MagbyIR PAR 186', to: 'Magby PAR 186' },
  { from: 'IronMothIR PAR 187', to: 'Iron Moth PAR 187' },
  { from: 'SnoruntIR PAR 188', to: 'Snorunt PAR 188' },
  { from: 'MantykeIR PAR 189', to: 'Mantyke PAR 189' },
  { from: 'VanillishIR PAR 190', to: 'Vanillish PAR 190' },
  { from: 'BlitzleIR PAR 195', to: 'Blitzle PAR 195' },
  { from: 'JoltikIR PAR 196', to: 'Joltik PAR 196' },
  { from: 'GimmighoulIR PAR 198', to: 'Gimmighoul PAR 198' },
  { from: 'GroudonIR PAR 199', to: 'Groudon PAR 199' },
  { from: 'MiniorIR PAR 201', to: 'Minior PAR 201' },
  { from: 'GarganacIR PAR 202', to: 'Garganacl PAR 202' },
  { from: 'SlitherWingIR PAR 203', to: 'Slither Wing PAR 203' },
  { from: 'GarbodorIR PAR 204', to: 'Garbodor PAR 204' },
  { from: 'YveltalIR PAR 205', to: 'Yveltal PAR 205' },
  { from: 'MorpekoIR PAR 206', to: 'Morpeko PAR 206' },
  { from: 'BruteBonnetIR PAR 207', to: 'Brute Bonnet PAR 207' },
  { from: 'FerrothorIR PAR 209', to: 'Ferrothorn PAR 209' },
  { from: 'AegislashIR PAR 210', to: 'Aegislash PAR 210' },
  { from: 'SwabluIR PAR 213', to: 'Swablu PAR 213' },
  { from: 'PorygonZIR PAR 214', to: 'Porygon-Z PAR 214' },
  { from: 'CyclizarIR PAR 215', to: 'Cyclizar PAR 215' },
  { from: 'IronJugulisIR PAR 216', to: 'Iron Jugulis PAR 216' },
  { from: 'FroslassexFA PAR 217', to: 'Froslass ex PAR 217' },
  { from: 'GarchompexFA PAR 219', to: 'Garchomp ex PAR 219' },
  { from: 'TsareenaexFA PAR 220', to: 'Tsareena ex PAR 220' },
  { from: 'TapuKokoexFA PAR 222', to: 'Tapu Koko ex PAR 222' },
  { from: 'IronHandsexFA PAR 223', to: 'Iron Hands ex PAR 223' },
  { from: 'IronValiantexFA PAR 225', to: 'Iron Valiant ex PAR 225' },
  { from: 'HoopaexFA PAR 226', to: 'Hoopa ex PAR 226' },
  { from: 'SandyShocksexFA PAR 228', to: 'Sandy Shocks ex PAR 228' },
  { from: 'RoaringMoonexFA PAR 229', to: 'Roaring Moon ex PAR 229' },
  { from: 'GholdengoexFA PAR 231', to: 'Gholdengo ex PAR 231' },
  { from: 'BombirdierexFA PAR 234', to: 'Bombirdier ex PAR 234' },
  { from: 'MelaFA PAR 236', to: 'Mela PAR 236' },
  { from: 'ProfessorSadasVitalityFA PAR 239', to: 'Professor Sada\'s Vitality PAR 239' },
  { from: 'ProfessorTurosScenarioFA PAR 240', to: 'Professor Turo\'s Scenario PAR 240' },
  { from: 'TulipFA PAR 244', to: 'Tulip PAR 244' },
  { from: 'GarchompexSIR PAR 245', to: 'Garchomp ex PAR 245' },
  { from: 'TapuKokoexSIR PAR 247', to: 'Tapu Koko ex PAR 247' },
  { from: 'IronHandsexSIR PAR 248', to: 'Iron Hands ex PAR 248' },
  { from: 'IronValiantexSIR PAR 249', to: 'Iron Valiant ex PAR 249' },
  { from: 'SandyShocksexSIR PAR 250', to: 'Sandy Shocks ex PAR 250' },
  { from: 'RoaringMoonexSIR PAR 251', to: 'Roaring Moon ex PAR 251' },
  { from: 'GholdengoexSIR PAR 252', to: 'Gholdengo ex PAR 252' },
  { from: 'MelaSIR PAR 254', to: 'Mela PAR 254' },
  { from: 'ProfessorSadasVitalitySIR PAR 256', to: 'Professor Sada\'s Vitality PAR 256' },
  { from: 'ProfessorTurosScenarioSIR PAR 257', to: 'Professor Turo\'s Scenario PAR 257' },
  { from: 'TulipSIR PAR 259', to: 'Tulip PAR 259' },
  { from: 'GarchompexHR PAR 260', to: 'Garchomp ex PAR 260' },
  { from: 'IronValiantexHR PAR 261', to: 'Iron Valiant ex PAR 261' },
  { from: 'RoaringMoonexHR PAR 262', to: 'Roaring Moon ex PAR 262' },
  { from: 'BeachCourtHR PAR 263', to: 'Beach Court PAR 263' },
  { from: 'CounterCatcherHR PAR 264', to: 'Counter Catcher PAR 264' },
  { from: 'LuxuriousCapeHR PAR 265', to: 'Luxurious Cape PAR 265' },
  { from: 'ReversalEnergyHR PAR 266', to: 'Reversal Energy PAR 266' },

  //PAF Shiny Vault
  { from: 'CharmanderSV PAF 109', to: 'Charmander PAF 109' },
  { from: 'CharmeleonSV PAF 110', to: 'Charmeleon PAF 110' },
  { from: 'FrigibaxSV PAF 128', to: 'Frigibax PAF 128' },
  { from: 'MimeJrSV PAF 157', to: 'Mime Jr. PAF 157' },
  { from: 'Espathra exSV PAF 214', to: 'Espathra exSV PAF 214' },
  { from: 'WugtrioFA PAF 224', to: 'Wugtrio PAF 224' },
  { from: 'PalafinFA PAF 225', to: 'Palafin PAF 225' },
  { from: 'PawmiFA PAF 226', to: 'Pawmi PAF 226' },
  { from: 'CliveFA PAF 227', to: 'Clive PAF 227' },
  { from: 'NemonaFA PAF 229', to: 'Nemona PAF 229' },
  { from: 'Paldean StudentFA PAF 230', to: 'Paldean Student PAF 230' },
  { from: 'Paldean StudentFA2 PAF 231', to: 'Paldean Student PAF 231' },
  { from: 'Mew exSIR PAF 232', to: 'Mew exSIR PAF 232' },
  { from: 'Gardevoir exSIR PAF 233', to: 'Gardevoir ex PAF 233' },
  { from: 'Charizard exSIR PAF 234', to: 'Charizard ex PAF 234' },
  { from: 'ArvenSIR PAF 236', to: 'Arven PAF 235' },
  { from: 'CliveSIR PAF 236', to: 'Clive PAF 236' },
  { from: 'IonoSIR PAF 237', to: 'Iono PAF 237' },
  { from: 'NemonaSIR PAF 238', to: 'Nemona PAF 238' },
  { from: 'PennySIR PAF 236', to: 'Penny PAF 239' },

  //TEF
  //TEF FA
  { from: 'GrotleIR TEF 164', to: 'Grotle TEF 164' },
  { from: 'CharjabugIR TEF 169', to: 'Charjabug TEF 169' },
  { from: 'ReuniclusIR TEF 171', to: 'Reuniclus TEF 171' },
  { from: 'RelicanthIR TEF 173', to: 'Relicanth TEF 173' },
  { from: 'GastlyIR TEF 177', to: 'Gastly TEF 177' },
  { from: 'MetagrossIR TEF 178', to: 'Metagross TEF 178' },
  { from: 'ChatotIR TEF 181', to: 'Chatot TEF 181' },
  { from: 'MinccinoIR TEF 182', to: 'Minccino TEF 182' },
  { from: 'CinccinoIR TEF 183', to: 'Cinccino TEF 183' },
  { from: 'TorterraexFA TEF 185', to: 'Torterra ex TEF 185' },
  { from: 'IronLeavesexFA TEF 186', to: 'Iron Leaves ex TEF 186' },
  { from: 'GougingFireexFA TEF 188', to: 'Gouging Fire ex TEF 188' },
  { from: 'WalkingWakeexFA TEF 189', to: 'Walking Wake ex TEF 189' },
  { from: 'IronCrownexFA TEF 191', to: 'Iron Crown ex TEF 191' },
  { from: 'GengarexFA TEF 193', to: 'Gengar ex TEF 193' },
  { from: 'RagingBoltexFA TEF 196', to: 'Raging Bolt ex TEF 196' },
  { from: 'BiancasDevotionFA TEF 197', to: 'Bianca\'s Devotion TEF 197' },
  { from: 'CiphermaniacsCodebreakingFA TEF 198', to: 'Ciphermaniac\'s Codebreaking TEF 198' },
  { from: 'EriFA TEF 199', to: 'Eri TEF 199' },
  { from: 'ExplorersGuidanceFA TEF 200', to: 'Explorer\'s Guidance TEF 200' },
  { from: 'MortysConvictionFA TEF 201', to: 'Morty\'s Conviction TEF 201' },
  { from: 'SalvatoreFA TEF 202', to: 'Salvatore TEF 202' },
  { from: 'IronLeavesexSIR TEF 203', to: 'Iron Leaves ex TEF 203' },
  { from: 'GougingFireexSIR TEF 204', to: 'Gouging Fire ex TEF 204' },
  { from: 'WalkingWakeexSIR TEF 205', to: 'Walking Wake ex TEF 205' },
  { from: 'IronCrownexSIR TEF 206', to: 'Iron Crown ex TEF 206' },
  { from: 'RagingBoltexSIR TEF 208', to: 'Raging Bolt ex TEF 208' },
  { from: 'BiancasDevotionSIR TEF 209', to: 'Bianca\'s Devotion TEF 209' },
  { from: 'EriSIR TEF 210', to: 'Eri TEF 210' },
  { from: 'MortysConvictionSIR TEF 211', to: 'Morty\'s Conviction TEF 211' },
  { from: 'SalvatoreSIR TEF 212', to: 'Salvatore TEF 212' },
  { from: 'IronLeavesexHR TEF 213', to: 'Iron Leaves ex TEF 213' },
  { from: 'GougingFireexHR TEF 214', to: 'Gouging Fire ex TEF 214' },
  { from: 'WalkingWakeexHR TEF 215', to: 'Walking Wake ex TEF 215' },
  { from: 'IronCrownexHR TEF 216', to: 'Iron Crown ex TEF 216' },
  { from: 'RagingBoltexHR TEF 218', to: 'Raging Bolt ex TEF 218' },

  //TWM
  { from: 'Applin TWM1 17', to: 'Applin TWM 17' },
  { from: 'Applin TWM2 126', to: 'Applin TWM 126' },
  { from: 'Dipplin TWM1 18', to: 'Dipplin TWM 18' },
  { from: 'Dipplin TWM2 127', to: 'Dipplin TWM 127' },
  //TWM FA
  { from: 'DipplinIR TWM 170', to: 'Dipplin TWM 170' },
  { from: 'PoltchageistIR TWM 171', to: 'Poltchageist TWM 171' },
  { from: 'InfernapeIR TWM 173', to: 'Infernape TWM 173' },
  { from: 'FroslassIR TWM 174', to: 'Froslass TWM 174' },
  { from: 'PhioneIR TWM 175', to: 'Phione TWM 175' },
  { from: 'HisuianGrowlitheIR TWM 181', to: 'Hisuian Growlithe TWM 181' },
  { from: 'TimburrIR TWM 183', to: 'Timburr TWM 183' },
  { from: 'LaironIR TWM 184', to: 'Lairon TWM 184' },
  { from: 'ApplinIR TWM 185', to: 'Applin TWM 185' },
  { from: 'TatsugiriIR TWM 186', to: 'Tatsugiri TWM 186' },
  { from: 'ChanseyIR TWM 187', to: 'Chansey TWM 187' },
  { from: 'EeveeIR TWM 188', to: 'Eevee TWM 188' },
  { from: 'Sinistcha exFA TWM 189', to: 'Sinistcha ex TWM 189' },
  { from: 'Teal Mask Ogerpon exFA TWM 190', to: 'Teal Mask Ogerpon ex TWM 190' },
  { from: 'Magcargo exFA TWM 191', to: 'Magcargo ex TWM 191' },
  { from: 'Hearthflame Mask Ogerpon exFA TWM 192', to: 'Hearthflame Mask Ogerpon ex TWM 192' },
  { from: 'Palafin exFA TWM 193', to: 'Palafin ex TWM 193' },
  { from: 'Wellspring Mask Ogerpon exFA TWM 194', to: 'Wellspring Mask Ogerpon ex TWM 194' },
  { from: 'Luxray exFA TWM 195', to: 'Luxray ex TWM 195' },
  { from: 'Iron Thorns exFA TWM 196', to: 'Iron Thorns ex TWM 196' },
  { from: 'Scream Tail exFA TWM 197', to: 'Scream Tail ex TWM 197' },
  { from: 'Greninja exFA TWM 198', to: 'Greninja ex TWM 198' },
  { from: 'Cornerstone Mask Ogerpon exFA TWM 199', to: 'Cornerstone Mask Ogerpon ex TWM 199' },
  { from: 'Dragapult exFA TWM 200', to: 'Dragapult ex TWM 200' },
  { from: 'Blissey exFA TWM 201', to: 'Blissey ex TWM 201' },
  { from: 'Bloodmoon Ursaluna exFA TWM 202', to: 'Bloodmoon Ursaluna ex TWM 202' },
  { from: 'CaretakerFA TWM 203', to: 'Caretaker TWM 203' },
  { from: 'CarmineFA TWM 204', to: 'Carmine TWM 204' },
  { from: 'HasselFA TWM 205', to: 'Hassel TWM 205' },
  { from: 'KieranFA TWM 206', to: 'Kieran TWM 206' },
  { from: 'Lana\'s AidFA TWM 207', to: 'Lana\'s Aid TWM 207' },
  { from: 'PerrinFA TWM 209', to: 'Perrin TWM 209' },
  { from: 'Sinistcha exSIR TWM 210', to: 'Sinistcha ex TWM 210' },
  { from: 'Teal Mask Ogerpon exSIR TWM 211', to: 'Teal Mask Ogerpon ex TWM 211' },
  { from: 'Hearthflame Mask Ogerpon exSIR TWM 212', to: 'Hearthflame Mask Ogerpon ex TWM 212' },
  { from: 'Wellspring Mask Ogerpon exSIR TWM 213', to: 'Wellspring Mask Ogerpon ex TWM 213' },
  { from: 'Greninja exSIR TWM 214', to: 'Greninja ex TWM 214' },
  { from: 'Cornerstone Mask Ogerpon exSIR TWM 215', to: 'Cornerstone Mask Ogerpon ex TWM 215' },
  { from: 'Bloodmoon Ursaluna exSIR TWM 216', to: 'Bloodmoon Ursaluna ex TWM 216' },
  { from: 'CarmineSIR TWM 217', to: 'Carmine TWM 217' },
  { from: 'KieranSIR TWM 218', to: 'Kieran TWM 218' },
  { from: 'Lana\'s AidSIR TWM 219', to: 'Lana\'s Aid TWM 219' },
  { from: 'PerrinSIR TWM 220', to: 'Perrin TWM 220' },
  { from: 'Teal Mask Ogerpon exHR TWM 221', to: 'Teal Mask Ogerpon ex TWM 221' },
  { from: 'Bloodmoon Ursaluna exHR TWM 222', to: 'Bloodmoon Ursaluna ex TWM 222' },
  { from: 'Buddy-Buddy PoffinHR TWM 223', to: 'Buddy-Buddy Poffin TWM 223' },
  { from: 'Enhanced HammerHR TWM 224', to: 'Enhanced Hammer TWM 224' },
  { from: 'Rescue BoardHR TWM 225', to: 'Rescue Board TWM 225' },

  //SFA
  { from: 'Bloodmoon Ursaluna SV6a 25', to: 'Bloodmoon Ursaluna SFA 25' },
  { from: 'Janine\'s Secret Technique SFA 59', to: 'Janine\'s Secret Art SFA 59' },
  { from: 'PokéVital A SFA 62', to: 'Poké Vital A SFA 62' },
  { from: 'Tapu BuluIR SFA 65', to: 'Tapu Bulu SFA 65' },
  { from: 'HoundoomIR SFA 66', to: 'Houndoom SFA 66' },
  { from: 'HorseaIR SFA 67', to: 'Horsea SFA 67' },
  { from: 'DuskullIR SFA 68', to: 'Duskull SFA 68' },
  { from: 'DusclopsIR SFA 69', to: 'Dusclops SFA 69' },
  { from: 'DusknoirIR SFA 70', to: 'Dusknoir SFA 70' },
  { from: 'CresseliaIR SFA 71', to: 'Cresselia SFA 71' },
  { from: 'ZoruaIR SFA 75', to: 'Zorua SFA 75' },
  { from: 'CufantIR SFA 76', to: 'Cufant SFA 76' },
  { from: 'FraxureIR SFA 77', to: 'Fraxure SFA 77' },
  { from: 'Kingdra exFA SFA 80', to: 'Kingdra ex SFA 80' },
  { from: 'Revavroom exFA SFA 81', to: 'Revavroom ex SFA 81' },
  { from: 'Okidogi exFA SFA 82', to: 'Okidogi ex SFA 82' },
  { from: 'Munkidori exFA SFA 83', to: 'Munkidori ex SFA 83' },
  { from: 'Fezandipiti exFA SFA 84', to: 'Fezandipiti ex SFA 84' },
  { from: 'Pecharunt exFA SFA 85', to: 'Pecharunt ex SFA 85' },
  { from: 'CassiopeiaFA SFA 86', to: 'Cassiopeia SFA 86' },
  { from: 'Colress\'s TenacityFA SFA 87', to: 'Colress\'s Tenacity SFA 87' },
  { from: 'Janine\'s Secret ArtFA SFA 88', to: 'Janine\'s Secret Art SFA 88' },
  { from: 'Xerosic\'s MachinationsFA SFA 89', to: 'Xerosic\'s Machinations SFA 89' },
  { from: 'Okidogi exSIR SFA 90', to: 'Okidogi ex SFA 90' },
  { from: 'Munkidori exSIR SFA 91', to: 'Munkidori ex SFA 91' },
  { from: 'Fezandipiti exSIR SFA 92', to: 'Fezandipiti ex SFA 92' },
  { from: 'Pecharunt exSIR SFA 93', to: 'Pecharunt ex SFA 93' },
  { from: 'CassiopeiaSIR SFA 94', to: 'Cassiopeia SFA 94' },
  { from: 'Pecharunt exUR SFA 95', to: 'Pecharunt ex SFA 95' },
  { from: 'PowerglassUR SFA 97', to: 'Powerglass SFA 97' },

  //SCR FA
  { from: 'BulbasaurIR SCR 143', to: 'Bulbasaur SCR 143' },
  { from: 'RabootIR SCR 147', to: 'Raboot SCR 147' },
  { from: 'SquirtleIR SCR 148', to: 'Squirtle SCR 148' },
  { from: 'JoltikIR SCR 150', to: 'Joltik SCR 150' },
  { from: 'ZeraoraIR SCR 151', to: 'Zeraora SCR 151' },
  { from: 'MilceryIR SCR 152', to: 'Milcery SCR 152' },
  { from: 'MedititeIR SCR 153', to: 'Meditite SCR 153' },
  { from: 'ArchaludonIR SCR 155', to: 'Archaludon SCR 155' },
  { from: 'Hydrapple exFA SCR 156', to: 'Hydrapple ex SCR 156' },
  { from: 'Cinderace exFA SCR 157', to: 'Cinderace ex SCR 157' },
  { from: 'Lapras exFA SCR 158', to: 'Lapras ex SCR 158' },
  { from: 'Galvantula exFA SCR 159', to: 'Galvantula ex SCR 159' },
  { from: 'Medicham exFA SCR 161', to: 'Medicham ex SCR 161' },
  { from: 'Orthworm exFA SCR 162', to: 'Orthworm ex SCR 162' },
  { from: 'BriarFA SCR 163', to: 'Briar SCR 163' },
  { from: 'CrispinFA SCR 164', to: 'Crispin SCR 164' },
  { from: 'KofuFA SCR 165', to: 'Kofu SCR 165' },
  { from: 'LaceyFA SCR 166', to: 'Lacey SCR 166' },
  { from: 'Hydrapple exSIR SCR 167', to: 'Hydrapple ex SCR 167' },
  { from: 'Galvantula exSIR SCR 168', to: 'Galvantula ex SCR 168' },
  { from: 'Terapagos exSIR SCR 170', to: 'Terapagos ex SCR 170' },
  { from: 'BriarSIR SCR 171', to: 'Briar SCR 171' },
  { from: 'LaceySIR SCR 172', to: 'Lacey SCR 172' },
  { from: 'Terapagos exHR SCR 173', to: 'Terapagos ex SCR 173' },
  { from: 'Area Zero UnderdepthsHR SCR 174', to: 'Area Zero Underdepths SCR 174' },

  //SSP FA
  { from: 'LarvestaIR SSP 196', to: 'Larvesta SSP 196' },
  { from: 'FeebasIR SSP 198', to: 'Feebas SSP 198' },
  { from: 'Milotic exFA SSP 218', to: 'Milotic ex SSP 218' },
  { from: 'Pikachu exFA SSP 219', to: 'Pikachu ex SSP 219' },
  { from: 'Latias exFA SSP 220', to: 'Latias ex SSP 220' },
  { from: 'Hydreigon exFA SSP 223', to: 'Hydreigon ex SSP 223' },
  { from: 'Archaludon exFA SSP 224', to: 'Archaludon ex SSP 224' },
  { from: 'CyranoFA SSP 230', to: 'Cyrano SSP 230' },
  { from: 'Lisia\'s AppealFA SSP 234', to: 'Lisia\'s Appeal SSP 234' },
  { from: 'SurferFA SSP 235', to: 'Surfer SSP 235' },
  { from: 'Milotic exSIR SSP 237', to: 'Milotic ex SSP 237' },
  { from: 'Pikachu exSIR SSP 238', to: 'Pikachu ex SSP 238' },
  { from: 'Latias exSIR SSP 239', to: 'Latias ex SSP 239' },
  { from: 'Hydreigon exSIR SSP 240', to: 'Hydreigon ex SSP 240' },
  { from: 'Archaludon exSIR SSP 241', to: 'Archaludon ex SSP 241' },
  { from: 'Lisia\'s AppealSIR SSP 246', to: 'Lisia\'s Appeal SSP 246' },
  { from: 'Pikachu exUR SSP 247', to: 'Pikachu ex SSP 247' },
  { from: 'Counter GainUR SSP 249', to: 'Counter Gain SSP 249' },

  //PRE Reprints & FA
  { from: 'Professor\'s ResearchO PRE 122', to: 'Professor\'s Research PRE 122' },
  { from: 'Professor\'s ResearchE PRE 123', to: 'Professor\'s Research PRE 123' },
  { from: 'Professor\'s ResearchR PRE 124', to: 'Professor\'s Research PRE 124' },
  { from: 'Professor\'s ResearchS PRE 125', to: 'Professor\'s Research PRE 125' },
  { from: 'AmarysFA PRE 132', to: 'Amarys PRE 132' },
  { from: 'AtticusFA PRE 133', to: 'Atticus PRE 133' },
  { from: 'AtticusFA2 PRE 134', to: 'Atticus PRE 134' },
  { from: 'EriFA PRE 136', to: 'Eri PRE 136' },
  { from: 'GiacomoFA PRE 138', to: 'Giacomo PRE 138' },
  { from: 'MelaFA PRE 140', to: 'Mela PRE 140' },
  { from: 'Leafeon exSAR PRE 144', to: 'Leafeon ex PRE 144' },
  { from: 'Teal Mask Ogerpon exSAR PRE 144', to: 'Teal Mask Ogerpon ex PRE 144' },
  { from: 'Flareon exSAR PRE 146', to: 'Flareon ex PRE 146' },
  { from: 'Ceruledge exSAR PRE 147', to: 'Ceruledge ex PRE 147' },
  { from: 'Hearthflame Mask Ogerpon exSAR PRE 148', to: 'Hearthflame Mask Ogerpon ex PRE 148' },
  { from: 'Vaporeon exSAR PRE 149', to: 'Vaporeon ex PRE 149' },
  { from: 'Glaceon exSAR PRE 150', to: 'Glaceon ex PRE 150' },
  { from: 'Palafin exSAR PRE 151', to: 'Palafin ex PRE 151' },
  { from: 'Wellspring Mask Ogerpon exSAR PRE 152', to: 'Wellspring Mask Ogerpon ex PRE 152' },
  { from: 'Jolteon exSAR PRE 153', to: 'Jolteon ex PRE 153' },
  { from: 'Iron Hands exSAR PRE 154', to: 'Iron Hands ex PRE 154' },
  { from: 'Espeon exSAR PRE 155', to: 'Espeon ex PRE 155' },
  { from: 'Sylveon exSAR PRE 156', to: 'Sylveon ex PRE 156' },
  { from: 'Iron Valiant exSAR PRE 157', to: 'Iron Valiant ex PRE 157' },
  { from: 'Iron Crown exSAR PRE 158', to: 'Iron Crown ex PRE 158' },
  { from: 'Sandy Shocks exSAR PRE 159', to: 'Sandy Shocks ex PRE 159' },
  { from: 'Cornerstone Mask Ogerpon exSAR PRE 160', to: 'Cornerstone Mask Ogerpon ex PRE 160' },
  { from: 'Umbreon exSAR PRE 161', to: 'Umbreon ex PRE 161' },
  { from: 'Roaring Moon exSAR PRE 162', to: 'Roaring Moon ex PRE 162' },
  { from: 'Pecharunt exSAR PRE 163', to: 'Pecharunt ex PRE 163' },
  { from: 'Gholdengo exSAR PRE 164', to: 'Gholdengo ex PRE 164' },
  { from: 'Dragapult exSAR PRE 165', to: 'Dragapult ex PRE 165' },
  { from: 'Raging Bolt exSAR PRE 166', to: 'Raging Bolt ex PRE 166' },
  { from: 'Eevee exSAR PRE 167', to: 'Eevee ex PRE 167' },
  { from: 'Bloodmoon Ursaluna exSAR PRE 168', to: 'Bloodmoon Ursaluna ex PRE 168' },
  { from: 'Terapagos exSAR PRE 169', to: 'Terapagos ex PRE 169' },
  { from: 'AmarysSAR PRE 170', to: 'Amarys PRE 170' },
  { from: 'CrispinSAR PRE 171', to: 'Crispin PRE 171' },
  { from: 'DraytonSAR PRE 172', to: 'Drayton PRE 172' },
  { from: 'Janine\'s Secret ArtSAR PRE 173', to: 'Janine\'s Secret Art PRE 173' },
  { from: 'KieranSAR PRE 174', to: 'Kieran PRE 174' },
  { from: 'LaceySAR PRE 175', to: 'Lacey PRE 175' },
  { from: 'Iron Leaves exUR PRE 176', to: 'Iron Leaves ex PRE 176' },
  { from: 'Teal Mask Ogerpon exUR PRE 177', to: 'Teal Mask Ogerpon ex PRE 177' },
  { from: 'Walking Wake exUR PRE 178', to: 'Walking Wake ex PRE 178' },
  { from: 'Pikachu exUR PRE 179', to: 'Pikachu ex PRE 179' },
  { from: 'Terapagos exUR PRE 180', to: 'Terapagos ex PRE 180' },

  //SV9
  { from: 'MaractusIR SV9 101', to: 'Maractus SV9 101' },
  { from: 'WailordIR SV9 103', to: 'Wailord SV9 103' },
  { from: 'Iono\'s KilowattrelIR SV9 104', to: 'Iono\'s Kilowattrel SV9 104' },
  { from: 'Lillie\'s RibombeeIR SV9 105', to: 'Lillie\'s Ribombee SV9 105' },
  { from: 'SwinubIR SV9 106', to: 'Swinub SV9 106' },
  { from: 'LycanrocIR SV9 107', to: 'Lycanroc SV9 107' },
  { from: 'N\'s ZoruaIR SV9 108', to: 'N\'s Zorua SV9 108' },
  { from: 'N\'s ReshiramIR SV9 109', to: 'N\'s Reshiram SV9 109' },
  { from: 'Hop\'s WoolooIR SV9 112', to: 'Hop\'s Wooloo SV9 112' },
  { from: 'Volcanion exFA SV9 113', to: 'Volcanion ex SV9 113' },
  { from: 'Iono\'s Bellibolt exFA SV9 114', to: 'Iono\'s Bellibolt ex SV9 114' },
  { from: 'Lillie\'s Clefairy exFA SV9 115', to: 'Lillie\'s Clefairy ex SV9 115' },
  { from: 'Mamoswine exFA SV9 116', to: 'Mamoswine ex SV9 116' },
  { from: 'N\'s Zoroark exFA SV9 117', to: 'N\'s Zoroark ex SV9 117' },
  { from: 'Hop\'s Zacian exFA SV9 118', to: 'Hop\'s Zacian ex SV9 118' },
  { from: 'Salamence exFA SV9 119', to: 'Salamence ex SV9 119' },
  { from: 'Dudunsparce exFA SV9 120', to: 'Dudunsparce ex SV9 120' },
  { from: 'Iris\'s Fighting SpiritFA SV9 121', to: 'Iris\'s Fighting Spirit SV9 121' },
  { from: 'RuffianFA SV9 122', to: 'Ruffian SV9 122' },
  { from: 'Brock\'s RecruitmentFA SV9 123', to: 'Brock\'s Recruitment SV9 123' },
  { from: 'Volcanion exSIR SV9 124', to: 'Volcanion ex SV9 124' },
  { from: 'Iono\'s Bellibolt exSIR SV9 125', to: 'Iono\'s Bellibolt ex SV9 125' },
  { from: 'Lillie\'s Clefairy exSIR SV9 126', to: 'Lillie\'s Clefairy ex SV9 126' },
  { from: 'N\'s Zoroark exSIR SV9 127', to: 'N\'s Zoroark ex SV9 127' },
  { from: 'Hop\'s Zacian exSIR SV9 128', to: 'Hop\'s Zacian ex SV9 128' },
  { from: 'Salamence exSIR SV9 129', to: 'Salamence ex SV9 129' },
  { from: 'Iono\'s Bellibolt exUR SV9 130', to: 'Iono\'s Bellibolt ex SV9 130' },
  { from: 'N\'s Zoroark exUR SV9 131', to: 'N\'s Zoroark ex SV9 131' },
  { from: 'Spike EnergyUR SV9 132', to: 'Spike Energy SV9 132' },

  //SVOM
  { from: 'Marnie\'s MorpekoIR SVOM 20', to: 'Marnie\'s Morpeko SVOM 20' },

  //SVOD
  { from: 'Steven\'s BeldumIR SVOD 19', to: 'Steven\'s Beldum SVOD 19' },

  //SV9a
  { from: 'Ethan\'s Ho-Oh exSIR SV9a 86', to: 'Ethan\'s Ho-Oh ex SV9a 86' },
  { from: 'Cynthia\'s RoseradeIR SV9a 65', to: 'Cynthia\'s Roserade SV9a 65' },
];