export const cardReplacements = [
  //Energy
  { from: 'Basic {D} Energy Energy 15', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 24', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 33', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 42', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 51', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy EVO 97', to: 'Darkness Energy EVO 97' },
  { from: 'Basic {D} Energy BLW 111', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy GEN 81', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy XY 138', to: 'Darkness Energy 7' },

  { from: 'Grass Energy SVE 1', to: 'Grass Energy 1' },

  //GRI
  { from: 'Mallow GRI 127', to: 'Mallow TEF 121' },

  //CRE
  { from: 'Klara CRE 145', to: 'Klara CRE 145 145' },

  //PGO
  { from: 'PokéStop PGO 68', to: 'Pokestop PGO 68' },

  //CRZ
  { from: 'Zacian VSTAR CRZ 96', to: 'Zacian VSTAR' },

  //SVI
  { from: 'Pokégear 3.0 SVI 186', to: 'Pokegear SVI 186' },
  { from: 'Pokémon Catcher SVI 187', to: 'Pokemon Catcher SVI 187' },
  { from: 'Professor\'s Research SVI 189', to: 'Professor\'s Research SVI 189 189' },
  { from: 'Professor\'s Research SVI 190', to: 'Professor\'s Research SVI 190 189' },

  //PAL
  { from: 'Frigibax PAL 57', to: '4 Frigibax PAL 57 ' },
  { from: 'Frigibax PAL 58', to: 'Frigibax PAL 58 ' },
  //PAL FA
  { from: 'Frigibax PAL 208', to: 'FrigibaxIR PAL 208' },
  { from: 'Arctibax PAL 209', to: 'ArctibaxIR PAL 209' },
  { from: 'Baxcalibur PAL 210', to: 'BaxcaliburIR PAL 210' },
  { from: 'Flamigo PAL 227', to: 'FlamigoIR PAL 227' },
  { from: 'Meowscarada ex PAL 231', to: 'Meowscarada exFA PAL 231' },
  { from: 'Wo-Chien ex PAL 232', to: 'Wo-Chien exFA PAL 232' },
  { from: 'Chi-Yu ex PAL 234', to: 'Chi-Yu exFA PAL 234' },
  { from: 'Chien-Pao ex PAL 236', to: 'Chien-Pao exFA PAL 236' },
  { from: 'Ting-Lu ex PAL 243', to: 'Ting-Lu exFA PAL 243' },
  { from: 'Noivern ex PAL 246', to: 'Noivern exFA PAL 246' },
  { from: 'Squawkabilly ex PAL 247', to: 'Squawkabilly exFA PAL 247' },
  { from: 'Boss\'s Orders PAL 248', to: 'Boss\'s OrdersFA PAL 248' },
  { from: 'Clavell PAL 249', to: 'ClavellFA PAL 249' },
  { from: 'Giacomo PAL 252', to: 'GiacomoFA PAL 252' },
  { from: 'Grusha PAL 253', to: 'GrushaFA PAL 253' },
  { from: 'Iono PAL 254', to: 'IonoFA PAL 254' },
  { from: 'Meowscarada ex PAL 256', to: 'Meowscarada exSIR PAL 256' },
  { from: 'Wo-Chien ex PAL 257', to: 'Wo-Chien exSIR PAL 257' },
  { from: 'Chi-Yu ex PAL 259', to: 'Chi-Yu exSIR PAL 259' },
  { from: 'Chien-Pao ex PAL 261', to: 'Chien-Pao exSIR PAL 261' },
  { from: 'Ting-Lu ex PAL 263', to: 'Ting-Lu exSIR PAL 263' },
  { from: 'Squawkabilly ex PAL 264', to: 'Squawkabilly exSIR PAL 264' },
  { from: 'Boss\'s Orders PAL 265', to: 'Boss\'s OrdersSIR PAL 265' },
  { from: 'Giacomo PAL 267', to: 'GiacomoSIR PAL 267' },
  { from: 'Grusha PAL 268', to: 'GrushaSIR PAL 268' },
  { from: 'Iono PAL 269', to: 'IonoSIR PAL 269' },
  { from: 'Meowscarada ex PAL 271', to: 'Meowscarada exHR PAL 271' },
  { from: 'Chien-Pao ex PAL 274', to: 'Chien-Pao exHR PAL 274' },
  { from: 'Ting-Lu ex PAL 275', to: 'Ting-Lu exHR PAL 275' },
  { from: 'Super Rod PAL 276', to: 'Super RodHR PAL 276' },
  { from: 'Superior Energy Retrieval PAL 277', to: 'Superior Energy RetrievalHR PAL 277' },
  { from: 'Froslass ex PAR 217', to: 'FroslassexFA PAR 217' },
  { from: 'Garchomp ex PAR 219', to: 'GarchompexFA PAR 219' },
  { from: 'Tsareena ex PAR 220', to: 'TsareenaexFA PAR 220' },
  { from: 'Tapu Koko ex PAR 222', to: 'TapuKokoexFA PAR 222' },
  { from: 'Iron Hands ex PAR 223', to: 'IronHandsexFA PAR 223' },
  { from: 'Iron Valiant ex PAR 225', to: 'IronValiantexFA PAR 225' },
  { from: 'Hoopa ex PAR 226', to: 'HoopaexFA PAR 226' },
  { from: 'Sandy Shocks ex PAR 228', to: 'SandyShocksexFA PAR 228' },
  { from: 'Roaring Moon ex PAR 229', to: 'RoaringMoonexFA PAR 229' },
  { from: 'Gholdengo ex PAR 231', to: 'GholdengoexFA PAR 231' },
  { from: 'Bombirdier ex PAR 234', to: 'BombirdierexFA PAR 234' },
  { from: 'Mela PAR 236', to: 'MelaFA PAR 236' },
  { from: 'Professor Sada\'s Vitality PAR 239', to: 'ProfessorSadasVitalityFA PAR 239' },
  { from: 'Professor Turo\'s Scenario PAR 240', to: 'ProfessorTurosScenarioFA PAR 240' },
  { from: 'Tulip PAR 244', to: 'TulipFA PAR 244' },
  { from: 'Garchomp ex PAR 245', to: 'GarchompexSIR PAR 245' },
  { from: 'Tapu Koko ex PAR 247', to: 'TapuKokoexSIR PAR 247' },
  { from: 'Iron Hands ex PAR 248', to: 'IronHandsexSIR PAR 248' },
  { from: 'Iron Valiant ex PAR 249', to: 'IronValiantexSIR PAR 249' },
  { from: 'Sandy Shocks ex PAR 250', to: 'SandyShocksexSIR PAR 250' },
  { from: 'Roaring Moon ex PAR 251', to: 'RoaringMoonexSIR PAR 251' },
  { from: 'Gholdengo ex PAR 252', to: 'GholdengoexSIR PAR 252' },
  { from: 'Mela PAR 254', to: 'MelaSIR PAR 254' },
  { from: 'Professor Sada\'s Vitality PAR 256', to: 'ProfessorSadasVitalitySIR PAR 256' },
  { from: 'Professor Turo\'s Scenario PAR 257', to: 'ProfessorTurosScenarioSIR PAR 257' },
  { from: 'Tulip PAR 259', to: 'TulipSIR PAR 259' },
  { from: 'Garchomp ex PAR 260', to: 'GarchompexHR PAR 260' },
  { from: 'Iron Valiant ex PAR 261', to: 'IronValiantexHR PAR 261' },
  { from: 'Roaring Moon ex PAR 262', to: 'RoaringMoonexHR PAR 262' },
  { from: 'Beach Court PAR 263', to: 'BeachCourtHR PAR 263' },
  { from: 'Counter Catcher PAR 264', to: 'CounterCatcherHR PAR 264' },
  { from: 'Luxurious Cape PAR 265', to: 'LuxuriousCapeHR PAR 265' },
  { from: 'Reversal Energy PAR 266', to: 'ReversalEnergyHR PAR 266' },

  //151
  //151 FA
  { from: 'Bulbasaur MEW 166', to: 'BulbasaurIR MEW 166' },
  { from: 'Ivysaur MEW 167', to: 'IvysaurIR MEW 167' },
  { from: 'Charmander MEW 168', to: 'CharmanderIR MEW 168' },
  { from: 'Charmeleon MEW 169', to: 'CharmeleonIR MEW 169' },
  { from: 'Squirtle MEW 170', to: 'SquirtleIR MEW 170' },
  { from: 'Wartortle MEW 171', to: 'WartortleIR MEW 171' },
  { from: 'Nidoking MEW 174', to: 'NidokingIR MEW 174' },
  { from: 'Venusaur ex MEW 182', to: 'Venusaur exFA MEW 182' },
  { from: 'Charizard ex MEW 183', to: 'Charizard exFA MEW 183' },
  { from: 'Blastoise ex MEW 184', to: 'Blastoise exFA MEW 184' },
  { from: 'Arbok ex MEW 185', to: 'Arbok exFA MEW 185' },
  { from: 'Alakazam ex MEW 188', to: 'Alakazam exFA MEW 188' },
  { from: 'Kangaskhan ex MEW 190', to: 'Kangaskhan exFA MEW 190' },
  { from: 'Zapdos ex MEW 192', to: 'Zapdos exFA MEW 192' },
  { from: 'Mew ex MEW 193', to: 'Mew exFA MEW 193' },
  { from: 'Erika\'s Invitation MEW 196', to: 'Erika\'s InvitationFA MEW 196' },
  { from: 'Giovanni\'s Charisma MEW 197', to: 'Giovanni\'s CharismaFA MEW 197' },
  { from: 'Venusaur ex MEW 198', to: 'Venusaur exSIR MEW 198' },
  { from: 'Charizard ex MEW 199', to: 'Charizard exSIR MEW 199' },
  { from: 'Blastoise ex MEW 200', to: 'Blastoise exSIR MEW 200' },
  { from: 'Alakazam ex MEW 201', to: 'Alakazam exSIR MEW 201' },
  { from: 'Zapdos ex MEW 202', to: 'Zapdos exSIR MEW 202' },
  { from: 'Erika\'s Invitation MEW 203', to: 'Erika\'s InvitationSIR MEW 203' },
  { from: 'Giovanni\'s Charisma MEW 204', to: 'Giovanni\'s CharismaSIR MEW 204' },
  { from: 'Mew ex MEW 205', to: 'Mew exHR MEW 205' },
  { from: 'Switch MEW 206', to: 'SwitchHR MEW 206' },
  { from: 'Psychic Energy MEW 207', to: 'Psychic Energy MEW 207' },

  //PAR
  //PAR FA
  { from: 'Toedscruel PAR 185', to: 'ToedscruelIR PAR 185' },
  { from: 'Iron Moth PAR 187', to: 'IronMothIR PAR 187' },
  { from: 'Snorunt PAR 188', to: 'SnoruntIR PAR 188' },
  { from: 'Vanillish PAR 190', to: 'VanillishIR PAR 190' },
  { from: 'Blitzle PAR 195', to: 'BlitzleIR PAR 195' },
  { from: 'Joltik PAR 196', to: 'JoltikIR PAR 196' },
  { from: 'Gimmighoul PAR 198', to: 'GimmighoulIR PAR 198' },
  { from: 'Groudon PAR 199', to: 'GroudonIR PAR 199' },
  { from: 'Minior PAR 201', to: 'MiniorIR PAR 201' },
  { from: 'Garganacl PAR 202', to: 'GarganacIR PAR 202' },
  { from: 'Slither Wing PAR 203', to: 'SlitherWingIR PAR 203' },
  { from: 'Garbodor PAR 204', to: 'GarbodorIR PAR 204' },
  { from: 'Yveltal PAR 205', to: 'YveltalIR PAR 205' },
  { from: 'Morpeko PAR 206', to: 'MorpekoIR PAR 206' },
  { from: 'Brute Bonnet PAR 207', to: 'BruteBonnetIR PAR 207' },
  { from: 'Ferrothorn PAR 209', to: 'FerrothorIR PAR 209' },
  { from: 'Aegislash PAR 210', to: 'AegislashIR PAR 210' },
  { from: 'Swablu PAR 213', to: 'SwabluIR PAR 213' },
  { from: 'Porygon-Z PAR 214', to: 'PorygonZIR PAR 214' },
  { from: 'Cyclizar PAR 215', to: 'CyclizarIR PAR 215' },
  { from: 'Iron Jugulis PAR 216', to: 'IronJugulisIR PAR 216' },

  //TEF
  //TEF FA
  { from: 'Grotle TEF 164', to: 'GrotleIR TEF 164' },
  { from: 'Charjabug TEF 169', to: 'CharjabugIR TEF 169' },
  { from: 'Reuniclus TEF 171', to: 'ReuniclusIR TEF 171' },
  { from: 'Gastly TEF 177', to: 'GastlyIR TEF 177' },
  { from: 'Metagross TEF 178', to: 'MetagrossIR TEF 178' },
  { from: 'Chatot TEF 181', to: 'ChatotIR TEF 181' },
  { from: 'Minccino TEF 182', to: 'MinccinoIR TEF 182' },
  { from: 'Cinccino TEF 183', to: 'CinccinoIR TEF 183' },
  { from: 'Torterra ex TEF 185', to: 'TorterraexFA TEF 185' },
  { from: 'Iron Leaves ex TEF 186', to: 'IronLeavesexFA TEF 186' },
  { from: 'Gouging Fire ex TEF 188', to: 'GougingFireexFA TEF 188' },
  { from: 'Walking Wake ex TEF 189', to: 'WalkingWakeexFA TEF 189' },
  { from: 'Iron Crown ex TEF 191', to: 'IronCrownexFA TEF 191' },
  { from: 'Gengar ex TEF 193', to: 'GengarexFA TEF 193' },
  { from: 'Raging Bolt ex TEF 196', to: 'RagingBoltexFA TEF 196' },
  { from: 'Bianca\'s Devotion TEF 197', to: 'BiancasDevotionFA TEF 197' },
  { from: 'Ciphermaniac\'s Codebreaking TEF 198', to: 'CiphermaniacsCodebreakingFA TEF 198' },
  { from: 'Eri TEF 199', to: 'EriFA TEF 199' },
  { from: 'Explorer\'s Guidance TEF 200', to: 'ExplorersGuidanceFA TEF 200' },
  { from: 'Morty\'s Conviction TEF 201', to: 'MortysConvictionFA TEF 201' },
  { from: 'Salvatore TEF 202', to: 'SalvatoreFA TEF 202' },
  { from: 'Iron Leaves ex TEF 203', to: 'IronLeavesexSIR TEF 203' },
  { from: 'Gouging Fire ex TEF 204', to: 'GougingFireexSIR TEF 204' },
  { from: 'Walking Wake ex TEF 205', to: 'WalkingWakeexSIR TEF 205' },
  { from: 'Iron Crown ex TEF 206', to: 'IronCrownexSIR TEF 206' },
  { from: 'Raging Bolt ex TEF 208', to: 'RagingBoltexSIR TEF 208' },
  { from: 'Bianca\'s Devotion TEF 209', to: 'BiancasDevotionSIR TEF 209' },
  { from: 'Eri TEF 210', to: 'EriSIR TEF 210' },
  { from: 'Morty\'s Conviction TEF 211', to: 'MortysConvictionSIR TEF 211' },
  { from: 'Salvatore TEF 212', to: 'SalvatoreSIR TEF 212' },
  { from: 'Iron Leaves ex TEF 213', to: 'IronLeavesexHR TEF 213' },
  { from: 'Gouging Fire ex TEF 214', to: 'GougingFireexHR TEF 214' },
  { from: 'Walking Wake ex TEF 215', to: 'WalkingWakeexHR TEF 215' },
  { from: 'Iron Crown ex TEF 216', to: 'IronCrownexHR TEF 216' },
  { from: 'Raging Bolt ex TEF 218', to: 'RagingBoltexHR TEF 218' },

  //TWM
  { from: 'Applin TWM 17', to: 'Applin TWM 17 ' },
  { from: 'Applin TWM 126', to: 'Applin TWM 126 ' },
  { from: 'Scovillain ex TEF 22', to: 'Scovillain ex PAF 107' },

  //SFA
  { from: 'Bloodmoon Ursaluna SFA 25', to: 'Bloodmoon Ursaluna SV6a 25' },
];

export const exportReplacements = [

  //GRI
  { from: 'Mallow TEF 121', to: 'Mallow GRI 127' },

  //CRE
  { from: 'Klara CRE 145 145', to: 'Klara CRE 145' },

  //PGO
  { from: 'Pokestop PGO 68', to: 'PokéStop PGO 68' },

  //CRZ
  { from: 'Zacian VSTAR', to: 'Zacian VSTAR CRZ 96' },

  //SVI
  { from: 'Pokegear SVI 186', to: 'Pokégear 3.0 SVI 186' },
  { from: 'Pokemon Catcher SVI 187', to: 'Pokémon Catcher SVI 187' },
  { from: 'Professor\'s Research SVI 189 189', to: 'Professor\'s Research SVI 189' },
  { from: 'Professor\'s Research SVI 190 189', to: 'Professor\'s Research SVI 190 190' },

  //PAL
  { from: 'Frigibax PAL 57 ', to: 'Frigibax PAL 57' },
  { from: 'Frigibax PAL 58 ', to: 'Frigibax PAL 58' },
  //PAL FA
  { from: 'FrigibaxIR PAL 208', to: 'Frigibax PAL 208' },
  { from: 'ArctibaxIR PAL 209', to: 'Arctibax PAL 209' },
  { from: 'BaxcaliburIR PAL 210', to: 'Baxcalibur PAL 210' },
  { from: 'FlamigoIR PAL 227', to: 'Flamigo PAL 227' },
  { from: 'Meowscarada exFA PAL 231', to: 'Meowscarada ex PAL 231' },
  { from: 'Wo-Chien exFA PAL 232', to: 'Wo-Chien ex PAL 232' },
  { from: 'Chi-Yu exFA PAL 234', to: 'Chi-Yu ex PAL 234' },
  { from: 'Chien-Pao exFA PAL 236', to: 'Chien-Pao ex PAL 236' },
  { from: 'Ting-Lu exFA PAL 243', to: 'Ting-Lu ex PAL 243' },
  { from: 'Noivern exFA PAL 246', to: 'Noivern ex PAL 246' },
  { from: 'Squawkabilly exFA PAL 247', to: 'Squawkabilly ex PAL 247' },
  { from: 'Boss\'s OrdersFA PAL 248', to: 'Boss\'s Orders PAL 248' },
  { from: 'ClavellFA PAL 249', to: 'Clavell PAL 249' },
  { from: 'GiacomoFA PAL 252', to: 'Giacomo PAL 252' },
  { from: 'GrushaFA PAL 253', to: 'Grusha PAL 253' },
  { from: 'IonoFA PAL 254', to: 'Iono PAL 254' },
  { from: 'Meowscarada exSIR PAL 256', to: 'Meowscarada ex PAL 256' },
  { from: 'Wo-Chien exSIR PAL 257', to: 'Wo-Chien ex PAL 257' },
  { from: 'Chi-Yu exSIR PAL 259', to: 'Chi-Yu ex PAL 259' },
  { from: 'Chien-Pao exSIR PAL 261', to: 'Chien-Pao ex PAL 261' },
  { from: 'Ting-Lu exSIR PAL 263', to: 'Ting-Lu ex PAL 263' },
  { from: 'Squawkabilly exSIR PAL 264', to: 'Squawkabilly ex PAL 264' },
  { from: 'Boss\'s OrdersSIR PAL 265', to: 'Boss\'s Orders PAL 265' },
  { from: 'GiacomoSIR PAL 267', to: 'Giacomo PAL 267' },
  { from: 'GrushaSIR PAL 268', to: 'Grusha PAL 268' },
  { from: 'IonoSIR PAL 269', to: 'Iono PAL 269' },
  { from: 'Meowscarada exHR PAL 271', to: 'Meowscarada ex PAL 271' },
  { from: 'Chien-Pao exHR PAL 274', to: 'Chien-Pao ex PAL 274' },
  { from: 'Ting-Lu exHR PAL 275', to: 'Ting-Lu ex PAL 275' },
  { from: 'Super RodHR PAL 276', to: 'Super Rod PAL 276' },
  { from: 'Superior Energy RetrievalHR PAL 277', to: 'Superior Energy Retrieval PAL 277' },

  //151
  //151 FA
  { from: 'BulbasaurIR MEW 166', to: 'Bulbasaur MEW 166' },
  { from: 'IvysaurIR MEW 167', to: 'Ivysaur MEW 167' },
  { from: 'CharmanderIR MEW 168', to: 'Charmander MEW 168' },
  { from: 'CharmeleonIR MEW 169', to: 'Charmeleon MEW 169' },
  { from: 'SquirtleIR MEW 170', to: 'Squirtle MEW 170' },
  { from: 'WartortleIR MEW 171', to: 'Wartortle MEW 171' },
  { from: 'NidokingIR MEW 174', to: 'Nidoking MEW 174' },
  { from: 'Venusaur exFA MEW 182', to: 'Venusaur ex MEW 182' },
  { from: 'Charizard exFA MEW 183', to: 'Charizard ex MEW 183' },
  { from: 'Blastoise exFA MEW 184', to: 'Blastoise ex MEW 184' },
  { from: 'Arbok exFA MEW 185', to: 'Arbok ex MEW 185' },
  { from: 'Alakazam exFA MEW 188', to: 'Alakazam ex MEW 188' },
  { from: 'Kangaskhan exFA MEW 190', to: 'Kangaskhan ex MEW 190' },
  { from: 'Zapdos exFA MEW 192', to: 'Zapdos ex MEW 192' },
  { from: 'Mew exFA MEW 193', to: 'Mew ex MEW 193' },
  { from: 'Erika\'s InvitationFA MEW 196', to: 'Erika\'s Invitation MEW 196' },
  { from: 'Giovanni\'s CharismaFA MEW 197', to: 'Giovanni\'s Charisma MEW 197' },
  { from: 'Venusaur exSIR MEW 198', to: 'Venusaur ex MEW 198' },
  { from: 'Charizard exSIR MEW 199', to: 'Charizard ex MEW 199' },
  { from: 'Blastoise exSIR MEW 200', to: 'Blastoise ex MEW 200' },
  { from: 'Alakazam exSIR MEW 201', to: 'Alakazam ex MEW 201' },
  { from: 'Zapdos exSIR MEW 202', to: 'Zapdos ex MEW 202' },
  { from: 'Erika\'s InvitationSIR MEW 203', to: 'Erika\'s Invitation MEW 203' },
  { from: 'Giovanni\'s CharismaSIR MEW 204', to: 'Giovanni\'s Charisma MEW 204' },
  { from: 'Mew exHR MEW 205', to: 'Mew ex MEW 205' },
  { from: 'SwitchHR MEW 206', to: 'Switch MEW 206' },
  { from: 'Psychic Energy MEW 207', to: 'Psychic Energy MEW 207' },

  //PAR
  //PAR FA
  { from: 'ToedscruelIR PAR 185', to: 'Toedscruel PAR 185' },
  { from: 'IronMothIR PAR 187', to: 'Iron Moth PAR 187' },
  { from: 'SnoruntIR PAR 188', to: 'Snorunt PAR 188' },
  { from: 'VanillishIR PAR 190', to: 'Vanillish PAR 190' },
  { from: 'BlitzleIR PAR 195', to: 'Blitzle PAR 195' },
  { from: 'JoltikIR PAR 196', to: 'Joltik PAR 196' },
  { from: 'GimmighoulIR PAR 198', to: 'Gimmighoul PAR 198' },
  { from: 'GroudonIR PAR 199', to: 'Groudon PAR 199' },
  { from: 'MiniorIR PAR 201', to: 'Minior PAR 201' },
  { from: 'GarganacIR PAR 202', to: 'Garganacl PAR 202' },
  { from: 'SlitherWingIR PAR 203', to: 'Slither Wing PAR 203' },
  { from: 'GarbodorIR PAR 204', to: 'Garbodor PAR 204' },
  { from: 'YveltalIR PAR 205', to: 'Yveltal PAR 205' },
  { from: 'MorpekoIR PAR 206', to: 'Morpeko PAR 206' },
  { from: 'BruteBonnetIR PAR 207', to: 'Brute Bonnet PAR 207' },
  { from: 'FerrothorIR PAR 209', to: 'Ferrothorn PAR 209' },
  { from: 'AegislashIR PAR 210', to: 'Aegislash PAR 210' },
  { from: 'SwabluIR PAR 213', to: 'Swablu PAR 213' },
  { from: 'PorygonZIR PAR 214', to: 'Porygon-Z PAR 214' },
  { from: 'CyclizarIR PAR 215', to: 'Cyclizar PAR 215' },
  { from: 'IronJugulisIR PAR 216', to: 'Iron Jugulis PAR 216' },
  { from: 'FroslassexFA PAR 217', to: 'Froslass ex PAR 217' },
  { from: 'GarchompexFA PAR 219', to: 'Garchomp ex PAR 219' },
  { from: 'TsareenaexFA PAR 220', to: 'Tsareena ex PAR 220' },
  { from: 'TapuKokoexFA PAR 222', to: 'Tapu Koko ex PAR 222' },
  { from: 'IronHandsexFA PAR 223', to: 'Iron Hands ex PAR 223' },
  { from: 'IronValiantexFA PAR 225', to: 'Iron Valiant ex PAR 225' },
  { from: 'HoopaexFA PAR 226', to: 'Hoopa ex PAR 226' },
  { from: 'SandyShocksexFA PAR 228', to: 'Sandy Shocks ex PAR 228' },
  { from: 'RoaringMoonexFA PAR 229', to: 'Roaring Moon ex PAR 229' },
  { from: 'GholdengoexFA PAR 231', to: 'Gholdengo ex PAR 231' },
  { from: 'BombirdierexFA PAR 234', to: 'Bombirdier ex PAR 234' },
  { from: 'MelaFA PAR 236', to: 'Mela PAR 236' },
  { from: 'ProfessorSadasVitalityFA PAR 239', to: 'Professor Sada\'s Vitality PAR 239' },
  { from: 'ProfessorTurosScenarioFA PAR 240', to: 'Professor Turo\'s Scenario PAR 240' },
  { from: 'TulipFA PAR 244', to: 'Tulip PAR 244' },
  { from: 'GarchompexSIR PAR 245', to: 'Garchomp ex PAR 245' },
  { from: 'TapuKokoexSIR PAR 247', to: 'Tapu Koko ex PAR 247' },
  { from: 'IronHandsexSIR PAR 248', to: 'Iron Hands ex PAR 248' },
  { from: 'IronValiantexSIR PAR 249', to: 'Iron Valiant ex PAR 249' },
  { from: 'SandyShocksexSIR PAR 250', to: 'Sandy Shocks ex PAR 250' },
  { from: 'RoaringMoonexSIR PAR 251', to: 'Roaring Moon ex PAR 251' },
  { from: 'GholdengoexSIR PAR 252', to: 'Gholdengo ex PAR 252' },
  { from: 'MelaSIR PAR 254', to: 'Mela PAR 254' },
  { from: 'ProfessorSadasVitalitySIR PAR 256', to: 'Professor Sada\'s Vitality PAR 256' },
  { from: 'ProfessorTurosScenarioSIR PAR 257', to: 'Professor Turo\'s Scenario PAR 257' },
  { from: 'TulipSIR PAR 259', to: 'Tulip PAR 259' },
  { from: 'GarchompexHR PAR 260', to: 'Garchomp ex PAR 260' },
  { from: 'IronValiantexHR PAR 261', to: 'Iron Valiant ex PAR 261' },
  { from: 'RoaringMoonexHR PAR 262', to: 'Roaring Moon ex PAR 262' },
  { from: 'BeachCourtHR PAR 263', to: 'Beach Court PAR 263' },
  { from: 'CounterCatcherHR PAR 264', to: 'Counter Catcher PAR 264' },
  { from: 'LuxuriousCapeHR PAR 265', to: 'Luxurious Cape PAR 265' },
  { from: 'ReversalEnergyHR PAR 266', to: 'Reversal Energy PAR 266' },

  //TEF
  //TEF FA
  { from: 'GrotleIR TEF 164', to: 'Grotle TEF 164' },
  { from: 'CharjabugIR TEF 169', to: 'Charjabug TEF 169' },
  { from: 'ReuniclusIR TEF 171', to: 'Reuniclus TEF 171' },
  { from: 'GastlyIR TEF 177', to: 'Gastly TEF 177' },
  { from: 'MetagrossIR TEF 178', to: 'Metagross TEF 178' },
  { from: 'ChatotIR TEF 181', to: 'Chatot TEF 181' },
  { from: 'MinccinoIR TEF 182', to: 'Minccino TEF 182' },
  { from: 'CinccinoIR TEF 183', to: 'Cinccino TEF 183' },
  { from: 'TorterraexFA TEF 185', to: 'Torterra ex TEF 185' },
  { from: 'IronLeavesexFA TEF 186', to: 'Iron Leaves ex TEF 186' },
  { from: 'GougingFireexFA TEF 188', to: 'Gouging Fire ex TEF 188' },
  { from: 'WalkingWakeexFA TEF 189', to: 'Walking Wake ex TEF 189' },
  { from: 'IronCrownexFA TEF 191', to: 'Iron Crown ex TEF 191' },
  { from: 'GengarexFA TEF 193', to: 'Gengar ex TEF 193' },
  { from: 'RagingBoltexFA TEF 196', to: 'Raging Bolt ex TEF 196' },
  { from: 'BiancasDevotionFA TEF 197', to: 'Bianca\'s Devotion TEF 197' },
  { from: 'CiphermaniacsCodebreakingFA TEF 198', to: 'Ciphermaniac\'s Codebreaking TEF 198' },
  { from: 'EriFA TEF 199', to: 'Eri TEF 199' },
  { from: 'ExplorersGuidanceFA TEF 200', to: 'Explorer\'s Guidance TEF 200' },
  { from: 'MortysConvictionFA TEF 201', to: 'Morty\'s Conviction TEF 201' },
  { from: 'SalvatoreFA TEF 202', to: 'Salvatore TEF 202' },
  { from: 'IronLeavesexSIR TEF 203', to: 'Iron Leaves ex TEF 203' },
  { from: 'GougingFireexSIR TEF 204', to: 'Gouging Fire ex TEF 204' },
  { from: 'WalkingWakeexSIR TEF 205', to: 'Walking Wake ex TEF 205' },
  { from: 'IronCrownexSIR TEF 206', to: 'Iron Crown ex TEF 206' },
  { from: 'RagingBoltexSIR TEF 208', to: 'Raging Bolt ex TEF 208' },
  { from: 'BiancasDevotionSIR TEF 209', to: 'Bianca\'s Devotion TEF 209' },
  { from: 'EriSIR TEF 210', to: 'Eri TEF 210' },
  { from: 'MortysConvictionSIR TEF 211', to: 'Morty\'s Conviction TEF 211' },
  { from: 'SalvatoreSIR TEF 212', to: 'Salvatore TEF 212' },
  { from: 'IronLeavesexHR TEF 213', to: 'Iron Leaves ex TEF 213' },
  { from: 'GougingFireexHR TEF 214', to: 'Gouging Fire ex TEF 214' },
  { from: 'WalkingWakeexHR TEF 215', to: 'Walking Wake ex TEF 215' },
  { from: 'IronCrownexHR TEF 216', to: 'Iron Crown ex TEF 216' },
  { from: 'RagingBoltexHR TEF 218', to: 'Raging Bolt ex TEF 218' },

  //TWM
  { from: 'Applin TWM 17 ', to: 'Applin TWM 17' },
  { from: 'Applin TWM 126 ', to: 'Applin TWM 126' },
  { from: 'Scovillain ex PAF 107', to: 'Scovillain ex TEF 22' },

  //SFA
  { from: 'Bloodmoon Ursaluna SV6a 25', to: 'Bloodmoon Ursaluna SFA 25' },
];
