export const cardReplacements = [
  //Energy
  { from: 'Basic {D} Energy Energy 15', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 24', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 33', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 42', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 51', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy EVO 97', to: 'Darkness Energy EVO 97' },
  { from: 'Basic {D} Energy BLW 111', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy GEN 81', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy XY 138', to: 'Darkness Energy 7' },

  { from: 'Grass Energy SVE 1', to: 'Grass Energy 1' },

  //PGO
  { from: 'PokéStop PGO 68', to: 'Pokestop PGO 68' },

  //SVI
  { from: 'Pokégear 3.0 SVI 186', to: 'Pokegear SVI 186' },
  { from: 'Pokémon Catcher SVI 187', to: 'Pokemon Catcher SVI 187' },
  { from: 'Professor\'s Research SVI 189', to: 'Professor\'s Research SVI 189 189' },
  { from: 'Professor\'s Research SVI 190', to: 'Professor\'s Research SVI 190 189' },

  //SFA
  // { from: 'Joltik SFA 1', to: 'Joltik SV6a 1' },
  // { from: 'Galvantula SFA 2', to: 'Galvantula SV6a 2' },
  // { from: 'Rowlet SFA 3', to: 'Rowlet SV6a 3' },
  // { from: 'Dartrix SFA 4', to: 'Dartrix SV6a 4' },
  // { from: 'Decidueye SFA 5', to: 'Decidueye SV6a 5' },
  // { from: 'Tapu Bulu SFA 6', to: 'Tapu Bulu SV6a 6' },
  // { from: 'Houndour SFA 7', to: 'Houndour SV6a 7' },
  // { from: 'Houndoom SFA 8', to: 'Houndoom SV6a 8' },
  // { from: 'Iron Moth SFA 9', to: 'Iron Moth SV6a 9' },
  // { from: 'Horsea SFA 10', to: 'Horsea SV6a 10' },
  // { from: 'Seadra SFA 11', to: 'Seadra SV6a 11' },
  // { from: 'Kingdra ex SFA 12', to: 'Kingdra ex SV6a 12' },
  // { from: 'Sneasel SFA 13', to: 'Sneasel SV6a 13' },
  // { from: 'Weavile SFA 14', to: 'Weavile SV6a 14' },
  // { from: 'Revavroom ex SFA 15', to: 'Revavroom ex SV6a 15' },
  // { from: 'Drowzee SFA 16', to: 'Drowzee SV6a 16' },
  // { from: 'Hypno SFA 17', to: 'Hypno SV6a 17' },
  // { from: 'Duskull SFA 18', to: 'Duskull SV6a 18' },
  // { from: 'Dusclops SFA 19', to: 'Dusclops SV6a 19' },
  // { from: 'Dusknoir SFA 20', to: 'Dusknoir SV6a 20' },
  // { from: 'Cresselia SFA 21', to: 'Cresselia SV6a 21' },
  // { from: 'Sylveon SFA 22', to: 'Sylveon SV6a 22' },
  // { from: 'Croagunk SFA 23', to: 'Croagunk SV6a 23' },
  // { from: 'Toxicroak SFA 24', to: 'Toxicroak SV6a 24' },
  // { from: 'Bloodmoon Ursaluna SFA 25', to: 'Bloodmoon Ursaluna SV6a 25' },
  // { from: 'Slither Wing SFA 26', to: 'Slither Wing SV6a 26' },
  // { from: 'Zubat SFA 27', to: 'Zubat SV6a 27' },
  // { from: 'Golbat SFA 28', to: 'Golbat SV6a 28' },
  // { from: 'Crobat SFA 29', to: 'Crobat SV6a 29' },
  // { from: 'Absol SFA 30', to: 'Absol SV6a 30' },
  // { from: 'Zorua SFA 31', to: 'Zorua SV6a 31' },
  // { from: 'Zoroark SFA 32', to: 'Zoroark SV6a 32' },
  // { from: 'Inkay SFA 33', to: 'Inkay SV6a 33' },
  // { from: 'Malamar SFA 34', to: 'Malamar SV6a 34' },
  // { from: 'Yveltal SFA 35', to: 'Yveltal SV6a 35' },
  // { from: 'Okidogi ex SFA 36', to: 'Okidogi ex SV6a 36' },
  // { from: 'Munkidori ex SFA 37', to: 'Munkidori ex SV6a 37' },
  // { from: 'Fezandipiti ex SFA 38', to: 'Fezandipiti ex SV6a 38' },
  // { from: 'Pecharunt ex SFA 39', to: 'Pecharunt ex SV6a 39' },
  // { from: 'Genesect SFA 40', to: 'Genesect SV6a 40' },
  // { from: 'Cufant SFA 41', to: 'Cufant SV6a 41' },
  // { from: 'Copperajah SFA 42', to: 'Copperajah SV6a 42' },
  // { from: 'Varoom SFA 43', to: 'Varoom SV6a 43' },
  // { from: 'Axew SFA 44', to: 'Axew SV6a 44' },
  // { from: 'Fraxure SFA 45', to: 'Fraxure SV6a 45' },
  // { from: 'Haxorus SFA 46', to: 'Haxorus SV6a 46' },
  // { from: 'Kyurem SFA 47', to: 'Kyurem SV6a 47' },
  // { from: 'Meowth SFA 48', to: 'Meowth SV6a 48' },
  // { from: 'Persian SFA 49', to: 'Persian SV6a 49' },
  // { from: 'Eevee SFA 50', to: 'Eevee SV6a 50' },
  // { from: 'Furfrou SFA 51', to: 'Furfrou SV6a 51' },
  // { from: 'Stufful SFA 52', to: 'Stufful SV6a 52' },
  // { from: 'Bewear SFA 53', to: 'Bewear SV6a 53' },
  // { from: 'Academy at Night SFA 54', to: 'Academy at Night SV6a 64' },
  // { from: 'Binding Mochi SFA 55', to: 'Binding Mochi SV6a 57' },
  // { from: 'Cassiopeia SFA 56', to: 'Cassiopeia SV6a 61' },
  // { from: 'Colress\'s Tenacity SFA 57', to: 'Colress\'s Tenacity SV6a 59' },
  // { from: 'Dangerous Laser SFA 58', to: 'Dangerous Laser SV6a 54' },
  // { from: 'Janine\'s Secret Art SFA 59', to: 'Janine\'s Secret Art SV6a 60' },
  // { from: 'Neutralization Zone SFA 60', to: 'Neutralization Zone SV6a 63' },
  // { from: 'Night Stretcher SFA 61', to: 'Night Stretcher SV6a 56' },
  // { from: 'Poké Vital A SFA 62', to: 'Poké Vital A SV6a 55' },
  // { from: 'Powerglass SFA 63', to: 'Powerglass SV6a 58' },
  // { from: 'Xerosic\'s Machinations SFA 64', to: 'Xerosic\'s Machinations SV6a 62' },
  // { from: 'Tapu Bulu SFA 65', to: 'Tapu Bulu SV6a 65' },
  // { from: 'Houndoom SFA 66', to: 'Houndoom SV6a 66' },
  // { from: 'Horsea SFA 67', to: 'Horsea SV6a 67' },
  // { from: 'Duskull SFA 68', to: 'Duskull SV6a 68' },
  // { from: 'Dusclops SFA 69', to: 'Dusclops SV6a 69' },
  // { from: 'Dusknoir SFA 70', to: 'Dusknoir SV6a 70' },
  // { from: 'Cresselia SFA 71', to: 'Cresselia SV6a 71' },
  // { from: 'Munkidori ex SFA 72', to: 'Munkidori ex SV6a 37' },
  // { from: 'Fezandipiti ex SFA 73', to: 'Fezandipiti ex SV6a 38' },
  // { from: 'Okidogi ex SFA 74', to: 'Okidogi ex SV6a 36' },
  // { from: 'Zorua SFA 75', to: 'Zorua SV6a 72' },
  // { from: 'Cufant SFA 76', to: 'Cufant SV6a 73' },
  // { from: 'Fraxure SFA 77', to: 'Fraxure SV6a 74' },
  // { from: 'Persian SFA 78', to: 'Persian SV6a 75' },
  // { from: 'Bewear SFA 79', to: 'Bewear SV6a 76' },
  // { from: 'Kingdra ex SFA 80', to: 'Kingdra ex SV6a 77' },
  // { from: 'Revavroom ex SFA 81', to: 'Revavroom ex SV6a 78' },
];