// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { PutCountersEffect } from '../../game/store/effects/attack-effects';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Doublade extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Honedge';
  public cardType: CardType = P;
  public hp: number = 80;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Curse of the Blade',
      cost: [P],
      damage: 0,
      text: 'Put 3 damage counters on each of your opponent\'s Pokémon that has a Pokémon Tool card attached to it.'
    }
  ];

  public set: string = 'FLI';
  public setNumber: string = '48';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Doublade';
  public fullName: string = 'Doublade FLI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Curse of the Blade
    // Ref: set-ultra-prism/magearna.ts (tools.length check pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        if (cardList.tools.length > 0) {
          const damageEffect = new PutCountersEffect(effect, 30); // 3 damage counters = 30 damage
          damageEffect.target = cardList;
          store.reduceEffect(state, damageEffect);
        }
      });
    }

    return state;
  }
}
