// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, MULTIPLE_COIN_FLIPS_PROMPT, THIS_POKEMON_DOES_DAMAGE_TO_ITSELF } from '../../game/store/prefabs/prefabs';
import { HEAL_X_DAMAGE_FROM_THIS_POKEMON } from '../../game/store/prefabs/attack-effects';

export class Gogoat extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Skiddo';
  public cardType: CardType = G;
  public hp: number = 120;
  public weakness = [{ type: R }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Milk Drink',
      cost: [G],
      damage: 0,
      text: 'Flip 2 coins. For each heads, heal 40 damage from this Pokémon.'
    },
    {
      name: 'Double-Edge',
      cost: [G, C, C],
      damage: 120,
      text: 'This Pokémon does 30 damage to itself.'
    }
  ];

  public set: string = 'FLI';
  public setNumber: string = '10';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Gogoat';
  public fullName: string = 'Gogoat FLI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Milk Drink
    // Refs: AGENTS-patterns.md (multiple coin flips), AGENTS-patterns.md (healing)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      MULTIPLE_COIN_FLIPS_PROMPT(store, state, effect.player, 2, results => {
        const heads = results.filter(r => r).length;
        if (heads > 0) {
          HEAL_X_DAMAGE_FROM_THIS_POKEMON(heads * 40, effect, store, state);
        }
      });
    }

    // Attack 2: Double-Edge
    // Ref: AGENTS-patterns.md (self damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      THIS_POKEMON_DOES_DAMAGE_TO_ITSELF(store, state, effect, 30);
    }

    return state;
  }
}
