// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, SuperType, EnergyType } from '../../game/store/card/card-types';
import { StoreLike, State, GameMessage, StateUtils, PlayerType, EnergyCard } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { DealDamageEffect, PutDamageEffect } from '../../game/store/effects/attack-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { ChooseCardsPrompt } from '../../game/store/prompts/choose-cards-prompt';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class ZygardeGx extends PokemonCard {
  public tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 200;
  public weakness = [{ type: G }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Cell Connector',
      cost: [C, C],
      damage: 50,
      text: 'Attach 2 [F] Energy cards from your discard pile to this Pokémon.'
    },
    {
      name: 'Land\'s Wrath',
      cost: [F, F, C, C],
      damage: 130,
      text: ''
    },
    {
      name: 'Verdict-GX',
      cost: [F, F, C, C],
      damage: 150,
      gxAttack: true,
      text: 'Prevent all damage done to this Pokémon by attacks from Pokémon-GX and Pokémon-EX during your opponent\'s next turn. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'FLI';
  public setNumber: string = '73';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Zygarde-GX';
  public fullName: string = 'Zygarde-GX FLI';

  public readonly VERDICT_MARKER = 'ZYGARDE_GX_FLI_VERDICT_MARKER';
  public readonly CLEAR_VERDICT_MARKER = 'ZYGARDE_GX_FLI_CLEAR_VERDICT_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Cell Connector
    // Ref: set-breakpoint/seismitoad.ts (Siphon Off)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const fightingEnergy = player.discard.cards.filter(c =>
        c instanceof EnergyCard && c.energyType === EnergyType.BASIC && c.name === 'Fighting Energy'
      );

      if (fightingEnergy.length > 0) {
        const maxAttach = Math.min(2, fightingEnergy.length);

        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_ATTACH,
          player.discard,
          { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Fighting Energy' },
          { min: maxAttach, max: maxAttach, allowCancel: false }
        ), cards => {
          cards = cards || [];
          cards.forEach(card => {
            player.discard.moveCardTo(card, player.active);
          });
        });
      }
    }

    // Attack 3: Verdict-GX
    // Refs: set-burning-shadows/darkrai-gx.ts (GX attack pattern), set-x-and-y/aegislash-2.ts (prevent damage marker)
    if (WAS_ATTACK_USED(effect, 2, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      player.active.marker.addMarker(this.VERDICT_MARKER, this);
      opponent.marker.addMarker(this.CLEAR_VERDICT_MARKER, this);
    }

    // Prevent damage from GX and EX Pokemon
    if ((effect instanceof DealDamageEffect || effect instanceof PutDamageEffect)
      && effect.target.marker.hasMarker(this.VERDICT_MARKER, this)
      && effect.target.cards.includes(this)
      && effect.target.getPokemonCard() === this) {
      const sourceCard = effect.source.getPokemonCard();
      if (sourceCard && (sourceCard.tags.includes(CardTag.POKEMON_GX) || sourceCard.tags.includes(CardTag.POKEMON_EX))) {
        effect.preventDefault = true;
        return state;
      }
    }

    // Cleanup at end of opponent's turn
    if (effect instanceof EndTurnEffect
      && effect.player.marker.hasMarker(this.CLEAR_VERDICT_MARKER, this)) {
      effect.player.marker.removeMarker(this.CLEAR_VERDICT_MARKER, this);
      const opponent = StateUtils.getOpponent(state, effect.player);
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        cardList.marker.removeMarker(this.VERDICT_MARKER, this);
      });
    }

    return state;
  }
}
