// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { AttackEffect } from '../../game/store/effects/game-effects';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class Zygarde extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 90;
  public weakness = [{ type: G }];
  public retreat = [C];

  public powers = [  {
    name: 'Earthen Aura',
    powerType: PowerType.ABILITY,
    text: 'Damage from this Pokémon\'s attacks isn\'t affected by Weakness or Resistance.'
  }];

  public attacks = [
    {
      name: 'Peace Maker',
      cost: [F],
      damage: 30,
      damageCalculation: '+' as '+',
      text: 'If your opponent has an Ultra Beast in play, this attack does 30 more damage.'
    }
  ];

  public set: string = 'FLI';
  public setNumber: string = '71';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Zygarde';
  public fullName: string = 'Zygarde FLI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Earthen Aura (passive - ignore Weakness/Resistance on this Pokemon's attacks)
    // Ref: set-burning-shadows/darkrai-gx.ts (ignoreResistance pattern)
    if (effect instanceof AttackEffect && effect.player.active.getPokemonCard() === this) {
      const player = effect.player;

      if (!IS_ABILITY_BLOCKED(store, state, player, this)) {
        effect.ignoreWeakness = true;
        effect.ignoreResistance = true;
      }
    }

    // Attack 1: Peace Maker
    // Ref: set-ultra-prism/bronzong.ts (Psychic Resonance - check opponent's Pokemon type)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      let hasUltraBeast = false;
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList, card) => {
        if (card.tags && card.tags.includes(CardTag.ULTRA_BEAST)) {
          hasUltraBeast = true;
        }
      });

      if (hasUltraBeast) {
        effect.damage += 30;
      }
    }

    return state;
  }
}
