// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED, ON_DAMAGED_BY_OPPONENT_ATTACK_EVEN_IF_KNOCKED_OUT } from '../../game/store/prefabs/prefabs';
import { HealEffect } from '../../game/store/effects/game-effects';

export class ChesnaughtV extends PokemonCard {
  public tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 230;
  public weakness = [{ type: R }];
  public retreat = [C, C, C, C];

  public powers = [  {
    name: 'Needle Line',
    powerType: PowerType.ABILITY,
    text: 'If your Active Chesnaught V is damaged by an attack from your opponent\'s Pokémon (even if it is Knocked Out), put 3 damage counters on the Attacking Pokémon.'
  }];

  public attacks = [
    {
      name: 'Touchdown',
      cost: [G, G, C],
      damage: 130,
      text: 'Heal 30 damage from this Pokémon.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '15';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Chesnaught V';
  public fullName: string = 'Chesnaught V SIT 15';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Needle Line (passive)
    // If this Pokemon (in Active) is damaged by opponent's attack, put 3 damage counters on Attacking Pokemon.
    // Ref: set-dragons-majesty/druddigon.ts (ON_DAMAGED_BY_OPPONENT_ATTACK_EVEN_IF_KNOCKED_OUT)
    if (ON_DAMAGED_BY_OPPONENT_ATTACK_EVEN_IF_KNOCKED_OUT(state, effect, { source: this })) {
      const targetPlayer = StateUtils.findOwner(state, effect.target);

      if (IS_ABILITY_BLOCKED(store, state, targetPlayer, this)) {
        return state;
      }

      // Must be in active spot
      if (effect.target !== targetPlayer.active) {
        return state;
      }

      effect.source.damage += 30;
    }

    // Attack 1: Touchdown
    // Ref: set-cosmic-eclipse/mallow-and-lana.ts (HealEffect pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const healEffect = new HealEffect(player, player.active, 30);
      store.reduceEffect(state, healEffect);
    }

    return state;
  }
}
