// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED } from '../../game/store/prefabs/attack-effects';
import { GameError } from '../../game/game-error';
import { GameMessage } from '../../game/game-message';
import { AttackEffect } from '../../game/store/effects/game-effects';

export class Dedenne extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = P;
  public hp: number = 60;
  public weakness = [{ type: M }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Tail Smack',
      cost: [C],
      damage: 10,
      text: ''
    },
    {
      name: 'Dede-Short',
      cost: [L],
      damage: 60,
      text: 'You can use this attack only if 1 of your Togedemaru used Toge Dash during your last turn. Your opponent\'s Active Pokémon is now Paralyzed.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '85';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Dedenne';
  public fullName: string = 'Dedenne SIT 85';

  public togeDashTurn = -10;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Track when a Togedemaru used Toge Dash
    // Ref: set-unbroken-bonds/hitmontop.ts (Finishing Combo - track attack used last turn)
    if (effect instanceof AttackEffect && effect.attack.name === 'Toge Dash'
      && effect.player.active.getPokemonCard()?.name === 'Togedemaru') {
      this.togeDashTurn = state.turn;
    }

    // Attack 2: Dede-Short
    // Ref: set-unbroken-bonds/hitmontop.ts (Finishing Combo - attack only usable if partner used move last turn)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      if (state.turn !== this.togeDashTurn + 2) {
        throw new GameError(GameMessage.CANNOT_USE_ATTACK);
      }
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED(store, state, effect);
    }

    return state;
  }
}
