// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';

export class Delphox extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Braixen';
  public cardType: CardType = R;
  public hp: number = 150;
  public weakness = [{ type: W }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Flare Parade',
      cost: [C],
      damage: 60,
      damageCalculation: 'x' as 'x',
      text: 'This attack does 60 damage for each Serena card in your discard pile.'
    },
    {
      name: 'Energy Crush',
      cost: [C, C],
      damage: 50,
      damageCalculation: 'x' as 'x',
      text: 'This attack does 50 damage for each Energy attached to all of your opponent\'s Pokémon.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '27';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Delphox';
  public fullName: string = 'Delphox (SIT 27)';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Flare Parade
    // Ref: set-astral-radiance/zoroark.ts (count specific card name in discard pile)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const serenaCount = player.discard.cards.filter(c => c.name === 'Serena').length;
      effect.damage = 60 * serenaCount;
    }

    // Attack 2: Energy Crush
    // Ref: set-astral-radiance/oranguru-v.ts (CheckProvidedEnergyEffect - count total energy on all opponent Pokemon)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      let totalEnergyCount = 0;
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        const checkEnergy = new CheckProvidedEnergyEffect(opponent, cardList);
        store.reduceEffect(state, checkEnergy);
        totalEnergyCount += checkEnergy.energyMap.reduce((sum, em) => sum + em.provides.length, 0);
      });

      effect.damage = 50 * totalEnergyCount;
    }

    return state;
  }
}
