// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, GameMessage, ConfirmPrompt, PlayerType, SlotType, CardTarget } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, DRAW_CARDS } from '../../game/store/prefabs/prefabs';
import { AfterAttackEffect } from '../../game/store/effects/game-phase-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { ChoosePokemonPrompt } from '../../game/store/prompts/choose-pokemon-prompt';

export class Honchkrow extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Murkrow';
  public cardType: CardType = D;
  public hp: number = 120;
  public weakness = [{ type: L }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C, C];

  public usedCallouWings = false;

  public attacks = [
    {
      name: 'Triple Draw',
      cost: [C],
      damage: 0,
      text: 'Draw 3 cards.'
    },
    {
      name: 'Callous Wings',
      cost: [D, C, C],
      damage: 120,
      text: 'You may switch this Pokémon with 1 of your Benched Murkrow.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '107';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Honchkrow';
  public fullName: string = 'Honchkrow SIT 107';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Triple Draw
    // Ref: AGENTS-patterns.md (draw cards prefab)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      DRAW_CARDS(player, 3);
    }

    // Attack 2: Callous Wings
    // Ref: set-brilliant-stars/morpeko-v.ts (optional switch via AfterAttackEffect + ConfirmPrompt)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const hasMurkrowOnBench = player.bench.some(b =>
        b.cards.length > 0 && b.getPokemonCard()?.name === 'Murkrow'
      );
      if (hasMurkrowOnBench) {
        this.usedCallouWings = true;
      }
    }

    if (effect instanceof AfterAttackEffect && this.usedCallouWings) {
      this.usedCallouWings = false;
      const player = effect.player;

      const hasMurkrowOnBench = player.bench.some(b =>
        b.cards.length > 0 && b.getPokemonCard()?.name === 'Murkrow'
      );
      if (!hasMurkrowOnBench) {
        return state;
      }

      return store.prompt(state, new ConfirmPrompt(
        player.id,
        GameMessage.WANT_TO_SWITCH_POKEMON
      ), (wantToSwitch: boolean) => {
        if (wantToSwitch) {
          // Build blocked list: only allow Murkrow on bench
          const blocked: CardTarget[] = [];
          player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card, target) => {
            if (target.slot === SlotType.BENCH && card.name !== 'Murkrow') {
              blocked.push(target);
            }
          });

          store.prompt(state, new ChoosePokemonPrompt(
            player.id,
            GameMessage.CHOOSE_POKEMON_TO_SWITCH,
            PlayerType.BOTTOM_PLAYER,
            [SlotType.BENCH],
            { min: 1, max: 1, allowCancel: false, blocked }
          ), selected => {
            if (!selected || selected.length === 0) {
              return;
            }
            player.switchPokemon(selected[0]);
          });
        }
      });
    }

    if (effect instanceof EndTurnEffect) {
      this.usedCallouWings = false;
    }

    return state;
  }
}
