import { Card } from '../../game/store/card/card';

import { AlolanVulpixVArt, AlolanVulpixVSTARArt, ArchenArt, ArcheopsArt, ArticunoArt, BeheeyemArt, BeldumArt, BraixenArt, CandiceArt, CapturingAromaArt, CobalionArt, CrobatArt, DragoniteArt, DrakloakArt, ElgyemArt, EmergencyJellyArt, FeebasArt, ForestSealStoneArt, FurisodeGirlArt, GardevoirArt, HisuianBraviaryArt, KirliaArt, KlangArt, KlinkArt, KlinklangArt, LanceArt, LugiaVArt, LugiaVSTARArt, MeowsticArt, MismagiusArt, PalossandArt, PrimordialAltarArt, RadiantAlakazamArt, RadiantJirachiArt, RadiantTsareenaArt, RaichuArt, RaltsArt, RegenerativeEnergyArt, RegidragoVArt, RegidragoVSTARArt, RegielekiVArt, RegielekiVMAXArt, RuffletArt, SandygastArt, SerenaArt, SerperiorVArt, SerperiorVSTARArt, SnowruntArt, SpindaArt, UnidentifiedFossilArt, UrsalunaVArt, VGuardEnergyArt, WailordArt, WorkerArt, ZeraoraArt, ZubatArt } from './card-images';

export const setSilverTempest: Card[] = [
  new AlolanVulpixVArt(),
  new AlolanVulpixVSTARArt(),
  new ArchenArt(),
  new ArcheopsArt(),
  new ArticunoArt(),
  new BeheeyemArt(),
  new BraixenArt(),
  new CandiceArt(),
  new CapturingAromaArt(),
  new CobalionArt(),
  new CrobatArt(),
  new DragoniteArt(),
  new DrakloakArt(),
  new ElgyemArt(),
  new EmergencyJellyArt(),
  new FeebasArt(),
  new ForestSealStoneArt(),
  new FurisodeGirlArt(),
  new GardevoirArt(),
  new HisuianBraviaryArt(),
  new KirliaArt(),
  new KlangArt(),
  new KlinkArt(),
  new KlinklangArt(),
  new LanceArt(),
  new LugiaVArt(),
  new LugiaVSTARArt(),
  new MeowsticArt(),
  // new MetagrossArt(),
  new MismagiusArt(),
  new PalossandArt(),
  new PrimordialAltarArt(),
  new RadiantAlakazamArt(),
  new RadiantJirachiArt(),
  new RadiantTsareenaArt(),
  new RaichuArt(),
  new RaltsArt(),
  new RegenerativeEnergyArt(),
  new RegidragoVArt(),
  new RegidragoVSTARArt(),
  new RegielekiVArt(),
  new RegielekiVMAXArt(),
  new RuffletArt(),
  new SandygastArt(),
  new SerenaArt(),
  new SerperiorVArt(),
  new SerperiorVSTARArt(),
  new SnowruntArt(),
  new SpindaArt(),
  //new TerrakionArt(),
  new UnidentifiedFossilArt(),
  new UrsalunaVArt(),
  new VGuardEnergyArt(),
  new WailordArt(),
  new WorkerArt(),
  new ZeraoraArt(),
  new ZubatArt(),
  new BeldumArt()
];
