import { Card } from '../../game/store/card/card';
import { AlolanVulpixVArt, AlolanVulpixVSTARArt, ArcheopsArt, ArticunoArt, BeheeyemArt, BeldumArt, BraixenArt, CandiceArt, CapturingAromaArt, CobalionArt, CrobatArt, DragoniteArt, DrakloakArt, ElgyemArt, EmergencyJellyArt, FeebasArt, ForestSealStoneArt, FurisodeGirlArt, HisuianBraviaryArt, KirliaArt, KlangArt, KlinkArt, KlinklangArt, LugiaVArt, LugiaVSTARArt, MeowsticArt, MetagrossArt, PalossandArt, PrimordialAltarArt, RadiantAlakazamArt, RadiantJirachiArt, RadiantTsareenaArt, RaichuArt, RaltsArt, RegenerativeEnergyArt, RegidragoVArt, RegidragoVSTARArt, RegielekiVArt, RegielekiVMAXArt, RuffletArt, SandygastArt, SerenaArt, SerperiorVArt, SerperiorVSTARArt, UrsalunaVArt, VGuardEnergyArt, WailordArt, WorkerArt, ZeraoraArt, ZubatArt } from './card-images';

export const setSilverTempest: Card[] = [
  new AlolanVulpixVArt(),
  new AlolanVulpixVSTARArt(),
  new ArcheopsArt(),
  new ArticunoArt(),
  new BeheeyemArt(),
  new BraixenArt(),
  new CandiceArt(),
  new CapturingAromaArt(),
  new CobalionArt(),
  new CrobatArt(),
  new DragoniteArt(),
  new DrakloakArt(),
  new ElgyemArt(),
  new EmergencyJellyArt(),
  new FeebasArt(),
  new ForestSealStoneArt(),
  new FurisodeGirlArt(),
  new HisuianBraviaryArt(),
  new KirliaArt(),
  new KlangArt(),
  new KlinkArt(),
  new KlinklangArt(),
  new LugiaVArt(),
  new LugiaVSTARArt(),
  new MeowsticArt(),
  new MetagrossArt(),
  new PalossandArt(),
  new PrimordialAltarArt(),
  new RadiantAlakazamArt(),
  new RadiantJirachiArt(),
  new RadiantTsareenaArt(),
  new RaichuArt(),
  new RaltsArt(),
  new RegenerativeEnergyArt(),
  new RegidragoVArt(),
  new RegidragoVSTARArt(),
  new RegielekiVArt(),
  new RegielekiVMAXArt(),
  new RuffletArt(),
  new SandygastArt(),
  new SerenaArt(),
  new SerperiorVArt(),
  new SerperiorVSTARArt(),
  new UrsalunaVArt(),
  new VGuardEnergyArt(),
  new WailordArt(),
  new WorkerArt(),
  new ZeraoraArt(),
  new ZubatArt(),
  new BeldumArt()
];
