import { Card } from '../../game/store/card/card';
import { AlolanVulpixVArt, AlolanVulpixVSTARArt, ArcheopsArt, ArticunoArt, BeheeyemArt, BeldumArt, BraixenArt, CandiceArt, CapturingAromaArt, CobalionArt, DragoniteArt, ElgyemArt, EmergencyJellyArt, FeebasArt, ForestSealStoneArt, FurisodeGirlArt, HisuianBraviaryArt, KirliaArt, LugiaVArt, LugiaVSTARArt, MeowsticArt, MetagrossArt, PrimordialAltarArt, RadiantAlakazamArt, RadiantJirachiArt, RadiantTsareenaArt, RaichuArt, RaltsArt, RegenerativeEnergyArt, RegidragoVArt, RegidragoVSTARArt, RegielekiVArt, RegielekiVMAXArt, RuffletArt, SerenaArt, SerperiorVArt, SerperiorVSTARArt, UrsalunaVArt, VGuardEnergyArt, WailordArt, WorkerArt, ZeraoraArt } from './card-images';

export const setSilverTempest: Card[] = [
  new AlolanVulpixVArt(),
  new AlolanVulpixVSTARArt(),
  new ArcheopsArt(),
  new ArticunoArt(),
  new BeheeyemArt(),
  new BraixenArt(),
  new CandiceArt(),
  new CapturingAromaArt(),
  new CobalionArt(),
  new DragoniteArt(),
  new ElgyemArt(),
  new EmergencyJellyArt(),
  new FeebasArt(),
  new ForestSealStoneArt(),
  new FurisodeGirlArt(),
  new HisuianBraviaryArt(),
  new KirliaArt(),
  new LugiaVArt(),
  new LugiaVSTARArt(),
  new MeowsticArt(),
  new MetagrossArt(),
  new PrimordialAltarArt(),
  new RadiantAlakazamArt(),
  new RadiantJirachiArt(),
  new RadiantTsareenaArt(),
  new RaichuArt(),
  new RaltsArt(),
  new RegenerativeEnergyArt(),
  new RegidragoVArt(),
  new RegidragoVSTARArt(),
  new RegielekiVArt(),
  new RegielekiVMAXArt(),
  new RuffletArt(),
  new SerenaArt(),
  new SerperiorVArt(),
  new SerperiorVSTARArt(),
  new UrsalunaVArt(),
  new VGuardEnergyArt(),
  new WailordArt(),
  new WorkerArt(),
  new ZeraoraArt(),

  new BeldumArt(),
];
