// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameMessage, PlayerType, GameError } from '../../game';
import { ChooseCardsPrompt } from '../../game/store/prompts/choose-cards-prompt';
import { Effect } from '../../game/store/effects/effect';
import { AttackEffect } from '../../game/store/effects/game-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, SHUFFLE_DECK } from '../../game/store/prefabs/prefabs';

export class OmastarV extends PokemonCard {
  public tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 190;
  public weakness = [{ type: L }];
  public retreat = [C];

  public readonly CANT_ATTACK_MARKER = 'OMASTAR_V_TENTACLE_LOCK_MARKER';

  public attacks = [
    {
      name: 'Primal Guidance',
      cost: [C],
      damage: 0,
      text: 'Search your deck for up to 2 Pokémon that evolve from an Item card that has "Fossil" in its name and put them onto your Bench. Then, shuffle your deck.'
    },
    {
      name: 'Tentacle Lock',
      cost: [W, C, C],
      damage: 110,
      text: 'If the Defending Pokémon is an Evolution Pokémon, it can\'t attack during your opponent\'s next turn.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '35';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Omastar V';
  public fullName: string = 'Omastar V SIT 35';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Primal Guidance
    // Ref: set-astral-radiance/hisuian-lilligant-vstar.ts (blocked array for filtered deck search to bench)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length === 0) {
        return state;
      }

      const slots = player.bench.filter(b => b.cards.length === 0);
      if (slots.length === 0) {
        return state;
      }

      // Build blocked list: only Pokemon that evolve from a Fossil Item
      const blocked: number[] = [];
      player.deck.cards.forEach((c, index) => {
        const isFossilPokemon = c instanceof PokemonCard
          && c.evolvesFrom
          && c.evolvesFrom.toLowerCase().includes('fossil');
        if (!isFossilPokemon) {
          blocked.push(index);
        }
      });

      const maxPick = Math.min(2, slots.length);

      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_PUT_ONTO_BENCH,
        player.deck,
        {},
        { min: 0, max: maxPick, allowCancel: false, blocked }
      ), selected => {
        const cards = selected || [];
        cards.forEach((card, index) => {
          player.deck.moveCardTo(card, slots[index]);
          slots[index].pokemonPlayedTurn = state.turn;
        });
        SHUFFLE_DECK(store, state, player);
      });
    }

    // Attack 2: Tentacle Lock
    // Ref: set-unbroken-bonds/rhyperior.ts (Hefty Cannon - block attack if condition met)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      const defendingCard = opponent.active.getPokemonCard();

      if (defendingCard && defendingCard.stage !== Stage.BASIC) {
        opponent.active.marker.addMarker(this.CANT_ATTACK_MARKER, this);
        opponent.marker.addMarker(this.CANT_ATTACK_MARKER, this);
      }
    }

    if (effect instanceof AttackEffect && effect.player.active.marker.hasMarker(this.CANT_ATTACK_MARKER, this)) {
      throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
    }

    if (effect instanceof EndTurnEffect
      && effect.player.marker.hasMarker(this.CANT_ATTACK_MARKER, this)) {
      effect.player.marker.removeMarker(this.CANT_ATTACK_MARKER, this);
      effect.player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList: any) => {
        cardList.marker.removeMarker(this.CANT_ATTACK_MARKER, this);
      });
    }

    return state;
  }
}
