// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, SEARCH_YOUR_DECK_FOR_POKEMON_AND_PUT_ONTO_BENCH } from '../../game/store/prefabs/prefabs';

export class Phione extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 70;
  public weakness = [{ type: L }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Sea Feast',
      cost: [W],
      damage: 0,
      text: 'Search your deck for up to 3 Basic Water Pokémon and put them onto your Bench. Then, shuffle your deck.'
    },
    {
      name: 'Wave Splash',
      cost: [W],
      damage: 20,
      text: ''
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '45';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Phione';
  public fullName: string = 'Phione (SIT 45)';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Sea Feast
    // Ref: set-silver-tempest/murkrow.ts (SEARCH_YOUR_DECK_FOR_POKEMON_AND_PUT_ONTO_BENCH with type filter)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      return SEARCH_YOUR_DECK_FOR_POKEMON_AND_PUT_ONTO_BENCH(
        store, state, player,
        { stage: Stage.BASIC, cardType: CardType.WATER },
        { min: 0, max: 3, allowCancel: false }
      );
    }

    return state;
  }
}
