// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { GameMessage, StoreLike, State, StateUtils, ChoosePokemonPrompt, SlotType, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { RetreatEffect } from '../../game/store/effects/game-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { PutDamageEffect } from '../../game/store/effects/attack-effects';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED, YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED } from '../../game/store/prefabs/attack-effects';

export class SkuntankV extends PokemonCard {
  public tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = D;
  public hp: number = 210;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  // Track the opponent's Pokemon that retreated from the Active Spot during the opponent's last turn.
  // We store the card reference directly since PokemonCardList.clearEffects() wipes all custom markers
  // before the retreat swap completes, making marker-based tracking unreliable.
  // The CLEAR_RETREATED_MARKER is on the player-level marker (not cardlist) and is NOT cleared by clearEffects().
  // Ref: set-steam-siege/seedot.ts (2-marker pattern for opponent's next turn effects)
  public readonly CLEAR_RETREATED_MARKER = 'SKUNTANK_V_SIT_CLEAR_RETREATED_MARKER';

  // Card reference to the Pokemon that retreated during the opponent's last turn
  public retreatedCard: PokemonCard | null = null;

  public attacks = [
    {
      name: 'Pursuit Blast',
      cost: [C, C],
      damage: 0,
      text: 'This attack does 30 damage to 1 of your opponent\'s Benched Pokémon. If that Pokémon retreated from the Active Spot during your opponent\'s last turn, this attack does 120 damage instead. (Don\'t apply Weakness and Resistance for Benched Pokémon.)'
    },
    {
      name: 'Shrieking Poison',
      cost: [D, C, C],
      damage: 90,
      text: 'Your opponent\'s Active Pokémon is now Confused and Poisoned.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '108';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Skuntank V';
  public fullName: string = 'Skuntank V SIT 108';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Track opponent's retreats - store the retreating Pokemon card reference.
    // NOTE: We cannot use PokemonCardList markers here because clearEffects() wipes all custom markers
    // on the active slot before the retreat swap completes. Instead, we store the card reference directly.
    // Ref: set-steam-siege/seedot.ts (2-marker clear pattern for opponent's next turn timing)
    if (effect instanceof RetreatEffect) {
      const retreatingPlayer = effect.player;
      // Get the card that is retreating BEFORE the swap
      const retreatingCard = retreatingPlayer.active.getPokemonCard();
      if (retreatingCard) {
        this.retreatedCard = retreatingCard;
        // Place clear marker on the player so we clean up at end of opponent's turn
        retreatingPlayer.marker.addMarker(this.CLEAR_RETREATED_MARKER, this);
      }
    }

    // Clean up retreat tracking at end of the opponent's turn (the player who retreated)
    if (effect instanceof EndTurnEffect
      && effect.player.marker.hasMarker(this.CLEAR_RETREATED_MARKER, this)) {
      effect.player.marker.removeMarker(this.CLEAR_RETREATED_MARKER, this);
      this.retreatedCard = null;
    }

    // Attack 1: Pursuit Blast
    // Ref: set-plasma-blast/ducklett.ts (damage to 1 benched Pokemon), set-steam-siege/seedot.ts (marker check)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const hasBenched = opponent.bench.some(b => b.cards.length > 0);
      if (!hasBenched) {
        return state;
      }

      return store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON_TO_DAMAGE,
        PlayerType.TOP_PLAYER,
        [SlotType.BENCH],
        { min: 1, max: 1, allowCancel: false }
      ), selected => {
        if (!selected || selected.length === 0) {
          return;
        }

        const target = selected[0];
        const hasRetreated = this.retreatedCard !== null &&
          target.getPokemonCard() === this.retreatedCard;
        const damage = hasRetreated ? 120 : 30;

        const putDamage = new PutDamageEffect(effect, damage);
        putDamage.target = target;
        store.reduceEffect(state, putDamage);
      });
    }

    // Attack 2: Shrieking Poison
    // Ref: set-plasma-blast/amoonguss.ts (Miracle Powder - choose special condition)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED(store, state, effect);
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED(store, state, effect);
    }

    return state;
  }
}
