// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { HEAL_X_DAMAGE_FROM_THIS_POKEMON } from '../../game/store/prefabs/attack-effects';

export class Slurpuff extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Swirlix';
  public cardType: CardType = P;
  public hp: number = 120;
  public weakness = [{ type: M }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Draining Kiss',
      cost: [C, C],
      damage: 30,
      text: 'Heal 30 damage from this Pokémon.'
    },
    {
      name: 'Magical Shot',
      cost: [P, C, C],
      damage: 100,
      text: ''
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '84';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Slurpuff';
  public fullName: string = 'Slurpuff SIT 84';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Draining Kiss
    // Ref: set-plasma-blast/lileep.ts (Spiral Drain - heal 10 from this Pokemon)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      HEAL_X_DAMAGE_FROM_THIS_POKEMON(30, effect, store, state);
    }

    return state;
  }
}
