// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { HEAL_X_DAMAGE_FROM_THIS_POKEMON } from '../../game/store/prefabs/attack-effects';

export class Virizion extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 110;
  public weakness = [{ type: R }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Four as One',
      cost: [C],
      damage: 20,
      damageCalculation: '+' as '+',
      text: 'If Cobalion, Terrakion, and Keldeo are on your Bench, this attack does 70 more damage.'
    },
    {
      name: 'Leaf Drain',
      cost: [G, C],
      damage: 50,
      text: 'Heal 20 damage from this Pokémon.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'SIT';
  public setNumber: string = '14';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Virizion';
  public fullName: string = 'Virizion (SIT 14)';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Four as One
    // Ref: set-lost-thunder/dedenne-2.ts (count Pokemon with specific name on bench)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      let hasCobalion = false;
      let hasTerrakion = false;
      let hasKeldeo = false;

      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card) => {
        if (cardList === player.active) {
          return; // Skip active
        }
        const pokemonCard = cardList.getPokemonCard();
        if (pokemonCard) {
          if (pokemonCard.name === 'Cobalion') hasCobalion = true;
          if (pokemonCard.name === 'Terrakion') hasTerrakion = true;
          if (pokemonCard.name === 'Keldeo') hasKeldeo = true;
        }
      });

      if (hasCobalion && hasTerrakion && hasKeldeo) {
        effect.damage += 70;
      }
    }

    // Attack 2: Leaf Drain
    // Ref: set-plasma-blast/lileep.ts (Spiral Drain - HEAL_X_DAMAGE_FROM_THIS_POKEMON)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      HEAL_X_DAMAGE_FROM_THIS_POKEMON(20, effect, store, state);
    }

    return state;
  }
}
