import { Card } from '../../game/store/card/card';
import { DreepyArt, DrakloakArt, DragapultexArt, FroslassArt, BlisseyexArt, HandyFanArt, RotoStickArt, HasselArt, LegacyEnergyArt, LuxrayexArt, ScoopUpCycloneArt, TatsugiriArt, MightyenaArt, PoochyenaArt, AggronArt, AronArt, LaironArt, FarfetchdArt, AlakazamArt, PerformanceFluteArt, LuxioArt, WellspringMaskOgerponexArt, CarmineArt, KieranArt, ChanseyArt, MorpekoArt, BugCatchingSetArt } from './card-images';
import { BloodmoonUrsalunaexArt, CaretakerArt, CommunityCenterArt, EnhancedHammerArt, FroakieArt, FrogadierArt, GreninjaexArt, HyperAromaArt, IronLeavesArt, IronThornsexArt, LoveBallArt, LuckyHelmetArt, PerrinArt, PhioneArt, ScreamTailexArt, SurvivalCastArt, TealMaskOgerponexArt, UnfairStampArt } from './card-images';
export const setTwilightMasquerade: Card[] = [

  new AggronArt(),
  new AlakazamArt(),
  new AronArt(),
  new BlisseyexArt(),
  new CarmineArt(),
  new DreepyArt(),
  new DrakloakArt(),
  new DragapultexArt(),
  new FarfetchdArt(),
  new FroslassArt(),
  new HandyFanArt(),
  new HasselArt(),
  new LaironArt(),
  new LegacyEnergyArt(),
  new LuxioArt(),
  new LuxrayexArt(),
  new MightyenaArt(),
  new MorpekoArt(),
  new PerformanceFluteArt(),
  new PoochyenaArt(),
  new RotoStickArt(),
  new ScoopUpCycloneArt(),
  new TatsugiriArt(),
  new WellspringMaskOgerponexArt(),
  new KieranArt(),
  new BloodmoonUrsalunaexArt(),
  new CaretakerArt(),
  new CommunityCenterArt(),
  new EnhancedHammerArt(),
  new HyperAromaArt(),
  new IronLeavesArt(),
  new IronThornsexArt(),
  new LoveBallArt(),
  new LuckyHelmetArt(),
  new PerrinArt(),
  new PhioneArt(),
  new ScreamTailexArt(),
  new SurvivalCastArt(),
  new UnfairStampArt(),
  new TealMaskOgerponexArt(),
  new FroakieArt(),
  new FrogadierArt(),
  new GreninjaexArt(),
  new ChanseyArt(),
  new BugCatchingSetArt(),
];
