// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, BoardEffect } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GameError, GameMessage, PlayerType } from '../../game';
import { HealEffect } from '../../game/store/effects/game-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, ADD_MARKER, HAS_MARKER, REMOVE_MARKER_AT_END_OF_TURN } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_BURNED } from '../../game/store/prefabs/attack-effects';

export class HeatranVmax extends PokemonCard {
  public tags = [CardTag.POKEMON_VMAX];
  public stage: Stage = Stage.VMAX;
  public evolvesFrom: string = 'Heatran V';
  public cardType: CardType = R;
  public hp: number = 330;
  public weakness = [{ type: W }];
  public retreat = [C, C, C, C];

  public powers = [{
    name: 'Magma Gain',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn, if you have a Stadium in play, you may heal 50 damage from this Pokémon.'
  }];

  public attacks = [
    {
      name: 'Max Heat Burst',
      cost: [R, R, C],
      damage: 180,
      text: 'Your opponent\'s Active Pokémon is now Burned.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'ASR';
  public setNumber: string = '26';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Heatran VMAX';
  public fullName: string = 'Heatran VMAX (ASR 26)';

  public readonly MAGMA_GAIN_MARKER = 'HEATRAN_VMAX_ASR_MAGMA_GAIN_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Magma Gain
    // Ref: set-astral-radiance/wyrdeer.ts (Hurried Gait - once-per-turn activated ability with IS_ABILITY_BLOCKED + marker)
    // Ref: set-astral-radiance/heatran-v.ts (StateUtils.getStadiumCard for stadium check)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      if (HAS_MARKER(this.MAGMA_GAIN_MARKER, player, this)) {
        throw new GameError(GameMessage.POWER_ALREADY_USED);
      }

      const stadiumCard = StateUtils.getStadiumCard(state);
      if (stadiumCard === undefined) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      ADD_MARKER(this.MAGMA_GAIN_MARKER, player, this);

      // Find this Pokemon in play and heal it
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList, card) => {
        if (card === this) {
          const healEffect = new HealEffect(player, cardList, 50);
          store.reduceEffect(state, healEffect);
          cardList.addBoardEffect(BoardEffect.ABILITY_USED);
        }
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.MAGMA_GAIN_MARKER, this);

    // Attack 1: Max Heat Burst
    // Ref: set-astral-radiance/heatran-v.ts (Heat Burn - YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_BURNED)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_BURNED(store, state, effect);
    }

    return state;
  }
}
