import { Card } from '../../game/store/card/card';
import { AdamanArt, CancelingCologneArt, CylleneArt, DarkPatchArt, DarkraiVArt, DarkraiVSTARArt, DiancieArt, EnergyLotoArt, FeatherBallArt, GalladeArt, GapejawBogArt, GardeniasVigorArt, GrantArt, GutsyPickaxeArt, HisuianArcanineArt, HisuianBasculinArt, HisuianHeavyBallArt, HisuianSamurottVArt, HisuianSamurottVSTARArt, IridaArt, KeldeoArt, KleavorArt, LucarioVArt, LuxrayVArt, MantineArt, MightyenaArt, MiltankArt, OriginFormeDialgaVArt, OriginFormeDialgaVSTARArt, OriginFormePalkiaVArt, OriginFormePalkiaVSTARArt, RadiantGreninjaArt, RadiantHawluchaArt, RaltsArt, RegiceArt, RegidragoArt, RegielekiArt, RegigigasArt, RegirockArt, RegisteelArt, RoxanneArt, SpicySeasonedCurryArt, StarmieVArt, SupereffectiveGlassesArt, SwitchCartArt, TempleofSinnohArt, TrekkingShoesArt, WyrdeerVArt } from './card-images';



export const setAstralRadiance: Card[] = [
  
  new AdamanArt(),
  new CancelingCologneArt(),
  new CylleneArt(),
  new DarkPatchArt(),
  new DarkraiVArt(),
  new DarkraiVSTARArt(),
  new DiancieArt(),
  new EnergyLotoArt(),
  new FeatherBallArt(),
  new GalladeArt(),
  new GapejawBogArt(),
  new GardeniasVigorArt(),
  new GrantArt(),
  new GutsyPickaxeArt(),
  new HisuianArcanineArt(),
  new HisuianBasculinArt(),
  new HisuianHeavyBallArt(),
  new HisuianSamurottVArt(),
  new HisuianSamurottVSTARArt(),
  new IridaArt(),
  new KeldeoArt(),
  new KleavorArt(),
  new LucarioVArt(),
  new LuxrayVArt(),
  new MightyenaArt(),
  new MantineArt(),
  new MiltankArt(),
  new OriginFormeDialgaVArt(),
  new OriginFormeDialgaVSTARArt(),
  new OriginFormePalkiaVArt(),
  new OriginFormePalkiaVSTARArt(),
  new RadiantGreninjaArt(),
  new RadiantHawluchaArt(),
  new RaltsArt(),
  new RegiceArt(),
  new RegidragoArt(),
  new RegielekiArt(),
  new RegigigasArt(),
  new RegirockArt(),
  new RegisteelArt(),
  new RoxanneArt(),
  new SpicySeasonedCurryArt(),
  new StarmieVArt(),
  new SupereffectiveGlassesArt(),
  new SwitchCartArt(),
  new TempleofSinnohArt(),
  new TrekkingShoesArt(),
  new WyrdeerVArt(),
  
];
