import { Card } from '../../game/store/card/card';
import { AdamanArt, BronzorArt, CancelingCologneArt, CylleneArt, DarkPatchArt, DarkraiVArt, DarkraiVSTARArt, DiancieArt, EnergyLotoArt, FeatherBallArt, GalladeArt, GapejawBogArt, GardeniasVigorArt, GrantArt, GutsyPickaxeArt, HisuianArcanineArt, HisuianBasculegionArt, HisuianBasculinArt, HisuianGrowlitheArt, HisuianHeavyBallArt, HisuianOverqwilArt, HisuianQwilfishArt2, HisuianSamurottVArt, HisuianSamurottVSTARArt, IridaArt, JubilifeVillageArt, KeldeoArt, KleavorArt, KricketuneArt, LucarioVArt, LuxrayVArt, MagnetonArt, MantineArt, MightyenaArt, MiltankArt, OriginFormeDialgaVArt, OriginFormeDialgaVSTARArt, OriginFormePalkiaVArt, OriginFormePalkiaVSTARArt, RadiantGreninjaArt, RadiantHawluchaArt, RaltsArt, RegiceArt, RegidragoArt, RegielekiArt, RegigigasArt, RegirockArt, RegisteelArt, RoxanneArt, ShieldonArt, SpicySeasonedCurryArt, StarmieVArt, SupereffectiveGlassesArt, SwitchCartArt, TempleofSinnohArt, TrekkingShoesArt, UrsalunaArt, WyrdeerVArt, YanmaArt } from './card-images';



export const setAstralRadiance: Card[] = [

  new AdamanArt(),
  new BronzorArt(),
  new CancelingCologneArt(),
  new CylleneArt(),
  new DarkPatchArt(),
  new DarkraiVArt(),
  new DarkraiVSTARArt(),
  new DiancieArt(),
  new EnergyLotoArt(),
  new FeatherBallArt(),
  new GalladeArt(),
  new GapejawBogArt(),
  new GardeniasVigorArt(),
  new GrantArt(),
  new GutsyPickaxeArt(),
  new HisuianArcanineArt(),
  new HisuianBasculegionArt(),
  new HisuianBasculinArt(),
  new HisuianGrowlitheArt(),
  new HisuianHeavyBallArt(),
  new HisuianOverqwilArt(),
  new HisuianQwilfishArt2(),
  //new HisuianQwilfishArt(),
  new HisuianSamurottVArt(),
  new HisuianSamurottVSTARArt(),
  new IridaArt(),
  new JubilifeVillageArt(),
  new KeldeoArt(),
  new KleavorArt(),
  new KricketuneArt(),
  new LucarioVArt(),
  new LuxrayVArt(),
  new MagnetonArt(),
  new MightyenaArt(),
  new MantineArt(),
  new MiltankArt(),
  new OriginFormeDialgaVArt(),
  new OriginFormeDialgaVSTARArt(),
  new OriginFormePalkiaVArt(),
  new OriginFormePalkiaVSTARArt(),
  new RadiantGreninjaArt(),
  new RadiantHawluchaArt(),
  new RaltsArt(),
  new RegiceArt(),
  new RegidragoArt(),
  new RegielekiArt(),
  new RegigigasArt(),
  new RegirockArt(),
  new RegisteelArt(),
  new RoxanneArt(),
  new ShieldonArt(),
  new SpicySeasonedCurryArt(),
  new StarmieVArt(),
  new SupereffectiveGlassesArt(),
  new SwitchCartArt(),
  new TempleofSinnohArt(),
  new TrekkingShoesArt(),
  new UrsalunaArt(),
  new WyrdeerVArt(),
  new YanmaArt(),
];
