// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { TrainerCard } from '../../game/store/card/trainer-card';
import { TrainerType } from '../../game/store/card/card-types';
import { StoreLike, State, GameMessage, Card, ChooseCardsPrompt } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { TrainerEffect } from '../../game/store/effects/play-card-effects';
import { GameError } from '../../game/game-error';
import { CLEAN_UP_SUPPORTER, DRAW_CARDS } from '../../game/store/prefabs/prefabs';

function* playCard(next: Function, store: StoreLike, state: State,
  self: Kamado, effect: TrainerEffect): IterableIterator<State> {
  const player = effect.player;

  // Need at least 2 cards in hand (the Kamado card + 1 other to keep)
  // The effect.trainerCard is already moved to supporter zone before this runs
  if (player.hand.cards.length === 0) {
    CLEAN_UP_SUPPORTER(effect, player);
    throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
  }

  // Player chooses 1 card from hand to keep
  let keptCard: Card | undefined;
  yield store.prompt(state, new ChooseCardsPrompt(
    player,
    GameMessage.CHOOSE_CARDS,
    player.hand,
    {},
    { min: 1, max: 1, allowCancel: false }
  ), selected => {
    keptCard = selected && selected.length > 0 ? selected[0] : undefined;
    next();
  });

  if (!keptCard) {
    CLEAN_UP_SUPPORTER(effect, player);
    return state;
  }

  // Discard all other cards from hand
  const cardsToDiscard = player.hand.cards.filter(c => c !== keptCard);
  cardsToDiscard.forEach(card => {
    player.hand.moveCardTo(card, player.discard);
  });

  // Draw 4 cards
  DRAW_CARDS(player, 4);

  CLEAN_UP_SUPPORTER(effect, player);
  return state;
}

export class Kamado extends TrainerCard {
  public trainerType: TrainerType = TrainerType.SUPPORTER;
  public regulationMark: string = 'F';
  public set: string = 'ASR';
  public setNumber: string = '149';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Kamado';
  public fullName: string = 'Kamado ASR 149';
  public text: string = 'Choose a card in your hand, and discard the other cards. If you do, draw 4 cards. (If you have no other cards in your hand, you can\'t use this card.) You may play only 1 Supporter card during your turn.';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ref: set-astral-radiance/adaman.ts (generator pattern), set-battle-styles/sordward-and-shielbert.ts (choose card from hand)
    if (effect instanceof TrainerEffect && effect.trainerCard === this) {
      const player = effect.player;

      // Must have other cards (not just Kamado) to use this card
      // After move to supporter, check remaining hand cards
      player.hand.moveCardTo(effect.trainerCard, player.supporter);
      effect.preventDefault = true;

      if (player.hand.cards.length === 0) {
        // No other cards in hand - can't use
        player.supporter.moveCardTo(effect.trainerCard, player.hand);
        effect.preventDefault = false;
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }

      const generator = playCard(() => generator.next(), store, state, this, effect);
      return generator.next().value;
    }

    return state;
  }
}
