// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, THIS_POKEMON_DOES_DAMAGE_TO_ITSELF } from '../../game/store/prefabs/prefabs';

export class Poochyena extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = D;
  public hp: number = 60;
  public weakness = [{ type: G }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Gnaw',
      cost: [C],
      damage: 10,
      text: ''
    },
    {
      name: 'Slight Intrusion',
      cost: [C, C],
      damage: 30,
      text: 'This Pokémon also does 10 damage to itself.'
    }
  ];

  public regulationMark: string = 'F';
  public set: string = 'ASR';
  public setNumber: string = '95';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Poochyena';
  public fullName: string = 'Poochyena ASR 95';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Slight Intrusion
    // Ref: set-ex-hidden-legends/rhyhorn.ts (Take Down - self damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      THIS_POKEMON_DOES_DAMAGE_TO_ITSELF(store, state, effect, 10);
    }

    return state;
  }
}
