// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, MULTIPLE_COIN_FLIPS_PROMPT } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED } from '../../game/store/prefabs/attack-effects';

export class Malamar extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Inkay';
  public cardType: CardType = D;
  public hp: number = 120;
  public weakness = [{ type: G }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Eerie Wave',
      cost: [D, C],
      damage: 50,
      text: 'Your opponent\'s Active Pokémon is now Confused.'
    },
    {
      name: 'Random Peck',
      cost: [D, D, C],
      damage: 80,
      damageCalculation: '+' as '+',
      text: 'Flip 2 coins. This attack does 40 more damage for each heads.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'CPA';
  public setNumber: string = '45';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Malamar';
  public fullName: string = 'Malamar CPA';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Eerie Wave
    // Ref: AGENTS-patterns.md (YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_CONFUSED(store, state, effect);
    }

    // Attack 2: Random Peck
    // Ref: set-darkness-ablaze/escavalier.ts (Fury Cutter - MULTIPLE_COIN_FLIPS_PROMPT for bonus damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      MULTIPLE_COIN_FLIPS_PROMPT(store, state, player, 2, results => {
        const heads = results.filter(r => r).length;
        effect.damage += 40 * heads;
      });
    }

    return state;
  }
}
