// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, SuperType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameMessage, PlayerType, SlotType, MoveEnergyPrompt } from '../../game';
import { EnergyCard } from '../../game/store/card/energy-card';
import { Effect } from '../../game/store/effects/effect';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED, SHUFFLE_DECK } from '../../game/store/prefabs/prefabs';

export class PalkiaGx extends PokemonCard {
  public tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = N;
  public hp: number = 180;
  public weakness = [{ type: Y }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Spatial Control',
      cost: [W],
      damage: 0,
      text: 'Move any number of Energy from your Benched Pokémon to this Pokémon.'
    },
    {
      name: 'Hydro Pressure',
      cost: [C, C, C],
      damage: 60,
      damageCalculation: '+' as '+',
      text: 'This attack does 20 more damage times the amount of [W] Energy attached to this Pokémon.'
    },
    {
      name: 'Zero Vanish-GX',
      cost: [W, W, W, C, C],
      damage: 150,
      text: 'Shuffle all Energy from each of your opponent\'s Pokémon into their deck. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'UPR';
  public setNumber: string = '101';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Palkia-GX';
  public fullName: string = 'Palkia-GX UPR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Spatial Control
    // Ref: set-x-and-y/aromatisse.ts (Fairy Transfer - MoveEnergyPrompt)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      // Only allow moving from bench, only allow moving to active
      const blockedTo = player.bench.map((_, index) => {
        return { player: PlayerType.BOTTOM_PLAYER, slot: SlotType.BENCH, index } as import('../../game').CardTarget;
      });

      const blockedFrom = [{ player: PlayerType.BOTTOM_PLAYER, slot: SlotType.ACTIVE, index: 0 } as import('../../game').CardTarget];

      store.prompt(state, new MoveEnergyPrompt(
        player.id,
        GameMessage.MOVE_ENERGY_CARDS,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.BENCH, SlotType.ACTIVE],
        { superType: SuperType.ENERGY },
        { allowCancel: true, blockedTo, blockedFrom }
      ), transfers => {
        if (transfers === null) {
          return;
        }

        for (const transfer of transfers) {
          const source = StateUtils.getTarget(state, player, transfer.from);
          const target = StateUtils.getTarget(state, player, transfer.to);
          source.moveCardTo(transfer.card, target);
        }
      });
    }

    // Attack 2: Hydro Pressure
    // Ref: set-plasma-storm/lucario-2.ts (Hurricane Kick - count-based damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      const checkEnergy = new CheckProvidedEnergyEffect(player, player.active);
      store.reduceEffect(state, checkEnergy);

      let waterCount = 0;
      checkEnergy.energyMap.forEach(em => {
        waterCount += em.provides.filter(p => p === CardType.WATER || p === CardType.ANY).length;
      });

      effect.damage += 20 * waterCount;
    }

    // Attack 3: Zero Vanish-GX
    // Ref: set-crimson-invasion/nihilego-gx.ts (Symbiont-GX - GX pattern)
    if (WAS_ATTACK_USED(effect, 2, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      // Shuffle all Energy from each of opponent's Pokemon into their deck
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        const energyCards = cardList.cards.filter(c => c instanceof EnergyCard);
        energyCards.forEach(card => {
          cardList.moveCardTo(card, opponent.deck);
        });
      });

      SHUFFLE_DECK(store, state, opponent);
    }

    return state;
  }
}
