// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../game/store/card/card-types';
import { StoreLike, State, GameMessage } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../game/store/prompts/choose-cards-prompt';
import { WAS_ATTACK_USED, SHUFFLE_DECK } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP } from '../../game/store/prefabs/attack-effects';

export class Shaymin extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 80;
  public weakness = [{ type: R }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Coax',
      cost: [C],
      damage: 0,
      text: 'Search your deck for up to 3 Basic Pokémon of different types and put them onto your Bench. Then, shuffle your deck.'
    },
    {
      name: 'Soothing Scent',
      cost: [G, C],
      damage: 30,
      text: 'Your opponent\'s Active Pokémon is now Asleep.'
    }
  ];

  public set: string = 'UPR';
  public setNumber: string = '15';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Shaymin';
  public fullName: string = 'Shaymin UPR';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Coax
    // Refs: set-breakpoint/dunsparce.ts (Call for Family), set-surging-sparks/energy-search-pro.ts (differentTypes)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const emptyBenchSlots = player.bench.filter(b => b.cards.length === 0).length;
      if (emptyBenchSlots === 0 || player.deck.cards.length === 0) {
        return state;
      }

      const maxPokemon = Math.min(3, emptyBenchSlots);

      return store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_PUT_ONTO_BENCH,
        player.deck,
        { superType: SuperType.POKEMON, stage: Stage.BASIC },
        { min: 0, max: maxPokemon, allowCancel: false, differentTypes: true }
      ), selected => {
        const cards = selected || [];
        cards.forEach(card => {
          const emptySlot = player.bench.find(b => b.cards.length === 0);
          if (emptySlot) {
            player.deck.moveCardTo(card, emptySlot);
            emptySlot.pokemonPlayedTurn = state.turn;
          }
        });
        return SHUFFLE_DECK(store, state, player);
      });
    }

    // Attack 2: Soothing Scent
    // Ref: AGENTS-patterns.md (special conditions)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP(store, state, effect);
    }

    return state;
  }
}
