// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { GamePhase, StoreLike, State, StateUtils, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { KnockOutEffect } from '../../game/store/effects/game-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, REPLACE_MARKER_AT_END_OF_TURN, SEARCH_DECK_FOR_CARDS_TO_HAND } from '../../game/store/prefabs/prefabs';

export class Marshadow extends PokemonCard {
  public tags = [CardTag.RAPID_STRIKE];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = P;
  public hp: number = 80;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -30 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Rapid Hunt',
      cost: [C],
      damage: 0,
      text: 'Search your deck for up to 2 Rapid Strike cards, reveal them, and put them into your hand. Then, shuffle your deck.'
    },
    {
      name: 'Shadow Flicker',
      cost: [C],
      damage: 10,
      text: 'If the Defending Pokémon is Knocked Out during your next turn, take 1 more Prize card.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'EVS';
  public setNumber: string = '80';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Marshadow';
  public fullName: string = 'Marshadow EVS';

  public readonly SHADOW_FLICKER_MARKER = 'MARSHADOW_EVS_SHADOW_FLICKER_MARKER';
  public readonly CLEAR_SHADOW_FLICKER_MARKER = 'MARSHADOW_EVS_CLEAR_SHADOW_FLICKER_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Rapid Hunt
    // Ref: set-battle-styles/octillery.ts (search deck for Rapid Strike cards)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const blocked: number[] = [];
      player.deck.cards.forEach((card, index: number) => {
        if (!card.tags.includes(CardTag.RAPID_STRIKE)) {
          blocked.push(index);
        }
      });

      SEARCH_DECK_FOR_CARDS_TO_HAND(store, state, player, this,
        {},
        { min: 0, max: 2, allowCancel: true, blocked }
      );
    }

    // Attack 2: Shadow Flicker
    // Ref: set-guardians-rising/whimsicott.ts (The Wages of Fluff - extra prize if KO'd next turn)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      opponent.active.marker.addMarker(this.SHADOW_FLICKER_MARKER, this);
      player.marker.addMarker(this.SHADOW_FLICKER_MARKER, this);
    }

    if (effect instanceof KnockOutEffect && effect.target.marker.hasMarker(this.SHADOW_FLICKER_MARKER, this)) {
      if (state.phase !== GamePhase.ATTACK) {
        return state;
      }
      if (effect.prizeCount > 0) {
        effect.prizeCount += 1;
      }
    }

    // 2-phase cleanup
    if (effect instanceof EndTurnEffect
      && effect.player.marker.hasMarker(this.CLEAR_SHADOW_FLICKER_MARKER, this)) {
      effect.player.marker.removeMarker(this.CLEAR_SHADOW_FLICKER_MARKER, this);
      const opponent = StateUtils.getOpponent(state, effect.player);
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        cardList.marker.removeMarker(this.SHADOW_FLICKER_MARKER, this);
      });
    }

    REPLACE_MARKER_AT_END_OF_TURN(effect, this.SHADOW_FLICKER_MARKER, this.CLEAR_SHADOW_FLICKER_MARKER, this);

    return state;
  }
}
