// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';

export class Palpitoad extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Tympole';
  public cardType: CardType = F;
  public hp: number = 100;
  public weakness = [{ type: G }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Stampede',
      cost: [F],
      damage: 20,
      text: ''
    },
    {
      name: 'Tongue Slap',
      cost: [F, C, C],
      damage: 50,
      text: ''
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'EVS';
  public setNumber: string = '89';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Palpitoad';
  public fullName: string = 'Palpitoad EVS';
}
