// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP } from '../../game/store/prefabs/attack-effects';

export class Clefairy extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = P;
  public hp: number = 70;
  public weakness = [{ type: M }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Moonbeam',
      cost: [C],
      damage: 10,
      text: ''
    },
    {
      name: 'Metronome',
      cost: [P, P],
      damage: 20,
      text: 'Your opponent\'s Active Pokémon is now Asleep.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'RCL';
  public setNumber: string = '82';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Clefairy';
  public fullName: string = 'Clefairy RCL';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Metronome
    // Ref: set-plasma-blast/glalie.ts (Powder Snow - sleep opponent's active)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP(store, state, effect);
    }

    return state;
  }
}
