// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, MULTIPLE_COIN_FLIPS_PROMPT } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP } from '../../game/store/prefabs/attack-effects';

export class GalarianMrMime extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 80;
  public weakness = [{ type: M }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Icy Wind',
      cost: [C],
      damage: 10,
      text: 'Your opponent\'s Active Pokémon is now Asleep.'
    },
    {
      name: 'Triple Spin',
      cost: [W, C],
      damage: 20,
      damageCalculation: 'x' as 'x',
      text: 'Flip 3 coins. This attack does 20 damage for each heads.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'RCL';
  public setNumber: string = '37';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Galarian Mr. Mime';
  public fullName: string = 'Galarian Mr. Mime RCL';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Icy Wind
    // Ref: AGENTS-patterns.md (Asleep)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP(store, state, effect);
    }

    // Attack 2: Triple Spin
    // Ref: set-cosmic-eclipse/florges.ts (Petal Dance - MULTIPLE_COIN_FLIPS_PROMPT 3 coins)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      MULTIPLE_COIN_FLIPS_PROMPT(store, state, effect.player, 3, results => {
        const heads = results.filter(r => r).length;
        effect.damage = 20 * heads;
      });
    }

    return state;
  }
}
