// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { DISCARD_A_STADIUM_CARD_IN_PLAY } from '../../game/store/prefabs/attack-effects';

export class Gyarados extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Magikarp';
  public cardType: CardType = W;
  public hp: number = 180;
  public weakness = [{ type: L }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Wrack Down',
      cost: [C, C, C],
      damage: 90,
      text: ''
    },
    {
      name: 'Big Storm',
      cost: [W, W, C, C, C],
      damage: 200,
      text: 'Discard any Stadium in play.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'RCL';
  public setNumber: string = '40';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Gyarados';
  public fullName: string = 'Gyarados RCL';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Big Storm
    // Ref: set-dragons-majesty/gyarados.ts (Big Storm - DISCARD_A_STADIUM_CARD_IN_PLAY)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_A_STADIUM_CARD_IN_PLAY(state);
    }

    return state;
  }
}
