// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../game/store/card/card-types';
import { Card, ChooseCardsPrompt, ChoosePokemonPrompt, EnergyCard, GameMessage, PlayerType, SlotType, StoreLike, State, StateUtils } from '../../game';
import { DiscardCardsEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, COIN_FLIP_PROMPT, THIS_POKEMON_DOES_DAMAGE_TO_ITSELF } from '../../game/store/prefabs/prefabs';

export class Heliolisk extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Helioptile';
  public cardType: CardType = L;
  public hp: number = 110;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Eerie Impulse',
      cost: [L],
      damage: 0,
      text: 'Flip a coin. If heads, discard an Energy from 1 of your opponent\'s Pokémon.'
    },
    {
      name: 'Thunder',
      cost: [L, C],
      damage: 120,
      text: 'This Pokémon also does 30 damage to itself.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'RCL';
  public setNumber: string = '64';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Heliolisk';
  public fullName: string = 'Heliolisk RCL';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Eerie Impulse
    // Ref: set-cosmic-eclipse/absol.ts (choose opponent's pokemon, discard energy)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      COIN_FLIP_PROMPT(store, state, player, result => {
        if (result) {
          // Check if any opponent's Pokemon has Energy
          let hasEnergy = false;
          opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
            if (cardList.cards.some(c => c instanceof EnergyCard)) {
              hasEnergy = true;
            }
          });

          if (!hasEnergy) { return; }

          store.prompt(state, new ChoosePokemonPrompt(
            player.id,
            GameMessage.CHOOSE_POKEMON,
            PlayerType.TOP_PLAYER,
            [SlotType.ACTIVE, SlotType.BENCH],
            { min: 1, max: 1, allowCancel: false }
          ), selected => {
            if (!selected || selected.length === 0) { return; }
            const target = selected[0];

            const energyCards = target.cards.filter(c => c instanceof EnergyCard);
            if (energyCards.length === 0) { return; }

            if (energyCards.length === 1) {
              const discardEnergy = new DiscardCardsEffect(effect, energyCards);
              discardEnergy.target = target;
              store.reduceEffect(state, discardEnergy);
            } else {
              store.prompt(state, new ChooseCardsPrompt(
                player,
                GameMessage.CHOOSE_CARD_TO_DISCARD,
                target,
                { superType: SuperType.ENERGY },
                { min: 1, max: 1, allowCancel: false }
              ), cards => {
                const selected: Card[] = cards || [];
                if (selected.length > 0) {
                  const discardEnergy = new DiscardCardsEffect(effect, selected);
                  discardEnergy.target = target;
                  store.reduceEffect(state, discardEnergy);
                }
              });
            }
          });
        }
      });
    }

    // Attack 2: Thunder
    // Ref: set-rebel-clash/helioptile.ts (THIS_POKEMON_DOES_DAMAGE_TO_ITSELF)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      THIS_POKEMON_DOES_DAMAGE_TO_ITSELF(store, state, effect, 30);
    }

    return state;
  }
}
