// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PlayerType, StoreLike, State, StateUtils, GameError, GameMessage } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { EvolveEffect } from '../../game/store/effects/game-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { PUT_X_DAMAGE_COUNTERS_ON_YOUR_OPPONENTS_ACTIVE_POKEMON } from '../../game/store/prefabs/attack-effects';

export class Banette2 extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Shuppet';
  public cardType: CardType = P;
  public hp: number = 90;
  public weakness = [{ type: D }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Evolution Jammer',
      cost: [P],
      damage: 20,
      text: 'Your opponent can\'t play any Pokémon from his or her hand to evolve his or her Pokémon during his or her next turn.'
    },
    {
      name: 'Curse Deeply',
      cost: [P, C],
      damage: 0,
      text: 'Put 5 damage counters on your opponent\'s Active Pokémon.'
    }
  ];

  public set: string = 'ROS';
  public setNumber: string = '32';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Banette';
  public fullName: string = 'Banette ROS 32';

  public readonly BLOCK_EVOLVE_MARKER = 'BANETTE_ROS_BLOCK_EVOLVE_MARKER';
  public readonly CLEAR_BLOCK_EVOLVE_MARKER = 'BANETTE_ROS_CLEAR_BLOCK_EVOLVE_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Evolution Jammer
    // Ref: set-phantom-forces/spiritomb.ts (B Cancel - but blocks ALL opponent Pokemon, not just defending)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      // Mark all opponent's Pokemon
      opponent.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        cardList.marker.addMarker(this.BLOCK_EVOLVE_MARKER, this);
      });
      opponent.marker.addMarker(this.CLEAR_BLOCK_EVOLVE_MARKER, this);
    }

    // Block evolution on marked Pokemon
    if (effect instanceof EvolveEffect) {
      if (effect.target.marker.hasMarker(this.BLOCK_EVOLVE_MARKER, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }
    }

    // Cleanup
    if (effect instanceof EndTurnEffect && effect.player.marker.hasMarker(this.CLEAR_BLOCK_EVOLVE_MARKER, this)) {
      effect.player.marker.removeMarker(this.CLEAR_BLOCK_EVOLVE_MARKER, this);
      const opponent = StateUtils.getOpponent(state, effect.player);
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        cardList.marker.removeMarker(this.BLOCK_EVOLVE_MARKER, this);
      });
    }

    // Attack 2: Curse Deeply
    // Ref: AGENTS-patterns.md (damage counters)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      PUT_X_DAMAGE_COUNTERS_ON_YOUR_OPPONENTS_ACTIVE_POKEMON(5, store, state, effect);
    }

    return state;
  }
}
