// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PlayerType, StoreLike, State, StateUtils, GameMessage, CardList, ChooseCardsPrompt } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { CheckHpEffect } from '../../game/store/effects/check-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, MOVE_CARDS, SHUFFLE_DECK, DISCARD_ALL_ENERGY_FROM_POKEMON } from '../../game/store/prefabs/prefabs';

export class Jirachi extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = M;
  public hp: number = 70;
  public weakness = [{ type: R }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Diminutive Desire',
      cost: [M],
      damage: 0,
      text: 'Look at the top 7 cards of your deck and put 1 of them into your hand. Shuffle the other cards back into your deck.'
    },
    {
      name: 'Doom Desire',
      cost: [M, C],
      damage: 0,
      text: 'Discard all Energy attached to this Pokémon. The Defending Pokémon is Knocked Out at the end of your opponent\'s next turn.'
    }
  ];

  public set: string = 'ROS';
  public setNumber: string = '42';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Jirachi';
  public fullName: string = 'Jirachi ROS';

  public readonly DOOM_DESIRE_MARKER = 'JIRACHI_ROS_DOOM_DESIRE_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Diminutive Desire
    // Ref: set-unbroken-bonds/venonat.ts (Radar Eyes)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length === 0) {
        return state;
      }

      const deckTop = new CardList();
      player.deck.moveTo(deckTop, 7);

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        deckTop,
        {},
        { min: 1, max: 1, allowCancel: false }
      ), selected => {
        MOVE_CARDS(store, state, deckTop, player.hand, { cards: selected });
        deckTop.moveTo(player.deck);
        SHUFFLE_DECK(store, state, player);
      });
    }

    // Attack 2: Doom Desire
    // Refs: set-primal-clash/beedrill.ts (Allergic Shock - 2-phase KO marker), AGENTS-patterns.md (discard all energy)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      DISCARD_ALL_ENERGY_FROM_POKEMON(store, state, effect, player.active.getPokemonCard()!);

      opponent.active.marker.addMarker(this.DOOM_DESIRE_MARKER, this);
      opponent.marker.addMarker(this.DOOM_DESIRE_MARKER, this);
    }

    // Doom Desire: KO at end of opponent's next turn
    if (effect instanceof EndTurnEffect) {
      if (effect.player.marker.hasMarker(this.DOOM_DESIRE_MARKER, this)) {
        effect.player.marker.removeMarker(this.DOOM_DESIRE_MARKER, this);

        // KO any Pokemon that still has the doom desire marker
        effect.player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
          if (cardList.marker.hasMarker(this.DOOM_DESIRE_MARKER, this)) {
            cardList.marker.removeMarker(this.DOOM_DESIRE_MARKER, this);

            // Deal damage equal to HP to KO the Pokemon
            const checkHp = new CheckHpEffect(effect.player, cardList);
            store.reduceEffect(state, checkHp);
            cardList.damage = checkHp.hp;
          }
        });
      }
    }

    return state;
  }
}
