// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, DRAW_CARDS } from '../../game/store/prefabs/prefabs';

export class Togepi extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = Y;
  public hp: number = 40;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Sweet Kiss',
      cost: [C],
      damage: 10,
      text: 'Your opponent draws a card.'
    }
  ];

  public set: string = 'ROS';
  public setNumber: string = '43';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Togepi';
  public fullName: string = 'Togepi ROS';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Sweet Kiss
    // Ref: set-plasma-storm/snorlax.ts (opponent draw pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      DRAW_CARDS(opponent, 1);
    }

    return state;
  }
}
