// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class JangmoO extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = N;
  public hp: number = 60;
  public weakness = [{ type: Y }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Raging Claws',
      cost: [L, F],
      damage: 20,
      damageCalculation: '+' as '+',
      text: 'This attack does 10 more damage for each damage counter on this Pokémon.'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '160';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Jangmo-o';
  public fullName: string = 'Jangmo-o CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Raging Claws
    // Ref: AGENTS-patterns.md (damage counters on this Pokemon)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const damageCounters = player.active.damage / 10;
      effect.damage += damageCounters * 10;
    }

    return state;
  }
}
