// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PlayerType, StoreLike, State } from '../../game';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, COIN_FLIP_PROMPT } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED } from '../../game/store/prefabs/attack-effects';

export class Raichu extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Pikachu';
  public cardType: CardType = L;
  public hp: number = 120;
  public weakness = [{ type: F }];
  public resistance = [{ type: M, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Nuzzle',
      cost: [C],
      damage: 0,
      text: 'Flip a coin. If heads, your opponent\'s Active Pokémon is now Paralyzed.'
    },
    {
      name: 'Powerful Spark',
      cost: [L],
      damage: 20,
      damageCalculation: 'x' as 'x',
      text: 'This attack does 20 damage times the amount of [L] Energy attached to all of your Pokémon.'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '67';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Raichu';
  public fullName: string = 'Raichu CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Nuzzle
    // Ref: AGENTS-patterns.md (coin flip + paralyzed)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      COIN_FLIP_PROMPT(store, state, player, result => {
        if (result) {
          YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED(store, state, effect);
        }
      });
    }

    // Attack 2: Powerful Spark
    // Ref: set-team-up/shaymin.ts (Flower Storm - energy count across all Pokemon)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      let lightningEnergyCount = 0;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        const checkEnergy = new CheckProvidedEnergyEffect(player, cardList);
        store.reduceEffect(state, checkEnergy);
        checkEnergy.energyMap.forEach(em => {
          em.provides.forEach(t => {
            if (t === CardType.LIGHTNING || t === CardType.ANY) {
              lightningEnergyCount++;
            }
          });
        });
      });

      effect.damage = 20 * lightningEnergyCount;
    }

    return state;
  }
}
