// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, GameError, GameMessage, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { KnockOutOpponentEffect } from '../../game/store/effects/attack-effects';
import { WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, USE_ABILITY_ONCE_PER_TURN, ABILITY_USED, REMOVE_MARKER_AT_END_OF_TURN, DRAW_CARDS_UNTIL_CARDS_IN_HAND, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class SilvallyGx extends PokemonCard {
  public tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Type: Null';
  public cardType: CardType = C;
  public hp: number = 210;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public readonly DISK_RELOAD_MARKER = 'SILVALLY_GX_CEC_DISK_RELOAD_MARKER';

  public powers = [  {
    name: 'Disk Reload',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn (before your attack), you may draw cards until you have 5 cards in your hand.'
  }];

  public attacks = [
    {
      name: 'Brave Buddies',
      cost: [C, C],
      damage: 50,
      damageCalculation: '+' as '+',
      text: 'If you played a Supporter card from your hand during this turn, this attack does 70 more damage.'
    },
    {
      name: 'Silver Knight-GX',
      cost: [C, C],
      damage: 0,
      text: 'If your opponent\'s Active Pokémon is an Ultra Beast, it is Knocked Out. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '184';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Silvally-GX';
  public fullName: string = 'Silvally-GX CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Disk Reload
    // Ref: set-unified-minds/dragonite-gx.ts (Draw cards until X in hand ability pattern)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      if (player.hand.cards.length >= 5) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.DISK_RELOAD_MARKER, this);
      ABILITY_USED(player, this);

      DRAW_CARDS_UNTIL_CARDS_IN_HAND(player, 5);
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.DISK_RELOAD_MARKER, this);

    // Attack 1: Brave Buddies
    // Ref: set-unified-minds/dragonite-gx.ts (supporterTurn check pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.supporterTurn > 0) {
        effect.damage += 70;
      }
    }

    // Attack 2: Silver Knight-GX
    // Ref: set-lost-thunder/alolan-ninetales-gx.ts (Sublimation-GX - KO Ultra Beast)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      const pokemon = opponent.active.getPokemonCard();
      if (pokemon && pokemon.tags.includes(CardTag.ULTRA_BEAST)) {
        const dealDamage = new KnockOutOpponentEffect(effect, 999);
        dealDamage.target = opponent.active;
        store.reduceEffect(state, dealDamage);
      }
    }

    return state;
  }
}
