// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, COIN_FLIP_PROMPT, FLIP_UNTIL_TAILS_AND_COUNT_HEADS, SEARCH_DECK_FOR_CARDS_TO_HAND } from '../../game/store/prefabs/prefabs';

export class Delibird extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 90;
  public weakness = [{ type: M }];
  public retreat = [C];

  public attacks = [
    {
      name: 'All the Presents',
      cost: [C],
      damage: 0,
      text: 'Flip a coin until you get tails. For each heads, you may search your deck for a card and put it into your hand. Then, shuffle your deck.'
    },
    {
      name: 'Surprise Attack',
      cost: [W],
      damage: 40,
      text: 'Flip a coin. If tails, this attack does nothing.'
    }
  ];

  public set: string = 'GRI';
  public setNumber: string = '26';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Delibird';
  public fullName: string = 'Delibird GRI';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: All the Presents
    // Refs: set-sun-and-moon/pyukumuku.ts (flip until tails), set-x-and-y/zorua.ts (search deck for cards)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.deck.cards.length === 0) {
        return state;
      }

      return FLIP_UNTIL_TAILS_AND_COUNT_HEADS(store, state, player, heads => {
        if (heads > 0 && player.deck.cards.length > 0) {
          const maxCards = Math.min(heads, player.deck.cards.length);
          SEARCH_DECK_FOR_CARDS_TO_HAND(store, state, player, this,
            {},
            { min: 0, max: maxCards, allowCancel: true }
          );
        }
      });
    }

    // Attack 2: Surprise Attack
    // Ref: set-sun-and-moon/pelipper.ts (Fly - coin flip, tails does nothing)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      COIN_FLIP_PROMPT(store, state, player, result => {
        if (!result) {
          effect.damage = 0;
        }
      });
    }

    return state;
  }
}
