// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { EnergyCard, StoreLike, State, StateUtils, GameMessage, PlayerType, SlotType, ChoosePokemonPrompt } from '../../game';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { AttackEffect } from '../../game/store/effects/game-effects';
import { AfterAttackEffect, EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Gothitelle extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Gothorita';
  public cardType: CardType = P;
  public hp: number = 140;
  public weakness = [{ type: P }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Tractorbeam',
      cost: [P],
      damage: 0,
      text: 'Switch 1 of your opponent\'s Benched Pokémon with their Active Pokémon. This attack does 30 damage to the new Active Pokémon.'
    },
    {
      name: 'Link Blast',
      cost: [P, C],
      damage: 50,
      damageCalculation: '+' as '+',
      text: 'If this Pokémon and your opponent\'s Active Pokémon have the same amount of Energy attached to them, this attack does 80 more damage.'
    }
  ];

  public set: string = 'GRI';
  public setNumber: string = '54';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Gothitelle';
  public fullName: string = 'Gothitelle GRI';

  public usedTractorbeam: boolean = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Tractorbeam
    // Ref: set-destined-rivals/primeape.ts (Drag Off)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      this.usedTractorbeam = true;
    }

    if (effect instanceof AfterAttackEffect && this.usedTractorbeam) {
      this.usedTractorbeam = false;
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const hasBench = opponent.bench.some(b => b.cards.length > 0);
      if (!hasBench) {
        return state;
      }

      return store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON_TO_SWITCH,
        PlayerType.TOP_PLAYER,
        [SlotType.BENCH],
        { allowCancel: false }
      ), result => {
        const cardList = result[0];
        opponent.switchPokemon(cardList);

        const afterDamage = new DealDamageEffect(effect as AttackEffect, 30);
        afterDamage.target = opponent.active;
        store.reduceEffect(state, afterDamage);
      });
    }

    if (effect instanceof EndTurnEffect) {
      this.usedTractorbeam = false;
    }

    // Attack 2: Link Blast
    // Ref: set-sun-and-moon/toxapex.ts (Venoshock - conditional bonus damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const myEnergyCount = player.active.cards.filter(c => c instanceof EnergyCard).length;
      const oppEnergyCount = opponent.active.cards.filter(c => c instanceof EnergyCard).length;

      if (myEnergyCount === oppEnergyCount) {
        effect.damage += 80;
      }
    }

    return state;
  }
}
