// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType, SuperType } from '../../game/store/card/card-types';
import { StoreLike, State, GameMessage, Card } from '../../game';
import { EnergyCard } from '../../game/store/card/energy-card';
import { Effect } from '../../game/store/effects/effect';
import { ChooseCardsPrompt } from '../../game/store/prompts/choose-cards-prompt';
import { ShowCardsPrompt } from '../../game/store/prompts/show-cards-prompt';
import { StateUtils } from '../../game/store/state-utils';
import { WAS_ATTACK_USED, COIN_FLIP_PROMPT, SHUFFLE_DECK } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED } from '../../game/store/prefabs/attack-effects';

export class Delcatty extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Skitty';
  public cardType: CardType = C;
  public hp: number = 80;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Energy Salon',
      cost: [C],
      damage: 0,
      text: 'Search your deck for 3 different types of basic Energy cards, reveal them, and put them into your hand. Shuffle your deck afterward.'
    },
    {
      name: 'Fake Out',
      cost: [C, C],
      damage: 30,
      text: 'Flip a coin. If heads, your opponent\'s Active Pokémon is now Paralyzed.'
    }
  ];

  public set: string = 'XY';
  public setNumber: string = '105';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Delcatty';
  public fullName: string = 'Delcatty XY';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Energy Salon
    // Ref: set-team-up/dragonite.ts (Fast Call)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const basicEnergyInDeck = player.deck.cards.filter(c =>
        c instanceof EnergyCard && c.energyType === EnergyType.BASIC
      );

      if (basicEnergyInDeck.length === 0) {
        return SHUFFLE_DECK(store, state, player);
      }

      // Build blocked indices for non-basic-energy cards
      const blocked: number[] = [];
      player.deck.cards.forEach((card, index) => {
        if (!(card instanceof EnergyCard) || card.energyType !== EnergyType.BASIC) {
          blocked.push(index);
        }
      });

      state = store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        player.deck,
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC },
        { min: 0, max: 3, allowCancel: false, blocked, differentTypes: true }
      ), selected => {
        const cards: Card[] = selected || [];

        if (cards.length > 0) {
          store.prompt(state, new ShowCardsPrompt(
            opponent.id,
            GameMessage.CARDS_SHOWED_BY_THE_OPPONENT,
            cards
          ), () => {
            cards.forEach(card => {
              player.deck.moveCardTo(card, player.hand);
            });
          });
        }

        SHUFFLE_DECK(store, state, player);
      });
    }

    // Attack 2: Fake Out
    // Ref: set-dragons-exalted/tympole.ts (Bubble)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      COIN_FLIP_PROMPT(store, state, effect.player, result => {
        if (result) {
          YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED(store, state, effect);
        }
      });
    }

    return state;
  }
}
