// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, PlayerType } from '../../game';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, COIN_FLIP_PROMPT, THIS_POKEMON_DOES_DAMAGE_TO_ITSELF } from '../../game/store/prefabs/prefabs';

export class Quilladin extends PokemonCard {
  public readonly SCRUNCH_MARKER = 'QUILLADIN_SCRUNCH_MARKER';
  public readonly CLEAR_SCRUNCH_MARKER = 'QUILLADIN_CLEAR_SCRUNCH_MARKER';
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Chespin';
  public cardType: CardType = G;
  public hp: number = 90;
  public weakness = [{ type: R }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Scrunch',
      cost: [C],
      damage: 0,
      text: 'Flip a coin. If heads, prevent all damage done to this Pokémon by attacks during your opponent\'s next turn.'
    },
    {
      name: 'Wood Hammer',
      cost: [G, G, C],
      damage: 70,
      text: 'This Pokémon does 10 damage to itself.'
    }
  ];

  public set: string = 'XY';
  public setNumber: string = '13';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Quilladin';
  public fullName: string = 'Quilladin XY';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Scrunch
    // Ref: set-dragons-exalted/silcoon.ts (Harden - prevent damage marker)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      COIN_FLIP_PROMPT(store, state, player, result => {
        if (result) {
          player.active.marker.addMarker(this.SCRUNCH_MARKER, this);
          opponent.marker.addMarker(this.CLEAR_SCRUNCH_MARKER, this);
        }
      });
    }

    // Prevent all damage
    if (effect instanceof DealDamageEffect && effect.target.cards.includes(this)) {
      if (effect.target.marker.hasMarker(this.SCRUNCH_MARKER, this)) {
        effect.preventDefault = true;
        return state;
      }
    }

    // Cleanup markers at end of opponent's turn
    if (effect instanceof EndTurnEffect
      && effect.player.marker.hasMarker(this.CLEAR_SCRUNCH_MARKER, this)) {
      effect.player.marker.removeMarker(this.CLEAR_SCRUNCH_MARKER, this);
      const opponent = StateUtils.getOpponent(state, effect.player);
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        cardList.marker.removeMarker(this.SCRUNCH_MARKER, this);
      });
    }

    // Attack 2: Wood Hammer
    // Ref: set-dragons-exalted/seismitoad.ts (self-damage)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      THIS_POKEMON_DOES_DAMAGE_TO_ITSELF(store, state, effect, 10);
    }

    return state;
  }
}
