// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { UseAttackEffect } from '../../game/store/effects/game-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, COIN_FLIP_PROMPT, ADD_MARKER, HAS_MARKER, REMOVE_MARKER_AT_END_OF_TURN } from '../../game/store/prefabs/prefabs';

export class Horsea extends PokemonCard {
  public readonly SMOKESCREEN_MARKER = 'HORSEA_BST_SMOKESCREEN_MARKER';
  public readonly CLEAR_SMOKESCREEN_MARKER = 'HORSEA_BST_CLEAR_SMOKESCREEN_MARKER';
  public readonly SMOKESCREEN_USED_MARKER = 'HORSEA_BST_SMOKESCREEN_USED_MARKER';
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 60;
  public weakness = [{ type: L }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Smokescreen',
      cost: [W],
      damage: 10,
      text: 'During your opponent\'s next turn, if the Defending Pokémon tries to attack, your opponent flips a coin. If tails, that attack doesn\'t happen.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'BST';
  public setNumber: string = '31';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Horsea';
  public fullName: string = 'Horsea BST';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Smokescreen
    // Ref: set-evolutions/sandshrew.ts (Sand Attack - smokescreen pattern with UseAttackEffect intercept)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      ADD_MARKER(this.SMOKESCREEN_MARKER, opponent.active, this);
      ADD_MARKER(this.CLEAR_SMOKESCREEN_MARKER, opponent, this);
    }

    if (effect instanceof UseAttackEffect && HAS_MARKER(this.SMOKESCREEN_MARKER, effect.player.active, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (HAS_MARKER(this.SMOKESCREEN_USED_MARKER, opponent, this)) {
        return state;
      }

      effect.preventDefault = true;
      ADD_MARKER(this.SMOKESCREEN_USED_MARKER, opponent, this);

      COIN_FLIP_PROMPT(store, state, player, result => {
        if (result) {
          const useAttackEffect = new UseAttackEffect(player, effect.attack);
          store.reduceEffect(state, useAttackEffect);
        } else {
          const endTurnEffect = new EndTurnEffect(player);
          store.reduceEffect(state, endTurnEffect);
        }
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.SMOKESCREEN_USED_MARKER, this);

    if (effect instanceof EndTurnEffect) {
      if (HAS_MARKER(this.CLEAR_SMOKESCREEN_MARKER, effect.player, this)) {
        effect.player.marker.removeMarker(this.CLEAR_SMOKESCREEN_MARKER, this);
        const opponent = StateUtils.getOpponent(state, effect.player);
        opponent.forEachPokemon(PlayerType.TOP_PLAYER, cardList => {
          cardList.marker.removeMarker(this.SMOKESCREEN_MARKER, this);
        });
      }
    }

    return state;
  }
}
