import { Card } from '../../game/store/card/card';
import { BellsproutArt, BronzongArt, BrunoArt, CherrimArt, CherubiArt, CherylArt, DurantArt, EmpoleonVArt, EnergyRecyclerArt, EscapeRopeArt, FalinksArt, FanOfWavesArt, FlappleVArt, FlappleVMAXArt, HoundoomArt, HoundourArt, KorrinasFocusArt, KricketuneVArt, LevelBallArt, MimikyuVArt, NecrozmaVArt, OctilleryArt, RapidStrikeEnergyArt, RapidStrikeUrshifuVArt, RapidStrikeUrshifuVMAXArt, RemoraidArt, SingleStrikeEnergyArt, SingleStrikeUrshifuVArt, SingleStrikeUrshifuVMAXArt, StonjournerArt, StoutlandVArt, TapuKokoVArt, TapuKokoVMAXArt, ToolJammerArt, TowerOfDarknessArt, TowerOfWatersArt, TyranitarVArt, UrnOfVitalityArt, VictiniVArt, VictiniVMAXArt, VictreebelArt, WeepinbellArt } from './card-images';

export const setBattleStyles: Card[] = [

  new BellsproutArt(),
  new BronzongArt(),
  new BrunoArt(),
  new CherrimArt(),
  new CherubiArt(),
  new CherylArt(),
  new DurantArt(),
  new EnergyRecyclerArt(),
  new EmpoleonVArt(),
  new EscapeRopeArt(),
  new FanOfWavesArt(),
  new FlappleVArt(),
  new FlappleVMAXArt(),
  new HoundoomArt(),
  new HoundourArt(),
  new KricketuneVArt(),
  new KorrinasFocusArt(),
  new LevelBallArt(),
  new MimikyuVArt(),
  new NecrozmaVArt(),
  new OctilleryArt(),
  new RapidStrikeEnergyArt(),
  new RapidStrikeUrshifuVArt(),
  new RapidStrikeUrshifuVMAXArt(),
  new RemoraidArt(),
  new SingleStrikeEnergyArt(),
  new SingleStrikeUrshifuVArt(),
  new SingleStrikeUrshifuVMAXArt(),
  new StonjournerArt(),
  new StoutlandVArt(),
  new TapuKokoVArt(),
  new TapuKokoVMAXArt(),
  new ToolJammerArt(),
  new TowerOfDarknessArt(),
  new TowerOfWatersArt(),
  new TyranitarVArt(),
  new UrnOfVitalityArt(),
  new VictiniVArt(),
  new VictiniVMAXArt(),
  new VictreebelArt(),
  new WeepinbellArt(),
  new FalinksArt(),
];