import { Card } from '../../game/store/card/card';
import { AzelfArt, CeruledgeArt, CrocalorArt, CyranoArt, DeinoArt, EternatusArt, ExcitingStadiumArt, FuecocoArt, GravityMountainArt, HydreigonexArt, MagnemiteArt, MagnetonArt, MespritArt, MiloticexArt, MiraculousIntercomArt, NinetalesArt, PikachuexArt, ScrambleSwitchArt, SkeledirgeArt, TerapagosArt, TogekissArt, TogepiArt, TogeticArt, UxieArt, VivillionArt, ZweilousArt } from './card-images';

export const setSV8: Card[] = [
  new PikachuexArt(),
  new TerapagosArt(),
  new MagnemiteArt(),
  new MagnetonArt(),
  new ExcitingStadiumArt(),
  new GravityMountainArt(),
  new CyranoArt(),
  new MiraculousIntercomArt(),
  new FuecocoArt(),
  new CrocalorArt(),
  new SkeledirgeArt(),
  new MiloticexArt(),
  new TogepiArt(),
  new TogeticArt(),
  new TogekissArt(),
  new DeinoArt(),
  new ZweilousArt(),
  new HydreigonexArt(),
  new EternatusArt(),
  new VivillionArt(),
  new AzelfArt(),
  new UxieArt(),
  new MespritArt(),
  new ScrambleSwitchArt(),
  new NinetalesArt(),
  new CeruledgeArt(),
];
