// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, BoardEffect } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GameMessage, PlayerType, SlotType, ChoosePokemonPrompt, ConfirmPrompt } from '../../game';
import { CardTarget } from '../../game/store/actions/play-card-action';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED } from '../../game/store/prefabs/attack-effects';
import { PlayPokemonEffect } from '../../game/store/effects/play-card-effects';

export class Ariados extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Spinarak';
  public cardType: CardType = D;
  public hp: number = 110;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public powers = [{
    name: 'Spider Net',
    powerType: PowerType.ABILITY,
    text: 'When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may switch 1 of your opponent\'s Benched Evolution Pokémon with their Active Pokémon.'
  }];

  public attacks = [
    {
      name: 'Poison Sting',
      cost: [D, C],
      damage: 30,
      text: 'Your opponent\'s Active Pokémon is now Poisoned.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'DAA';
  public setNumber: string = '103';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Ariados';
  public fullName: string = 'Ariados DAA';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Spider Net (on-evolve - switch opponent's benched evolution with active)
    // Ref: set-guardians-rising/lycanroc-gx.ts (Bloodthirsty Eyes - PlayPokemonEffect + ConfirmPrompt + ChoosePokemonPrompt)
    if (effect instanceof PlayPokemonEffect && effect.pokemonCard === this) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Check if opponent has benched Evolution Pokemon
      const hasEvolutionOnBench = opponent.bench.some(b => {
        const card = b.getPokemonCard();
        return b.cards.length > 0 && card && card.stage !== Stage.BASIC;
      });

      if (!hasEvolutionOnBench) {
        return state;
      }

      state = store.prompt(state, new ConfirmPrompt(
        player.id,
        GameMessage.WANT_TO_USE_ABILITY,
      ), wantToUse => {
        if (wantToUse) {
          // Build blocked list - block non-evolution or empty slots
          const blocked: CardTarget[] = [];
          opponent.bench.forEach((b, index) => {
            const card = b.getPokemonCard();
            if (b.cards.length === 0 || !card || card.stage === Stage.BASIC) {
              blocked.push({ player: PlayerType.TOP_PLAYER, slot: SlotType.BENCH, index });
            }
          });

          return store.prompt(state, new ChoosePokemonPrompt(
            player.id,
            GameMessage.CHOOSE_POKEMON_TO_SWITCH,
            PlayerType.TOP_PLAYER,
            [SlotType.BENCH],
            { allowCancel: false, blocked }
          ), result => {
            if (!result || result.length === 0) {
              return;
            }

            // Mark ability used
            player.forEachPokemon(PlayerType.BOTTOM_PLAYER, cardList => {
              if (cardList.getPokemonCard() === this) {
                cardList.addBoardEffect(BoardEffect.ABILITY_USED);
              }
            });

            opponent.switchPokemon(result[0]);
          });
        }
      });
    }

    // Attack 1: Poison Sting
    // Ref: AGENTS-patterns.md (YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED(store, state, effect);
    }

    return state;
  }
}
