// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class ScizorVmax extends PokemonCard {
  public tags = [CardTag.POKEMON_VMAX];
  public stage: Stage = Stage.VMAX;
  public evolvesFrom: string = 'Scizor V';
  public cardType: CardType = M;
  public hp: number = 320;
  public weakness = [{ type: R }];
  public resistance = [{ type: G, value: -30 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Hard Scissors',
      cost: [M, C],
      damage: 90,
      text: 'During your opponent\'s next turn, this Pokémon takes 30 less damage from attacks (after applying Weakness and Resistance).'
    },
    {
      name: 'Max Steelspike',
      cost: [M, M, C],
      damage: 190,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'DAA';
  public setNumber: string = '119';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Scizor VMAX';
  public fullName: string = 'Scizor VMAX DAA';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Hard Scissors
    // Ref: set-rebel-clash/copperajah-v.ts (damage reduction marker pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      effect.player.active.damageReductionNextTurn = 30;
    }

    // Reduce damage taken
    

    // Cleanup at end of opponent's turn
    

    return state;
  }
}
