// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { DISCARD_X_ENERGY_FROM_THIS_POKEMON } from '../../game/store/prefabs/costs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED } from '../../game/store/prefabs/attack-effects';

export class Toxapex extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Mareanie';
  public cardType: CardType = W;
  public hp: number = 130;
  public weakness = [{ type: L }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Recover',
      cost: [C],
      damage: 0,
      text: 'Discard an Energy from this Pokémon and heal all damage from it.'
    },
    {
      name: 'Poisonous Whip',
      cost: [W, C, C],
      damage: 80,
      text: 'Your opponent\'s Active Pokémon is now Poisoned.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'DAA';
  public setNumber: string = '52';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Toxapex';
  public fullName: string = 'Toxapex DAA';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Recover
    // Ref: set-rebel-clash/alcremie.ts (DISCARD_X_ENERGY); AGENTS-patterns.md (heal all damage = damage = 0)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      DISCARD_X_ENERGY_FROM_THIS_POKEMON(store, state, effect, 1);
      // Heal all damage from this Pokemon
      effect.player.active.damage = 0;
    }

    // Attack 2: Poisonous Whip
    // Ref: AGENTS-patterns.md (YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED(store, state, effect);
    }

    return state;
  }
}
