/**
 * Centralized marker constants for the PTCG game
 * This file contains all marker names used throughout the game to avoid duplication
 */

export class MarkerConstants {
  // ===== COMMON MARKERS (used across multiple cards) =====
  public static readonly ATTACK_USED_MARKER = 'ATTACK_USED_MARKER';
  public static readonly ATTACK_USED_2_MARKER = 'ATTACK_USED_2_MARKER';
  public static readonly DAMAGE_DEALT_MARKER = 'DAMAGE_DEALT_MARKER';
  public static readonly KNOCKOUT_MARKER = 'KNOCKOUT_MARKER';
  public static readonly CLEAR_KNOCKOUT_MARKER = 'CLEAR_KNOCKOUT_MARKER';

  // ===== POKEMON CARD LIST SPECIFIC MARKERS =====
  public static readonly CLEAR_KNOCKOUT_MARKER_2 = 'CLEAR_KNOCKOUT_MARKER_2';
  public static readonly NEXT_TURN_MORE_DAMAGE_MARKER = 'NEXT_TURN_MORE_DAMAGE_MARKER';
  public static readonly NEXT_TURN_MORE_DAMAGE_MARKER_2 = 'NEXT_TURN_MORE_DAMAGE_MARKER_2';
  public static readonly PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN = 'PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN';
  public static readonly CLEAR_PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN = 'CLEAR_PREVENT_ALL_DAMAGE_AND_EFFECTS_DURING_OPPONENTS_NEXT_TURN';
  public static readonly PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN = 'PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN';
  public static readonly CLEAR_PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN = 'CLEAR_PREVENT_OPPONENTS_ACTIVE_FROM_ATTACKING_DURING_OPPONENTS_NEXT_TURN';
  public static readonly PREVENT_ALL_DAMAGE_BY_POKEMON_WITH_ABILITIES_MARKER = 'PREVENT_ALL_DAMAGE_BY_POKEMON_WITH_ABILITIES_MARKER';
  public static readonly PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER = 'PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER';
  public static readonly CLEAR_PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER = 'CLEAR_PREVENT_ALL_DAMAGE_DONE_BY_OPPONENTS_BASIC_POKEMON_MARKER';

  // ===== RETREAT PREVENTION MARKERS =====
  public static readonly DEFENDING_POKEMON_CANNOT_RETREAT_MARKER = 'DEFENDING_POKEMON_CANNOT_RETREAT_MARKER';
  public static readonly CANT_RETREAT_NEXT_TURN_MARKER = 'CANT_RETREAT_NEXT_TURN_MARKER';

  // ===== DAMAGE PREVENTION/MODIFICATION MARKERS =====
  public static readonly PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER = 'PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER';
  public static readonly CLEAR_PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER = 'CLEAR_PREVENT_DAMAGE_DURING_OPPONENTS_NEXT_TURN_MARKER';
  public static readonly DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER = 'DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER';
  public static readonly CLEAR_DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER = 'CLEAR_DURING_OPPONENTS_NEXT_TURN_TAKE_LESS_DAMAGE_MARKER';
  public static readonly PREVENT_KNOCKED_OUT_DURING_OPPONENTS_NEXT_TURN_MARKER = 'PREVENT_KNOCKED_OUT_DURING_OPPONENTS_NEXT_TURN_MARKER';
  public static readonly CLEAR_PREVENT_KNOCKED_OUT_DURING_OPPONENTS_NEXT_TURN_MARKER = 'CLEAR_PREVENT_KNOCKED_OUT_DURING_OPPONENTS_NEXT_TURN_MARKER';
  public static readonly DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER = 'DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER';
  public static readonly CLEAR_DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER = 'CLEAR_DURING_OPPONENTS_NEXT_TURN_DEFENDING_POKEMON_TAKES_MORE_DAMAGE_MARKER';
  public static readonly PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER = 'PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER';
  public static readonly CLEAR_PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER = 'CLEAR_PREVENT_DAMAGE_FROM_BASIC_POKEMON_MARKER';

  // ===== ATTACK PREVENTION MARKERS =====
  public static readonly OPPONENTS_POKEMON_CANNOT_USE_THAT_ATTACK_MARKER = 'OPPONENTS_POKEMON_CANNOT_USE_THAT_ATTACK_MARKER';
  public static readonly DEFENDING_POKEMON_CANNOT_ATTACK_MARKER = 'DEFENDING_POKEMON_CANNOT_ATTACK_MARKER';

  // ===== SPECIAL CONDITION MARKERS =====
  public static readonly SMOKESCREEN_MARKER = 'SMOKESCREEN_MARKER';
  public static readonly FROZEN_LOCK_MARKER = 'FROZEN_LOCK_MARKER';
  public static readonly SLUMBERING_MARKER = 'SLUMBERING_MARKER';

  // ===== ENERGY AND CARD EFFECT MARKERS =====
  public static readonly OPPONENT_CANNOT_PLAY_ITEM_CARDS_MARKER = 'OPPONENT_CANNOT_PLAY_ITEM_CARDS_MARKER';
  public static readonly U_TURN_BOARD_MARKER = 'U_TURN_BOARD_MARKER';
  public static readonly RECYCLE_ENERGY_MARKER = 'RECYCLE_ENERGY_MARKER';
  public static readonly ENERGY_GROUNDING_MARKER = 'ENERGY_GROUNDING_MARKER';

  // ===== ABILITY MARKERS =====
  public static readonly ABILITY_USED_MARKER = 'ABILITY_USED_MARKER';
  public static readonly HEARING_MARKER = 'HEARING_MARKER';
  public static readonly ILLUMINATE_MARKER = 'ILLUMINATE_MARKER';
  public static readonly PRECOGNITIVE_MARKER = 'PRECOGNITIVE_MARKER';

  // ===== SURGING SPARKS SET MARKERS =====
  public static readonly AMULET_OF_HOPE_MARKER = 'AMULET_OF_HOPE_MARKER';
  public static readonly ANGELITE_MARKER = 'ANGELITE_MARKER';
  public static readonly CLEAR_ANGELITE_MARKER = 'CLEAR_ANGELITE_MARKER';
  public static readonly BECKONING_TAIL_MARKER = 'BECKONING_TAIL_MARKER';
  public static readonly EVOLUTIONARY_ADVANTAGE_MARKER = 'EVOLUTIONARY_ADVANTAGE_MARKER';
  public static readonly JASMINES_GAZE_MARKER = 'JASMINES_GAZE_MARKER';
  public static readonly METAL_DEFENDER_MARKER = 'METAL_DEFENDER_MARKER';
  public static readonly CLEAR_METAL_DEFENDER_MARKER = 'CLEAR_METAL_DEFENDER_MARKER';
  public static readonly UP_TEMPO_MARKER = 'UP_TEMPO_MARKER';
  public static readonly FRIGID_FANGS_MARKER = 'FRIGID_FANGS_MARKER';

  // ===== PARADOX RIFT SET MARKERS =====
  public static readonly AKASHIC_SENSE_MARKER = 'AKASHIC_SENSE_MARKER';
  public static readonly CORNER_MARKER = 'CORNER_MARKER';
  public static readonly COUNTER_CATCHER_MARKER = 'COUNTER_CATCHER_MARKER';
  public static readonly ENERGIZING_ROCK_SALT_MARKER = 'ENERGIZING_ROCK_SALT_MARKER';
  public static readonly INCENDIARY_SONG_MARKER = 'INCENDIARY_SONG_MARKER';
  public static readonly MAGNETIC_ABSORPTION_MARKER = 'MAGNETIC_ABSORPTION_MARKER';
  public static readonly MAKE_IT_RAIN_MARKER = 'MAKE_IT_RAIN_MARKER';
  public static readonly MELA_MARKER = 'MELA_MARKER';
  public static readonly REFRIGERATED_STREAM_MARKER = 'REFRIGERATED_STREAM_MARKER';
  public static readonly RETALIATE_MARKER = 'RETALIATE_MARKER';
  public static readonly SCORCHING_HEATER_MARKER = 'SCORCHING_HEATER_MARKER';
  public static readonly CLEAR_SCORCHING_HEATER_MARKER = 'CLEAR_SCORCHING_HEATER_MARKER';
  public static readonly TACHYON_BITS_MARKER = 'TACHYON_BITS_MARKER';
  public static readonly TOXIC_POWDER_MARKER = 'TOXIC_POWDER_MARKER';

  // ===== CELESTIAL STORM SET MARKERS =====
  public static readonly BANETTE_GX_SHADY_MARKER = 'SHADY_MARKER';
  public static readonly EXCAVATE_MARKER = 'EXCAVATE_MARKER';
  public static readonly POWER_DRAW_MARKER = 'POWER_DRAW_MARKER';
  public static readonly SUDDEN_SHRIEK_MARKER = 'SUDDEN_SHRIEK_MARKER';

  // ===== UNIFIED MINDS SET MARKERS =====
  public static readonly DARK_MOON_MARKER = 'DARK_MOON_MARKER';
  public static readonly FLYINIUM_Z_MARKER = 'FLYINIUM_Z_MARKER';
  public static readonly HURRICANE_CHARGE_MARKER = 'HURRICANE_CHARGE_MARKER';

  // ===== ULTRA PRISM SET MARKERS =====
  public static readonly INVASION_MARKER = 'INVASION_MARKER';
  public static readonly ECLIPSE_MARKER = 'ECLIPSE_MARKER';
  public static readonly CLEAR_ECLIPSE_MARKER = 'CLEAR_ECLIPSE_MARKER';
  public static readonly TIMELESS_GX_MARKER = 'TIMELESS_GX_MARKER';
  public static readonly TIMELESS_GX_MARKER_2 = 'TIMELESS_GX_MARKER_2';
  public static readonly TERRIFY_MARKER = 'TERRIFY_MARKER';
  public static readonly CYNTHIA_MARKER = 'CYNTHIA_MARKER';

  // ===== EX DELTA SPECIES SET MARKERS =====
  public static readonly AGILITY_MARKER = 'AGILITY_MARKER';
  public static readonly BACKUP_MARKER = 'BACKUP_MARKER';
  public static readonly DELTA_CHARGE_MARKER = 'DELTA_CHARGE_MARKER';
  public static readonly DELTA_CONTROL_MARKER = 'DELTA_CONTROL_MARKER';
  public static readonly DUPLICATE_MARKER = 'DUPLICATE_MARKER';
  public static readonly ENERGY_JUMP_MARKER = 'ENERGY_JUMP_MARKER';
  public static readonly FLAME_SCREEN_MARKER = 'FLAME_SCREEN_MARKER';

  // ===== PCG P PROMOTIONAL CARDS MARKERS =====
  public static readonly DEFENSE_CURL_MARKER = 'DEFENSE_CURL_MARKER';
  public static readonly DETECT_MARKER = 'DETECT_MARKER';
  public static readonly IRON_DEFENSE_MARKER = 'IRON_DEFENSE_MARKER';

  // ===== MEGA EVOLUTION SET MARKERS =====
  public static readonly BIND_DOWN_MARKER = 'BIND_DOWN_MARKER';
  public static readonly GATHER_EVIDENCE_MARKER = 'GATHER_EVIDENCE_MARKER';
  public static readonly IRON_DEFENDER_MARKER = 'IRON_DEFENDER_MARKER';
  public static readonly LUSTER_ASSIST_MARKER = 'LUSTER_ASSIST_MARKER';
  public static readonly MEGA_BRAVE_MARKER = 'MEGA_BRAVE_MARKER';
  public static readonly CLEAR_MEGA_BRAVE_MARKER = 'CLEAR_MEGA_BRAVE_MARKER';
  public static readonly POWER_PROTEIN_MARKER = 'POWER_PROTEIN_MARKER';

  // ===== STELLAR CROWN SET MARKERS =====
  public static readonly BLOCK_HAMMER_MARKER = 'BLOCK_HAMMER_MARKER';
  public static readonly CLEAR_BLOCK_HAMMER_MARKER = 'CLEAR_BLOCK_HAMMER_MARKER';
  public static readonly JEWEL_HUNT_MARKER = 'JEWEL_HUNT_MARKER';
  public static readonly RIPE_CHARGE_MARKER = 'RIPE_CHARGE_MARKER';
  public static readonly SUDDEN_SCORCHING_MARKER = 'SUDDEN_SCORCHING_MARKER';

  // ===== CHAMPIONS PATH SET MARKERS =====
  public static readonly WICKED_RULER_MARKER = 'WICKED_RULER_MARKER';

  // ===== OTHER SPECIFIC MARKERS =====
  public static readonly AZURE_PULSE_MARKER = 'AZURE_PULSE_MARKER';
  public static readonly BARRIER_ATTACK_MARKER = 'BARRIER_ATTACK_MARKER';
  public static readonly BREAKING_SWIPE_MARKER = 'BREAKING_SWIPE_MARKER';
  public static readonly COTTON_LIFT_MARKER = 'COTTON_LIFT_MARKER';
  public static readonly DAUNT_MARKER = 'DAUNT_MARKER';
  public static readonly DELTA_REDUCTION_MARKER = 'DELTA_REDUCTION_MARKER';
  public static readonly DYNAMOTOR_MARKER = 'DYNAMOTOR_MARKER';
  public static readonly ECHOING_MADNESS_ITEM_LOCK_MARKER = 'ECHOING_MADNESS_ITEM_LOCK_MARKER';
  public static readonly ECHOING_MADNESS_SUPPORTER_LOCK_MARKER = 'ECHOING_MADNESS_SUPPORTER_LOCK_MARKER';
  public static readonly FLEET_FOOTED_MARKER = 'FLEET_FOOTED_MARKER';
  public static readonly FORME_CHANGE_MARKER = 'FORME_CHANGE_MARKER';
  public static readonly GROWL_MARKER = 'GROWL_MARKER';
  public static readonly HAYMAKER_MARKER_1 = 'HAYMAKER_MARKER_1';
  public static readonly HAYMAKER_MARKER_2 = 'HAYMAKER_MARKER_2';
  public static readonly MAGMA_RING_MARKER = 'MAGMA_RING_MARKER';
  public static readonly OMINOUS_POSTURE_MARKER = 'OMINOUS_POSTURE_MARKER';
  public static readonly PLUS_POWER_MARKER = 'PLUS_POWER_MARKER';
  public static readonly PSYCHIC_LOCK_MARKER = 'PSYCHIC_LOCK_MARKER';
  public static readonly QUICK_SHOOTING_MARKER = 'QUICK_SHOOTING_MARKER';
  public static readonly RAIHAN_MARKER = 'RAIHAN_MARKER';
  public static readonly REVENGE_MARKER = 'REVENGE_MARKER';
  public static readonly STEEL_WING_MARKER = 'STEEL_WING_MARKER';
  public static readonly TELEPASS_MARKER = 'TELEPASS_MARKER';
  public static readonly TOGEKISS_KNOCKOUT_FLIP = 'TOGEKISS_KNOCKOUT_FLIP';
  public static readonly YOGA_LOOP_MARKER = 'YOGA_LOOP_MARKER';

  // ===== ATTACK EFFECT LOCK MARKERS =====
  public static readonly ATTACK_EFFECT_SUPPORTER_LOCK = 'ATTACK_EFFECT_SUPPORTER_LOCK';
  public static readonly ATTACK_EFFECT_STADIUM_LOCK = 'ATTACK_EFFECT_STADIUM_LOCK';
  public static readonly ATTACK_EFFECT_TOOL_LOCK = 'ATTACK_EFFECT_TOOL_LOCK';
  public static readonly ATTACK_EFFECT_ITEM_LOCK = 'ATTACK_EFFECT_ITEM_LOCK';

  // ===== ADDITIONAL MARKERS FROM SETS =====
  public static readonly AUXILIARY_LIGHT_MARKER = 'AUXILIARY_LIGHT_MARKER';
  public static readonly GENTLE_FINS_MARKER = 'GENTLE_FINS_MARKER';
  public static readonly HEALING_LEAVES_MARKER = 'HEALING_LEAVES_MARKER';
  public static readonly HEAT_WAVE_SCALES_MARKER = 'HEAT_WAVE_SCALES_MARKER';
  public static readonly IGNITION_ENERGY_MARKER = 'IGNITION_ENERGY_MARKER';
  public static readonly MAGMA_SWITCH_MARKER = 'MAGMA_SWITCH_MARKER';
  public static readonly METAL_SIGNAL_MARKER = 'METAL_SIGNAL_MARKER';
  public static readonly OVERHEAT_MARKER = 'OVERHEAT_MARKER';
  public static readonly POISON_RING_MARKER = 'POISON_RING_MARKER';
  public static readonly POWER_SHIFT_MARKER = 'POWER_SHIFT_MARKER';
  public static readonly PRIMAL_WINGS_MARKER = 'PRIMAL_WINGS_MARKER';
  public static readonly STRONG_CURRENTS_MARKER = 'STRONG_CURRENTS_MARKER';
  public static readonly UNRELENTING_ONSLAUGHT_MARKER = 'UNRELENTING_ONSLAUGHT_MARKER';
  public static readonly UNRELENTING_ONSLAUGHT_2_MARKER = 'UNRELENTING_ONSLAUGHT_2_MARKER';

  // ===== ADDITIONAL MARKERS FROM SEARCH RESULTS =====
  public static readonly AIPOM_SNAPPY_MOVE_MARKER = 'SNAPPY_MOVE_MARKER';
  public static readonly AMPHAROS_UNSEEN_FLASH_MARKER = 'UNSEEN_FLASH_MARKER';
  public static readonly AUDINO_HEARING_MARKER = 'HEARING_MARKER';
  public static readonly AZELF_DEFENDING_POKEMON_CANNOT_RETREAT_MARKER = 'DEFENDING_POKEMON_CANNOT_RETREAT_MARKER';
  public static readonly BANETTE_GX_SHADY_MARKER_2 = 'SHADY_MARKER';
  public static readonly BEAUTIFLY_STOKED_STRAW_MARKER = 'STOKED_STRAW_MARKER';
  public static readonly BEHEEYEM_OPPONENT_CANNOT_PLAY_ITEM_CARDS_MARKER = 'OPPONENT_CANNOT_PLAY_ITEM_CARDS_MARKER';
  public static readonly BLASTOISE_AGILITY_MARKER = 'AGILITY_MARKER';
  public static readonly BRONZONG_METAL_LINKS_MARKER = 'METAL_LINKS_MARKER';
  public static readonly BUZZWOLE_GX_ATTACK_USED_MARKER = 'ATTACK_USED_MARKER';
  public static readonly BUZZWOLE_GX_ATTACK_USED_2_MARKER = 'ATTACK_USED_2_MARKER';
  public static readonly CHARGE_MARKER = 'CHARGE_MARKER';
  public static readonly CHIMECHO_OPPONENT_CANNOT_PLAY_ITEM_CARDS_MARKER = 'OPPONENT_CANNOT_PLAY_ITEM_CARDS_MARKER';
  public static readonly COALOSSAL_TAR_GENERATOR_MARKER = 'TAR_GENERATOR_MARKER';
  public static readonly COBALION_GX_IRON_RULE_MARKER = 'IRON_RULE_MARKER';
  public static readonly COMFEY_FLOWER_SELECTING_MARKER = 'FLOWER_SELECTING_MARKER';
  public static readonly COUNTERS_MARKER = 'COUNTERS_MARKER';
  public static readonly CLEAR_COUNTERS_MARKER = 'CLEAR_COUNTERS_MARKER';
  public static readonly CRUSHING_CHARGE_MARKER = 'CRUSHING_CHARGE_MARKER';
  public static readonly CURSE_MARKER = 'CURSE_MARKER';
  public static readonly DARK_ASSET_MARKER = 'DARK_ASSET_MARKER';
  public static readonly DARK_ELECTRODE_DARKNESS_NAVIGATION_MARKER = 'DARKNESS_NAVIGATION_MARKER';
  public static readonly DARK_DRAGONAIR_EVOLUTIONARY_LIGHT_MARKER = 'EVOLUTIONARY_LIGHT_MARKER';
  public static readonly DARK_IMPULSE_MARKER = 'DARK_IMPULSE_MARKER';
  public static readonly DAWN_WINGS_NECROZMA_GX_INVASION_MARKER = 'INVASION_MARKER';
  public static readonly DAWN_WINGS_NECROZMA_GX_ECLIPSE_MARKER = 'ECLIPSE_MARKER';
  public static readonly DAWN_WINGS_NECROZMA_GX_CLEAR_ECLIPSE_MARKER = 'CLEAR_ECLIPSE_MARKER';
  public static readonly DECIDUEYE_EX_TOTAL_FREEDOM_MARKER = 'TOTAL_FREEDOM_MARKER';
  public static readonly DEFENSE_CURL_MARKER_2 = 'DEFENSE_CURL_MARKER';
  public static readonly DETECT_MARKER_2 = 'DETECT_MARKER';
  public static readonly DIGLETT_SAND_PIT_MARKER = 'SAND_PIT_MARKER';
  public static readonly DISTORTION_DOOR_MARKER = 'DISTORTION_DOOR_MARKER';
  public static readonly DONPHAN_NEXT_TURN_MORE_DAMAGE_MARKER = 'NEXT_TURN_MORE_DAMAGE_MARKER';
  public static readonly DRAGONITE_STEP_IN_MARKER = 'STEP_IN_MARKER';
  public static readonly DRAGONITE_TAILWIND_MARKER = 'TAILWIND_MARKER';
  public static readonly DRAGONITE_TAILWIND_USED_MARKER = 'TAILWIND_USED_MARKER';
  public static readonly DUSKNOIR_DEFENDING_POKEMON_CANNOT_RETREAT_MARKER = 'DEFENDING_POKEMON_CANNOT_RETREAT_MARKER';
  public static readonly EISCUE_EX_SCALDING_BLOCK_MARKER = 'SCALDING_BLOCK_MARKER';
  public static readonly ELECTROPOWER_MARKER = 'ELECTROPOWER_MARKER';
  public static readonly EVOLUTION_ROAR_MARKER = 'EVOLUTION_ROAR_MARKER';
  public static readonly EXP_SHARE_MARKER = 'EXP_SHARE_MARKER';
  public static readonly FEZANDIPITI_EX_OPPONENT_KNOCKOUT_MARKER = 'OPPONENT_KNOCKOUT_MARKER';
  public static readonly FLARE_COMMAND_MARKER = 'FLARE_COMMAND_MARKER';
  public static readonly FLATTER_MARKER = 'FLATTER_MARKER';
  public static readonly FLUFFY_PILLOW_MARKER = 'FLUFFY_PILLOW_MARKER';
  public static readonly FORRETRESS_COUNTERS_MARKER = 'COUNTERS_MARKER';
  public static readonly FORRETRESS_CLEAR_COUNTERS_MARKER = 'CLEAR_COUNTERS_MARKER';
  public static readonly GARBODOR_POISON_STRUCTURE_MARKER = 'POISON_STRUCTURE_MARKER';
  public static readonly GATHER_MATERIALS_MARKER = 'GATHER_MATERIALS_MARKER';
  public static readonly GENGAR_NETHERWORLD_GATE_MARKER = 'NETHERWORLD_GATE_MARKER';
  public static readonly GIFT_ENERGY_MARKER = 'GIFT_ENERGY_MARKER';
  public static readonly GIRATINA_DISTORTION_DOOR_MARKER = 'DISTORTION_DOOR_MARKER';
  public static readonly GIRATINA_V_FLOWER_SELECTING_MARKER = 'FLOWER_SELECTING_MARKER';
  public static readonly GRAVELER_HARDEN_MARKER = 'HARDEN_MARKER';
  public static readonly GROVYLE_SUNSHINE_GRACE_MARKER = 'SUNSHINE_GRACE_MARKER';
  public static readonly HARDEN_MARKER = 'HARDEN_MARKER';
  public static readonly IRON_RULE_MARKER = 'IRON_RULE_MARKER';
  public static readonly METAL_LINKS_MARKER = 'METAL_LINKS_MARKER';
  public static readonly NETHERWORLD_GATE_MARKER = 'NETHERWORLD_GATE_MARKER';
  public static readonly OPPONENT_KNOCKOUT_MARKER = 'OPPONENT_KNOCKOUT_MARKER';
  public static readonly POISON_STRUCTURE_MARKER = 'POISON_STRUCTURE_MARKER';
  public static readonly SAND_PIT_MARKER = 'SAND_PIT_MARKER';
  public static readonly SCALDING_BLOCK_MARKER = 'SCALDING_BLOCK_MARKER';
  public static readonly STEP_IN_MARKER = 'STEP_IN_MARKER';
  public static readonly SUNSHINE_GRACE_MARKER = 'SUNSHINE_GRACE_MARKER';
  public static readonly TAILWIND_MARKER = 'TAILWIND_MARKER';
  public static readonly TAILWIND_USED_MARKER = 'TAILWIND_USED_MARKER';
  public static readonly TAR_GENERATOR_MARKER = 'TAR_GENERATOR_MARKER';
  public static readonly TOTAL_FREEDOM_MARKER = 'TOTAL_FREEDOM_MARKER';
  public static readonly UNSEEN_FLASH_MARKER = 'UNSEEN_FLASH_MARKER';

} 