// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../game';
import { EnergyCard } from '../../game/store/card/energy-card';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class Shelgon extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Bagon';
  public cardType: CardType = N;
  public hp: number = 80;
  public weakness = [{ type: Y }];
  public retreat = [C, C];

  public powers = [{
    name: 'Energy Guard',
    powerType: PowerType.ABILITY,
    text: 'If this Pokémon has any basic Energy attached to it, it takes 20 less damage from attacks (after applying Weakness and Resistance).'
  }];

  public attacks = [
    {
      name: 'Rollout',
      cost: [C, C],
      damage: 30,
      text: ''
    }
  ];

  public set: string = 'DRM';
  public setNumber: string = '43';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Shelgon';
  public fullName: string = 'Shelgon DRM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Energy Guard (passive - damage reduction)
    // Ref: set-celestial-storm/scizor-gx.ts (Steel Wing - DealDamageEffect damage reduction)
    if (effect instanceof DealDamageEffect && effect.target.cards.includes(this)
      && effect.target.getPokemonCard() === this) {
      const player = StateUtils.findOwner(state, effect.target);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      // Check if this Pokemon has any basic Energy attached
      const hasBasicEnergy = effect.target.cards.some(c =>
        c instanceof EnergyCard && c.energyType === EnergyType.BASIC
      );

      if (hasBasicEnergy) {
        effect.damage = Math.max(0, effect.damage - 20);
      }
    }

    return state;
  }
}
