// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { ADD_BURN_TO_PLAYER_ACTIVE, AFTER_ATTACK } from '../../game/store/prefabs/prefabs';
import { CardTag, CardType, Stage } from '../../game/store/card/card-types';
import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Effect } from '../../game/store/effects/effect';
import { State, StoreLike } from '../../game';
export class CoalossalV extends PokemonCard {
  public tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 220;
  public weakness = [{ type: G }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Searing Flame',
      cost: [F, F, C],
      damage: 90,
      text: 'Your opponent\'s Active Pokémon is now Burned.'
    },
    {
      name: 'Boulder Crush',
      cost: [F, F, F, C],
      damage: 180,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'VIV';
  public setNumber: string = '98';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Coalossal V';
  public fullName: string = 'Coalossal V VIV';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Searing Flame
    // Ref: set-champions-path/centiskorch.ts (Searing Flame - YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_BURNED)
    if (AFTER_ATTACK(effect, 0, this)) {
      ADD_BURN_TO_PLAYER_ACTIVE(store, state, effect.opponent, this);
    }

    return state;
  }
}
