// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PokemonCardList, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED } from '../../game/store/prefabs/attack-effects';

export class Cloyster extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Shellder';
  public cardType: CardType = W;
  public hp: number = 100;
  public weakness = [{ type: G }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Sudden Grip',
      cost: [W],
      damage: 10,
      text: 'If this Pokémon evolved from Shellder during this turn, your opponent\'s Active Pokémon is now Paralyzed.'
    },
    {
      name: 'Surf',
      cost: [W, C, C],
      damage: 70,
      text: ''
    }
  ];

  public set: string = 'BKP';
  public setNumber: string = '24';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Cloyster';
  public fullName: string = 'Cloyster BKP';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Sudden Grip
    // Ref: set-steam-siege/persian.ts (Raid - evolved this turn check)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const cardList = StateUtils.findCardList(state, this);
      if (cardList instanceof PokemonCardList && cardList.pokemonPlayedTurn === state.turn) {
        YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED(store, state, effect);
      }
    }

    return state;
  }
}
