// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, DISCARD_TOP_X_CARDS_FROM_YOUR_DECK } from '../../game/store/prefabs/prefabs';

export class Durant extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 70;
  public weakness = [{ type: R }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Mountain Munch',
      cost: [G],
      damage: 10,
      text: 'Discard the top card of your opponent\'s deck.'
    },
    {
      name: 'Scrape Down',
      cost: [G, C],
      damage: 0,
      text: 'If this Pokémon has any damage counters on it, discard the top 4 cards of your opponent\'s deck.'
    }
  ];

  public set: string = 'BKP';
  public setNumber: string = '9';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Durant';
  public fullName: string = 'Durant BKP';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Mountain Munch
    // Ref: set-steam-siege/avalugg.ts (Melting Floe)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      if (opponent.deck.cards.length > 0) {
        DISCARD_TOP_X_CARDS_FROM_YOUR_DECK(store, state, opponent, 1, this, effect);
      }
    }

    // Attack 2: Scrape Down
    // Ref: set-steam-siege/avalugg.ts (Melting Floe)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      if (player.active.damage > 0 && opponent.deck.cards.length > 0) {
        const cardsToDiscard = Math.min(4, opponent.deck.cards.length);
        DISCARD_TOP_X_CARDS_FROM_YOUR_DECK(store, state, opponent, cardsToDiscard, this, effect);
      }
    }

    return state;
  }
}
