// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { AfterAttackEffect, EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, SWITCH_ACTIVE_WITH_BENCHED } from '../../game/store/prefabs/prefabs';

export class Shinx extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = L;
  public hp: number = 60;
  public weakness = [{ type: F }];
  public resistance = [{ type: M, value: -20 }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Roar',
      cost: [C],
      damage: 0,
      text: 'Your opponent switches his or her Active Pokémon with 1 of his or her Benched Pokémon.'
    },
    {
      name: 'Flop',
      cost: [C],
      damage: 10,
      text: ''
    }
  ];

  public set: string = 'BKP';
  public setNumber: string = '44';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Shinx';
  public fullName: string = 'Shinx BKP';

  public usedRoar = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Roar
    // Ref: AGENTS-patterns.md (post-damage switching)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      this.usedRoar = true;
    }

    if (effect instanceof AfterAttackEffect && this.usedRoar) {
      this.usedRoar = false;
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);
      if (opponent.bench.some(b => b.cards.length > 0)) {
        SWITCH_ACTIVE_WITH_BENCHED(store, state, opponent);
      }
    }

    if (effect instanceof EndTurnEffect) {
      this.usedRoar = false;
    }

    return state;
  }
}
