// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Reshiram extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = R;
  public hp: number = 130;
  public weakness = [{ type: W }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Outrage',
      cost: [C, C],
      damage: 20,
      damageCalculation: '+' as '+',
      text: 'This attack does 10 more damage for each damage counter on this Pokémon.'
    },
    {
      name: 'Scorching Breath',
      cost: [R, R, C],
      damage: 130,
      text: 'This Pokémon can’t attack during your next turn.'
    }
  ];

  public set: string = 'SLG';
  public setNumber: string = '14';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Reshiram';
  public fullName: string = 'Reshiram SLG';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Outrage
    // Ref: set-noble-victories/kyurem.ts (Outrage)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      effect.damage += effect.player.active.damage;
    }

    // Attack 2: Scorching Breath
    // Ref: set-burning-shadows/rhyperior.ts (Rock Wrecker)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      effect.player.active.cannotAttackNextTurnPending = true;
    }

    return state;
  }
}
