// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../../game/store/card/card-types';
import { TrainerCard } from '../../../game/store/card/trainer-card';
import { GameMessage, PlayerType, PowerType, StoreLike, State, StateUtils } from '../../../game';
import { CheckPokemonTypeEffect } from '../../../game/store/effects/check-effects';
import { Effect } from '../../../game/store/effects/effect';
import { PokemonCardList } from '../../../game/store/state/pokemon-card-list';
import { IS_ABILITY_BLOCKED } from '../../../game/store/prefabs/prefabs';
import { HANDLE_ABILITY_LOCK } from '../../../game/store/prefabs/ability-lock';

export class Flareon extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Eevee';
  public cardType: CardType[] = [R];
  public hp: number = 110;
  public weakness = [{ type: W }];
  public retreat = [C, C];

  public powers = [{
    name: 'Incandescent Awakening',
    powerType: PowerType.ABILITY,
    text: 'If this Pokémon has a Memory Capsule attached, Grass Pokémon in play (both yours and your opponent\'s) have no Abilities.'
  }];

  public attacks = [
    {
      name: 'Fire Mane',
      cost: [R, R, C],
      damage: 100,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'VIV';
  public setNumber: string = '26';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Flareon';
  public fullName: string = 'Flareon VIV';

  private findFlareonInPlay(state: State): { cardList: PokemonCardList; owner: import('../../../game/store/state/player').Player } | null {
    for (const player of state.players) {
      let found: PokemonCardList | null = null;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        if (cardList.getPokemonCard() === this) {
          found = cardList;
        }
      });
      if (found) {
        return { cardList: found, owner: player };
      }
    }
    return null;
  }

  private hasMemoryCapsule(cardList: PokemonCardList): boolean {
    return cardList.tools.some(
      (tool) => tool instanceof TrainerCard && tool.name === 'Memory Capsule'
    );
  }

  private isGrassPokemon(store: StoreLike, state: State, card: PokemonCard): boolean {
    const targetCardList = StateUtils.findCardList(state, card);
    if (!(targetCardList instanceof PokemonCardList)) {
      return false;
    }
    const checkType = new CheckPokemonTypeEffect(targetCardList);
    store.reduceEffect(state, checkType);
    return checkType.cardTypes.includes(CardType.GRASS);
  }

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    const isTargetLocked = ({ card }: { card: PokemonCard }) => {
      if (!this.isGrassPokemon(store, state, card)) {
        return false;
      }

      const flareon = this.findFlareonInPlay(state);
      if (!flareon || !this.hasMemoryCapsule(flareon.cardList)) {
        return false;
      }

      if (IS_ABILITY_BLOCKED(store, state, flareon.owner, this)) {
        return false;
      }

      try {
        return StateUtils.findCardList(state, card) instanceof PokemonCardList;
      } catch {
        return false;
      }
    };

    HANDLE_ABILITY_LOCK(effect, ({ card }) => isTargetLocked({ card }), {
      allowUseFromHand: true,
      allowUseFromDiscard: true,
      error: GameMessage.BLOCKED_BY_EFFECT,
    });

    return state;
  }
}
