import { Card } from '../../game/store/card/card';
import { ArchaludonArt, AreaZeroUnderdepthsArt, BouffalantArt, BriarArt, ChewtleArt, CinderaceexArt, CrispinArt, DiancieArt, DrednawArt, DrifblimArt, ElectabuzzArt, FanRotomArt, GalvantulexaArt, GarganaclexArt, GlassTrumpetArt, GlisteningCrystalArt, GreatTreeArt, HoothootArt, HydrappleexArt, IronBoulderArt, JoltikArt, LaprasexArt, MedichamexArt, MedititeArt, NoctowlArt, RabootArt, RagingBoltArt, ScorbunnyArt, TerapagosexArt, ZeraoraArt } from './card-images';

export const setStellarCrown: Card[] = [
  new ArchaludonArt(),
  new AreaZeroUnderdepthsArt(),
  new BouffalantArt(),
  new BriarArt(),
  new ChewtleArt(),
  new CinderaceexArt(),
  new CrispinArt(),
  new DiancieArt(),
  new DrednawArt(),
  new DrifblimArt(),
  new ElectabuzzArt(),
  new FanRotomArt(),
  new GalvantulexaArt(),
  new GarganaclexArt(),
  new GlassTrumpetArt(),
  new GlisteningCrystalArt(),
  new GreatTreeArt(),
  new HoothootArt(),
  new HydrappleexArt(),
  new IronBoulderArt(),
  new JoltikArt(),
  new LaprasexArt(),
  new MedichamexArt(),
  new MedititeArt(),
  new NoctowlArt(),
  // new OrthwormexArt(),
  new RabootArt(),
  new RagingBoltArt(),
  new ScorbunnyArt(),
  new TerapagosexArt(),
  new ZeraoraArt(),

];
