// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, MULTIPLE_COIN_FLIPS_PROMPT, SEARCH_DECK_FOR_CARDS_TO_HAND } from '../../game/store/prefabs/prefabs';

export class AlolanRaticate extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Alolan Rattata';
  public cardType: CardType = D;
  public hp: number = 120;
  public weakness = [{ type: F }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Evil Orders',
      cost: [C, C],
      damage: 0,
      text: 'Search your deck for a number of cards up to the number of your Benched Pokémon and put them into your hand. Then, shuffle your deck.'
    },
    {
      name: 'Endeavor',
      cost: [D, C, C],
      damage: 60,
      damageCalculation: '+' as '+',
      text: 'Flip 2 coins. This attack does 30 more damage for each heads.'
    }
  ];

  public set: string = 'SUM';
  public setNumber: string = '77';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Alolan Raticate';
  public fullName: string = 'Alolan Raticate SUM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Evil Orders
    // Ref: set-x-and-y/zorua.ts (Nasty Plot - SEARCH_DECK_FOR_CARDS_TO_HAND)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const benchCount = player.bench.filter(b => b.cards.length > 0).length;

      if (benchCount === 0) {
        return state;
      }

      SEARCH_DECK_FOR_CARDS_TO_HAND(store, state, player, this,
        {},
        { min: 0, max: benchCount, allowCancel: true }
      );
    }

    // Attack 2: Endeavor
    // Ref: set-x-and-y/tauros.ts (Seething Anger - multiple coin flips)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      MULTIPLE_COIN_FLIPS_PROMPT(store, state, effect.player, 2, results => {
        effect.damage += 30 * results.filter(r => r).length;
      });
    }

    return state;
  }
}
