// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Poliwag extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 60;
  public weakness = [{ type: G }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Water Gun',
      cost: [W],
      damage: 10,
      text: ''
    },
    {
      name: 'Hydro Pump',
      cost: [C, C, C],
      damage: 30,
      damageCalculation: '+' as '+',
      text: 'This attack does 10 more damage times the amount of [W] Energy attached to this Pokémon.'
    }
  ];

  public set: string = 'SUM';
  public setNumber: string = '30';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Poliwag';
  public fullName: string = 'Poliwag SUM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Hydro Pump
    // Ref: set-team-up/lapras.ts (Hydro Pump)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      const checkEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkEnergy);

      let energyCount = 0;
      checkEnergy.energyMap.forEach(em => {
        energyCount += em.provides.filter(cardType =>
          cardType === CardType.WATER || cardType === CardType.ANY
        ).length;
      });
      effect.damage += energyCount * 10;
    }

    return state;
  }
}
