// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State, PlayerType, PokemonCardList } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { HealEffect } from '../../game/store/effects/game-effects';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON } from '../../game/store/prefabs/attack-effects';

export class PrimarinaGx extends PokemonCard {
  public tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Brionne';
  public cardType: CardType = W;
  public hp: number = 250;
  public weakness = [{ type: G }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Bubble Beat',
      cost: [C, C],
      damage: 10,
      damageCalculation: '+' as '+',
      text: 'This attack does 20 more damage times the amount of [W] Energy attached to your Pokémon.'
    },
    {
      name: 'Roaring Seas',
      cost: [W, W, W, C],
      damage: 120,
      text: 'Discard an Energy from your opponent\'s Active Pokémon.'
    },
    {
      name: 'Grand Echo-GX',
      cost: [C, C],
      damage: 0,
      text: 'Heal all damage from all of your Pokémon. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'SUM';
  public setNumber: string = '42';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Primarina-GX';
  public fullName: string = 'Primarina-GX SUM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Bubble Beat
    // Ref: set-sun-and-moon/espeon-gx.ts (Psychic - energy count)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      let waterEnergyCount = 0;

      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        const checkEnergy = new CheckProvidedEnergyEffect(player, cardList);
        store.reduceEffect(state, checkEnergy);
        checkEnergy.energyMap.forEach(em => {
          em.provides.forEach(type => {
            if (type === CardType.WATER || type === CardType.ANY) {
              waterEnergyCount++;
            }
          });
        });
      });

      effect.damage += 20 * waterEnergyCount;
    }

    // Attack 2: Roaring Seas
    // Ref: AGENTS-patterns.md (discard energy from opponent)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      DISCARD_AN_ENERGY_FROM_OPPONENTS_ACTIVE_POKEMON(store, state, effect);
    }

    // Attack 3: Grand Echo-GX
    // Ref: set-sun-and-moon/espeon-gx.ts (GX attack pattern), set-shrouded-fable/cresselia.ts (heal all)
    if (WAS_ATTACK_USED(effect, 2, this)) {
      const player = effect.player;

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList: PokemonCardList) => {
        if (cardList.damage > 0) {
          const healEffect = new HealEffect(player, cardList, cardList.damage);
          store.reduceEffect(state, healEffect);
        }
      });
    }

    return state;
  }
}
