// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../game/store/card/card-types';
import { Card, ChooseCardsPrompt, GameMessage, StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, MOVE_CARDS, DRAW_CARDS_UNTIL_CARDS_IN_HAND } from '../../game/store/prefabs/prefabs';

export class AlolanExeggutor2 extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Exeggcute';
  public cardType: CardType = N;
  public hp: number = 160;
  public weakness = [{ type: Y }];
  public retreat = [C, C, C, C];

  public attacks = [
    {
      name: 'Paradise Draw',
      cost: [],
      damage: 0,
      text: 'You may discard any number of cards from your hand. Then, draw cards until you have 6 cards in your hand.'
    },
    {
      name: 'Egg Splat',
      cost: [G, C],
      damage: 60,
      damageCalculation: 'x' as 'x',
      text: 'Discard any number of Exeggcute from your hand. This attack does 60 damage for each card you discarded in this way.'
    }
  ];

  public set: string = 'TEU';
  public setNumber: string = '115';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Alolan Exeggutor';
  public fullName: string = 'Alolan Exeggutor TEU 115';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Paradise Draw
    // Ref: set-celestial-storm/minun.ts (Ditch and Draw)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      if (player.hand.cards.length > 0) {
        state = store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_DISCARD,
          player.hand,
          {},
          { min: 0, max: player.hand.cards.length, allowCancel: false }
        ), (selected) => {
          const cards: Card[] = selected || [];
          if (cards.length > 0) {
            MOVE_CARDS(store, state, player.hand, player.discard, { cards });
          }
          DRAW_CARDS_UNTIL_CARDS_IN_HAND(player, 6);
        });
      } else {
        DRAW_CARDS_UNTIL_CARDS_IN_HAND(player, 6);
      }
    }

    // Attack 2: Egg Splat
    // Ref: set-ultra-prism/alolan-dugtrio.ts (Gold Rush)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      const exeggcuteCards = player.hand.cards.filter(c =>
        c instanceof PokemonCard && c.name === 'Exeggcute'
      );

      if (exeggcuteCards.length === 0) {
        effect.damage = 0;
        return state;
      }

      const blocked: number[] = [];
      player.hand.cards.forEach((card, index) => {
        if (card instanceof PokemonCard && card.name === 'Exeggcute') {
          return;
        }
        blocked.push(index);
      });

      state = store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.hand,
        { superType: SuperType.POKEMON },
        { allowCancel: true, min: 0, max: exeggcuteCards.length, blocked }
      ), cards => {
        cards = cards || [];
        if (cards.length === 0) {
          effect.damage = 0;
          return;
        }

        MOVE_CARDS(store, state, player.hand, player.discard, { cards, sourceCard: this });
        effect.damage = 60 * cards.length;
      });
    }

    return state;
  }
}
