// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, SWITCH_ACTIVE_WITH_BENCHED } from '../../game/store/prefabs/prefabs';
import { AfterAttackEffect, EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED } from '../../game/store/prefabs/attack-effects';

export class CrobatVmax extends PokemonCard {
  public tags = [CardTag.POKEMON_VMAX];
  public stage: Stage = Stage.VMAX;
  public evolvesFrom: string = 'Crobat V';
  public cardType: CardType = D;
  public hp: number = 300;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Stealth Poison',
      cost: [D, C],
      damage: 70,
      text: 'Your opponent\'s Active Pokémon is now Poisoned. Switch this Pokémon with 1 of your Benched Pokémon.'
    },
    {
      name: 'Max Cutter',
      cost: [D, D, C],
      damage: 180,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = '45';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Crobat VMAX';
  public fullName: string = 'Crobat VMAX SHF';

  public usedStealthPoison = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Stealth Poison
    // Ref: AGENTS-patterns.md (poison + AfterAttackEffect switch pattern)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_POISIONED(store, state, effect);
      this.usedStealthPoison = true;
    }

    if (effect instanceof AfterAttackEffect && this.usedStealthPoison) {
      const player = effect.player;
      if (player.bench.some(b => b.cards.length > 0)) {
        SWITCH_ACTIVE_WITH_BENCHED(store, state, player);
      }
    }

    if (effect instanceof EndTurnEffect) {
      this.usedStealthPoison = false;
    }

    return state;
  }
}
