// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { StoreLike, State } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, THIS_POKEMON_DOES_DAMAGE_TO_ITSELF } from '../../game/store/prefabs/prefabs';

export class Yanmega extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Yanma';
  public cardType: CardType = G;
  public hp: number = 120;
  public weakness = [{ type: R }];
  public retreat = [];

  public attacks = [
    {
      name: 'Bug Bite',
      cost: [G],
      damage: 30,
      text: ''
    },
    {
      name: 'Nosedive',
      cost: [G, C],
      damage: 120,
      text: 'This Pokémon also does 30 damage to itself.'
    }
  ];

  public regulationMark: string = 'E';
  public set: string = 'SHF';
  public setNumber: string = '2';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Yanmega';
  public fullName: string = 'Yanmega SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Nosedive
    // Ref: set-vivid-voltage/gogoat.ts (Take Down - THIS_POKEMON_DOES_DAMAGE_TO_ITSELF)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      THIS_POKEMON_DOES_DAMAGE_TO_ITSELF(store, state, effect, 30);
    }

    return state;
  }
}
