// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { Inteleon as InteleonCRE } from '../set-chilling-reign/inteleon';

export class Inteleon extends InteleonCRE {
  public set: string = 'EVS';
  public setNumber: string = '227';
  public fullName: string = 'Inteleon EVS';
}
