import { Card } from '../../game/store/card/card';
import { AdventureBagArt, AlolanMeowthArt, AlolanNinetalesGXArt, BlitzleArt, CascoonArt, ChikoritaArt, ChikoritaArt2, ChinchouArt, CounterGainArt, CustomCatcherArt, CutieflyArt, DittoPrismStarArt, ElectropowerArt, FabaArt, GirafarigArt, GiratinaArt, GranbullArt, GrovleArt, LostBlenderArt, MareepArt, MeganiumArt, MinaArt, NaganadelArt, NetBallArt, NihilegoArt, PoipoleArt, SlowkingArt, SnubbullArt, SpellTagArt, ThunderMountainPrismStarArt, TreeckoArt, WhiteKyuremArt, WurmpleArt, ZebstrikaArt, ZeraoraGXArt } from './card-images';

export const setLostThunder: Card[] = [
  new AdventureBagArt(),
  new AlolanMeowthArt(),
  new AlolanNinetalesGXArt(),
  new BlitzleArt(),
  new CascoonArt(),
  new ChikoritaArt(),
  new ChikoritaArt2(),
  new ChinchouArt(),
  new CounterGainArt(),
  new CustomCatcherArt(),
  new CutieflyArt(),
  new ElectropowerArt(),
  new FabaArt(),
  new GirafarigArt(),
  new GiratinaArt(),
  new GranbullArt(),
  new GrovleArt(),
  new LostBlenderArt(),
  new MareepArt(),
  new MeganiumArt(),
  new MinaArt(),
  new NaganadelArt(),
  new NetBallArt(),
  new NihilegoArt(),
  new PoipoleArt(),
  new SlowkingArt(),
  new SnubbullArt(),
  new SpellTagArt(),
  new ThunderMountainPrismStarArt(),
  new TreeckoArt(),
  new WhiteKyuremArt(),
  new WurmpleArt(),
  new ZebstrikaArt(),
  new ZeraoraGXArt(),
  new DittoPrismStarArt(),
];