import { Card } from '../../game/store/card/card';
import { AdventureBagArt, AlolanMeowthArt, BlitzleArt, ChikoritaArt, ChikoritaArt2, ChinchouArt, CounterGainArt, CustomCatcherArt, DittoPrismStarArt, ElectropowerArt, GirafarigArt, GiratinaArt, GrovleArt, LostBlenderArt, MareepArt, MeganiumArt, MinaArt, NetBallArt, NihilegoArt, SlowkingArt, SpellTagArt, ThunderMountainPrismStarArt, TreeckoArt, WhiteKyuremArt, WurmpleArt, ZebstrikaArt, ZeraoraGXArt } from './card-images';

export const setLostThunder: Card[] = [
  new AdventureBagArt(),
  new AlolanMeowthArt(),
  new BlitzleArt(),
  new ChikoritaArt(),
  new ChikoritaArt2(),
  new ChinchouArt(),
  new CounterGainArt(),
  new CustomCatcherArt(),
  new ElectropowerArt(),
  new GirafarigArt(),
  new GiratinaArt(),
  new GrovleArt(),
  new LostBlenderArt(),
  new MareepArt(),
  new MeganiumArt(),
  new MinaArt(),
  new NetBallArt(),
  new NihilegoArt(),
  new SlowkingArt(),
  new SpellTagArt(),
  new ThunderMountainPrismStarArt(),
  new TreeckoArt(),
  new WhiteKyuremArt(),
  new WurmpleArt(),
  new ZebstrikaArt(),
  new ZeraoraGXArt(),
  new DittoPrismStarArt(),
];