// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { GameMessage, PowerType, StoreLike, State, CardList, GameError } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { OrderCardsPrompt } from '../../game/store/prompts/order-cards-prompt';
import { WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, ABILITY_USED, USE_ABILITY_ONCE_PER_TURN, REMOVE_MARKER_AT_END_OF_TURN, BLOCK_IF_DECK_EMPTY, SHOW_CARDS_TO_PLAYER, COIN_FLIP_PROMPT } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED } from '../../game/store/prefabs/attack-effects';

export class Lapras extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 120;
  public weakness = [{ type: M }];
  public retreat = [C, C];

  public powers = [  {
    name: 'Go for a Swim',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn (before your attack), you may look at the top 2 cards of your deck and put them back in any order.'
  }];

  public attacks = [
    {
      name: 'Ice Beam',
      cost: [W, C],
      damage: 50,
      text: 'Flip a coin. If heads, your opponent\'s Active Pokémon is now Paralyzed.'
    }
  ];

  public set: string = 'LOT';
  public setNumber: string = '56';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Lapras';
  public fullName: string = 'Lapras LOT';

  public readonly GO_FOR_A_SWIM_MARKER = 'LAPRAS_LOT_GO_FOR_A_SWIM_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Go for a Swim
    // Ref: set-plasma-storm/lunatone.ts (Premonition)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      BLOCK_IF_DECK_EMPTY(player);
      USE_ABILITY_ONCE_PER_TURN(player, this.GO_FOR_A_SWIM_MARKER, this);
      ABILITY_USED(player, this);

      const count = Math.min(2, player.deck.cards.length);
      const deckTop = new CardList();
      player.deck.moveTo(deckTop, count);

      SHOW_CARDS_TO_PLAYER(store, state, player, deckTop.cards);

      return store.prompt(state, new OrderCardsPrompt(
        player.id,
        GameMessage.CHOOSE_CARDS_ORDER,
        deckTop,
        { allowCancel: false }
      ), order => {
        if (order !== null) {
          deckTop.applyOrder(order);
        }
        deckTop.moveToTopOfDestination(player.deck);
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.GO_FOR_A_SWIM_MARKER, this);

    // Attack 1: Ice Beam
    // Ref: set-celestial-storm/voltorb.ts (Thunder Shock)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      COIN_FLIP_PROMPT(store, state, effect.player, result => {
        if (result) {
          YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED(store, state, effect);
        }
      });
    }

    return state;
  }
}
