// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, PokemonCardList, GameMessage } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { JUST_EVOLVED, IS_ABILITY_BLOCKED, CONFIRMATION_PROMPT } from '../../game/store/prefabs/prefabs';

export class Pupitar extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Larvitar';
  public cardType: CardType = F;
  public hp: number = 70;
  public weakness = [{ type: G }];
  public retreat = [C, C, C];

  public powers = [  {
    name: 'Hard Shell Evolution',
    powerType: PowerType.ABILITY,
    text: 'When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may prevent all damage done to this Pokémon by your opponent\'s attacks until the end of your opponent\'s next turn.'
  }];

  public attacks = [
    {
      name: 'Hammer In',
      cost: [C, C, C],
      damage: 30,
      text: ''
    }
  ];

  public set: string = 'LOT';
  public setNumber: string = '116';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Pupitar';
  public fullName: string = 'Pupitar LOT';

  public readonly HARD_SHELL_MARKER: string = 'HARD_SHELL_EVOLUTION_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Hard Shell Evolution
    // Ref: set-burning-shadows/lucario.ts (Stance - on-evolve prevent damage)
    if (JUST_EVOLVED(effect, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      CONFIRMATION_PROMPT(store, state, player, wantToUse => {
        if (wantToUse) {
          const cardList = StateUtils.findCardList(state, this) as PokemonCardList;
          cardList.marker.addMarker(this.HARD_SHELL_MARKER, this);
        }
      }, GameMessage.WANT_TO_USE_ABILITY);

      return state;
    }

    // Prevent all damage from opponent's attacks while marker is active
    if (effect instanceof DealDamageEffect && effect.target.cards.includes(this) && effect.target.getPokemonCard() === this && effect.target.marker.hasMarker(this.HARD_SHELL_MARKER, this)) {
      effect.damage = 0;
      return state;
    }

    // Remove marker at end of opponent's turn
    if (effect instanceof EndTurnEffect) {
      const player = effect.player;
      const cardList = StateUtils.findCardList(state, this) as PokemonCardList;
      const owner = StateUtils.findOwner(state, cardList);

      if (owner !== player) {
        cardList.marker?.removeMarker(this.HARD_SHELL_MARKER, this);
      }
    }

    return state;
  }
}
