// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GamePhase } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { AfterDamageEffect } from '../../game/store/effects/attack-effects';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED, IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class SigilyphGx extends PokemonCard {
  public tags = [CardTag.POKEMON_GX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = P;
  public hp: number = 170;
  public weakness = [{ type: L }];
  public resistance = [{ type: F, value: -20 }];
  public retreat = [C, C];

  public powers = [{
    name: 'Mirror Counter',
    powerType: PowerType.ABILITY,
    text: 'If this Pokémon is your Active Pokémon and is damaged by an attack from your opponent\'s Pokémon-GX or Pokémon-EX (even if this Pokémon is Knocked Out), put damage counters on the Attacking Pokémon equal to the damage done to this Pokémon.'
  }];

  public attacks = [
    {
      name: 'Sonic Wing',
      cost: [P, C, C],
      damage: 80,
      text: 'This attack\'s damage isn\'t affected by Resistance.'
    },
    {
      name: 'Intercept-GX',
      cost: [P, C, C],
      damage: 60,
      damageCalculation: 'x' as 'x',
      text: 'This attack does 60 damage times the amount of Energy attached to your opponent\'s Active Pokémon. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'LOT';
  public setNumber: string = '98';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Sigilyph-GX';
  public fullName: string = 'Sigilyph-GX LOT';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Mirror Counter (passive - reflect damage from GX/EX)
    // Ref: set-steam-siege/bastiodon.ts (Counter Head - AfterDamageEffect reflection)
    if (effect instanceof AfterDamageEffect && effect.target.cards.includes(this)) {
      const targetPlayer = StateUtils.findOwner(state, effect.target);

      if (IS_ABILITY_BLOCKED(store, state, targetPlayer, this)) {
        return state;
      }

      if (effect.target.getPokemonCard() !== this) {
        return state;
      }

      // Must be active
      if (targetPlayer.active !== effect.target) {
        return state;
      }

      // Must be from opponent
      if (effect.player === targetPlayer) {
        return state;
      }

      // Must be from GX or EX
      const sourceCard = effect.source.getPokemonCard();
      if (!sourceCard || !(sourceCard.tags.includes(CardTag.POKEMON_GX) || sourceCard.tags.includes(CardTag.POKEMON_EX))) {
        return state;
      }

      if (effect.damage > 0 && state.phase === GamePhase.ATTACK) {
        effect.source.damage += effect.damage;
      }
    }

    // Attack 1: Sonic Wing
    // Ref: set-forbidden-light/zygarde.ts (Earthen Aura - ignore resistance)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      effect.ignoreResistance = true;
    }

    // Attack 2: Intercept-GX
    // Ref: set-dragons-majesty/altaria-gx.ts (GX attack pattern)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      const checkEnergy = new CheckProvidedEnergyEffect(opponent, opponent.active);
      store.reduceEffect(state, checkEnergy);

      const totalEnergy = checkEnergy.energyMap.reduce((total, p) => total + p.provides.length, 0);
      effect.damage = 60 * totalEnergy;
    }

    return state;
  }
}
