// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, GameError, GameMessage, GameWinner } from '../../game';
import { endGame } from '../../game/store/effect-reducers/check-effect';
import { Effect } from '../../game/store/effects/effect';
import { WAS_POWER_USED, IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class Unown2 extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = P;
  public hp: number = 60;
  public weakness = [{ type: P }];
  public retreat = [C];

  public powers = [  {
    name: 'HAND',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn (before your attack), if this Pokémon is your Active Pokémon, and if you have 35 or more cards in your hand, you may use this Ability. If you do, you win this game.'
  }];

  public attacks = [
    {
      name: 'Hidden Power',
      cost: [P],
      damage: 10,
      text: ''
    }
  ];

  public set: string = 'LOT';
  public setNumber: string = '91';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Unown';
  public fullName: string = 'Unown LOT 91';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: HAND
    // Ref: set-lost-thunder/unown-hand.ts (HAND - win game if 35+ cards in hand)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      if (player.active.getPokemonCard() !== this || player.hand.cards.length < 35) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      const owner = state.activePlayer;
      if (owner === 0) {
        state = endGame(store, state, GameWinner.PLAYER_1);
      }
      if (owner === 1) {
        state = endGame(store, state, GameWinner.PLAYER_2);
      }

      return state;
    }

    return state;
  }
}
