import { Card } from '../../game/store/card/card';
import { AbsolArt, ArchaludonArt, AreaZeroUnderdepthsArt, AxewArt, BindingMochiArt, BloodmoonUrsalunaArt, BriarArt, CassiopeiaArt, ColresssObsessionArt, CopperajahArt, CresseliaArt, CrispinArt, CufantArt, DangerousLaserArt, DartrixArt, DecidueyeArt, DrednawArt, DrifblimArt, DusclopsArt, DusknoirArt, DuskullArt, FanRotomArt, FezandipitiexArt, FraxureArt, GalvantulaArt, GlassTrumpetArt, GlisteningCrystalArt, GreatTreeArt, HaxorusArt, HoothootArt, HorseaArt, HoundoomArt, HoundourArt, HydrappleexArt, IronMothArt, JaninesSecretTechniqueArt, JoltikArt, KingdraexArt, KyuremArt, LaprasexArt, MunkidoriexArt, NeutralCenterArt, NightTimeAcademyArt, NightlyStretcherArt, NoctowlArt, OkidogiexArt, PecharuntexArt, PokeVitalAArt, PowerHourglassArt, RevavroomexArt, RowletArt, SeadraArt, SlitherWingArt, SneaselArt, TapuBuluArt, TerapagosexArt, WeavileArt, XerosicsSchemeArt, ZeraoraArt, ZoroarkArt, ZoruaArt } from './card-images';

export const setSV7: Card[] = [
  new AbsolArt(),
  new ArchaludonArt(),
  new AreaZeroUnderdepthsArt(),
  new AxewArt(),
  new BindingMochiArt(),
  new BloodmoonUrsalunaArt(),
  new BriarArt(),
  new CassiopeiaArt(),
  new ColresssObsessionArt(),
  new CopperajahArt(),
  new CresseliaArt(),
  new CrispinArt(),
  new CufantArt(),
  new DangerousLaserArt(),
  new DartrixArt(),
  new DecidueyeArt(),
  new DrednawArt(),
  new DrifblimArt(),
  new DusclopsArt(),
  new DusknoirArt(),
  new DuskullArt(),
  new FanRotomArt(),
  new FezandipitiexArt(),
  new FraxureArt,
  new GalvantulaArt(),
  // new GenesectArt(),
  new GlassTrumpetArt(),
  new GlisteningCrystalArt(),
  new GreatTreeArt(),
  new HaxorusArt(),
  new HoothootArt(),
  new HorseaArt(),
  new HoundoomArt(),
  new HoundourArt(),
  new HydrappleexArt(),
  new IronMothArt(),
  new JaninesSecretTechniqueArt(),
  new JoltikArt(),
  new KingdraexArt(),
  new KyuremArt(),
  new LaprasexArt(),
  new MunkidoriexArt(),
  new NeutralCenterArt(),
  new NightTimeAcademyArt(),
  new NightlyStretcherArt(),
  new NoctowlArt(),
  new OkidogiexArt(),
  // new OrthwormexArt(),
  new PecharuntexArt(),
  new PokeVitalAArt(),
  new PowerHourglassArt(),
  new RevavroomexArt(),
  new RowletArt(),
  new SeadraArt(),
  new SlitherWingArt(),
  new SneaselArt(),
  new TapuBuluArt(),
  new TerapagosexArt(),
  new WeavileArt(),
  new XerosicsSchemeArt(),
  new ZeraoraArt(),
  new ZoroarkArt(),
  new ZoruaArt(),

];
