import { Card } from '../../game/store/card/card';
import { AbsolArt, AxewArt, BindingMochiArt, BloodmoonUrsalunaArt, CassiopeiaArt, ColresssObsessionArt, CopperajahArt, CresseliaArt, CufantArt, DangerousLaserArt, DartrixArt, DecidueyeArt, DusclopsArt, DusknoirArt, DuskullArt, FezandipitiexArt, FraxureArt, HaxorusArt, HorseaArt, HoundoomArt, HoundourArt, JaninesSecretTechniqueArt, KingdraexArt, KyuremArt, MunkidoriexArt, NeutralCenterArt, NightTimeAcademyArt, NightlyStretcherArt, OkidogiexArt, PecharuntexArt, PokeVitalAArt, PowerHourglassArt, RevavroomexArt, RowlettArt, SeadraArt, SlitherWingArt, TapuBuluArt, XerosicsSchemeArt, ZoroarkArt, ZoruaArt } from './card-images';

export const setSV7: Card[] = [
  new AbsolArt(),
  new AxewArt(),
  new BindingMochiArt(),
  new BloodmoonUrsalunaArt(),
  new CassiopeiaArt(),
  new ColresssObsessionArt(),
  new CopperajahArt(),
  new CresseliaArt(),
  new CufantArt(),
  new DangerousLaserArt(),
  new DartrixArt(),
  new DecidueyeArt(),
  new DusclopsArt(),
  new DusknoirArt(),
  new DuskullArt(),
  new FezandipitiexArt(),
  new FraxureArt,
  // new GenesectArt(),
  new HaxorusArt(),
  new HorseaArt(),
  new HoundoomArt(),
  new HoundourArt(),
  new JaninesSecretTechniqueArt(),
  new KingdraexArt(),
  new KyuremArt(),
  new MunkidoriexArt(),
  new NeutralCenterArt(),
  new NightTimeAcademyArt(),
  new NightlyStretcherArt(),
  new OkidogiexArt(),
  new PecharuntexArt(),
  new PokeVitalAArt(),
  new PowerHourglassArt(),
  new RevavroomexArt(),
  new RowlettArt(),
  new SeadraArt(),
  new SlitherWingArt(),
  new TapuBuluArt(),
  new XerosicsSchemeArt(),
  new ZoroarkArt(),
  new ZoruaArt(),

];
