/**
 * List of cards where any printing is legal in any format where the card is legal.
 * These cards are considered functionally identical across all printings and can be
 * used regardless of their specific set/printing as long as the card name matches.
 */
export const ANY_PRINTING_ALLOWED: string[] = [
  'Pokémon Fan Club',
  'Master Ball',
  'Quick Ball',
  'Crushing Hammer',
  'Energy Search',
  'Energy Switch',
  'Exp. Share',
  'Judge',
  'Nest Ball',
  'Pal Pad',
  'Poké Ball',
  'Pokégear 3.0',
  'Pokémon Catcher',
  'Potion',
  'Professor\'s Research',
  'Rare Candy',
  'Rocky Helmet',
  'Switch',
  'Ultra Ball',
  'Vitality Band',
  'Boss\'s Orders',
  'Choice Belt',
  'Great Ball',
  'Super Rod',
  'Superior Energy Retrieval',
  'Leftovers',
  'Counter Catcher',
  'Cook',
  'Enhanced Hammer',
  'Lucky Helmet',
  'Counter Gain',
  'Dusk Ball',
  'Super Potion',
  'Energy Recycler',
  'Sacred Ash',
  'Air Balloon',
  'Prism Energy',
  'Energy Retrieval',
  'Tool Scrapper',
  'Cheren',
  'Rainbow Energy',
  'N',
  'Tropical Beach',
  'Professor Juniper',
  'Professor Sycamore',
  'Tool Scrapper',
  'Double Colorless Energy'
]; 