export enum CardTag {
  POKEMON_SP = 'SP',
  POKEMON_EX = 'EX',
  POKEMON_GX = 'GX',
  POKEMON_LV_X = 'LV_X',
  POKEMON_V = 'V',
  POKEMON_VMAX = 'VMAX',
  POKEMON_VSTAR = 'VSTAR',
  POKEMON_VUNION = 'VUNION',
  ACE_SPEC = 'ACE_SPEC',
  RADIANT = 'RADIANT',
  ROCKETS_SECRET_MACHINE = 'ROCKETS_SECRET_MACHINE',
  TEAM_PLASMA = 'TEAM_PLASMA',
  FUSION_STRIKE = 'FUSION_STRIKE',
  SINGLE_STRIKE = 'SINGLE_STRIKE',
  RAPID_STRIKE = 'RAPID_STRIKE',
  POKEMON_ex = 'ex',
  FUTURE = 'Future',
  ANCIENT = 'Ancient',
  POKEMON_TERA = 'POKEMON_TERA',
  ULTRA_BEAST = 'ULTRA_BEAST',
  TAG_TEAM = 'TAG_TEAM',
  TEAM_MAGMA = 'TEAM_MAGMA',
  PRISM_STAR = 'PRISM_STAR',
  STAR = 'STAR',
  BREAK = 'BREAK',
  PRIME = 'PRIME',
  HOLO = 'HOLO',
  LEGEND = 'LEGEND',
  DUAL_LEGEND = 'DUAL_LEGEND',
  TEAM_FLARE = 'TEAM_FLARE',
  MEGA = 'MEGA',
  PLAY_DURING_SETUP = 'PLAY_DURING_SETUP',
  DELTA_SPECIES = 'DELTA_SPECIES',
  DARK = 'DARK',
  LILLIES = 'LILLIES',
  NS = 'NS',
  IONOS = 'IONOS',
  HOPS = 'HOPS',
  MARNIES = 'MARNIES',
  STEVENS = 'STEVENS',
  ETHANS = 'ETHANS',
  MISTYS = 'MISTYS',
  CYNTHIAS = 'CYNTHIAS',
  ARVENS = 'ARVENS',
  AURAS = 'AURAS',
  POKEMON_SV_MEGA = 'POKEMON_SV_MEGA',
  HOLONS = 'HOLONS',
  ROCKETS = 'ROCKETS', // For old cards
  TEAM_ROCKET = 'TEAM_ROCKET', // For new cards
  UNOWN = 'UNOWN',
  PRIMAL = 'PRIMAL',
  ARCEUS = 'ARCEUS',
}

export enum SuperType {
  NONE,
  POKEMON,
  TRAINER,
  ENERGY,
  ANY
}

export enum EnergyType {
  BASIC,
  SPECIAL,
}

export enum TrainerType {
  ITEM,
  SUPPORTER,
  STADIUM,
  TOOL,
}

export enum PokemonType {
  NORMAL,
  EX,
  LEGEND,
}

export enum Stage {
  NONE,
  RESTORED,
  BASIC,
  STAGE_1,
  STAGE_2,
  VMAX,
  VSTAR,
  VUNION,
  LEGEND,
  MEGA,
  BREAK,
  LV_X,
}

export enum Archetype {

  PALKIA_ORIGIN = 'Palkia Origin',
  COMFEY = 'Comfey',
  IRON_THORNS = 'Iron Thorns',
  SNORLAX = 'Snorlax',
  CERULEDGE = 'Ceruledge',
  KLAWF = 'Klawf',
  FERALIGATR = 'Feraligatr',
  BLISSEY = 'Blissey',
  MILOTIC = 'Milotic',
  ZOROARK = 'Zoroark',
  BELLIBOLT = 'Bellibolt',
  FLAREON = 'Flareon',
  MAMOSWINE = 'Mamoswine',
  ZACIAN = 'Zacian',
  FROSLASS = 'Froslass',
  ROTOM = 'Rotom',
  HOOH = 'Ho-oh',
  HYDREIGON = 'Hydreigon',
  MEGA_GARDEVOIR = 'Mega Gardevoir',
  BULBASAUR = 'Bulbasaur',
  IVYSAUR = 'Ivysaur',
  VENUSAUR = 'Venusaur',
  MEGA_VENUSAUR = 'Mega Venusaur',
  CHARMANDER = 'Charmander',
  CHARMELEON = 'Charmeleon',
  CHARIZARD = 'Charizard',
  MEGA_CHARIZARD_X = 'Mega Charizard X',
  MEGA_CHARIZARD_Y = 'Mega Charizard Y',
  SQUIRTLE = 'Squirtle',
  WARTORTLE = 'Wartortle',
  BLASTOISE = 'Blastoise',
  MEGA_BLASTOISE = 'Mega Blastoise',
  CATERPIE = 'Caterpie',
  METAPOD = 'Metapod',
  BUTTERFREE = 'Butterfree',
  WEEDLE = 'Weedle',
  KAKUNA = 'Kakuna',
  BEEDRILL = 'Beedrill',
  MEGA_BEEDRILL = 'Mega Beedrill',
  PIDGEY = 'Pidgey',
  PIDGEOTTO = 'Pidgeotto',
  PIDGEOT = 'Pidgeot',
  MEGA_PIDGEOT = 'Mega Pidgeot',
  RATTATA = 'Rattata',
  ALOLAN_RATTATA = 'Alolan Rattata',
  RATICATE = 'Raticate',
  ALOLAN_RATICATE = 'Alolan Raticate',
  SPEAROW = 'Spearow',
  FEAROW = 'Fearow',
  EKANS = 'Ekans',
  ARBOK = 'Arbok',
  PIKACHU = 'Pikachu',
  RAICHU = 'Raichu',
  ALOLAN_RAICHU = 'Alolan Raichu',
  SANDSHREW = 'Sandshrew',
  ALOLAN_SANDSHREW = 'Alolan Sandshrew',
  SANDSLASH = 'Sandslash',
  ALOLAN_SANDSLASH = 'Alolan Sandslash',
  NIDORAN_F = 'Nidoran♀',
  NIDORINA = 'Nidorina',
  NIDOQUEEN = 'Nidoqueen',
  NIDORAN_M = 'Nidoran♂',
  NIDORINO = 'Nidorino',
  NIDOKING = 'Nidoking',
  CLEFAIRY = 'Clefairy',
  CLEFABLE = 'Clefable',
  VULPIX = 'Vulpix',
  ALOLAN_VULPIX = 'Alolan Vulpix',
  NINETALES = 'Ninetales',
  ALOLAN_NINETALES = 'Alolan Ninetales',
  JIGGLYPUFF = 'Jigglypuff',
  WIGGLYTUFF = 'Wigglytuff',
  ZUBAT = 'Zubat',
  GOLBAT = 'Golbat',
  ODDISH = 'Oddish',
  GLOOM = 'Gloom',
  VILEPLUME = 'Vileplume',
  PARAS = 'Paras',
  PARASECT = 'Parasect',
  VENONAT = 'Venonat',
  VENOMOTH = 'Venomoth',
  DIGLETT = 'Diglett',
  ALOLAN_DIGLETT = 'Alolan Diglett',
  DUGTRIO = 'Dugtrio',
  ALOLAN_DUGTRIO = 'Alolan Dugtrio',
  MEOWTH = 'Meowth',
  ALOLAN_MEOWTH = 'Alolan Meowth',
  GALARIAN_MEOWTH = 'Galarian Meowth',
  PERSIAN = 'Persian',
  ALOLAN_PERSIAN = 'Alolan Persian',
  PSYDUCK = 'Psyduck',
  GOLDUCK = 'Golduck',
  MANKEY = 'Mankey',
  PRIMEAPE = 'Primeape',
  GROWLITHE = 'Growlithe',
  HISUIAN_GROWLITHE = 'Hisuian Growlithe',
  ARCANINE = 'Arcanine',
  HISUIAN_ARCANINE = 'Hisuian Arcanine',
  POLIWAG = 'Poliwag',
  POLIWHIRL = 'Poliwhirl',
  POLIWRATH = 'Poliwrath',
  ABRA = 'Abra',
  KADABRA = 'Kadabra',
  ALAKAZAM = 'Alakazam',
  MEGA_ALAKAZAM = 'Mega Alakazam',
  MACHOP = 'Machop',
  MACHOKE = 'Machoke',
  MACHAMP = 'Machamp',
  BELLSPROUT = 'Bellsprout',
  WEEPINBELL = 'Weepinbell',
  VICTREEBEL = 'Victreebel',
  TENTACOOL = 'Tentacool',
  TENTACRUEL = 'Tentacruel',
  GEODUDE = 'Geodude',
  ALOLAN_GEODUDE = 'Alolan Geodude',
  GRAVELER = 'Graveler',
  ALOLAN_GRAVELER = 'Alolan Graveler',
  GOLEM = 'Golem',
  ALOLAN_GOLEM = 'Alolan Golem',
  PONYTA = 'Ponyta',
  GALARIAN_PONYTA = 'Galarian Ponyta',
  RAPIDASH = 'Rapidash',
  GALARIAN_RAPIDASH = 'Galarian Rapidash',
  SLOWPOKE = 'Slowpoke',
  GALARIAN_SLOWPOKE = 'Galarian Slowpoke',
  SLOWBRO = 'Slowbro',
  MEGA_SLOWBRO = 'Mega Slowbro',
  GALARIAN_SLOWBRO = 'Galarian Slowbro',
  MAGNEMITE = 'Magnemite',
  MAGNETON = 'Magneton',
  FARFETCHD = 'Farfetch\'d',
  GALARIAN_FARFETCHD = 'Galarian Farfetch\'d',
  DODUO = 'Doduo',
  DODRIO = 'Dodrio',
  SEEL = 'Seel',
  DEWGONG = 'Dewgong',
  GRIMER = 'Grimer',
  ALOLAN_GRIMER = 'Alolan Grimer',
  MUK = 'Muk',
  ALOLAN_MUK = 'Alolan Muk',
  SHELLDER = 'Shellder',
  CLOYSTER = 'Cloyster',
  GASTLY = 'Gastly',
  HAUNTER = 'Haunter',
  GENGAR = 'Gengar',
  MEGA_GENGAR = 'Mega Gengar',
  ONIX = 'Onix',
  DROWZEE = 'Drowzee',
  HYPNO = 'Hypno',
  KRABBY = 'Krabby',
  KINGLER = 'Kingler',
  VOLTORB = 'Voltorb',
  HISUIAN_VOLTORB = 'Hisuian Voltorb',
  ELECTRODE = 'Electrode',
  HISUIAN_ELECTRODE = 'Hisuian Electrode',
  EXEGGCUTE = 'Exeggcute',
  EXEGGUTOR = 'Exeggutor',
  ALOLAN_EXEGGUTOR = 'Alolan Exeggutor',
  CUBONE = 'Cubone',
  MAROWAK = 'Marowak',
  ALOLAN_MAROWAK = 'Alolan Marowak',
  HITMONLEE = 'Hitmonlee',
  HITMONCHAN = 'Hitmonchan',
  LICKITUNG = 'Lickitung',
  KOFFING = 'Koffing',
  WEEZING = 'Weezing',
  GALARIAN_WEEZING = 'Galarian Weezing',
  RHYHORN = 'Rhyhorn',
  RHYDON = 'Rhydon',
  CHANSEY = 'Chansey',
  TANGELA = 'Tangela',
  KANGASKHAN = 'Kangaskhan',
  MEGA_KANGASKHAN = 'Mega Kangaskhan',
  HORSEA = 'Horsea',
  SEADRA = 'Seadra',
  GOLDEEN = 'Goldeen',
  SEAKING = 'Seaking',
  STARYU = 'Staryu',
  STARMIE = 'Starmie',
  MR_MIME = 'Mr. Mime',
  GALARIAN_MR_MIME = 'Galarian Mr. Mime',
  SCYTHER = 'Scyther',
  JYNX = 'Jynx',
  ELECTABUZZ = 'Electabuzz',
  MAGMAR = 'Magmar',
  PINSIR = 'Pinsir',
  MEGA_PINSIR = 'Mega Pinsir',
  TAUROS = 'Tauros',
  PALDEAN_TAUROS_COMBAT = 'Paldean Tauros Combat Breed',
  PALDEAN_TAUROS_BLAZE = 'Paldean Tauros Blaze Breed',
  PALDEAN_TAUROS_AQUA = 'Paldean Tauros Aqua Breed',
  MAGIKARP = 'Magikarp',
  GYARADOS = 'Gyarados',
  MEGA_GYARADOS = 'Mega Gyarados',
  LAPRAS = 'Lapras',
  DITTO = 'Ditto',
  EEVEE = 'Eevee',
  VAPOREON = 'Vaporeon',
  JOLTEON = 'Jolteon',
  PORYGON = 'Porygon',
  OMANYTE = 'Omanyte',
  OMASTAR = 'Omastar',
  KABUTO = 'Kabuto',
  KABUTOPS = 'Kabutops',
  AERODACTYL = 'Aerodactyl',
  MEGA_AERODACTYL = 'Mega Aerodactyl',
  ARTICUNO = 'Articuno',
  GALARIAN_ARTICUNO = 'Galarian Articuno',
  ZAPDOS = 'Zapdos',
  GALARIAN_ZAPDOS = 'Galarian Zapdos',
  MOLTRES = 'Moltres',
  GALARIAN_MOLTRES = 'Galarian Moltres',
  DRATINI = 'Dratini',
  DRAGONAIR = 'Dragonair',
  DRAGONITE = 'Dragonite',
  MEWTWO = 'Mewtwo',
  MEGA_MEWTWO_X = 'Mega Mewtwo X',
  MEGA_MEWTWO_Y = 'Mega Mewtwo Y',
  MEW = 'Mew',
  CHIKORITA = 'Chikorita',
  BAYLEEF = 'Bayleef',
  MEGANIUM = 'Meganium',
  CYNDAQUIL = 'Cyndaquil',
  QUILAVA = 'Quilava',
  TYPHLOSION = 'Typhlosion',
  TYPHLOSION_HISUIAN = 'Typhlosion Hisuian',
  TOTODILE = 'Totodile',
  CROCONAW = 'Croconaw',
  SENTRET = 'Sentret',
  FURRET = 'Furret',
  HOOTHOOT = 'Hoothoot',
  NOCTOWL = 'Noctowl',
  LEDYBA = 'Ledyba',
  LEDIAN = 'Ledian',
  SPINARAK = 'Spinarak',
  ARIADOS = 'Ariados',
  CHINCHOU = 'Chinchou',
  LANTURN = 'Lanturn',
  PICHU = 'Pichu',
  CLEFFA = 'Cleffa',
  IGGLYBUFF = 'Igglybuff',
  TOGEPI = 'Togepi',
  TOGETIC = 'Togetic',
  NATU = 'Natu',
  XATU = 'Xatu',
  MAREEP = 'Mareep',
  FLAAFFY = 'Flaaffy',
  AMPHAROS = 'Ampharos',
  BELLOSSOM = 'Bellossom',
  MARILL = 'Marill',
  AZUMARILL = 'Azumarill',
  SUDOWOODO = 'Sudowoodo',
  POLITOED = 'Politoed',
  HOPPIP = 'Hoppip',
  SKIPLOOM = 'Skiploom',
  JUMPLUFF = 'Jumpluff',
  AIPOM = 'Aipom',
  SUNKERN = 'Sunkern',
  SUNFLORA = 'Sunflora',
  YANMA = 'Yanma',
  WOOPER = 'Wooper',
  WOOPER_PALDEAN = 'Wooper Paldean',
  QUAGSIRE = 'Quagsire',
  ESPEON = 'Espeon',
  UMBREON = 'Umbreon',
  MURKROW = 'Murkrow',
  SLOWKING = 'Slowking',
  SLOWKING_GALARIAN = 'Slowking Galarian',
  MISDREAVUS = 'Misdreavus',
  UNOWN = 'Unown',
  WOBBUFFET = 'Wobbuffet',
  GIRAFARIG = 'Girafarig',
  PINECO = 'Pineco',
  FORRETRESS = 'Forretress',
  DUNSPARCE = 'Dunsparce',
  GLIGAR = 'Gligar',
  STEELIX = 'Steelix',
  SNUBBULL = 'Snubbull',
  GRANBULL = 'Granbull',
  QWILFISH = 'Qwilfish',
  QWILFISH_HISUIAN = 'Qwilfish Hisuian',
  SCIZOR = 'Scizor',
  SHUCKLE = 'Shuckle',
  HERACROSS = 'Heracross',
  SNEASEL = 'Sneasel',
  SNEASEL_HISUIAN = 'Sneasel Hisuian',
  TEDDIURSA = 'Teddiursa',
  URSARING = 'Ursaring',
  SLUGMA = 'Slugma',
  MAGCARGO = 'Magcargo',
  SWINUB = 'Swinub',
  PILOSWINE = 'Piloswine',
  CORSOLA = 'Corsola',
  CORSOLA_GALARIAN = 'Corsola Galarian',
  REMORAID = 'Remoraid',
  OCTILLERY = 'Octillery',
  DELIBIRD = 'Delibird',
  MANTINE = 'Mantine',
  SKARMORY = 'Skarmory',
  HOUNDOUR = 'Houndour',
  HOUNDOOM = 'Houndoom',
  KINGDRA = 'Kingdra',
  PHANPY = 'Phanpy',
  DONPHAN = 'Donphan',
  PORYGON2 = 'Porygon2',
  STANTLER = 'Stantler',
  SMEARGLE = 'Smeargle',
  TYROGUE = 'Tyrogue',
  HITMONTOP = 'Hitmontop',
  SMOOCHUM = 'Smoochum',
  ELEKID = 'Elekid',
  MAGBY = 'Magby',
  MILTANK = 'Miltank',
  RAIKOU = 'Raikou',
  ENTEI = 'Entei',
  SUICUNE = 'Suicune',
  LARVITAR = 'Larvitar',
  PUPITAR = 'Pupitar',
  TYRANITAR = 'Tyranitar',
  LUGIA = 'Lugia',
  HO_OH = 'Ho-Oh',
  CELEBI = 'Celebi',
  TREECKO = 'Treecko',
  GROVYLE = 'Grovyle',
  SCEPTILE = 'Sceptile',
  MEGA_SCEPTILE = 'Mega Sceptile',
  TORCHIC = 'Torchic',
  COMBUSKEN = 'Combusken',
  BLAZIKEN = 'Blaziken',
  MEGA_BLAZIKEN = 'Mega Blaziken',
  MUDKIP = 'Mudkip',
  MARSHTOMP = 'Marshtomp',
  SWAMPERT = 'Swampert',
  MEGA_SWAMPERT = 'Mega Swampert',
  POOCHYENA = 'Poochyena',
  MIGHTYENA = 'Mightyena',
  ZIGZAGOON = 'Zigzagoon',
  GALARIAN_ZIGZAGOON = 'Galarian Zigzagoon',
  LINOONE = 'Linoone',
  GALARIAN_LINOONE = 'Galarian Linoone',
  WURMPLE = 'Wurmple',
  SILCOON = 'Silcoon',
  BEAUTIFLY = 'Beautifly',
  CASCOON = 'Cascoon',
  DUSTOX = 'Dustox',
  LOTAD = 'Lotad',
  LOMBRE = 'Lombre',
  LUDICOLO = 'Ludicolo',
  SEEDOT = 'Seedot',
  NUZLEAF = 'Nuzleaf',
  SHIFTRY = 'Shiftry',
  TAILLOW = 'Taillow',
  SWELLOW = 'Swellow',
  WINGULL = 'Wingull',
  PELIPPER = 'Pelipper',
  RALTS = 'Ralts',
  KIRLIA = 'Kirlia',
  GARDEVOIR = 'Gardevoir',
  SURSKIT = 'Surskit',
  MASQUERAIN = 'Masquerain',
  SHROOMISH = 'Shroomish',
  BRELOOM = 'Breloom',
  SLAKOTH = 'Slakoth',
  VIGOROTH = 'Vigoroth',
  SLAKING = 'Slaking',
  NINCADA = 'Nincada',
  NINJASK = 'Ninjask',
  SHEDINJA = 'Shedinja',
  WHISMUR = 'Whismur',
  LOUDRED = 'Loudred',
  EXPLOUD = 'Exploud',
  MAKUHITA = 'Makuhita',
  HARIYAMA = 'Hariyama',
  NOSEPASS = 'Nosepass',
  SKITTY = 'Skitty',
  DELCATTY = 'Delcatty',
  SABLEYE = 'Sableye',
  MEGA_SABLEYE = 'Mega Sableye',
  MAWILE = 'Mawile',
  MEGA_MAWILE = 'Mega Mawile',
  ARON = 'Aron',
  LAIRON = 'Lairon',
  AGGRON = 'Aggron',
  MEGA_AGGRON = 'Mega Aggron',
  MEDITITE = 'Meditite',
  MEDICHAM = 'Medicham',
  MEGA_MEDICHAM = 'Mega Medicham',
  ELECTRIKE = 'Electrike',
  MANECTRIC = 'Manectric',
  MEGA_MANECTRIC = 'Mega Manectric',
  PLUSLE = 'Plusle',
  MINUN = 'Minun',
  VOLBEAT = 'Volbeat',
  ILLUMISE = 'Illumise',
  ROSELIA = 'Roselia',
  GULPIN = 'Gulpin',
  SWALOT = 'Swalot',
  CARVANHA = 'Carvanha',
  SHARPEDO = 'Sharpedo',
  MEGA_SHARPEDO = 'Mega Sharpedo',
  WAILMER = 'Wailmer',
  WAILORD = 'Wailord',
  NUMEL = 'Numel',
  CAMERUPT = 'Camerupt',
  MEGA_CAMERUPT = 'Mega Camerupt',
  TORKOAL = 'Torkoal',
  SPOINK = 'Spoink',
  GRUMPIG = 'Grumpig',
  SPINDA = 'Spinda',
  TRAPINCH = 'Trapinch',
  VIBRAVA = 'Vibrava',
  FLYGON = 'Flygon',
  CACNEA = 'Cacnea',
  CACTURNE = 'Cacturne',
  SWABLU = 'Swablu',
  ALTARIA = 'Altaria',
  MEGA_ALTARIA = 'Mega Altaria',
  ZANGOOSE = 'Zangoose',
  SEVIPER = 'Seviper',
  LUNATONE = 'Lunatone',
  SOLROCK = 'Solrock',
  BARBOACH = 'Barboach',
  WHISCASH = 'Whiscash',
  CORPHISH = 'Corphish',
  CRAWDAUNT = 'Crawdaunt',
  BALTOY = 'Baltoy',
  CLAYDOL = 'Claydol',
  LILEEP = 'Lileep',
  CRADILY = 'Cradily',
  ANORITH = 'Anorith',
  ARMALDO = 'Armaldo',
  FEEBAS = 'Feebas',
  CASTFORM = 'Castform',
  CASTFORM_SUNNY = 'Castform Sunny',
  CASTFORM_RAINY = 'Castform Rainy',
  CASTFORM_SNOWY = 'Castform Snowy',
  KECLEON = 'Kecleon',
  SHUPPET = 'Shuppet',
  BANETTE = 'Banette',
  MEGA_BANETTE = 'Mega Banette',
  DUSKULL = 'Duskull',
  DUSCLOPS = 'Dusclops',
  TROPIUS = 'Tropius',
  CHIMECHO = 'Chimecho',
  ABSOL = 'Absol',
  MEGA_ABSOL = 'Mega Absol',
  SNORUNT = 'Snorunt',
  GLALIE = 'Glalie',
  MEGA_GLALIE = 'Mega Glalie',
  SPHEAL = 'Spheal',
  SEALEO = 'Sealeo',
  WALREIN = 'Walrein',
  CLAMPERL = 'Clamperl',
  HUNTAIL = 'Huntail',
  GOREBYSS = 'Gorebyss',
  RELICANTH = 'Relicanth',
  LUVDISC = 'Luvdisc',
  BAGON = 'Bagon',
  SHELGON = 'Shelgon',
  SALAMENCE = 'Salamence',
  MEGA_SALAMENCE = 'Mega Salamence',
  BELDUM = 'Beldum',
  METANG = 'Metang',
  METAGROSS = 'Metagross',
  MEGA_METAGROSS = 'Mega Metagross',
  REGIROCK = 'Regirock',
  REGICE = 'Regice',
  REGISTEEL = 'Registeel',
  LATIAS = 'Latias',
  MEGA_LATIAS = 'Mega Latias',
  LATIOS = 'Latios',
  MEGA_LATIOS = 'Mega Latios',
  KYOGRE = 'Kyogre',
  PRIMAL_KYOGRE = 'Primal Kyogre',
  GROUDON = 'Groudon',
  PRIMAL_GROUDON = 'Primal Groudon',
  RAYQUAZA = 'Rayquaza',
  MEGA_RAYQUAZA = 'Mega Rayquaza',
  JIRACHI = 'Jirachi',
  DEOXYS = 'Deoxys',
  DEOXYS_ATTACK = 'Deoxys Attack',
  DEOXYS_DEFENSE = 'Deoxys Defense',
  DEOXYS_SPEED = 'Deoxys Speed',
  TURTWIG = 'Turtwig',
  GROTLE = 'Grotle',
  TORTERRA = 'Torterra',
  CHIMCHAR = 'Chimchar',
  MONFERNO = 'Monferno',
  INFERNAPE = 'Infernape',
  PIPLUP = 'Piplup',
  PRINPLUP = 'Prinplup',
  EMPOLEON = 'Empoleon',
  STARLY = 'Starly',
  STARAVIA = 'Staravia',
  STARAPTOR = 'Staraptor',
  BIDOOF = 'Bidoof',
  BIBAREL = 'Bibarel',
  KRICKETOT = 'Kricketot',
  KRICKETUNE = 'Kricketune',
  SHINX = 'Shinx',
  LUXIO = 'Luxio',
  LUXRAY = 'Luxray',
  BUDEW = 'Budew',
  ROSERADE = 'Roserade',
  CRANIDOS = 'Cranidos',
  RAMPARDOS = 'Rampardos',
  SHIELDON = 'Shieldon',
  BASTIODON = 'Bastiodon',
  BURMY = 'Burmy',
  WORMADAM = 'Wormadam',
  MOTHIM = 'Mothim',
  COMBEE = 'Combee',
  VESPIQUEN = 'Vespiquen',
  PACHIRISU = 'Pachirisu',
  BUIZEL = 'Buizel',
  FLOATZEL = 'Floatzel',
  CHERUBI = 'Cherubi',
  CHERRIM = 'Cherrim',
  SHELLOS = 'Shellos',
  GASTRODON = 'Gastrodon',
  AMBIPOM = 'Ambipom',
  DRIFLOON = 'Drifloon',
  DRIFBLIM = 'Drifblim',
  BUNEARY = 'Buneary',
  LOPUNNY = 'Lopunny',
  MISMAGIUS = 'Mismagius',
  HONCHKROW = 'Honchkrow',
  GLAMEOW = 'Glameow',
  PURUGLY = 'Purugly',
  CHINGLING = 'Chingling',
  STUNKY = 'Stunky',
  SKUNTANK = 'Skuntank',
  BRONZOR = 'Bronzor',
  BRONZONG = 'Bronzong',
  BONSLY = 'Bonsly',
  MIME_JR = 'Mime Jr.',
  HAPPINY = 'Happiny',
  CHATOT = 'Chatot',
  SPIRITOMB = 'Spiritomb',
  GIBLE = 'Gible',
  GABITE = 'Gabite',
  GARCHOMP = 'Garchomp',
  MUNCHLAX = 'Munchlax',
  RIOLU = 'Riolu',
  LUCARIO = 'Lucario',
  HIPPOPOTAS = 'Hippopotas',
  HIPPOWDON = 'Hippowdon',
  SKORUPI = 'Skorupi',
  DRAPION = 'Drapion',
  CROAGUNK = 'Croagunk',
  TOXICROAK = 'Toxicroak',
  CARNIVINE = 'Carnivine',
  FINNEON = 'Finneon',
  LUMINEON = 'Lumineon',
  MANTYKE = 'Mantyke',
  SNOVER = 'Snover',
  ABOMASNOW = 'Abomasnow',
  WEAVILE = 'Weavile',
  MAGNEZONE = 'Magnezone',
  LICKILICKY = 'Lickilicky',
  RHYPERIOR = 'Rhyperior',
  TANGROWTH = 'Tangrowth',
  ELECTIVIRE = 'Electivire',
  MAGMORTAR = 'Magmortar',
  TOGEKISS = 'Togekiss',
  YANMEGA = 'Yanmega',
  LEAFEON = 'Leafeon',
  GLACEON = 'Glaceon',
  GLISCOR = 'Gliscor',
  PORYGON_Z = 'Porygon-Z',
  GALLADE = 'Gallade',
  PROBOPASS = 'Probopass',
  DUSKNOIR = 'Dusknoir',
  UXIE = 'Uxie',
  MESPRIT = 'Mesprit',
  AZELF = 'Azelf',
  DIALGA = 'Dialga',
  PALKIA = 'Palkia',
  HEATRAN = 'Heatran',
  REGIGIGAS = 'Regigigas',
  GIRATINA = 'Giratina',
  CRESSELIA = 'Cresselia',
  PHIONE = 'Phione',
  MANAPHY = 'Manaphy',
  DARKRAI = 'Darkrai',
  SHAYMIN = 'Shaymin',
  ARCEUS = 'Arceus',
  VICTINI = 'Victini',
  SNIVY = 'Snivy',
  SERVINE = 'Servine',
  SERPERIOR = 'Serperior',
  TEPIG = 'Tepig',
  PIGNITE = 'Pignite',
  EMBOAR = 'Emboar',
  OSHAWOTT = 'Oshawott',
  DEWOTT = 'Dewott',
  SAMUROTT = 'Samurott',
  PATRAT = 'Patrat',
  WATCHOG = 'Watchog',
  LILLIPUP = 'Lillipup',
  HERDIER = 'Herdier',
  STOUTLAND = 'Stoutland',
  PURRLOIN = 'Purrloin',
  LIEPARD = 'Liepard',
  PANSAGE = 'Pansage',
  SIMISAGE = 'Simisage',
  PANSEAR = 'Pansear',
  SIMISEAR = 'Simisear',
  PANPOUR = 'Panpour',
  SIMIPOUR = 'Simipour',
  MUNNA = 'Munna',
  MUSHARNA = 'Musharna',
  PIDOVE = 'Pidove',
  TRANQUILL = 'Tranquill',
  UNFEZANT = 'Unfezant',
  BLITZLE = 'Blitzle',
  ZEBSTRIKA = 'Zebstrika',
  ROGGENROLA = 'Roggenrola',
  BOLDORE = 'Boldore',
  GIGALITH = 'Gigalith',
  WOOBAT = 'Woobat',
  SWOOBAT = 'Swoobat',
  DRILBUR = 'Drilbur',
  EXCADRILL = 'Excadrill',
  AUDINO = 'Audino',
  TIMBURR = 'Timburr',
  GURDURR = 'Gurdurr',
  CONKELDURR = 'Conkeldurr',
  TYMPOLE = 'Tympole',
  PALPITOAD = 'Palpitoad',
  SEISMITOAD = 'Seismitoad',
  THROH = 'Throh',
  SAWK = 'Sawk',
  SEWADDLE = 'Sewaddle',
  SWADLOON = 'Swadloon',
  LEAVANNY = 'Leavanny',
  VENIPEDE = 'Venipede',
  WHIRLIPEDE = 'Whirlipede',
  SCOLIPEDE = 'Scolipede',
  COTTONEE = 'Cottonee',
  WHIMSICOTT = 'Whimsicott',
  PETILIL = 'Petilil',
  LILLIGANT = 'Lilligant',
  BASCULIN = 'Basculin',
  SANDILE = 'Sandile',
  KROKOROK = 'Krokorok',
  KROOKODILE = 'Krookodile',
  DARUMAKA = 'Darumaka',
  DARMANITAN = 'Darmanitan',
  MARACTUS = 'Maractus',
  DWEBBLE = 'Dwebble',
  CRUSTLE = 'Crustle',
  SCRAGGY = 'Scraggy',
  SCRAFTY = 'Scrafty',
  SIGILYPH = 'Sigilyph',
  YAMASK = 'Yamask',
  COFAGRIGUS = 'Cofagrigus',
  TIRTOUGA = 'Tirtouga',
  CARRACOSTA = 'Carracosta',
  ARCHEN = 'Archen',
  ARCHEOPS = 'Archeops',
  TRUBBISH = 'Trubbish',
  GARBODOR = 'Garbodor',
  ZORUA = 'Zorua',
  MINCCINO = 'Minccino',
  GOTHITA = 'Gothita',
  GOTHORITA = 'Gothorita',
  GOTHITELLE = 'Gothitelle',
  SOLOSIS = 'Solosis',
  DUOSION = 'Duosion',
  REUNICLUS = 'Reuniclus',
  DUCKLETT = 'Ducklett',
  SWANNA = 'Swanna',
  VANILLITE = 'Vanillite',
  VANILLISH = 'Vanillish',
  VANILLUXE = 'Vanilluxe',
  DEERLING = 'Deerling',
  SAWSBUCK = 'Sawsbuck',
  EMOLGA = 'Emolga',
  KARRABLAST = 'Karrablast',
  ESCAVALIER = 'Escavalier',
  FOONGUS = 'Foongus',
  AMOONGUSS = 'Amoonguss',
  FRILLISH = 'Frillish',
  JELLICENT = 'Jellicent',
  ALOMOMOLA = 'Alomomola',
  JOLTIK = 'Joltik',
  GALVANTULA = 'Galvantula',
  FERROSEED = 'Ferroseed',
  FERROTHORN = 'Ferrothorn',
  KLINK = 'Klink',
  KLANG = 'Klang',
  KLINKLANG = 'Klinklang',
  TYNAMO = 'Tynamo',
  EELEKTRIK = 'Eelektrik',
  EELEKTROSS = 'Eelektross',
  ELGYEM = 'Elgyem',
  BEHEEYEM = 'Beheeyem',
  LITWICK = 'Litwick',
  LAMPENT = 'Lampent',
  CHANDELURE = 'Chandelure',
  AXEW = 'Axew',
  FRAXURE = 'Fraxure',
  HAXORUS = 'Haxorus',
  CUBCHOO = 'Cubchoo',
  BEARTIC = 'Beartic',
  CRYOGONAL = 'Cryogonal',
  SHELMET = 'Shelmet',
  ACCELGOR = 'Accelgor',
  STUNFISK = 'Stunfisk',
  MIENFOO = 'Mienfoo',
  MIENSHAO = 'Mienshao',
  DRUDDIGON = 'Druddigon',
  GOLETT = 'Golett',
  GOLURK = 'Golurk',
  PAWNIARD = 'Pawniard',
  BISHARP = 'Bisharp',
  BOUFFALANT = 'Bouffalant',
  RUFFLET = 'Rufflet',
  BRAVIARY = 'Braviary',
  VULLABY = 'Vullaby',
  MANDIBUZZ = 'Mandibuzz',
  HEATMOR = 'Heatmor',
  DURANT = 'Durant',
  DEINO = 'Deino',
  ZWEILOUS = 'Zweilous',
  LARVESTA = 'Larvesta',
  VOLCARONA = 'Volcarona',
  COBALION = 'Cobalion',
  TERRAKION = 'Terrakion',
  VIRIZION = 'Virizion',
  TORNADUS = 'Tornadus',
  THUNDURUS = 'Thundurus',
  RESHIRAM = 'Reshiram',
  ZEKROM = 'Zekrom',
  LANDORUS = 'Landorus',
  KYUREM = 'Kyurem',
  KYUREM_WHITE = 'White Kyurem',
  KYUREM_BLACK = 'Black Kyurem',
  KELDEO = 'Keldeo',
  MELOETTA = 'Meloetta',
  GENESECT = 'Genesect',
  CHESPIN = 'Chespin',
  QUILLADIN = 'Quilladin',
  CHESNAUGHT = 'Chesnaught',
  FENNEKIN = 'Fennekin',
  BRAIXEN = 'Braixen',
  DELPHOX = 'Delphox',
  FROAKIE = 'Froakie',
  FROGADIER = 'Frogadier',
  GRENINJA = 'Greninja',
  BUNNELBY = 'Bunnelby',
  DIGGERSBY = 'Diggersby',
  FLETCHLING = 'Fletchling',
  FLETCHINDER = 'Fletchinder',
  TALONFLAME = 'Talonflame',
  SCATTERBUG = 'Scatterbug',
  SPEWPA = 'Spewpa',
  VIVILLON = 'Vivillon',
  LITLEO = 'Litleo',
  PYROAR = 'Pyroar',
  FLABEBE = 'Flabébé',
  FLOETTE = 'Floette',
  FLORGES = 'Florges',
  SKIDDO = 'Skiddo',
  GOGOAT = 'Gogoat',
  PANCHAM = 'Pancham',
  PANGORO = 'Pangoro',
  FURFROU = 'Furfrou',
  ESPURR = 'Espurr',
  MEOWSTIC = 'Meowstic',
  HONEDGE = 'Honedge',
  DOUBLADE = 'Doublade',
  AEGISLASH = 'Aegislash',
  SPRITZEE = 'Spritzee',
  AROMATISSE = 'Aromatisse',
  SWIRLIX = 'Swirlix',
  SLURPUFF = 'Slurpuff',
  INKAY = 'Inkay',
  MALAMAR = 'Malamar',
  BINACLE = 'Binacle',
  BARBARACLE = 'Barbaracle',
  SKRELP = 'Skrelp',
  DRAGALGE = 'Dragalge',
  CLAUNCHER = 'Clauncher',
  CLAWITZER = 'Clawitzer',
  HELIOPTILE = 'Helioptile',
  HELIOLISK = 'Heliolisk',
  TYRUNT = 'Tyrunt',
  TYRANTRUM = 'Tyrantrum',
  AMAURA = 'Amaura',
  AURORUS = 'Aurorus',
  SYLVEON = 'Sylveon',
  HAWLUCHA = 'Hawlucha',
  DEDENNE = 'Dedenne',
  CARBINK = 'Carbink',
  GOOMY = 'Goomy',
  SLIGGOO = 'Sliggoo',
  GOODRA = 'Goodra',
  KLEFKI = 'Klefki',
  PHANTUMP = 'Phantump',
  TREVENANT = 'Trevenant',
  PUMPKABOO = 'Pumpkaboo',
  GOURGEIST = 'Gourgeist',
  BERGMITE = 'Bergmite',
  AVALUGG = 'Avalugg',
  NOIBAT = 'Noibat',
  NOIVERN = 'Noivern',
  XERNEAS = 'Xerneas',
  YVELTAL = 'Yveltal',
  ZYGARDE = 'Zygarde',
  DIANCIE = 'Diancie',
  HOOPA = 'Hoopa',
  VOLCANION = 'Volcanion',
  ROWLET = 'Rowlet',
  DARTRIX = 'Dartrix',
  DECIDUEYE = 'Decidueye',
  LITTEN = 'Litten',
  TORRACAT = 'Torracat',
  INCINEROAR = 'Incineroar',
  POPPLIO = 'Popplio',
  BRIONNE = 'Brionne',
  PRIMARINA = 'Primarina',
  PIKIPEK = 'Pikipek',
  TRUMBEAK = 'Trumbeak',
  TOUCANNON = 'Toucannon',
  YUNGOOS = 'Yungoos',
  GUMSHOOS = 'Gumshoos',
  GRUBBIN = 'Grubbin',
  CHARJABUG = 'Charjabug',
  VIKAVOLT = 'Vikavolt',
  CRABRAWLER = 'Crabrawler',
  CRABOMINABLE = 'Crabominable',
  ORICORIO = 'Oricorio',
  CUTIEFLY = 'Cutiefly',
  RIBOMBEE = 'Ribombee',
  ROCKRUFF = 'Rockruff',
  LYCANROC = 'Lycanroc',
  WISHIWASHI = 'Wishiwashi',
  MAREANIE = 'Mareanie',
  TOXAPEX = 'Toxapex',
  MUDBRAY = 'Mudbray',
  MUDSDALE = 'Mudsdale',
  DEWPIDER = 'Dewpider',
  ARAQUANID = 'Araquanid',
  FOMANTIS = 'Fomantis',
  LURANTIS = 'Lurantis',
  MORELULL = 'Morelull',
  SHIINOTIC = 'Shiinotic',
  SALANDIT = 'Salandit',
  SALAZZLE = 'Salazzle',
  STUFFUL = 'Stufful',
  BEWEAR = 'Bewear',
  BOUNSWEET = 'Bounsweet',
  STEENEE = 'Steenee',
  TSAREENA = 'Tsareena',
  ORANGURU = 'Oranguru',
  PASSIMIAN = 'Passimian',
  WIMPOD = 'Wimpod',
  GOLISOPOD = 'Golisopod',
  SANDYGAST = 'Sandygast',
  PALOSSAND = 'Palossand',
  PYUKUMUKU = 'Pyukumuku',
  TYPE_NULL = 'Type: Null',
  SILVALLY = 'Silvally',
  MINIOR = 'Minior',
  KOMALA = 'Komala',
  TURTONATOR = 'Turtonator',
  TOGEDEMARU = 'Togedemaru',
  MIMIKYU = 'Mimikyu',
  BRUXISH = 'Bruxish',
  DRAMPA = 'Drampa',
  DHELMISE = 'Dhelmise',
  JANGMO_O = 'Jangmo-o',
  HAKAMO_O = 'Hakamo-o',
  KOMMO_O = 'Kommo-o',
  TAPU_KOKO = 'Tapu Koko',
  TAPU_LELE = 'Tapu Lele',
  TAPU_BULU = 'Tapu Bulu',
  TAPU_FINI = 'Tapu Fini',
  COSMOG = 'Cosmog',
  COSMOEM = 'Cosmoem',
  SOLGALEO = 'Solgaleo',
  LUNALA = 'Lunala',
  NIHILEGO = 'Nihilego',
  BUZZWOLE = 'Buzzwole',
  PHEROMOSA = 'Pheromosa',
  XURKITREE = 'Xurkitree',
  CELESTEELA = 'Celesteela',
  KARTANA = 'Kartana',
  GUZZLORD = 'Guzzlord',
  NECROZMA = 'Necrozma',
  MAGEARNA = 'Magearna',
  MARSHADOW = 'Marshadow',
  POIPOLE = 'Poipole',
  NAGANADEL = 'Naganadel',
  STAKATAKA = 'Stakataka',
  BLACEPHALON = 'Blacephalon',
  ZERAORA = 'Zeraora',
  MELTAN = 'Meltan',
  MELMETAL = 'Melmetal',
  GROOKEY = 'Grookey',
  THWACKEY = 'Thwackey',
  RILLABOOM = 'Rillaboom',
  SCORBUNNY = 'Scorbunny',
  RABOOT = 'Raboot',
  CINDERACE = 'Cinderace',
  SOBBLE = 'Sobble',
  DRIZZILE = 'Drizzile',
  INTELEON = 'Inteleon',
  SKWOVET = 'Skwovet',
  GREEDENT = 'Greedent',
  ROOKIDEE = 'Rookidee',
  CORVISQUIRE = 'Corvisquire',
  CORVIKNIGHT = 'Corviknight',
  BLIPBUG = 'Blipbug',
  DOTTLER = 'Dottler',
  ORBEETLE = 'Orbeetle',
  NICKIT = 'Nickit',
  THIEVUL = 'Thievul',
  GOSSIFLEUR = 'Gossifleur',
  ELDEGOSS = 'Eldegoss',
  WOOLOO = 'Wooloo',
  DUBWOOL = 'Dubwool',
  CHEWTLE = 'Chewtle',
  DREDNAW = 'Drednaw',
  YAMPER = 'Yamper',
  BOLTUND = 'Boltund',
  ROLYCOLY = 'Rolycoly',
  CARKOL = 'Carkol',
  COALOSSAL = 'Coalossal',
  APPLIN = 'Applin',
  FLAPPLE = 'Flapple',
  APPLETUN = 'Appletun',
  SILICOBRA = 'Silicobra',
  SANDACONDA = 'Sandaconda',
  CRAMORANT = 'Cramorant',
  ARROKUDA = 'Arrokuda',
  BARRASKEWDA = 'Barraskewda',
  TOXEL = 'Toxel',
  TOXTRICITY = 'Toxtricity',
  SIZZLIPEDE = 'Sizzlipede',
  CENTISKORCH = 'Centiskorch',
  CLOBBOPUS = 'Clobbopus',
  GRAPPLOCT = 'Grapploct',
  SINISTEA = 'Sinistea',
  POLTEAGEIST = 'Polteageist',
  HATENNA = 'Hatenna',
  HATTREM = 'Hattrem',
  HATTERENE = 'Hatterene',
  IMPIDIMP = 'Impidimp',
  MORGREM = 'Morgrem',
  GRIMMSNARL = 'Grimmsnarl',
  OBSTAGOON = 'Obstagoon',
  PERRSERKER = 'Perrserker',
  CURSOLA = 'Cursola',
  SIRFETCHD = 'Sirfetch\'d',
  MR_RIME = 'Mr. Rime',
  RUNERIGUS = 'Runerigus',
  MILCERY = 'Milcery',
  ALCREMIE = 'Alcremie',
  FALINKS = 'Falinks',
  PINCURCHIN = 'Pincurchin',
  SNOM = 'Snom',
  FROSMOTH = 'Frosmoth',
  STONJOURNER = 'Stonjourner',
  EISCUE = 'Eiscue',
  INDEEDEE = 'Indeedee',
  MORPEKO = 'Morpeko',
  CUFANT = 'Cufant',
  COPPERAJAH = 'Copperajah',
  DRACOZOLT = 'Dracozolt',
  ARCTOZOLT = 'Arctozolt',
  DRACOVISH = 'Dracovish',
  ARCTOVISH = 'Arctovish',
  DURALUDON = 'Duraludon',
  DREEPY = 'Dreepy',
  DRAKLOAK = 'Drakloak',
  DRAGAPULT = 'Dragapult',
  ZAMAZENTA = 'Zamazenta',
  ETERNATUS = 'Eternatus',
  KUBFU = 'Kubfu',
  URSHIFU = 'Urshifu',
  ZARUDE = 'Zarude',
  REGIELEKI = 'Regieleki',
  REGIDRAGO = 'Regidrago',
  GLASTRIER = 'Glastrier',
  SPECTRIER = 'Spectrier',
  CALYREX = 'Calyrex',
  WYRDEER = 'Wyrdeer',
  KLEAVOR = 'Kleavor',
  URSALUNA = 'Ursaluna',
  BASCULEGION = 'Basculegion',
  SNEASLER = 'Sneasler',
  OVERQWIL = 'Overqwil',
  ENAMORUS = 'Enamorus',
  SPRIGATITO = 'Sprigatito',
  FLORAGATO = 'Floragato',
  MEOWSCARADA = 'Meowscarada',
  FUECOCO = 'Fuecoco',
  CROCALOR = 'Crocalor',
  SKELEDIRGE = 'Skeledirge',
  QUAXLY = 'Quaxly',
  QUAXWELL = 'Quaxwell',
  QUAQUAVAL = 'Quaquaval',
  LECHONK = 'Lechonk',
  OINKOLOGNE = 'Oinkologne',
  TAROUNTULA = 'Tarountula',
  SPIDOPS = 'Spidops',
  NYMBLE = 'Nymble',
  LOKIX = 'Lokix',
  PAWMI = 'Pawmi',
  PAWMO = 'Pawmo',
  PAWMOT = 'Pawmot',
  TANDEMAUS = 'Tandemaus',
  MAUSHOLD = 'Maushold',
  FIDOUGH = 'Fidough',
  DACHSBUN = 'Dachsbun',
  SMOLIV = 'Smoliv',
  DOLLIV = 'Dolliv',
  ARBOLIVA = 'Arboliva',
  SQUAWKABILLY = 'Squawkabilly',
  NACLI = 'Nacli',
  NACLSTACK = 'Naclstack',
  GARGANACL = 'Garganacl',
  CHARCADET = 'Charcadet',
  ARMAROUGE = 'Armarouge',
  TADBULB = 'Tadbulb',
  WATTREL = 'Wattrel',
  KILOWATTREL = 'Kilowattrel',
  MASCHIFF = 'Maschiff',
  MABOSSTIFF = 'Mabosstiff',
  SHROODLE = 'Shroodle',
  GRAFAIAI = 'Grafaiai',
  BRAMBLIN = 'Bramblin',
  BRAMBLEGHAST = 'Brambleghast',
  TOEDSCOOL = 'Toedscool',
  TOEDSCRUEL = 'Toedscruel',
  CAPSAKID = 'Capsakid',
  SCOVILLAIN = 'Scovillain',
  RELLOR = 'Rellor',
  RABSCA = 'Rabsca',
  FLITTLE = 'Flittle',
  ESPATHRA = 'Espathra',
  TINKATINK = 'Tinkatink',
  TINKATUFF = 'Tinkatuff',
  TINKATON = 'Tinkaton',
  WIGLETT = 'Wiglett',
  WUGTRIO = 'Wugtrio',
  BOMBIRDIER = 'Bombirdier',
  FINIZEN = 'Finizen',
  PALAFIN = 'Palafin',
  VAROOM = 'Varoom',
  REVAVROOM = 'Revavroom',
  CYCLIZAR = 'Cyclizar',
  ORTHWORM = 'Orthworm',
  GLIMMET = 'Glimmet',
  GLIMMORA = 'Glimmora',
  GREAVARD = 'Greavard',
  HOUNDSTONE = 'Houndstone',
  FLAMIGO = 'Flamigo',
  CETODDLE = 'Cetoddle',
  CETITAN = 'Cetitan',
  VELUZA = 'Veluza',
  DONDOZO = 'Dondozo',
  TATSUGIRI = 'Tatsugiri',
  ANNIHILAPE = 'Annihilape',
  CLODSIRE = 'Clodsire',
  FARIGIRAF = 'Farigiraf',
  DUDUNSPARCE = 'Dudunsparce',
  KINGAMBIT = 'Kingambit',
  GREAT_TUSK = 'Great Tusk',
  SCREAM_TAIL = 'Scream Tail',
  BRUTE_BONNET = 'Brute Bonnet',
  FLUTTER_MANE = 'Flutter Mane',
  SLITHER_WING = 'Slither Wing',
  IRON_TREADS = 'Iron Treads',
  IRON_BUNDLE = 'Iron Bundle',
  IRON_HANDS = 'Iron Hands',
  IRON_JUGULIS = 'Iron Jugulis',
  IRON_MOTH = 'Iron Moth',
  FRIGIBAX = 'Frigibax',
  ARCTIBAX = 'Arctibax',
  BAXCALIBUR = 'Baxcalibur',
  GIMMIGHOUL = 'Gimmighoul',
  GHOLDENGO = 'Gholdengo',
  CHIEN_PAO = 'Chien-Pao',
  WO_CHIEN = 'Wo-Chien',
  TING_LU = 'Ting-Lu',
  CHI_YU = 'Chi-Yu',
  ROARING_MOON = 'Roaring Moon',
  IRON_VALIANT = 'Iron Valiant',
  KORAIDON = 'Koraidon',
  MIRAIDON = 'Miraidon',
  WALKING_WAKE = 'Walking Wake',
  IRON_LEAVES = 'Iron Leaves',
  DIPPLIN = 'Dipplin',
  POLTCHAGEIST = 'Poltchageist',
  SINISTCHA = 'Sinistcha',
  OKIDOGI = 'Okidogi',
  MUNKIDORI = 'Munkidori',
  FEZANDIPITI = 'Fezandipiti',
  OGERPON = 'Ogerpon',
  ARCHALUDON = 'Archaludon',
  HYDRAPPLE = 'Hydrapple',
  GOUGING_FIRE = 'Gouging Fire',
  RAGING_BOLT = 'Raging Bolt',
  IRON_BOULDER = 'Iron Boulder',
  IRON_CROWN = 'Iron Crown',
  TERAPAGOS = 'Terapagos',
  PECHARUNT = 'Pecharunt'
}

export enum CardType {
  ANY,
  GRASS,
  FIRE,
  WATER,
  LIGHTNING,
  PSYCHIC,
  FIGHTING,
  DARK,
  METAL,
  COLORLESS,
  FAIRY,
  DRAGON,
  NONE,
  CHARIZARD_EX,
  PIDGEOT_EX,
  GIRATINA_VSTAR,
  ARCEUS_VSTAR,
  COMFEY,
  SABLEYE,
  RAGING_BOLT_EX,
  SOLROCK,
  LUNATONE,
  KYUREM_VMAX,
  MURKROW,
  FLAMIGO,
  CHIEN_PAO_EX,
  BAXCALIBUR,
  SNORLAX_STALL,
  LUGIA_VSTAR,
  ABSOL_EX,
  THWACKEY,
  DIPPLIN,
  PALKIA_VSTAR,
  ROTOM_V,
  BIBAREL,
  GHOLDENGO_EX,
  SANDY_SHOCKS_EX,
  GARDEVOIR_EX,
  XATU,
  TEALMASK_OGERPON_EX,
  LUXRAY_EX,
  GRENINJA_EX,
  BLISSEY_EX,
  ROARING_MOON,
  KORAIDON,
  IRON_CROWN_EX,
  CINCCINO,
  ARCHEOPS,
  MIRAIDON_EX,
  IRON_HANDS_EX,
  DRAGAPULT_EX,
  DRIFLOON,
  FROSLASS,
  WLFM,
  GRW,
  LPM,
  FDY,
  GRPD
}

export enum SpecialCondition {
  PARALYZED,
  CONFUSED,
  ASLEEP,
  POISONED,
  BURNED,
  ABILITY_USED,
  POWER_GLOW
}

export enum BoardEffect {
  ABILITY_USED,
  POWER_GLOW,
  POWER_NEGATED_GLOW,
  POWER_RETURN,
  EVOLVE,
  REVEAL_OPPONENT_HAND
}

export enum Format {
  NONE,
  STANDARD,
  EXPANDED,
  UNLIMITED,
  RETRO,
  GLC,
  STANDARD_NIGHTLY,
  RSPK,
  BW,
  XY,
  SM,
  SWSH,
  SV,
  WORLDS_2013,
}

export const Energy = {
  D: CardType.DARK,
  C: CardType.COLORLESS,
  F: CardType.FIGHTING,
  G: CardType.GRASS,
  L: CardType.LIGHTNING,
  M: CardType.METAL,
  P: CardType.PSYCHIC,
  R: CardType.FIRE,
  W: CardType.WATER,
  Y: CardType.FAIRY,
  N: CardType.DRAGON
} as const;

Object.entries(Energy).forEach(([key, value]) => {
  (global as any)[key] = value;
});

declare global {
  const D: typeof Energy.D;
  const C: typeof Energy.C;
  const F: typeof Energy.F;
  const G: typeof Energy.G;
  const L: typeof Energy.L;
  const M: typeof Energy.M;
  const P: typeof Energy.P;
  const R: typeof Energy.R;
  const W: typeof Energy.W;
  const Y: typeof Energy.Y;
  const N: typeof Energy.N;
}

export function isCoreFormat(format: Format): boolean {
  return format === Format.STANDARD || format === Format.EXPANDED || format === Format.UNLIMITED || format === Format.STANDARD_NIGHTLY || format === Format.GLC;
}