import { Card } from '../../game/store/card/card';
import { AegislashSVP, AlakazamexSVP, ArctibaxSVP, ArmarougeexSVP, BaxcaliburSVP, BloodmoonUrsalunaexSVP, BouffalantSVP, Charizardex2SVP, Charizardex3SVP, CharizardexSVP, CharmanderIRSVP, ChienPaoexSVP, ChienPaoSVP, ChiYuSVP, CinderaceexSVP, CleffaSVP, CrabominableSVP, CrocalorSVP, DrifblimSVP, EeveeSVP, FeraligatrSVP, FloragatoSVP, FlutterManeSVP, FroslassSVP, GougingFireexSVP, GougingFireSVP, GreatTuskexSVP, GrowlitheSVP, HawluchaSVP, InfernapeSVP, IonoSVP, IronBundleIRSVP, IronBundleSVP, IronCrownexSVP, IronLeavesexSVP, IronThornsSVP, IronValiantexSVP, JolteonSVP, KangaskhanexSVP, KingdraexSVP, KoraidonexSVP, KoraidonSVP, LaprasexSVP, MagnetonIRSVP, MagnetonSVP, MeowscaradaexFASVP, MeowscaradaexSVP, MetangSVP, MewexSVP, MimikyuSVP, Miraidonex2SVP, MiraidonexSVP, MiraidonSVP, MurkrowSVP, NoctowlSVP, PalafinexSVP, PalafinSVP, PawmotSVP, PecharuntIRSVP, PelipperSVP, PinecoSVP, Porygon2SVP, PupitarSVP, QuaquavalexFASVP, QuaquavalexSVP, RagingBoltexSVP, RevavroomSVP, RoaringMoonexSVP, ScreamTailSVP, SkeledirgeexFASVP, SkeledirgeexSVP, SmolivSVP, SnorlaxSVP, SquawkabillyexSVP, TatsugiriSVP, TealMaskOgerponexSVP, TerapagosexSVP, ThwackeySVP, TinkatonSVP, TogekissSVP, VictiniexSVP, WalkingWakeexSVP, XatuSVP, ZapdosexSVP } from './alt-arts';
import { Ampharosex } from './ampharos-ex';
import { Charmander } from './charmander';
import { Mimikyuex } from './mimikyu-ex';
import { Pecharunt } from './pecharunt';
import { Scrafty } from './scrafty';
import { Tinkatonex } from './tinkaton-ex';
import { TMMachine } from './tm-machine';
import { Toxtricityex } from './toxtricity-ex';


export const setScarletAndVioletPromos: Card[] = [
  new Ampharosex(),
  new Charmander(),
  new Mimikyuex(),
  new Pecharunt(),
  new Tinkatonex(),
  new TMMachine(),
  new Toxtricityex(),
  new Scrafty(),

  // Alt arts
  new PawmotSVP(),
  new HawluchaSVP(),
  new RevavroomSVP(),
  new BaxcaliburSVP(),
  new TinkatonSVP(),
  new MurkrowSVP(),
  new PelipperSVP(),
  new SmolivSVP(),
  new GrowlitheSVP(),
  new MiraidonexSVP(),
  new KoraidonexSVP(),
  new ChienPaoexSVP(),
  new MeowscaradaexSVP(),
  new SkeledirgeexSVP(),
  new QuaquavalexSVP(),
  new PalafinSVP(),
  new CleffaSVP(),
  new TogekissSVP(),
  new CharmanderIRSVP(),
  new ZapdosexSVP(),
  new AlakazamexSVP(),
  new SnorlaxSVP(),
  new MewexSVP(),
  new KangaskhanexSVP(),
  new CharizardexSVP(),
  new ChiYuSVP(),
  new IronBundleSVP(),
  new XatuSVP(),
  new AegislashSVP(),
  new PinecoSVP(),
  new ArctibaxSVP(),
  new ScreamTailSVP(),
  new IronBundleIRSVP(),
  new RoaringMoonexSVP(),
  new IronValiantexSVP(),
  new GreatTuskexSVP(),
  new Charizardex2SVP(),
  new MimikyuSVP(),
  new FloragatoSVP(),
  new MeowscaradaexFASVP(),
  new CrocalorSVP(),
  new SkeledirgeexFASVP(),
  new QuaquavalexFASVP(),
  new FeraligatrSVP(),
  new MetangSVP(),
  new KoraidonSVP(),
  new MiraidonSVP(),
  new FlutterManeSVP(),
  new IronThornsSVP(),
  new ThwackeySVP(),
  new InfernapeSVP(),
  new FroslassSVP(),
  new TatsugiriSVP(),
  new PupitarSVP(),
  new IonoSVP(),
  new ArmarougeexSVP(),
  new PalafinexSVP(),
  new WalkingWakeexSVP(),
  new IronLeavesexSVP(),
  new PecharuntIRSVP(),
  new KingdraexSVP(),
  new CrabominableSVP(),
  new DrifblimSVP(),
  new BouffalantSVP(),
  new Porygon2SVP(),
  new NoctowlSVP(),
  new VictiniexSVP(),
  new Miraidonex2SVP(),
  new GougingFireexSVP(),
  new RagingBoltexSVP(),
  new IronCrownexSVP(),
  new GougingFireSVP(),
  new ChienPaoSVP(),
  new MagnetonSVP(),
  new MagnetonIRSVP(),
  new SquawkabillyexSVP(),
  new Charizardex3SVP(),
  new CinderaceexSVP(),
  new LaprasexSVP(),
  new TerapagosexSVP(),
  new TealMaskOgerponexSVP(),
  new JolteonSVP(),
  new EeveeSVP(),
  new BloodmoonUrsalunaexSVP(),
];