import { HawluchaSVP, RevavroomSVP, BaxcaliburSVP, TinkatonSVP, MurkrowSVP, PelipperSVP, SmolivSVP, GrowlitheSVP, MiraidonexSVP, KoraidonexSVP, ChienPaoexSVP, MeowscaradaexSVP, SkeledirgeexSVP, QuaquavalexSVP, PalafinSVP, CleffaSVP, TogekissSVP, CharmanderSVP, ZapdosexSVP, AlakazamexSVP, MewexSVP, KangaskhanexSVP, CharizardexSVP, ChiYuSVP, IronBundleSVP, XatuSVP, AegislashSVP, PinecoSVP, ArctibaxSVP, ScreamTailSVP, IronBundle2SVP, RoaringMoonexSVP, IronValiantexSVP, GreatTuskexSVP, Charizardex2SVP, MimikyuSVP, FloragatoSVP, Meowscaradaex2SVP, CrocalorSVP, Skeledirgeex2SVP, Quaquavalex2SVP, FeraligatrSVP, MetangSVP, Koraidon2SVP, Miraidon2SVP, FlutterManeSVP, IronThornsSVP, ThwackeySVP, InfernapeSVP, FroslassSVP, TatsugiriSVP, PupitarSVP, IonoSVP, ArmarougeEX2SVP, PalafinexSVP, WalkingWakeexSVP, IronLeavesexSVP, PecharuntSVP, KingdraexSVP, CrabominableSVP, DrifblimSVP, BouffalantSVP, Porygon2SVP, NoctowlSVP, VictiniexSVP, Miraidonex2SVP, GougingFireexSVP, RagingBoltexSVP, IronCrownexSVP, GougingFireSVP, ChienPaoSVP, MagnetonSVP, Magneton2SVP, SquawkabillyexSVP, Charizardex3SVP, CinderaceexSVP, LaprasexSVP, TerapagosexSVP, TealMaskOgerponexSVP, BloodmoonUrsalunaexSVP } from './alt-arts';
import { Card } from '../../game/store/card/card';
import { PawmotSVP, SnorlaxSVP } from './alt-arts';
import { Ampharosex } from './ampharos-ex';
import { Charmander } from './charmander';
import { Mimikyuex } from './mimikyu-ex';
import { Pecharunt } from './pecharunt';
import { Tinkatonex } from './tinkaton-ex';
import { TMMachine } from './tm-machine';
import { Toxtricityex } from './toxtricity-ex';


export const setScarletAndVioletPromos: Card[] = [
  new Ampharosex(),
  new Charmander(),
  new Mimikyuex(),
  new Pecharunt(),
  new Tinkatonex(),
  new TMMachine(),
  new Toxtricityex(),

  // Alt arts
  new PawmotSVP(),
  new SnorlaxSVP(),
  new HawluchaSVP(),
  new RevavroomSVP(),
  new BaxcaliburSVP(),
  new TinkatonSVP(),
  new MurkrowSVP(),
  new PelipperSVP(),
  new SmolivSVP(),
  new GrowlitheSVP(),
  new MiraidonexSVP(),
  new KoraidonexSVP(),
  new ChienPaoexSVP(),
  new MeowscaradaexSVP(),
  new SkeledirgeexSVP(),
  new QuaquavalexSVP(),
  new PalafinSVP(),
  new CleffaSVP(),
  new TogekissSVP(),
  new CharmanderSVP(),
  new ZapdosexSVP(),
  new AlakazamexSVP(),
  new MewexSVP(),
  new KangaskhanexSVP(),
  new CharizardexSVP(),
  new ChiYuSVP(),
  new IronBundleSVP(),
  new XatuSVP(),
  new AegislashSVP(),
  new PinecoSVP(),
  new ArctibaxSVP(),
  new ScreamTailSVP(),
  new IronBundle2SVP(),
  new RoaringMoonexSVP(),
  new IronValiantexSVP(),
  new GreatTuskexSVP(),
  new Charizardex2SVP(),
  new MimikyuSVP(),
  new FloragatoSVP(),
  new Meowscaradaex2SVP(),
  new CrocalorSVP(),
  new Skeledirgeex2SVP(),
  new Quaquavalex2SVP(),
  new FeraligatrSVP(),
  new MetangSVP(),
  new Koraidon2SVP(),
  new Miraidon2SVP(),
  new FlutterManeSVP(),
  new IronThornsSVP(),
  new ThwackeySVP(),
  new InfernapeSVP(),
  new FroslassSVP(),
  new TatsugiriSVP(),
  new PupitarSVP(),
  new IonoSVP(),
  new ArmarougeEX2SVP(),
  new PalafinexSVP(),
  new WalkingWakeexSVP(),
  new IronLeavesexSVP(),
  new PecharuntSVP(),
  new KingdraexSVP(),
  new CrabominableSVP(),
  new DrifblimSVP(),
  new BouffalantSVP(),
  new Porygon2SVP(),
  new NoctowlSVP(),
  new VictiniexSVP(),
  new Miraidonex2SVP(),
  new GougingFireexSVP(),
  new RagingBoltexSVP(),
  new IronCrownexSVP(),
  new GougingFireSVP(),
  new ChienPaoSVP(),
  new MagnetonSVP(),
  new Magneton2SVP(),
  new SquawkabillyexSVP(),
  new Charizardex3SVP(),
  new CinderaceexSVP(),
  new LaprasexSVP(),
  new TerapagosexSVP(),
  new TealMaskOgerponexSVP(),
  new BloodmoonUrsalunaexSVP(),
];